<ips:template parameters="$members, $memberCount, $orientation='vertical'" />

<h3 class='ipsType_reset ipsWidget_title'>
	{{if \IPS\Dispatcher::i()->application->directory !== 'core'}}
		{lang="block_activeUsers"}
	{{else}}
		{lang="block_activeUsers_noApp"}
	{{endif}}
	{{if $orientation == 'horizontal'}}
		&nbsp;&nbsp;<span class='ipsType_light ipsType_unbold ipsType_medium'>{lang="block_user_online_info" pluralize="$memberCount"}</span>
	{{endif}}
</h3>
<div class='ipsWidget_inner ipsPad'>
	{{if $memberCount}}
		<ul class='ipsList_inline ipsList_csv ipsList_noSpacing ipsType_normal'>
			{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'members' ) ) }}
				{{foreach $members as $row}}
					<li>
						<a href="{url="app=core&module=members&controller=profile&id={$row['member_id']}" seoTemplate="profile" seoTitle="$row['seo_name']"}" data-ipsHover data-ipsHover-target='{url="app=core&module=members&controller=profile&id={$row['member_id']}&do=hovercard" seoTemplate="profile" seoTitle="$row['seo_name']"}' {{if $row['in_editor']}}data-ipsTooltip data-ipsTooltip-label="{lang="block_user_in_editor"}"{{else}}title="{lang="view_user_profile" sprintf="$row['member_name']"}"{{endif}} {{if $row['in_editor']}}class='cActiveUserEditor'{{endif}}>{expression="\IPS\Member\Group::load( $row['member_group'] )->formatName( $row['member_name'] )" raw="true"}</a>{{if \IPS\Member::loggedIn()->member_id AND \IPS\Member::loggedIn()->member_id === $row['member_id'] AND \IPS\Member::loggedIn()->isOnlineAnonymously()}}
							<span title='{lang="signed_in_anoymously"}' data-ipsTooltip>
								<i class='fa fa-eye-slash'></i>
							</span>{{endif}}</li>
				{{endforeach}}
			{{else}}
				{{foreach $members as $row}}
					<li>
						{{if $row['in_editor']}}<i class="fa fa-circle-o-notch fa-spin" data-ipsTooltip data-ipsTooltip-label="{lang="block_user_in_editor"}"></i>{{endif}}
						{expression="\IPS\Member\Group::load( $row['member_group'] )->formatName( $row['member_name'] )" raw="true"}

						{{if \IPS\Member::loggedIn()->member_id AND \IPS\Member::loggedIn()->member_id === $row['member_id'] AND \IPS\Member::loggedIn()->isOnlineAnonymously()}}
							<span title='{lang="signed_in_anoymously"}' data-ipsTooltip>
								<i class='fa fa-eye-slash'></i>
							</span>
						{{endif}}
					</li>
				{{endforeach}}
			{{endif}}
		</ul>
		{{if $memberCount > 60 && $orientation == 'vertical'}}
			<p class='ipsType_medium ipsType_reset'>
				<a href='{url="app=core&module=online&controller=online" seoTemplate="online"}'>{lang="and_x_others" pluralize="$memberCount - 60"}</a>
			</p>
		{{endif}}
	{{else}}
		<p class='ipsType_reset ipsType_medium ipsType_light'>{lang="active_users_empty"}</p>
	{{endif}}
</div>