<ips:template parameters="$availableBlocks" />
{{if isset( $availableBlocks['plugin'] )}}
	{{foreach $availableBlocks['plugin'] as $pluginId => $blocks}}
	<h3 class='ipsToolbox_sectionTitle ipsCursor_pointer'>{expression="\IPS\Plugin::load( $pluginId )->name"}</h3>
	<ul class='ipsList_reset'>
		{{foreach $blocks as $block}}
			<li data-blockTitle="{$block->title()}" data-blockID='plugin_{$block->plugin}_{$block->key}' {{if $block->hasConfiguration()}}data-blockConfig='true'{{endif}} {{if isset( $block->menuStyle)}}data-menuStyle='{$block->menuStyle}'{{endif}} {{if !empty( $block->allowReuse)}}data-allowReuse='true'{{endif}} class='ipsCursor_drag cSidebarManager_block'>
				<h4 class='ipsType_reset'>{lang="block_{$block->key}"}</h4>
				<p class='ipsType_reset ipsType_light ipsType_small'>{lang="block_{$block->key}_desc"}</p>
			</li>
		{{endforeach}}
	</ul>
	{{endforeach}}
{{endif}}

{{if isset( $availableBlocks['apps'] )}}
	{{foreach $availableBlocks['apps'] as $app => $blocks}}
	<h3 class='ipsToolbox_sectionTitle ipsCursor_pointer'>{lang="__app_{$app}"}</h3>
	<ul class='ipsList_reset'>
		{{foreach $blocks as $block}}
			<li data-blockTitle="{$block->title()}" data-blockErrorMessage="{lang="$block->errorMessage" escape="true"}" data-blockID='app_{$block->app}_{$block->key}' {{if $block->hasConfiguration()}}data-blockConfig='true'{{endif}} {{if isset( $block->menuStyle)}}data-menuStyle='{$block->menuStyle}'{{endif}} {{if !empty( $block->allowReuse)}}data-allowReuse='true'{{endif}} class='ipsCursor_drag cSidebarManager_block'>
				<h4 class='ipsType_reset'>{lang="block_{$block->key}"}</h4>
				<p class='ipsType_reset ipsType_light ipsType_small'>{lang="block_{$block->key}_desc"}</p>
			</li>
		{{endforeach}}
	</ul>
	<p class='ipsType_light ipsType_center ipsPad_half ipsHide'><em>{lang="no_app_widgets"}</em></p>
	{{endforeach}}
{{endif}}
