<ips:template parameters="$output, $config" />
{{if isset( \IPS\Request::i()->do ) and \IPS\Request::i()->do == 'getBlock'}}
<style type="text/css">
	{{if isset($config['custom'])}}{$config['custom']}{{endif}}
	{{if ! $config['border']}}
	{{$block = \IPS\Request::i()->blockID;}}
	.ipsBox[data-blockid="{$block}"] {
		border: none;
		box-shadow: none;
	}
	.ipsWidget[data-blockid="{$block}"] {
		background: transparent !important;
	}
	{{endif}}
</style>
{{endif}}
{{if ! empty( $config['background_custom_image_overlay'] )}}
	{{$padding = isset( $config['style']['padding'] ) ? $config['style']['padding'] : '';}}
	{{unset( $config['style']['padding'] );}}
	{{$style = implode( " ", $config['style']);}}
{{else}}
	{{$style = implode( " ", $config['style']);}}
{{endif}}
<div class='{$config['class']} {{if ! empty($config['border'])}}ipsBox{{endif}}
			{{if  empty( $config['background_custom_image_overlay'] )}}{{if ! empty($config['padding']) and $config['padding'] == 'half'}}ipsPad_half{{elseif ! empty($config['padding']) and $config['padding'] == 'full'}}ipsPad{{endif}}{{endif}}
			{{if ! empty($config['fontsize']) and $config['fontsize'] != 'custom' and $config['fontsize'] != 'inherit'}}{$config['fontsize']}{{endif}}'
	 style='{{if ! empty($config['style'])}}{$style}{{endif}}'>
	{{if ! empty( $config['background_custom_image_overlay'] )}}
	<div class='{$config['class']}_overlay' style="background-color: {$config['background_custom_image_overlay']}; {$padding}"
		 class="{{if ! empty($config['padding']) and $config['padding'] == 'half'}}ipsPad_half{{elseif ! empty($config['padding']) and $config['padding'] == 'full'}}ipsPad{{endif}}">
	{{endif}}
	{$output|raw}
	{{if ! empty( $config['background_custom_image_overlay'] )}}
	</div>
	{{endif}}
</div>
