<ips:template parameters="$widget, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
{template="includeJS" app="core" group="global" location="global" params=""}
{{$visibilityFields = array( 'show_on_all_devices', 'devices_to_show', 'clubs_visibility');}}
<form accept-charset='utf-8' class="ipsForm ipsForm_vertical" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	<div class='ipsMenu_headerBar'>
		<h4 class='ipsType_sectionHead'>{lang="editBlockSettings"}</h4>
	</div>

	{{$hasSettings = FALSE;}}
	{{foreach $elements as $collection}}
		{{foreach $collection as $input}}
			{{if \mb_substr( $input->name, 0, 12 ) != 'widget_adv__' and ! \in_array( $input->name, $visibilityFields )}}
				{{$hasSettings = TRUE; break 2;}}
			{{endif}}
		{{endforeach}}
	{{endforeach}}
	
	<div class='ipsTabs ipsClearfix ipsJS_show' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
		<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
		<ul role='tablist'>
			{{if $hasSettings}}
			<li>
				<a href='#ipsTabs_tabs_{$id}_{$id}_tab_settings_panel' id='{$id}_tab_settings' class="ipsTabs_item" role="tab" aria-selected="true">
					{lang="settings"}
				</a>
			</li>
			{{endif}}
			<li>
				<a href='#ipsTabs_tabs_{$id}_{$id}_tab_visibility_panel' id='{$id}_tab_visibility' class="ipsTabs_item" role="tab" aria-selected="true">
					{lang="visibility"}
				</a>
			</li>
			{{if ( \in_array( 'IPS\Widget\Builder', class_implements( $widget ) ) )}}
			<li>
				<a href='#ipsTabs_tabs_{$id}_{$id}_tab_advanced_panel' id='{$id}_tab_advanced' class="ipsTabs_item" role="tab" aria-selected="false">
					{lang="widget_tab_advanced"}
				</a>
			</li>
			{{endif}}
		</ul>
	</div>
	<div id='ipsTabs_content_{$id}' class='ipsTabs_panels'>
		<div id='ipsTabs_tabs_{$id}_{$id}_tab_settings_panel' class="{{if $widget->menuStyle !== 'modal'}}ipsMenu_innerContent{{endif}} ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_settings" aria-hidden="false">
			<ul class='ipsList_reset'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $input}}
						{{if \mb_substr( $input->name, 0, 12 ) != 'widget_adv__' and ! \in_array( $input->name, $visibilityFields )}}
							{{if \is_object( $input )}}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endif}}
					{{endforeach}}
				{{endforeach}}
			</ul>
		</div>
		<div id='ipsTabs_tabs_{$id}_{$id}_tab_visibility_panel' class="{{if $widget->menuStyle !== 'modal'}}ipsMenu_innerContent{{endif}} ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_visibility" aria-hidden="false">
			<ul class='ipsList_reset'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $input}}
						{{if \is_object( $input ) and \in_array( $input->name, $visibilityFields )}}
							{$input->rowHtml($form)|raw}
						{{elseif \in_array( $input->name, $visibilityFields )}}
							{$input|raw}
						{{endif}}
					{{endforeach}}
				{{endforeach}}
			</ul>
		</div>

		{{if ( \in_array( 'IPS\Widget\Builder', class_implements( $widget ) ) )}}
		<div id='ipsTabs_tabs_{$id}_{$id}_tab_advanced_panel' class="{{if $widget->menuStyle !== 'modal'}}ipsMenu_innerContent{{endif}}ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_advanced" aria-hidden="false">
			<ul class='ipsList_reset'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $input}}
						{{if \mb_substr( $input->name, 0, 12 ) == 'widget_adv__' and ! \in_array( $input->name, $visibilityFields )}}
							{{if \is_object( $input )}}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endif}}
					{{endforeach}}
				{{endforeach}}
			</ul>
		</div>
		{{endif}}
	</div>
	<div class='ipsMenu_footerBar ipsType_center'>
		{{foreach $actionButtons as $button}}
			{$button|raw}
		{{endforeach}}
	</div>
</form>