<ips:template parameters="$subject, $url" />
<h3 class='ipsType_reset ipsWidget_title'>
	{lang="block_invite"}
</h3>
<div class='ipsWidget_inner ipsPadding:half ipsType_center'>
	<div class="ipsPadding_bottom ipsPadding_top:half">
		{template="richText" group="global" app="core" location="global" params="\IPS\Member::loggedIn()->language()->addToStack('block_invite_text', FALSE, array( 'sprintf' => array( \IPS\Settings::i()->board_name ) ) ), array('ipsType_reset','ipsType_medium')"}
	</div>
	<ul class="ipsList_reset ipsFlex ipsFlex-ai:center ipsFlex-jc:stretch ipsFlex-fw:wrap ipsGap:1">
		<li class='ipsFlex-flex:11'><a class="ipsButton ipsButton_small ipsButton_light ipsButton_fullWidth " href='mailto:?subject={$subject}&body={$url}'><i class="fa fa-envelope"></i> {lang="block_invite_button"}</a></li>
		<li class='ipsFlex-flex:11'><a class="ipsButton ipsButton_small ipsButton_light ipsButton_fullWidth " href='{url="app=core&module=system&controller=settings&do=invite"}' data-ipsDialog data-ipsDialog-size="narrow"><i class="fa fa-share-alt"></i> {lang="block_invite_share"}</a></li>
	</ul>
</div>