<ips:template parameters="$results, $timeframe, $orientation='vertical'" />
{{if \count( $results )}}
	{{if $orientation == 'vertical'}}
		<ol class='ipsDataList ipsDataList_reducedSpacing cTopContributors'>
			{{$idx = 1;}}
			{{foreach $results as $memberId => $solvedCount}}
				{{$member = \IPS\Member::load( $memberId );}}
				<li class='ipsDataItem'>
					<div class='ipsDataItem_icon ipsPos_middle ipsType_center ipsType_large ipsType_light'><strong>{expression="$idx++"}</strong></div>
					<div class='ipsDataItem_main ipsPhotoPanel ipsPhotoPanel_tiny'>
						{template="userPhoto" app="core" group="global" params="$member, 'tiny'"}
						<div>
							{$member->link()|raw}
							<br>
							<span title="{lang="solved_badge_tooltip_time"}" data-ipsTooltip class='ipsRepBadge ipsRepBadge_positive'><i class='fa fa-check-circle'></i> {expression="\IPS\Member::loggedIn()->language()->formatNumber( $solvedCount )"}</span>
						</div>
					</div>
				</li>
			{{endforeach}}
		</ol>
	{{else}}
		<div class="ipsGrid ipsGrid_collapsePhone">
			{{$count = 0;}}
			{{foreach $results as $memberId => $solvedCount}}
				{{if $count == 4}}
					{{break;}}
				{{else}}
					{{$count++;}}
				{{endif}}
				{{$member = \IPS\Member::load( $memberId );}}
				<div class='ipsGrid_span3'>
					<div class='ipsPad_half ipsPhotoPanel ipsPhotoPanel_tiny'>
						{template="userPhoto" app="core" group="global" params="$member, 'tiny'"}
						<div>
							<p class='ipsType_reset ipsTruncate ipsTruncate_line'>
								{$member->link()|raw}
							</p>
							<span title="{lang="solved_badge_tooltip_time"}" data-ipsTooltip class='ipsRepBadge ipsRepBadge_positive'><i class='fa fa-check-circle'></i> {expression="\IPS\Member::loggedIn()->language()->formatNumber( $solvedCount )"}</span>
						</div>
					</div>
				</div>
			{{endforeach}}
		</div>
	{{endif}}
{{else}}
	<div class='ipsPad'>
		<p class='ipsType_reset'>{lang="top_solved_empty__{$timeframe}"}</p>
	</div>
{{endif}}