<ips:template parameters="$indexData, $articles, $authorData, $itemData, $unread, $objectUrl, $itemUrl, $containerUrl, $containerTitle, $repCount, $showRepUrl, $snippet, $iPostedIn, $view, $canIgnoreComments=FALSE, $reactions=array()" />
<li class='cWidgetStream ipsFlex {{if $view == 'horizontal'}}ipsGap:5{{else}}ipsGap:3{{endif}}' data-orientation="{$view}">
	{{if \in_array( 'IPS\Content\Comment', class_parents( $indexData['index_class'] ) )}}
		{{$itemClass = $indexData['index_class']::$itemClass;}}
		<div class="cWidgetStream__icon ipsFlex-flex:00">
			{{if $view == 'horizontal'}}{template="userPhotoFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], \IPS\Member::photoUrl( $authorData ), ( $view == 'horizontal' ) ? 'mini' : 'tiny'"}{{endif}}
			{{if $indexData['index_title']}}
				<span class='cWidgetStreamIcon' data-ipsTooltip title='{lang="$itemClass::$title"}'><i class='fa fa-{$itemClass::$icon}'></i></span>
			{{else}}				
				<span class='cWidgetStreamIcon' data-ipsTooltip title='{lang="$indexData['index_class']::$title"}'><i class='fa fa-{$indexData['index_class']::$icon}'></i></span>
			{{endif}}		
		</div>
		<div class='cWidgetStream__main ipsFlex-flex:11'>
			{{if isset( $itemClass::$databaseColumnMap['num_comments'] ) and isset( $itemData[ $itemClass::$databasePrefix . $itemClass::$databaseColumnMap['num_comments'] ] )}}	
				{{$commentCount = $itemData[ $itemClass::$databasePrefix . $itemClass::$databaseColumnMap['num_comments'] ];}}
				{{if $itemClass::$firstCommentRequired}}
					<div class="ipsCommentCount ipsPos_right" data-ipsTooltip title='{lang="replies_number" pluralize="$commentCount - 1"}'>{expression="\IPS\Member::loggedIn()->language()->formatNumber( $commentCount - 1 )"}</div>
				{{else}}
					<div class="ipsCommentCount ipsPos_right" data-ipsTooltip title='{lang="replies_number" pluralize="$commentCount"}'>{expression="\IPS\Member::loggedIn()->language()->formatNumber( $commentCount )"}</div>
				{{endif}}
			{{endif}}
			<div class="ipsType_break">
				<h4 class='ipsDataItem_title {{if $view == 'horizontal'}}ipsType_large ipsType_break{{endif}}'>
					{{if isset( $indexData['index_prefix'] )}}
						<span>{template="prefix" group="global" app="core" params="rawurlencode($indexData['index_prefix']), $indexData['index_prefix']"}</span>
					{{endif}}
					<span class='ipsType_break'>
						<a href='{$objectUrl}' data-linkType="link" data-searchable>{$itemData[ $itemClass::$databasePrefix . $itemClass::$databaseColumnMap['title'] ]}</a>
					</span>
					{{if $indexData['index_hidden']}}
						{{if $indexData['index_hidden'] === -1}}
						<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="hidden"}'><i class='fa fa-eye-slash'></i></span></span>
						{{elseif $indexData['index_hidden'] === 1}}
						<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span></span>
						{{endif}}
					{{endif}}
				</h4>
				<div class='ipsType_reset ipsType_blendLinks ipsType_medium'>
					{template="searchResultSnippet" app="core" location="front" group="system" params="$indexData"}
					{{if \IPS\IPS::classUsesTrait( $indexData['index_class'], 'IPS\Content\Reactable' ) and settings.reputation_enabled and \count( $reactions )}}
						{{if \in_array( 'IPS\Content\Review', class_parents( $indexData['index_class'] ) )}}
							<span class="cWidgetStreamReaction">{template="searchReaction" group="search" app="core" params="$reactions, $itemUrl->setQueryString('do', 'showReactionsReview')->setQueryString('review', $indexData['index_object_id']), $repCount"}</span>
						{{else}}
							<span class="cWidgetStreamReaction">{template="searchReaction" group="search" app="core" params="$reactions, $itemUrl->setQueryString('do', 'showReactionsComment')->setQueryString('comment', $indexData['index_object_id']), $repCount"}</span>
						{{endif}}
					{{endif}}
				</div>
			
				<div class='cWidgetStreamTime ipsType_blendLinks ipsType_light ipsType_medium'>
					{{if $view == 'horizontal'}}
						<i class='fa fa-clock-o'></i> <a href='{{if $indexData['index_title']}}{$objectUrl}{{else}}{{if \in_array( 'IPS\Content\Review', class_parents( $indexData['index_class'] ) )}}{$objectUrl->setQueryString( array( 'do' => 'findReview', 'review' => $indexData['index_object_id'] ) )}{{else}}{$objectUrl->setQueryString( array( 'do' => 'findComment', 'comment' => $indexData['index_object_id'] ) )}{{endif}}{{endif}}'>{datetime="$indexData['index_date_created']"}</a> - {expression="$itemClass::searchResultSummaryLanguage( $authorData, $articles, $indexData, $itemData )"} <a href='{$containerUrl}'>{$containerTitle|raw}</a>
					{{else}}
						{template="userPhotoFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], \IPS\Member::photoUrl( $authorData ), ( $view == 'horizontal' ) ? 'mini' : 'tiny'"} <a href='{{if $indexData['index_title']}}{$objectUrl}{{else}}{{if \in_array( 'IPS\Content\Review', class_parents( $indexData['index_class'] ) )}}{$objectUrl->setQueryString( array( 'do' => 'findReview', 'review' => $indexData['index_object_id'] ) )}{{else}}{$objectUrl->setQueryString( array( 'do' => 'findComment', 'comment' => $indexData['index_object_id'] ) )}{{endif}}{{endif}}'>{datetime="$indexData['index_date_created']"}</a> {lang="in"} <a href='{$containerUrl}'>{$containerTitle|raw}</a>	
					{{endif}}
				</div>
				{{if isset( $indexData['index_tags'] )}}
					<div>{template="tags" group="global" app="core" params="explode( ',', $indexData['index_tags'] ), true, true"}</div>
				{{endif}}
			</div>
		</div>
	{{else}}
		{{$itemClass = $indexData['index_class'];}}
		<div class="cWidgetStream__icon ipsFlex-flex:00">
			{{if $view == 'horizontal'}}{template="userPhotoFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], \IPS\Member::photoUrl( $authorData ), ( $view == 'horizontal' ) ? 'mini' : 'tiny'"}{{endif}}
			{{if $indexData['index_title']}}
				<span class='cWidgetStreamIcon' data-ipsTooltip title='{lang="$itemClass::$title"}'><i class='fa fa-{$itemClass::$icon}'></i></span>
			{{else}}				
				<span class='cWidgetStreamIcon' data-ipsTooltip title='{lang="$indexData['index_class']::$title"}'><i class='fa fa-{$indexData['index_class']::$icon}'></i></span>
			{{endif}}
		</div>
		<div class='cWidgetStream__main ipsFlex-flex:11'>
			{{if isset( $itemClass::$databaseColumnMap['num_comments'] ) and isset( $itemData[ $itemClass::$databasePrefix . $itemClass::$databaseColumnMap['num_comments'] ] )}}
				{{$commentCount = $itemData[ $itemClass::$databasePrefix . $itemClass::$databaseColumnMap['num_comments'] ];}}
				{{if $itemClass::$firstCommentRequired}}
					<div class="ipsCommentCount ipsPos_right" data-ipsTooltip title='{lang="replies_number" pluralize="$commentCount - 1"}'>{expression="\IPS\Member::loggedIn()->language()->formatNumber( $commentCount - 1 )"}</div>
				{{else}}
					<div class="ipsCommentCount ipsPos_right" data-ipsTooltip title='{lang="replies_number" pluralize="$commentCount"}'>{expression="\IPS\Member::loggedIn()->language()->formatNumber( $commentCount )"}</div>
				{{endif}}
			{{endif}}
			<div class='ipsType_break'>
				<h4 class='ipsDataItem_title {{if $view == 'horizontal'}}ipsType_large ipsType_break{{endif}}'>
					{{if isset( $indexData['index_prefix'] )}}
						<span>{template="prefix" group="global" app="core" params="rawurlencode($indexData['index_prefix']), $indexData['index_prefix']"}</span>
					{{endif}}
					<span class='ipsType_break'><a href='{$itemUrl}' data-linkType="link" data-searchable>{$indexData['index_title']}</a>
                    {{if $indexData['index_hidden']}}
						<span><span class="ipsBadge ipsBadge_icon ipsBadge_warning ipsBadge_medium " data-ipsTooltip title='{lang="hidden"}'><i class='fa fa-eye-slash'></i></span></span>
					{{endif}}
                    </span>
				</h4>
				{{if $containerTitle}}
					<div class='ipsType_reset ipsType_blendLinks ipsType_light ipsType_medium'>
						{$snippet|raw}
					</div>
					<div class='cWidgetStreamTime ipsType_blendLinks ipsType_light ipsType_medium'>
						{{if $view == 'horizontal'}}
							<i class='fa fa-clock-o'></i> <a href='{{if $indexData['index_title']}}{$objectUrl}{{else}}{{if \in_array( 'IPS\Content\Review', class_parents( $indexData['index_class'] ) )}}{$objectUrl->setQueryString( array( 'do' => 'findReview', 'review' => $indexData['index_object_id'] ) )}{{else}}{$objectUrl->setQueryString( array( 'do' => 'findComment', 'comment' => $indexData['index_object_id'] ) )}{{endif}}{{endif}}'>{datetime="$indexData['index_date_created']"}</a> - {expression="$itemClass::searchResultSummaryLanguage( $authorData, $articles, $indexData, $itemData )"} <a href='{$containerUrl}'>{$containerTitle|raw}</a>
						{{else}}
							{template="userPhotoFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], \IPS\Member::photoUrl( $authorData ), ( $view == 'horizontal' ) ? 'mini' : 'tiny'"} <a href='{{if $indexData['index_title']}}{$objectUrl}{{else}}{{if \in_array( 'IPS\Content\Review', class_parents( $indexData['index_class'] ) )}}{$objectUrl->setQueryString( array( 'do' => 'findReview', 'review' => $indexData['index_object_id'] ) )}{{else}}{$objectUrl->setQueryString( array( 'do' => 'findComment', 'comment' => $indexData['index_object_id'] ) )}{{endif}}{{endif}}'>{datetime="$indexData['index_date_created']"}</a> {lang="in"} <a href='{$containerUrl}'>{$containerTitle|raw}</a>	
						{{endif}}
					</div>
					{{if isset( $indexData['index_tags'] )}}
						<div>{template="tags" group="global" app="core" params="explode( ',', $indexData['index_tags'] ), true, true"}</div>
					{{endif}}
				{{endif}}
			</div>
		</div>
	{{endif}}
</li>