<ips:template parameters="$members, $memberCount, $guests, $anonymous, $orientation='vertical'" />
<h3 class='ipsType_reset ipsWidget_title'>
	{lang="block_whosOnline"}
	{{if $orientation == 'horizontal'}}
		&nbsp;&nbsp;<span class='ipsType_light ipsType_unbold ipsType_medium'>{lang="block_whos_online_info_members" pluralize="$memberCount"}, {lang="block_whos_online_info_anonymous" pluralize="$anonymous"}, {lang="block_whos_online_info_guests" pluralize="$guests"}</span>
	{{endif}}
	<span class='ipsType_medium ipsType_light ipsType_unbold ipsType_blendLinks'><a href='{url="app=core&module=online&controller=online" seoTemplate="online"}'>{lang="see_full_list"}</a></span>
</h3>
<div class='ipsWidget_inner ipsPadding'>
	{{if $memberCount}}
		<ul class='ipsList_inline ipsList_csv ipsList_noSpacing ipsType_normal'>
			{{foreach $members as $row}}
				<li>
					{template="userLinkFromData" group="global" app="core" params="$row['member_id'], $row['member_name'], $row['seo_name'], $row['member_group'], TRUE"}{{if \IPS\Member::loggedIn()->member_id AND \IPS\Member::loggedIn()->member_id === $row['member_id'] AND \IPS\Member::loggedIn()->isOnlineAnonymously()}}
						<span title='{lang="signed_in_anoymously"}' data-ipsTooltip>
							<i class='fa fa-eye-slash'></i>
						</span>{{endif}}</li>
			{{endforeach}}
		</ul>
		{{if $orientation == 'vertical' and $memberCount > 60}}
			<p class='ipsType_medium ipsType_reset'>
				<a href='{url="app=core&module=online&controller=online" seoTemplate="online"}'>{lang="and_x_others" pluralize="$memberCount - 60"}</a>
			</p>
		{{endif}}
	{{else}}
		<p class='ipsType_reset ipsType_medium ipsType_light'>{lang="whos_online_users_empty"}</p>
	{{endif}}
</div>