<ips:template parameters="$member, $followers, $followersCount" />
{{if !\IPS\Request::i()->isAjax()}}
	<h3 class='ipsType_sectionHead'>{lang="members_followers" sprintf="$member->name"}</h3>
	<br>
{{endif}}
{{if $followersCount > 50}}
	{{$url = \IPS\Http\Url::internal( "app=core&module=members&controller=profile&do=followers&id={$member->member_id}", 'front', 'profile_followers', $member->members_seo_name );}}
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
		<div data-role="tablePagination">
			{template="pagination" group="global" app="core" location="global" params="$url, ceil( $followersCount / 50 ), \IPS\Request::i()->page ?: 1, 50"}
		</div>
	</div>
{{endif}}
<br>
<ul class='ipsDataList'>
	{{if $followers !== NULL and \count( $followers )}}
		{{foreach $followers AS $follower}}
			<li class='ipsDataItem ipsClearfix {{if $follower['follow_is_anon']}}ipsFaded{{endif}}'>
				<div class='ipsDataItem_icon ipsPos_top'>
					{template="userPhoto" app="core" group="global" params="\IPS\Member::load($follower['follow_member_id']), 'tiny', NULL, '', FALSE"}<br>
				</div>
				<div class='ipsDataItem_main'>
					{{if \IPS\Member::loggedIn()->member_id != $follower['follow_member_id'] and ( !\IPS\Member::load($follower['follow_member_id'])->members_bitoptions['pp_setting_moderate_followers'] or \IPS\Member::loggedIn()->following( 'core', 'member', $follower['follow_member_id'] ) )}}
						<div class='ipsPos_right'>{template="memberFollow" app="core" group="profile" params="'core', 'member', $follower['follow_member_id'], \IPS\Member::load( $follower['follow_member_id'] )->followersCount(), TRUE"}</div>
					{{endif}}
					<strong class='ipsDataItem_title'>{expression="\IPS\Member::load($follower['follow_member_id'])->link( NULL, FALSE )" raw="true"}</strong> {{if $follower['follow_is_anon']}} {lang="anon_follower"}{{endif}}<br>
					{expression="\IPS\Member\Group::load( \IPS\Member::load($follower['follow_member_id'])->member_group_id )->formattedName" raw="true"}
				</div>
			</li>
		{{endforeach}}
	{{endif}}
</ul>
{{if $followersCount > 50}}
	<br>
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
		<div data-role="tablePagination">
			{template="pagination" group="global" app="core" location="global" params="$url, ceil( $followersCount / 50 ), \IPS\Request::i()->page ?: 1, 50"}
		</div>
	</div>
{{endif}}