<ips:template parameters="$member, $followers" />

<h2 class='ipsWidget_title ipsType_reset'>
	{{if \IPS\Member::loggedIn()->member_id === $member->member_id}}
		<a href='#elFollowPref_menu' data-role='followOption' data-ipsMenu data-ipsMenu-selectable='radio' data-ipsMenu-appendTo='#elFollowers' id='elFollowPref' class='ipsType_blendLinks ipsType_small ipsPos_right'>{lang="options"} <i class='fa fa-caret-down'></i></a>
		<ul id='elFollowPref_menu' class='ipsMenu ipsMenu_selectable ipsMenu_normal ipsHide'>
			<li data-ipsMenuValue='enable' class='ipsMenu_item {{if !$member->members_bitoptions['pp_setting_moderate_followers']}}ipsMenu_itemChecked{{endif}}'>
				<a href='{url="app=core&module=members&controller=profile&id={$member->member_id}&do=changeFollow&enabled=1" seoTemplate="profile" seoTitle="$member->members_seo_name" csrf="true"}'>{lang="allow_follow"}</a>
			</li>
			<li data-ipsMenuValue='disable' class='ipsMenu_item {{if $member->members_bitoptions['pp_setting_moderate_followers']}}ipsMenu_itemChecked{{endif}}'>
				<a href='{url="app=core&module=members&controller=profile&id={$member->member_id}&do=changeFollow&enabled=0" seoTemplate="profile" seoTitle="$member->members_seo_name" csrf="true"}'>{lang="disallow_follow"}</a>
			</li>
			<li class='ipsMenu_sep'><hr></li>
			<li class='ipsPad_half ipsType_center ipsType_light ipsType_medium'>
				{lang="follow_setting_desc"}
			</li>
		</ul>
	{{endif}}
	{lang="x_followers" pluralize="($followers !== NULL) ? $member->followersCount() : 0"}
</h2>
<div class='ipsWidget_inner'>
	{{if $followers !== NULL and \count( $followers )}}
		<ul class='ipsGrid ipsSpacer_top'>
			{{foreach $followers as $idx => $follower}}
				{{if $idx <= 11}}
					<li class='ipsGrid_span3 ipsType_center {{if $follower['follow_is_anon']}}ipsFaded{{endif}}' data-ipsTooltip title='{expression="\IPS\Member::load( $follower['follow_member_id'] )->name"}{{if $follower['follow_is_anon']}} {lang="anon_follower"}{{endif}}'>{template="userPhoto" app="core" group="global" params="\IPS\Member::load($follower['follow_member_id']), 'mini', NULL, '', FALSE"}</li>
				{{endif}}
			{{endforeach}}
		</ul>
	{{else}}
		<p class='ipsType_center ipsPad_half ipsType_light'>{lang="no_followers_yet"}</p>
	{{endif}}
</div>
{{if $followers !== NULL and $member->followersCount() > 12}}
	<p class='ipsType_right ipsType_reset ipsPad_half ipsType_small ipsType_light ipsAreaBackground_light'>
		<a href='{url="app=core&module=members&controller=profile&do=followers&id={$member->member_id}" seoTemplate="profile_followers" seoTitle="$member->members_seo_name"}' class='ipsType_blendLinks'>{lang="see_all_followers"} <i class='fa fa-caret-right'></i></a>
	</p>
{{endif}}