<ips:template parameters="$member, $addWarningUrl" />
{{$rnd = mt_rand();}}
{{$referrer = \IPS\Request::i()->referrer;}}
{{$coverPhoto = $member->coverPhoto();}}
<!-- When altering this template be sure to also check for similar in main profile view -->
<div class="cUserHovercard" id="elUserHovercard_{$member->member_id}{$rnd}">
	<div class='ipsPageHead_special' id='elProfileHeader_{$rnd}' data-controller='core.global.core.coverPhoto' data-url="{$member->url()->csrf()}" data-coverOffset='{$coverPhoto->offset}'>
		{{if $coverPhoto->file}}
			<div class='ipsCoverPhoto_container'>
				<img src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo' alt=''>
			</div>
		{{else}}
			<div class='ipsCoverPhoto_container' style="background-color: {$member->coverPhotoBackgroundColor()}">
				<img src='{resource="pattern.png" app="core" location="global"}' class='ipsCoverPhoto_photo' data-action="toggleCoverPhoto" alt=''>
			</div>
		{{endif}}
		<a href='{$member->url()}'><img src='{$member->photo}' class="ipsUserPhoto ipsUserPhoto_medium"></a>
		<h2 class="ipsType_reset ipsType_sectionHead ipsTruncate ipsTruncate_line ipsType_blendLinks">
			<span class='ipsPageHead_barText_small'>
				<a href='{$member->url()}'>{$member->name}</a>
				{{if \IPS\Member::loggedIn()->member_id AND \IPS\Member::loggedIn()->member_id === $member->member_id AND $member->isOnlineAnonymously()}}
					<span class='cProfileHeader_history ipsType_large ipsPos_right' title='{lang="member_is_currently_anon"}' data-ipsTooltip>
						<i class='fa fa-eye-slash'></i>
					</span>
				{{endif}}
			</span>
		</h2>
		<p class='ipsType_reset ipsType_normal'><span class='ipsPageHead_barText_small'>{expression="\IPS\Member\Group::load( $member->member_group_id )->formattedName" raw="true"}</span></p>
	</div>
	<br>
	{template="reputationBadge" group="global" app="core" params="$member"}
	<div class='cUserHovercard_data'>
		<ul class="ipsDataList ipsDataList_reducedSpacing">
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="members_member_posts"}</strong></span>
				<span class="ipsDataItem_main">{number="$member->member_posts"}</span>
			</li>
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="members_joined"}</strong></span>
				<span class="ipsDataItem_main">{datetime="$member->joined"}</span>
			</li>
            {{if ( !$member->isOnlineAnonymously() ) OR ( $member->isOnlineAnonymously() AND \IPS\Member::loggedIn()->isAdmin() )}}
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="members_last_visit"}</strong></span>
				<span class="ipsDataItem_main">
					{{if $member->isOnline()}}<i class="fa fa-circle ipsOnlineStatus_online" data-ipsTooltip title="{lang="online_now" sprintf="$member->name"}"></i>{{endif}}
					{{if $member->last_activity}}{datetime="$member->last_activity"}{{else}}{lang="never"}{{endif}}
				</span>
			</li>
            {{endif}}
			{{if $member->isOnline() AND ( !$member->isOnlineAnonymously() OR ( $member->isOnlineAnonymously() AND \IPS\Member::loggedIn()->isAdmin() ) ) AND $member->location}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="online_users_location_lang"}</strong></span>
					<span class="ipsDataItem_main">{$member->location()|raw}</span>
				</li>
			{{endif}}
			{{if \IPS\Member::loggedIn()->modPermission('can_see_emails')}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="email"}</strong></span>
					<span class="ipsDataItem_main">
						{$member->email}<br>
						<span class='ipsType_light ipsType_small'>{lang="profile_email_addresses"}</span>
					</span>
				</li>
			{{endif}}
			{{if \IPS\Settings::i()->warn_on and !$member->inGroup( explode( ',', \IPS\Settings::i()->warn_protected ) ) and ( \IPS\Member::loggedIn()->modPermission('mod_see_warn') or ( \IPS\Settings::i()->warn_show_own and \IPS\Member::loggedIn()->member_id == $member->member_id ) )}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="member_warnings"}</strong></span>
					<span class="ipsDataItem_main">{$member->warn_level}</span>
				</li>
			{{endif}}
		</ul>
	</div>
	<br>
	<div class="ipsBorder_top ipsPadding_vertical ipsMargin_horizontal ipsClearfix">
		<ul class="ipsList_inline ipsType_blendLinks">
			{{if ( \IPS\Member::loggedIn()->member_id and \IPS\Member::loggedIn()->member_id !== $member->member_id ) && !$member->members_disable_pm and !\IPS\Member::loggedIn()->members_disable_pm and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'messaging' ) )}}
				<li><a href='{url="app=core&module=messaging&controller=messenger&do=compose&to={$member->member_id}" seoTemplate="messenger_compose"}' data-ipsDialog data-ipsDialog-title='{lang="compose_new"}' data-ipsDialog-remoteSubmit data-ipsDialog-flashMessage="{lang="message_sent"}" data-ipsDialog-forceReload><i class='fa fa-envelope'></i> {lang="message_send"}</a></li>
			{{endif}}
			{{if \IPS\Member::loggedIn()->member_id && $member->canBeIgnored() and \IPS\Member::loggedIn()->member_id !== $member->member_id }}
				<li><a href="{url="app=core&module=system&controller=ignore&id={$member->member_id}" csrf="true" seoTemplate="ignore"}"><i class='fa fa-times-circle'></i> {lang="add_ignore"}</a></li>
			{{endif}}
			<li><a href="{url="app=core&module=members&controller=profile&do=content&id={$member->member_id}" base="front" seoTemplate="profile_content" seoTitle="$member->members_seo_name"}"><i class='fa fa-search'></i> {lang="find_content"}</a></li>
			{{if ( member.canWarn( $member ) || ( member.modPermission('can_flag_as_spammer') and !$member->modPermission() and !$member->isAdmin() ) ) and $member->member_id != member.member_id }}
				<li class="ipsPos_right">
					<a href="#elUserHovercard_{$member->member_id}_more_menu" id="elUserHovercard_{$member->member_id}{$rnd}_more" title='{lang="more_options"}' data-ipsTooltip data-ipsMenu data-ipsMenu-appendTo="#elUserHovercard_{$member->member_id}{$rnd}">
						<i class="fa fa-cog ipsType_large"></i> <i class="fa fa-caret-down"></i>
					</a>
				</li>
			{{endif}}
		</ul>
		{{if ( \IPS\Member::loggedIn()->modPermission('can_flag_as_spammer') AND $member->member_id != \IPS\Member::loggedIn()->member_id ) || member.canWarn( $member )}}
			<ul class="ipsMenu ipsMenu_narrow ipsHide" id="elUserHovercard_{$member->member_id}{$rnd}_more_menu">
				{{if member.modPermission('can_flag_as_spammer') and $member->member_id != member.member_id and !$member->modPermission() and !$member->isAdmin()}}
					{{if $member->members_bitoptions['bw_is_spammer']}}
						<li class="ipsMenu_item"><a href='{url="app=core&module=system&controller=moderation&do=flagAsSpammer&id={$member->member_id}&s=0&referrer={$referrer}" seoTemplate="flag_as_spammer" seoTitle="$member->members_seo_name" csrf="true"}' data-confirm data-confirmSubMessage="{lang="spam_unflag_confirm"}"><i class="fa fa-flag"></i> {lang="spam_unflag"}</a></li>
					{{else}}
						<li class="ipsMenu_item"><a href='{url="app=core&module=system&controller=moderation&do=flagAsSpammer&id={$member->member_id}&s=1&referrer={$referrer}" seoTemplate="flag_as_spammer" seoTitle="$member->members_seo_name" csrf="true"}' data-confirm><i class="fa fa-flag"></i> {lang="spam_flag"}</a></li>
					{{endif}}
				{{endif}}
				{{if member.canWarn( $member )}}
					<li class="ipsMenu_item"><a href="{$addWarningUrl}" title='{lang="warn_user_title"}' data-ipsDialog data-ipsDialog-title='{lang="warn_user"}' data-ipsDialog-destructOnClose><i class="fa fa-exclamation-triangle"></i> {lang="warn_user"}</a></li>
				{{endif}}
			</ul>
		{{endif}}
	</div>
</div>