<ips:template parameters="$app, $area, $id, $count" />
{{if member.member_id}}
	<div class="ipsResponsive_hidePhone ipsResponsive_block">
		{{if member.following( $app, $area, $id )}}
			<a href="{url="app=core&module=system&controller=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="following_this_member"}" data-ipsTooltip class="ipsButton ipsButton_positive" data-role="followButton" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick><i class='fa fa-check'></i><i class='fa fa-user'></i> <span class='ipsResponsive_showDesktop ipsResponsive_inline'> {lang="following_member"}</span> <i class='fa fa-caret-down'></i></a>
		{{else}}	
			<a href="{url="app=core&module=system&controller=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="follow_this_member"}" data-ipsTooltip class="ipsButton ipsButton_primary" data-role="followButton" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick><i class='fa fa-plus'></i><i class='fa fa-user'></i> <span class='ipsResponsive_showDesktop ipsResponsive_inline'> {lang="follow_member"}</span></a>
		{{endif}}
	</div>
	<div class="ipsResponsive_showPhone ipsResponsive_block">
		{{if member.following( $app, $area, $id )}}
			<a href="{url="app=core&module=system&controller=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="following_this_member"}" data-ipsTooltip class="ipsButton ipsButton_positive ipsButton_fullWidth ipsButton_small" data-role="followButton" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick><i class='fa fa-check'></i><i class='fa fa-user'></i> <i class='fa fa-caret-down'></i></a>
		{{else}}	
			<a href="{url="app=core&module=system&controller=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="follow_this_member"}" data-ipsTooltip class="ipsButton ipsButton_fullWidth ipsButton_small ipsButton_alternate" data-role="followButton" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick><i class='fa fa-plus'></i><i class='fa fa-user'></i></a>
		{{endif}}
	</div>
{{endif}}