<ips:template parameters="$member, $latestActivity, $statusForm=NULL" />
<div data-controller="core.front.statuses.statusFeed">
	{{if $statusForm}}
		<div class='ipsAreaBackground ipsPad ipsSpacer_bottom'>
			<div class='ipsComposeArea ipsComposeArea_withPhoto ipsClearfix ipsContained' data-role='newStatus'>
				<div class='ipsPos_left ipsResponsive_hidePhone ipsResponsive_block'>{template="userPhoto" app="core" group="global" params="\IPS\Member::loggedIn(), 'small'"}</div>
				<div class='ipsComposeArea_editor'>
					{$statusForm|raw}
				</div>
			</div>
		</div>
	{{elseif !\count( $latestActivity )}}
		<div class='ipsPad ipsType_center ipsType_large ipsType_light'>
			{lang="no_recent_activity" sprintf="$member->name"}
		</div>
	{{endif}}
	{{if $statusForm or \count( $latestActivity )}}
		<ol class='ipsStream ipsList_reset' data-role='activityStream' id='elProfileActivityOverview'>
			{{foreach $latestActivity as $activity}}
				{$activity->html()|raw}
			{{endforeach}}
		</ol>
	{{endif}}
</div>