<ips:template parameters="$member, $clubs, $pagination" />

{{if \count( $clubs )}}
	{{if $pagination}}
		{$pagination|raw}
	{{endif}}

	<ul class='ipsGrid ipsGrid_collapsePhone' data-ipsGrid data-ipsGrid-minItemSize='400' data-ipsGrid-maxItemSize='600' data-ipsGrid-equalHeights='row'>
		{{foreach $clubs as $club}}
			<li class='ipsGrid_span6 ipsBox'>{template="clubCard" group="clubs" app="core" params="$club"}</li>
		{{endforeach}}
	</ul>

	{{if $pagination}}
		{$pagination|raw}
	{{endif}}
{{else}}
	<p class='ipsType_light ipsType_large ipsType_center'>
		{lang="member_no_clubs" sprintf="$member->name"}
	</p>
{{endif}}