<ips:template parameters="$member, $small=FALSE" />
{{$coverPhoto = $member->coverPhoto();}}
<header data-role="profileHeader">
	<div class='ipsPageHead_special {{if $small === true}}cProfileHeaderMinimal{{endif}}' id='elProfileHeader' data-controller='core.global.core.coverPhoto' data-url="{$member->url()->csrf()}" data-coverOffset='{$coverPhoto->offset}'>
		{{if $coverPhoto->file}}
			<div class='ipsCoverPhoto_container'>
				{{if settings.lazy_load_enabled}}
					<img src='{expression="\IPS\Text\Parser::blankImage()"}' data-src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo' data-action="toggleCoverPhoto" alt=''>
				{{else}}
					<img src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo' data-action="toggleCoverPhoto" alt=''>
				{{endif}}
			</div>
		{{else}}
			<div class='ipsCoverPhoto_container' style="background-color: {$member->coverPhotoBackgroundColor()}">
				<img src='{resource="pattern.png" app="core" location="global"}' class='ipsCoverPhoto_photo' data-action="toggleCoverPhoto" alt=''>
			</div>
		{{endif}}
		{{if \IPS\Member::loggedIn()->modPermission('can_modify_profiles') or ( \IPS\Member::loggedIn()->member_id == $member->member_id and $member->group['g_edit_profile'] )}}
			<ul class='ipsButton_split' id='elEditProfile' data-hideOnCoverEdit>
				<li>
					<a href='{url="app=core&module=members&controller=profile&do=edit&id={$member->member_id}" base="front" seoTemplate="edit_profile" seoTitle="$member->members_seo_name"}' class='ipsButton ipsButton_small ipsButton_overlaid' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-title='{lang="profile_edit"}'>
						<i class='fa fa-pencil'></i>&nbsp;<span class='ipsResponsive_hidePhone ipsResponsive_inline'>&nbsp;&nbsp;{lang="profile_edit"}</span>
					</a>
				</li>
				{{if $coverPhoto->editable}}
					<li>
					<a href='#elEditPhoto_menu' data-hideOnCoverEdit class='ipsButton ipsButton_small ipsButton_overlaid' data-ipsMenu id='elEditPhoto' data-role='coverPhotoOptions'>
						<i class='fa fa-picture-o'></i>&nbsp;<span class='ipsResponsive_hidePhone ipsResponsive_inline'>&nbsp;&nbsp;{lang="profile_edit_cover_photo_tab"} <i class='fa fa-caret-down'></i></span>
					</a>
					<ul class='ipsMenu ipsMenu_auto ipsHide' id='elEditPhoto_menu'>
						{{if $coverPhoto->file}}
						<li class='ipsMenu_item' data-role="photoEditOption">
							<a href='{$member->url()->setQueryString( 'do', 'coverPhotoRemove' )->csrf()}' data-action='removeCoverPhoto'>{lang="cover_photo_remove"}</a>
						</li>
						<li class='ipsMenu_item ipsHide' data-role="photoEditOption">
							<a href='#' data-action='positionCoverPhoto'>{lang="cover_photo_reposition"}</a>
						</li>
						{{endif}}
						<li class='ipsMenu_item'>
							<a href='{$member->url()->setQueryString( 'do', 'coverPhotoUpload' )}' data-ipsDialog data-ipsDialog-title="{lang="cover_photo_add"}">{lang="cover_photo_add"}</a>
						</li>
					</ul>
				</li>
				{{endif}}
			</ul>
			
		{{endif}}
		<div class='ipsColumns ipsColumns_collapsePhone' data-hideOnCoverEdit>
			<div class='ipsColumn ipsColumn_fixed ipsColumn_narrow ipsPos_center' id='elProfilePhoto'>
				{{if $member->pp_main_photo and ( mb_substr( $member->pp_photo_type, 0, 5 ) === 'sync-' or $member->pp_photo_type === 'custom' )}}
					<a href="{file="$member->pp_main_photo" extension="core_Profile"}" data-ipsLightbox class='ipsUserPhoto ipsUserPhoto_xlarge'>					
						<img src='{$member->photo}' alt=''>
					</a>
				{{else}}
					<span class='ipsUserPhoto ipsUserPhoto_xlarge'>					
						<img src='{$member->photo}' alt=''>
					</span>
				{{endif}}
				{{if ( \IPS\Member::loggedIn()->modPermission('can_modify_profiles') or ( \IPS\Member::loggedIn()->member_id == $member->member_id and $member->group['g_edit_profile'] ) ) AND explode( ':', $member->group['g_photo_max_vars'] )[0]}}
					<a href='{url="app=core&module=members&controller=profile&do=editPhoto&id={$member->member_id}" base="front" seoTemplate="edit_profile_photo" seoTitle="$member->members_seo_name"}' class='ipsButton ipsButton_verySmall ipsButton_light ipsButton_narrow' data-action='editPhoto' data-ipsDialog data-ipsDialog-forceReload='true' data-ipsDialog-modal='true' data-ipsDialog-title='{lang="profile_edit_photo_tab"}' title='{lang="profile_edit_photo_tab"}' data-ipsTooltip><i class='fa fa-photo'></i></a>
				{{endif}}
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				<div class='ipsPos_left ipsPad cProfileHeader_name ipsType_normal'>
					<h1 class='ipsType_reset ipsPageHead_barText'>
						{$member->name}

						{{if \IPS\Member::loggedIn()->group['g_view_displaynamehistory'] AND $member->hasNameChanges()}}
							<a href='{$member->url()->setQueryString( 'do', 'namehistory' )}' class='cProfileHeader_history ipsType_large ipsPos_right' title='{lang="membername_history"}' data-ipsTooltip data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="membername_history"}'>
								<i class='fa fa-history'></i></span>
							</a>
						{{endif}}
                        {{if \IPS\Member::loggedIn()->member_id AND \IPS\Member::loggedIn()->member_id === $member->member_id AND $member->isOnlineAnonymously()}}
                            <span class='cProfileHeader_history ipsType_large ipsPos_right' title='{lang="member_is_currently_anon"}' data-ipsTooltip>
                                <i class='fa fa-eye-slash'></i>
                            </span>
                        {{endif}}
					</h1>
					<span>
						<span class='ipsPageHead_barText'>{expression="\IPS\Member\Group::load( $member->member_group_id )->formattedName" raw="true"}</span>
					</span>
				</div>
				{{if \IPS\Member::loggedIn()->member_id != $member->member_id}}
					<ul class='ipsList_inline ipsPad ipsResponsive_hidePhone ipsResponsive_block ipsPos_left'>
						{{if \IPS\Member::loggedIn()->member_id != $member->member_id and ( !$member->members_bitoptions['pp_setting_moderate_followers'] or \IPS\Member::loggedIn()->following( 'core', 'member', $member->member_id ) )}}
							<li>{template="memberFollow" app="core" group="profile" params="'core', 'member', $member->member_id, $member->followersCount()"}</li>
						{{endif}}
						{{if \IPS\Member::loggedIn()->member_id && !$member->members_disable_pm and !\IPS\Member::loggedIn()->members_disable_pm and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'messaging' ) )}}
							<li><a href='{url="app=core&module=messaging&controller=messenger&do=compose&to={$member->member_id}" seoTemplate="messenger_compose"}' data-ipsDialog data-ipsDialog-title='{lang="compose_new"}' data-ipsDialog-remoteSubmit data-ipsDialog-flashMessage="{lang="message_sent"}" class='ipsButton ipsButton_primary'><i class='fa fa-envelope'></i> <span class='ipsResponsive_showDesktop ipsResponsive_inline'>&nbsp; {lang="message_send"}</span></a></li>
						{{endif}}
					</ul>
				{{endif}}
			</div>
		</div>
	</div>

	<div class='ipsGrid ipsAreaBackground ipsPad ipsResponsive_showPhone ipsResponsive_block'>
		{{$span = 1;}}
		{{if \IPS\Member::loggedIn()->member_id && \IPS\Member::loggedIn()->member_id != $member->member_id and !$member->members_bitoptions['pp_setting_moderate_followers']}}
			{{$span++;}}
		{{endif}}
		{{if \IPS\Member::loggedIn()->member_id != $member->member_id && \IPS\Member::loggedIn()->member_id && !$member->members_disable_pm and !\IPS\Member::loggedIn()->members_disable_pm}}
			{{$span++;}}
		{{endif}}

		{{if \IPS\Member::loggedIn()->member_id && \IPS\Member::loggedIn()->member_id != $member->member_id and !$member->members_bitoptions['pp_setting_moderate_followers']}}
			<div class='ipsGrid_span{{if $span == 1}}12{{elseif $span == 2}}6{{else}}4{{endif}}'>
				{template="memberFollow" app="core" group="profile" params="'core', 'member', $member->member_id, $member->followersCount()"}
			</div>
		{{endif}}
		{{if \IPS\Member::loggedIn()->member_id != $member->member_id && \IPS\Member::loggedIn()->member_id && !$member->members_disable_pm and !\IPS\Member::loggedIn()->members_disable_pm}}
			<a href='{url="app=core&module=messaging&controller=messenger&do=compose&to={$member->member_id}" seoTemplate="messenger_compose"}' data-ipsDialog data-ipsDialog-title='{lang="compose_new"}' data-ipsDialog-remoteSubmit data-ipsDialog-flashMessage="{lang="message_sent"}" data-ipsDialog-forceReload class='ipsGrid_span{{if $span == 1}}12{{elseif $span == 2}}6{{else}}4{{endif}} ipsButton ipsButton_alternate ipsButton_small'><i class='
			fa fa-envelope'></i> <i class='fa fa-caret-right'></i></a>
		{{endif}}
		<div data-role='switchView' class='ipsGrid_span{{if $span == 1}}12{{elseif $span == 2}}6{{else}}4{{endif}}'>
			<div data-action="goToProfile" data-type='phone' class='{{if $small != true}}ipsHide{{endif}}'>
				<a href='{$member->url()}' class='ipsButton ipsButton_veryLight ipsButton_small ipsButton_fullWidth' title="{lang="members_profile" sprintf="$member->name"}"><i class='fa fa-user'></i></a>
			</div>
			<div data-action="browseContent" data-type='phone' class='{{if $small == true}}ipsHide{{endif}}'>
				<a href="{url="app=core&module=members&controller=profile&do=content&id={$member->member_id}" base="front" seoTemplate="profile_content" seoTitle="$member->members_seo_name"}" class='ipsButton ipsButton_veryLight ipsButton_small ipsButton_fullWidth'  title="{lang="members_content" sprintf="$member->name"}"><i class='fa fa-newspaper-o'></i></a>
			</div>
		</div>
	</div>

	<div id='elProfileStats' class='ipsClearfix sm:ipsPadding ipsResponsive_pull'>
		<div data-role='switchView' class='ipsResponsive_hidePhone ipsPos_right'>
			<a href='{$member->url()}' class='ipsButton ipsButton_veryLight ipsButton_small ipsPos_right {{if $small != true}}ipsHide{{endif}}' data-action="goToProfile" data-type='full' title="{lang="members_profile" sprintf="$member->name"}"><i class='fa fa-user'></i> <span class='ipsResponsive_showDesktop ipsResponsive_inline'>&nbsp;{lang="profile_view_profile"}</span></a>
			<a href="{url="app=core&module=members&controller=profile&do=content&id={$member->member_id}" base="front" seoTemplate="profile_content" seoTitle="$member->members_seo_name"}" class='ipsButton ipsButton_veryLight ipsButton_small ipsPos_right {{if $small == true}}ipsHide{{endif}}' data-action="browseContent" data-type='full' title="{lang="members_content" sprintf="$member->name"}"><i class='fa fa-newspaper-o'></i> <span class='ipsResponsive_showDesktop ipsResponsive_inline'>&nbsp;{{if member.member_id === $member->member_id}}{lang="profile_browse_my_content"}{{else}}{lang="profile_browse_content"}{{endif}}</span></a>
		</div>
		<ul class='ipsList_reset ipsFlex ipsFlex-ai:center ipsFlex-fw:wrap ipsPos_left ipsResponsive_noFloat'>
			<li>
				<h4 class='ipsType_minorHeading'>{lang="members_member_posts"}</h4>
				{number="$member->member_posts"}
			</li>
			<li>
				<h4 class='ipsType_minorHeading'>{lang="joined"}</h4>
				{datetime="$member->joined"}
			</li>
            {{if ( !$member->isOnlineAnonymously() ) OR ( $member->isOnlineAnonymously() AND \IPS\Member::loggedIn()->isAdmin() )}}
			<li>
				<h4 class='ipsType_minorHeading'>{lang="members_last_visit"}</h4>
				<span>
					{{if $member->isOnline() AND ( !$member->isOnlineAnonymously() OR ( $member->isOnlineAnonymously() AND \IPS\Member::loggedIn()->isAdmin() ) )}}
                    	<i class="fa fa-circle ipsOnlineStatus_online" data-ipsTooltip title='{{if $member->isOnlineAnonymously()}}{lang="online_now_anon" sprintf="$member->name"}{{elseif $member->isOnline()}}{lang="online_now" sprintf="$member->name"}{{endif}}'></i>
                    {{endif}}
                    {{if $member->last_activity}}{datetime="$member->last_activity"}{{else}}{lang="never"}{{endif}}
				</span>
			</li>
            {{endif}}
			{{if settings.reputation_leaderboard_on and settings.reputation_show_days_won_trophy and $member->getReputationDaysWonCount()}}
			<li>
				<h4 class='ipsType_minorHeading'>{lang="members_days_won_count"}</h4>
				<span data-ipsTooltip title='{lang="members_days_won_count_desc" sprintf="$member->name"}'>{number="$member->getReputationDaysWonCount()"}</span>
			</li>
			{{endif}}
		</ul>
	</div>
</header>