<ips:template parameters="$member, $tabs, $activeTab, $activeTabContents" />
{{if \count( $tabs ) > 1}}
	<div class='ipsTabs ipsTabs_stretch ipsClearfix' id='elProfileTabs' data-ipsTabBar data-ipsTabBar-contentArea='#elProfileTabs_content'>
		<a href='#elProfileTabs' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
		<ul role="tablist">
			{{foreach $tabs as $tab => $title}}
				<li>
					<a href='{$member->url()->setQueryString( 'tab', $tab )}' id='elProfileTab_{$tab}' class='ipsTabs_item ipsType_center {{if $activeTab == $tab}}ipsTabs_activeItem{{endif}}' role="tab" aria-selected="{{if $activeTab == $tab}}true{{else}}false{{endif}}">{lang="$title"}</a>
				</li>
			{{endforeach}}
		</ul>
	</div>
{{endif}}
<div id='elProfileTabs_content' class='ipsTabs_panels ipsPadding ipsAreaBackground_reset'>
	{{foreach $tabs as $tab => $title}}
		{{if $activeTab == $tab}}
			<div id="ipsTabs_elProfileTabs_elProfileTab_{$tab}_panel" class='ipsTabs_panel ipsAreaBackground_reset'>
				{$activeTabContents|raw}
			</div>
		{{endif}}
	{{endforeach}}
</div>