<ips:template parameters="$member, $types, $currentAppModule, $currentType, $table" />
<div class='ipsBox'>
	<h2 class='ipsType_sectionTitle ipsType_reset'>{{if !$currentAppModule}}{lang="all_content_by_user" sprintf="$member->name"}{{else}}{lang="content_by_user" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $types[ $currentAppModule ][ $currentType ]::$title . '_pl' ), $member->name"}{{endif}}</h2>
	{$table|raw}
</div>