<ips:template parameters="$member, $types, $currentAppModule, $currentType, $table" />
{{$baseUrl = \IPS\Http\Url::internal( "app=core&module=members&controller=profile&id={$member->member_id}&do=content", 'front', 'profile_content', $member->members_seo_name );}}
{{if !\IPS\Request::i()->isAjax()}}
<div data-controller='core.front.profile.main' id='elProfileUserContent'>
	{template="profileHeader" app="core" location="front" group="profile" params="$member, true"}
	<div data-role="profileContent" class='ipsSpacer_top'>
{{endif}}
		<div class="ipsColumns ipsColumns_collapsePhone">
			<div class="ipsColumn ipsColumn_wide">
				<div class='ipsPadding:half ipsBox'>
					<div class="ipsSideMenu" data-ipsTabBar data-ipsTabBar-contentArea='#elUserContent' data-ipsTabBar-itemselector=".ipsSideMenu_item" data-ipsTabBar-activeClass="ipsSideMenu_itemActive" data-ipsSideMenu>
						<h3 class="ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium">
							<a href="#user_content" class="ipsPad_double" data-action="openSideMenu"><i class="fa fa-bars"></i> &nbsp;{lang="user_content_type"}&nbsp;<i class="fa fa-caret-down"></i></a>
						</h3>
						<div>
							<ul class="ipsSideMenu_list">
								<li><a href="{$baseUrl->setQueryString( array( 'change_section' => 1 ) )}" class="ipsSideMenu_item {{if !$currentType}}ipsSideMenu_itemActive{{endif}}">{lang="all_activity"}</a></li>
							</ul>
							{{foreach $types as $app => $_types}}
								<h4 class='ipsSideMenu_subTitle'>{lang="module__{$app}"}</h4>
								<ul class="ipsSideMenu_list">
									{{foreach $_types as $key => $class}}
										<li><a href="{$baseUrl->setQueryString( array( 'type' => $key, 'change_section' => 1 ) )}" class="ipsSideMenu_item {{if $currentType == $key}}ipsSideMenu_itemActive{{endif}}">{lang="{$class::$title}_pl"}</a></li>
									{{endforeach}}
								</ul>
							{{endforeach}}
						</div>			
					</div>
				</div>
			</div>
			<div class="ipsColumn ipsColumn_fluid" id='elUserContent'>
				{template="userContentSection" group="profile" app="core" params="$member, $types, $currentAppModule, $currentType, $table"}
			</div>
		</div>
{{if !\IPS\Request::i()->isAjax()}}
	</div>
</div>
{{endif}}