<ips:template parameters="$item, $size = 'verySmall', $type = 'link'" />
{{$id = mt_rand();}}
{{if \count( $item->sharelinks() ) }}
    <a href='#elShareItem_{$id}_menu' id='elShareItem_{$id}' data-ipsMenu class='ipsShareButton ipsButton ipsButton_{$size} ipsButton_{$type} {{if $type == 'link'}}ipsButton_link--light{{endif}}'>
        <span><i class='fa fa-share-alt'></i></span> &nbsp;{lang="share"}
    </a>

    <div class='ipsPadding ipsMenu ipsMenu_auto ipsHide' id='elShareItem_{$id}_menu' data-controller="core.front.core.sharelink">
        <ul class='ipsList_inline'>
            {{foreach $item->sharelinks() as $sharelink }}
                <li>{$sharelink|raw}</li>
            {{endforeach}}
        </ul>
    </div>
{{endif}}