<ips:template parameters="$table" />
<div class=''>
	<a href='{url="app=core&module=modcp&tab=announcements&action=create" seoTemplate="modcp_announcements"}' id='elAdd_Announcement' class='ipsButton ipsButton_primary ipsPos_right' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-title='{lang="add_announcement"}'><i class='fa fa-add'></i>&nbsp;<span class='ipsResponsive_inline'>{lang="add_announcement"}</span></a>
	<br><br><br>
	<div class='ipsClear ipsBox'>
		{$table|raw}
	</div>
</div>