<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	<li class="ipsDataItem sm:ipsPadding {{if $row->active !== 1}}ipsFaded ipsFaded_withHover{{endif}} ipsDataItem_unread {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if !$row->active}}ipsModerated{{endif}} cModCPAnnouncementRow">
		<div class='ipsDataItem_icon ipsPos_top ipsResponsive_hidePhone'>
			{template="userPhoto" app="core" group="global" params="$row->author(), 'tiny'"}
		</div>
		<div class='ipsDataItem_main'>
			<h4 class='ipsDataItem_title ipsContained_container'>
				<span class='ipsType_break ipsContained'>
					<a href='{$row->url()}' title='{lang="view_announcement"}'>
						{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}
					</a>
					&nbsp;&nbsp;
					{{if $row->active}}
						<span class='ipsBadge ipsBadge_new'>{lang="active"}</span>
					{{else}}
						<span class='ipsBadge ipsBadge_style5'>{lang="inactive"}</span>
					{{endif}}
				</span>
			</h4>
			<p class='ipsType_reset ipsType_light'>{lang="byline" sprintf="$row->author()->name"}{datetime="$row->__get( $row::$databaseColumnMap['date'] )" dateonly="true"}</p>
			<div class='ipsDataItem_meta ipsType_break ipsMargin_top:half'>
				{{$truncateAttributes = array('data-ipsTruncate', 'data-ipsTruncate-size="4 lines"', 'data-ipsTruncate-type="hide"');}}
				{template="richText" group="global" app="core" location="global" params="$row->content(), array('ipsType_medium', 'ipsContained'), array(), $truncateAttributes"}
			</div>
		</div>
		{{if $table->canModerate()}}
			<div class='ipsDataItem_modCheck ipsType_noBreak ipsPos_center'>
				<a href='#elAnnouncement{$row->id}_menu' id='elAnnouncement{$row->id}' class='ipsType_large ipsPos_middle ipsType_blendLinks' data-ipsMenu>
					<i class='fa fa-cog'></i> <i class='fa fa-caret-down'></i>
				</a>
				<input type='checkbox' data-role='moderation' name="moderate[{$row->id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{$row->tableStates()}'>

				<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide' id='elAnnouncement{$row->id}_menu'>
					<li class='ipsMenu_item'>
						<a href='{$row->url('status')->csrf()}' title='{lang="announce_toggle"}'>
							<span data-role="ipsMenu_selectedText">{{if $row->active}}{lang="announce_mark_inactive"}{{else}}{lang="announce_mark_active"}{{endif}}</span>
						</a>
					</li>
					<li class='ipsMenu_item'>
						<a href='{$row->url('create')}' title='{lang="edit_announcement"}' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-destructOnClose='true' data-ipsDialog-title='{lang="edit_announcement"}'>
							<span data-role="ipsMenu_selectedText">{lang="edit"}</span>
						</a>
					</li>
					<li class='ipsMenu_sep'></li>
					<li class='ipsMenu_item'>
						<a href='{$row->url('delete')->csrf()}' data-confirm title='{lang="announce_delete"}'>
							{lang="delete"}
						</a>
					</li>
				</ul>
			</div>
		{{endif}}
	</li>
{{endforeach}}