<ips:template parameters="$item, $ref, $container, $title" />
<div id="elApprovePanel" class='ipsBox'>
	<article class="ipsClearfix ipsClear">
		<div class='ipsAreaBackground_light ipsBorder_bottom ipsPadding'>
			<p class="ipsType_reset ipsPos_right">
				<a href='{$item->url()}' class='ipsType_normal ipsType_light'>
					<i class='fa fa-{$item::$icon}'></i> {lang="$item::$title"}
				</a>
			</p>
			<div class="ipsPhotoPanel ipsPhotoPanel_small ipsClearfix"> 
				{template="userPhoto" group="global" params="$item->author()"}
				<div>
					<a href="#user{$item->author()->member_id}_menu" id="user{$item->author()->member_id}" class="ipsType_sectionHead" data-ipsmenu="">{$item->author()->name} &nbsp;<i class="fa fa-caret-down"></i></a>
					<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="user{$item->author()->member_id}_menu">
						{{if \IPS\Member::loggedIn()->modPermission('mod_can_warn')}}
							<li class='ipsMenu_item'><a href='{url="app=core&module=system&controller=warnings&do=warn&id={$item->author()->member_id}&ref={$ref}" seoTemplate="warn_add" seoTitle="$item->author()->members_seo_name"}' data-ipsDialog data-ipsDialog-title="{lang="warn_member" sprintf="$item->author()->name"}" data-ipsDialog-remoteSubmit data-ipsDialog-destructOnClose data-ipsDialog-flashMessage="{lang="warning_issued"}" data-role="warnUserDialog">{lang="warn_user"}</a></li>
						{{endif}}
						{{if $item->author()->member_id != \IPS\Member::loggedIn()->member_id}}
							{{if $item->author()->members_bitoptions['bw_is_spammer']}}
								<li class='ipsMenu_item' data-ipsMenuValue='spamFlagButton'><a href='{url="app=core&module=system&controller=moderation&do=flagAsSpammer&id={$item->author()->member_id}&s=0" seoTemplate="flag_as_spammer" seoTitle="$item->author()->members_seo_name" csrf="true"}' data-confirm data-confirmSubMessage="{lang="spam_unflag_confirm"}">{lang="spam_unflag"}</a></li>
							{{else}}
								<li class='ipsMenu_item' data-ipsMenuValue='spamFlagButton'><a href='{url="app=core&module=system&controller=moderation&do=flagAsSpammer&id={$item->author()->member_id}&s=1" seoTemplate="flag_as_spammer" seoTitle="$item->author()->members_seo_name" csrf="true"}' data-confirm>{lang="spam_flag"}</a></li>
							{{endif}}
						{{endif}}
						<li class="ipsMenu_item"><a href='{url="app=core&module=messaging&controller=messenger&do=compose&to={$item->author()->member_id}" seoTemplate="messenger_compose"}' data-ipsDialog data-ipsDialog-title='{lang="compose_new"}' data-ipsDialog-remoteSubmit data-ipsDialog-flashMessage="{lang="message_sent"}">{lang="message_send"}</a></li>
					</ul>
					{{if $container}}
						<p class='ipsType_reset'>{lang="posted_in_container"} <a href="{$container->url()}">{$container->_title}</a></p>
					{{endif}}
					<p class="ipsType_light ipsType_reset">{lang="date_replied" htmlsprintf="\IPS\DateTime::ts( $item->mapped('date') )->html(FALSE)"}</p>
				</div>
			</div>
		</div>
		<div class=''>
			<h2 class="ipsType_sectionTitle ipsType_blendLinks"><a href="{$item->url()}">{$title}</a></h2>
			<div class="ipsType_richText ipsPost ipsType_normal ipsPadding" data-controller='core.front.core.lightboxedImages'>
				{$item->content()|raw}
			</div>
		</div>
	</article>
</div>
