<ips:template parameters="$table, $headers, $rows" />
{{if empty( $rows )}}
	<tr>
		<td colspan="{expression="\count( $headers )"}">
			<div class='ipsPad_double ipsType_light'>
				{lang="no_results"}
			</div>
		</td>
	</tr>
{{else}}
	{{foreach $rows as $r}}
		<tr class='ipsClearfix'>
			{{foreach $r as $k => $v}}
				<td>
					{{if $k === '_buttons'}}
						{template="controlStrip" params="$v" group="global" app="core"}
					{{else}}
						{$v|raw}
					{{endif}}
				</td>
			{{endforeach}}
		</tr>
	{{endforeach}}
{{endif}}