<ips:template parameters="$content, $tabs, $activeTab, $form" />
<div class='ipsBox ipsPadding ipsFieldRow ipsFieldRow_primary ipsBox' id='elModCPMemberSearch'>
	{$form|raw}
</div>
<div class='ipsBox'>
	<div class='ipsTabs ipsClearfix' id='elmodCPTabs' data-ipsTabBar data-ipsTabBar-contentArea='#elModCPMemberTabContent'>
		<a href='#elmodCPTabs' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
		<ul role='tablist' class='ipsList_reset'>
			{{foreach $tabs as $key => $tab}}
				<li>
					<a href='{url="app=core&module=modcp&tab=members&area=$key" seoTemplate="modcp_members"}' id='modcp_{$key}' class='ipsTabs_item {{if $activeTab === $key}}ipsTabs_activeItem{{endif}}' role="tab" aria-selected="{{if $activeTab == $tab}}true{{else}}false{{endif}}">
						{lang="modcp_members_{$key}"}
					</a>
				</li>
			{{endforeach}}
		</ul>
	</div>
	<section id='elModCPMemberTabContent' class='ipsPad'>
		<div id="ipsTabs_elmodCPTabs_modcp_{$activeTab}_panel" class="ipsTabs_panel" aria-labelledby="modcp_{$activeTab}" aria-hidden="false">
			{$content|raw}
		</div>
	</section>
</div>