<ips:template parameters="$table, $headers, $rows, $quickSearch, $advancedSearch" />
<ol class='ipsDataList'>
	{{if \count($rows)}}
		{{foreach $rows as $row}}
			<li class="ipsDataItem {{if $row->unread()}}ipsDataItem_unread{{endif}}">
				<div class='ipsDataItem_icon ipsPos_top ipsType_center'>
					<i class='ipsType_large {{if $row->status == 1}}fa fa-flag{{elseif $row->status == 2}}fa fa-exclamation-triangle{{else}}fa fa-check-circle{{endif}}' data-role="ipsMenu_selectedIcon" title="{{if $row->status == 1}}{lang="report_status_1"}{{elseif $row->status == 2}}{lang="report_status_2"}{{else}}{lang="report_status_3"}{{endif}}" data-ipsTooltip></i>
				</div>
				<div class="ipsDataItem_main ipsType_break">
					<h4 class="ipsDataItem_title"><a href='{$row->url()}'>{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}</a></h4>
					<ul class="ipsDataItem_meta ipsList_inline">
						<li class='ipsType_light'>
							{{if $row->last_updated}}{datetime="$row->last_updated"}{{else}}{datetime="$row->first_report_date"}{{endif}}
						</li>
						{{foreach $row->stats() as $k => $v}}
							<li>
								<span class='ipsDataItem_stats_number'>{number="$v"}</span>
								<span class='ipsDataItem_stats_type'>{lang="$k" pluralize="$v"}</span>
							</li>
						{{endforeach}}
					</ul>
				</div>
				<div class='ipsDataItem_generic ipsDataItem_size1 ipsResponsive_hidePhone ipsResponsive_hideTablet ipsType_center'>
					{{if $lastComment = $row->comments( 1, 0, 'date', 'desc' )}}
						{template="userPhoto" app="core" group="global" params="$lastComment->author(), 'tiny'"}
					{{else}}
						{template="userPhoto" app="core" group="global" params="$row->author(), 'tiny'"}
					{{endif}}
				</div>
			</li>
		{{endforeach}}
	{{else}}
		<li class='ipsDataItem'>
			<div class='ipsPad ipsType_light ipsType_center ipsType_normal'>{lang="no_results_reports"}</div>
		</li>
	{{endif}}
</ol>