<ips:template parameters="$report,$comment,$item,$ref,$prevReport,$prevItem,$nextReport,$nextItem,$delLog=NULL" />
{{if $comment}}
	{{$idField = $comment::$databaseColumnId;}}
	{{$quoteData = json_encode( array( 'userid' => $comment->author()->member_id, 'username' => $comment->author()->name, 'timestamp' => $comment->mapped('date'), 'contentapp' => $item::$application, 'contenttype' => $item::$module, 'contentclass' => str_replace( '\\', '_', mb_substr( $comment::$itemClass, 4 ) ) ) );}}
{{else}}
	{{if $item}}
		{{$class = \get_class( $item );}}
		{{$quoteData = json_encode( array( 'userid' => $item->author()->member_id, 'username' => $item->author()->name, 'timestamp' => $item->mapped('date'), 'contentapp' => $item::$application, 'contenttype' => $item::$module, 'contentclass' => str_replace( '\\', '_', mb_substr( \get_class( $item ), 4 ) ) ) );}}
	{{else}}
		{{$quoteData = json_encode( array() );}}
	{{endif}}
{{endif}}
{{$pointCount = $report->getReportTypeCounts( true );}}
{{$filterByType = isset( \IPS\Request::i()->report_type ) ? \IPS\Request::i()->report_type : NULL;}}
<div class='ipsBox ipsPadding'>
	<article class='ipsColumns ipsColumns_collapseTablet ipsClear ipsClearfix' data-controller="core.front.modcp.report">
		<div class='ipsColumn ipsColumn_fluid' data-controller='core.front.core.comment' data-quoteData='{$quoteData}'>
			{{if $comment AND !( $item::$firstCommentRequired and $comment->isFirst() )}}
				{{if $comment->hidden() === -2}}
					<div class="ipsType_center ipsType_large ipsEmpty">
						<i class='fa fa-trash-o'></i>
						<br>
						{{if $delLog}}
							{lang="content_delete_pending" sprintf="$delLog->deletion_date"}
						{{else}}
							{lang="content_deleted"}
						{{endif}}
							</div>
						{{if $delLog}}
							<hr class='ipsHr'>
							<div class="ipsClearfix" id='elReportComment'>
								<div class='ipsPost' data-role='commentContent'>
									<div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="50 lines">
										<div class='ipsType_richText ipsType_normal ipsContained' data-controller='core.front.core.lightboxedImages'>
											{$comment->content()|raw}
										</div>
									</div>
									<hr class='ipsHr'>
									<ul class='ipsList_inline' data-role="commentControls">
										{{if \IPS\Member::loggedIn()->modPermission('can_manage_deleted_content')}}
											<li><a href='{$comment->url('restore')->csrf()->setQueryString( '_report', $report->id )}' data-confirm data-confirmSubMessage='{lang="restore_as_visible_desc"}'>{lang="restore_as_visible"}</a></li>
											<li><a href='{$comment->url('restore')->csrf()->setQueryString( array( 'restoreAsHidden' => 1, '_report' => $report->id ) )}' data-confirm data-confirmSubMessage='{lang="restore_as_hidden_desc"}'>{lang="restore_as_hidden"}</a></li>
											<li><a href='{$comment->url('delete')->csrf()->setQueryString( array( 'immediate' => 1, '_report' => $report->id ) )}' data-confirm data-confirmSubMessage='{lang="delete_immediately_desc"}'>{lang="delete_immediately"}</a></li>
										{{endif}}
									</ul>
								</div>
							</div>
						{{endif}}
				{{else}}
					<div class="ipsClearfix" id='elReportComment'>
						<h2 class="ipsType_pageTitle">
							<a href='{$report->url()->setQueryString( array( 'action' => 'find', 'parent' => 1 ) )}' class='ipsType_blendLinks'>{$comment->item()->mapped('title')}</a>
						</h2>
						<a href='{$report->url()->setQueryString( array( 'action' => 'find' ) )}' class='ipsType_normal ipsType_light'>
							{$report->tableDescription()|raw}
						</a>
						{{if $pointCount}}<span class="ipsBadge ipsBadge_positive">{lang="automoderation_report_points_flag" pluralize="$pointCount"}</span>{{endif}}
						<br><br>
						<div class='ipsPost' data-role='commentContent'>
							<div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="50 lines">
								<div class='ipsType_richText ipsType_normal ipsContained' data-controller='core.front.core.lightboxedImages'>
									{$comment->content()|raw}
								</div>
							</div>
						</div>
						<hr class='ipsHr'>
						<ul class='ipsList_inline' data-role="commentControls">
							{{if $comment->canEdit( \IPS\Member::loggedIn() )}}
								<li><a href='{$comment->url('edit')}&_report={$report->id}' data-action='editComment'>{lang="edit"}</a></li>
							{{endif}}
							{{if $comment->canHide( \IPS\Member::loggedIn() )}}
								<li><a href='{$comment->url('hide')->csrf()}&_report={$report->id}' data-action='hideComment' {{if isset( $comment::$databaseColumnMap['edit_reason'] )}}data-ipsDialog data-ipsDialog-title="{lang="hide"}"{{endif}}>{lang="hide"}</a></li>
							{{endif}}
							{{if $comment->canDelete( \IPS\Member::loggedIn() )}}
								<li><a href='{$comment->url('delete')->csrf()->setPage('page',\IPS\Request::i()->page)}&_report={$report->id}' {{if !\IPS\Settings::i()->dellog_retention_period}}data-action='deleteComment' data-showOnDelete="#elReportCommentDeleted" data-hideOnDelete="#elReportComment"{{else}}data-confirm{{endif}}>{lang="delete"}</a></li>
							{{endif}}
							{{if $comment->item()->canDelete( \IPS\Member::loggedIn() )}}
								<li><a href='{$item->url('moderate')->setQueryString( 'action', 'delete' )->csrf()}&_report={$report->id}' {{if !\IPS\Settings::i()->dellog_retention_period}}data-action='deleteComment' data-showOnDelete="#elReportCommentDeleted" data-hideOnDelete="#elReportComment"{{else}}data-confirm{{endif}}>{lang="delete_thing" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $item::$title )"}</a></li>
							{{endif}}
						</ul>
					</div>
				{{endif}}
			{{elseif $item}}
				{{if $item->hidden() === -2}}
					<div class="ipsType_center ipsType_large ipsEmpty">
						<i class='fa fa-trash-o'></i>
						<br>
						{{if $delLog}}
							{lang="content_delete_pending" sprintf="$delLog->deletion_date"}
						{{else}}
							{lang="content_deleted"}
						{{endif}}
						</div>

						{{if $delLog}}
							<hr class='ipsHr'>
							<div class='ipsPost' data-role='commentContent'>
								<div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="50 lines">
									<div class='ipsType_richText ipsType_normal ipsContained' data-controller='core.front.core.lightboxedImages'>
										{$item->content()|raw}
									</div>
								</div>
								<hr class='ipsHr'>
								<ul class='ipsList_inline' data-role="commentControls">
									{{if \IPS\Member::loggedIn()->modPermission('can_manage_deleted_content')}}
										<li><a href='{$item->url('restore')->csrf()->setQueryString( '_report', $report->id )}' data-confirm data-confirmSubMessage='{lang="restore_as_visible_desc"}'>{lang="restore_as_visible"}</a></li>
										<li><a href='{$item->url('restore')->csrf()->setQueryString( array( 'restoreAsHidden' => 1, '_report' => $report->id ) )}' data-confirm data-confirmSubMessage='{lang="restore_as_hidden_desc"}'>{lang="restore_as_hidden"}</a></li>
										<li><a href='{$item->url('moderate')->csrf()->setQueryString( array( 'action' => 'delete', 'immediate' => 1, '_report' => $report->id ) )}' data-confirm data-confirmSubMessage='{lang="delete_immediately_desc"}'>{lang="delete_immediately"}</a></li>
									{{endif}}
								</ul>
							</div>
						{{endif}}
				{{else}}
					<div class="ipsClearfix ipsPad" id='elReportComment'>
						<h2 class="ipsType_sectionHead">
							<a href='{$report->url()->setQueryString( 'action', 'find' )}' class='ipsType_blendLinks'>{$item->mapped('title')}</a>
						</h2>
						<br>
						<a href='{$report->url()->setQueryString( array( 'action' => 'find' ) )}' class='ipsType_normal ipsType_light'>
							<i class='fa fa-{$item::$icon}'></i> {lang="$item::$title"}
						</a>
						{{if $pointCount}}<span class="ipsBadge ipsBadge_positive">{lang="automoderation_report_points_flag" pluralize="$pointCount"}</span>{{endif}}
						<br><br>
						<div class='ipsPost' data-role='commentContent'>
							<div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="50 lines">
								<div class='ipsType_richText ipsType_normal ipsContained' data-controller='core.front.core.lightboxedImages'>
									{$item->content()|raw}
								</div>
							</div>
						</div>
						<hr class='ipsHr'>
						<ul class='ipsList_inline' data-role="commentControls">
							{{if $item->canEdit( \IPS\Member::loggedIn() )}}
								<li><a href='{$item->url('edit')}&_report={$report->id}' data-action='editComment'>{lang="edit"}</a></li>
							{{endif}}
							{{if $item->canHide( \IPS\Member::loggedIn() )}}
								<li><a href='{$item->url('moderate')->setQueryString( 'action', 'hide' )->csrf()}&_report={$report->id}' data-action='hideComment' data-ipsDialog data-ipsDialog-title="{lang="hide"}">{lang="hide"}</a></li>
							{{endif}}
							{{if $item->canDelete( \IPS\Member::loggedIn() )}}
								<li><a href='{$item->url('moderate')->setQueryString( 'action', 'delete' )->csrf()->setPage('page',\IPS\Request::i()->page)}&_report={$report->id}' {{if !\IPS\Settings::i()->dellog_retention_period}}data-action='deleteComment' data-showOnDelete="#elReportCommentDeleted" data-hideOnDelete="#elReportComment"{{else}}data-confirm{{endif}}>{lang="delete"}</a></li>
							{{endif}}
						</ul>
					</div>
				{{endif}}
			{{endif}}
			<div class="ipsType_center ipsType_large ipsEmpty {{if $comment or $item}}ipsHide{{endif}}" id='elReportCommentDeleted'>
				<i class="fa fa-trash-o"></i>
				<br>
				{lang="content_deleted"}
			</div>
			<div class="ipsType_center ipsType_large ipsEmpty ipsHide" id='elReportCommentDeletePending'>
				<i class='fa fa-trash-o'></i>
				<br>
				{lang="content_delete_pending"}
			</div>
		</div>
		<aside class='ipsColumn ipsColumn_veryWide sm:ipsMargin_top'>
			<div id="elReportSidebar">
				<div class='ipsBox ipsBox--child ipsAreaBackground_light ipsPadding:half' id='elReportSidebar_toggle' data-controller='core.front.modcp.reportToggle'>
					<div class='ipsPad_half ipsType_center ipsType_normal'>
						<p class='ipsType_reset ipsType_large cReportSidebar_icon ipsSpacer_bottom ipsSpacer_half'><i class='{{if $report->status == 1}}fa fa-flag{{elseif $report->status == 2}}fa fa-exclamation-triangle{{else}}fa fa-check-circle{{endif}}' data-role='reportIcon'></i></p>
						<strong>{lang="status"}:</strong> <span data-role="reportStatus">{lang="report_status_{$report->status}"}</span>
					</div>

					<a href='#elReportItem{$report->id}_menu' id='elReportItem{$report->id}' class='ipsButton ipsButton_primary ipsButton_small ipsButton_fullWidth' data-ipsMenu data-ipsMenu-closeOnClick data-ipsMenu-appendTo='#elReportSidebar_toggle' data-ipsMenu-selectable>
						{lang="mark_report_as"} <i class='fa fa-caret-down'></i>
					</a>
					{template="reportToggle" group="modcp" params="$report, '', FALSE"}
				</div>
				<br>
				<div id='elReportPanel' class='ipsBox'>
					{template="reportPanel" group="modcp" params="$report,$comment,$ref"}
				</div>
			</div>
		</aside>
	</article>
</div>
{{if $prevReport or $nextReport}}
<nav class='ipsPager ipsSpacer_top'>
	<div class='ipsPager_prev'>
		{{if $prevReport}}
			<a href="{url="app=core&module=modcp&controller=modcp&tab=reports&action=view&id={$prevReport['id']}" seoTemplate="modcp_report"}" title='{lang="previous_report"}'>
				<span class='ipsPager_type'>{lang="previous_report"}</span>
				{{if $prevItem}}
					<span class='ipsPager_title ipsType_break ipsTruncate ipsTruncate_line'>{$prevItem->mapped('title')}</span>
				{{else}}
					<span class='ipsPager_title'><em class="ipsType_light">{lang="content_deleted"}</em></span>
				{{endif}}
			</a>
		{{endif}}
	</div>
	<div class='ipsPager_next'>
		{{if $nextReport}}
			<a href="{url="app=core&module=modcp&controller=modcp&tab=reports&action=view&id={$nextReport['id']}" seoTemplate="modcp_report"}" title='{lang="next_report"}'>
				<span class='ipsPager_type'>{lang="next_report"}</span>
				{{if $nextItem}}
					<span class='ipsPager_title ipsType_break ipsTruncate ipsTruncate_line'>{$nextItem->mapped('title')}</span>
				{{else}}
					<span class='ipsPager_title'><em class="ipsType_light">{lang="content_deleted"}</em></span>
				{{endif}}
			</a>
		{{endif}}
	</div>
</nav>
{{endif}}
<section class='ipsBox ipsMargin_top'>
	<div class="ipsClearfix">
		<h2 class="ipsType_sectionTitle ipsFlex ipsFlex-ai:center ipsFlex-jc:between">
			{lang="responses_to_report"}
			<ul class="ipsButtonRow ipsPos_right ipsClearfix">
				<li>
					<a class="ipsJS_show" href="#elFilter_menu" id="elFilter"  data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" ipsMenu-selectable="radio">
						{lang="automoderation_report_type_filter"} <i class="fa fa-caret-down"></i>
					</a>
					<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elFilter_menu">
						<li class="ipsMenu_item {{if ! isset( \IPS\Request::i()->report_type )}}ipsMenu_itemChecked{{endif}}"><a href="{$report->url()}">{lang="all"}</a></li>
						<li class="ipsMenu_sep"><hr></li>
						{{foreach \IPS\core\Reports\Types::roots() as $type}}
							<li class="ipsMenu_item {{if isset( \IPS\Request::i()->report_type ) and \IPS\Request::i()->report_type == $type->id}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="{$type->id}"><a href="{$report->url()->setQueryString( array( 'report_type' => $type->id ) )}">{$type->_title}</a></li>
						{{endforeach}}
					</ul>
				</li>
			</ul>	
		</h2>
	</div>
	
	<div data-controller="core.front.core.commentsWrapper" data-tabsId='elTabsReport'>
		<div class="ipsTabs ipsClearfix" id="elTabsReport" data-ipsTabBar data-ipstabbar-contentarea="#elReportComments">
			<a href="#elTabs_report" data-action="expandTabs"><i class="fa fa-caret-down"></i></a>
			<ul role="tablist">
				<li>
					<a href="#" id="elUserReports" class="ipsTabs_item {{if ! isset( \IPS\Request::i()->activeTab ) or \IPS\Request::i()->activeTab != 'comments'}}ipsTabs_activeItem{{endif}}" title="" role="tab" aria-selected="true">
						{lang="report_user_reports" pluralize="\count( $report->reports( $filterByType ) )"}
					</a>
				</li>
				<li>
					<a href="#" id="elTabsReport_tab_mod_comments" class="ipsTabs_item {{if isset( \IPS\Request::i()->activeTab ) and \IPS\Request::i()->activeTab == 'comments'}}ipsTabs_activeItem{{endif}}" title="" role="tab" aria-selected="false">
						{lang="report_mod_comments" pluralize="$report->num_comments"}
					</a>
				</li>
			</ul>
		</div>
		<div id="elReportComments" class="ipsTabs_contained ipsTabs_panels">
			<div id="ipsTabs_elTabsReport_elUserReports_panel" class="ipsTabs_panel" aria-labelledby="elUserReports" aria-hidden="false">
				<div data-role="commentFeed">
					{{foreach $report->reports( $filterByType ) as $r}}
						<article id="elCommentMod_{$r['rid']}" class="ipsComment ipsComment_parent ipsClearfix ipsClear ">
							<div class='ipsComment_content ipsType_medium'>
								<div class='ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini'>
									{template="userPhoto" app="core" group="global" params="\IPS\Member::load( $r['report_by'] ), 'mini'"}
									<div>
										<h3 class='ipsComment_author ipsType_normal ipsType_blendLinks'>{member="link()" id="$r['report_by']" raw="true"}</h3>
										{{if \IPS\Member::loggedIn()->modPermission('can_use_ip_tools') and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) )}}
											<p class='ipsPos_right ipsType_reset ipsType_blendLinks ipsFaded ipsFaded_more'>
												<span class='ipsResponsive_hidePhone'>(<a href="{url="app=core&module=modcp&controller=modcp&tab=ip_tools&ip={$r['ip_address']}" seoTemplate="modcp_ip_tools"}">{lang="ip_prefix" sprintf="$r['ip_address']"}</a>)</span>
											</p>
										{{endif}}
										<p class="ipsComment_meta ipsType_light ipsType_medium">
											{{if $r['report_type']}}
												{{$type = ''; try{ $type = \IPS\core\Reports\Types::load( $r['report_type'] )->_title; } catch( \Exception $e ) { } }}
												{lang="report_type_byline" sprintf="$type"}
											{{endif}}
											{lang="report_date_submitted"} {datetime="$r['date_reported']"}
										</p>
									</div>
								</div>
								<div class='ipsPad'>
									<div class="ipsType_normal ipsType_richText ipsType_break ipsContained" data-controller='core.front.core.lightboxedImages'>
										{{if $r['report']}}
											{$r['report']|raw}
										{{else}}
											<p><em class="ipsType_light">{lang="report_no_message"}</em></p>
										{{endif}}
									</div>
								</div>
							</div>
						</article>
					{{endforeach}}
				</div>
			</div>
			<div id="ipsTabs_elTabsReport_elTabsReport_tab_mod_comments_panel" class="ipsTabs_panel" aria-labelledby="elTabsReport_tab_mod_comments" aria-hidden="false">
				<div data-controller='core.front.core.commentFeed' {{if settings.auto_polling_enabled}}data-autoPoll{{endif}} data-commentsType='mod_comments' data-baseURL='{$report->url()}' {{if $report->isLastPage()}}data-lastPage{{endif}} data-feedID='report-{$report->id}'>
					{{if $report->commentPageCount() > 1}}
						{$report->commentPagination()|raw}
						<br><br>
					{{endif}}
					<div data-role='commentFeed' data-controller='core.front.core.moderation'>
						<form action="{$report->url()->csrf()->setQueryString( 'action', 'multimodComment' )}" method="post" data-ipsPageAction data-role='moderationTools'>
							{{foreach $report->comments() as $modcomment}}
								{$modcomment->html()|raw}
							{{endforeach}}
							{template="commentMultimod" app="core" group="global" params="$report"}
						</form>
					</div>
					{{if $report->commentPageCount() > 1}}
						<hr class='ipsHr'>
						{$report->commentPagination()|raw}
						<br><br>
					{{endif}}
					<div data-role='replyArea' class='ipsAreaBackground ipsPad'>
						{$report->commentForm()|raw}
					</div>
				</div>
			</div>
		</div>
	</div>
</section>