<ips:template parameters="$warning" />
<div class="{{if !\IPS\Request::i()->isAjax()}}ipsBox{{endif}} ipsPad" id="warnhovercard_{$warning->id}" data-controller="core.front.modcp.warnPopup">	
	<h2 class="ipsType_pageTitle">
		{{if $warning->canViewDetails()}}
			<span class='ipsPoints'>{$warning->points}</span>
			{lang="core_warn_reason_{$warning->reason}"}
		{{else}}
			{lang="warning"}
		{{endif}}
	</h2>
	{{if \IPS\Settings::i()->warnings_acknowledge OR \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
		<p class='ipsType_medium'>
			{{if $warning->acknowledged}}
				<strong class='ipsType_success'><i class='fa fa-check-circle'></i> {lang="warning_acknowledged"}</strong>
			{{else}}
				{{if $warning->canAcknowledge()}}
					<div class='ipsAreaBackground_light ipsPad ipsType_center'>
						<a href="{$warning->url('acknowledge')->csrf()}" class="ipsButton ipsButton_important ipsButton_medium ipsButton_fullWidth"><i class='fa fa-check'></i> {lang="acknowledge"}</a>
						<p class='ipsType_light ipsType_small'>{lang="acknowledge_message"}</p>
					</div>
				{{else}}
					<strong class='ipsType_light'><i class='fa fa-circle-o'></i> {lang="warning_not_acknowledged"}</strong>
				{{endif}}
			{{endif}}
		</p>
	{{endif}}
	{{if $content = $warning->content() and $content->canView()}}
		<a href='{$content->url()->setQueryString( '_warn', $warning->id )}' class='ipsType_light ipsType_blendLinks' title='{lang="warning_go_to_content"}'><i class='fa fa-{$content::$icon}'></i> &nbsp;&nbsp;{{if $content instanceof \IPS\Content\Comment}}{$content->item()->mapped('title')}{{else}}{$content->mapped('title')}{{endif}}</a>
	{{endif}}
	{{if $warning->canViewDetails()}}
		<hr class='ipsHr'>
		<div class='ipsPhotoPanel ipsPhotoPanel_tiny'>
			{template="userPhoto" app="core" group="global" params="\IPS\Member::load( $warning->moderator ), 'tiny'"}
			<div>
				{{if $warning->canDelete()}}
					<a href="{$warning->url('delete')->csrf()}" title='{lang="revoke_this_warning"}' data-action="revoke" class='ipsPos_right ipsButton ipsButton_verySmall ipsButton_primary'><i class="fa fa-undo"></i> {lang="revoke"}</a></li>
				{{endif}}
				<p class="ipsType_reset">{lang="warning_byline" sprintf="\IPS\Member::load( $warning->moderator )->name"}</p>
				<p class='ipsType_reset ipsType_light'>{datetime="$warning->date"}</p>
			</div>
		</div>
	{{endif}}
	{{if $warning->canViewDetails() or $warning->mq or $warning->rpa or $warning->suspend}}
		<hr class='ipsHr'>
		<h3 class='ipsType_sectionHead'>{lang="warn_punishment"}</h3>
		<br>
		<ul class='ipsList_bullets ipsType_medium'>
			{{if $warning->canViewDetails()}}
				<li>
					{{if $warning->expire_date}}
						{{if $warning->expire_date < time()}}
							{{if $warning->expire_date == -1}}
								{lang="warn_action_points_never_expire" sprintf="$warning->points"}
							{{else}}
								{lang="warn_action_points_expired" sprintf="$warning->points, \IPS\DateTime::ts( $warning->expire_date )"}
							{{endif}}
						{{else}}
							{lang="warn_action_points_expire" sprintf="$warning->points, \IPS\DateTime::ts( $warning->expire_date )"}
						{{endif}}
					{{else}}
						{lang="warn_action_points" sprintf="$warning->points"}
					{{endif}}			
				</li>
			{{endif}}
			{{if $warning->mq}}
				<li>
					{lang="moderation_modq"} - 
					{{if $warning->mq == -1}}
						{lang="indefinitely"}
					{{else}}
						{expression="\IPS\DateTime::formatInterval( new \DateInterval( $warning->mq ), 2 )"}
					{{endif}}
				</li>
			{{endif}}
			{{if $warning->rpa}}
				<li>
					{lang="moderation_nopost"} - 
					{{if $warning->rpa == -1}}
						{lang="indefinitely"}
					{{else}}
						{expression="\IPS\DateTime::formatInterval( new \DateInterval( $warning->rpa ), 2 )"}
					{{endif}}
				</li>
			{{endif}}
			{{if $warning->suspend}}
				<li>
					{lang="moderation_banned"} - 
					{{if $warning->suspend == -1}}
						{lang="indefinitely"}
					{{else}}
						{expression="\IPS\DateTime::formatInterval( new \DateInterval( $warning->suspend ), 2 )"}
					{{endif}}
				</li>
			{{endif}}
		</ul>
	{{endif}}
	{{if $warning->note_member}}
		<hr class='ipsHr'>
		<h3 class='ipsType_sectionHead'>{lang="warn_member_note"}</h3>
		<div class='ipsType_richText ipsType_medium'>
			{template="richText" group="global" app="core" location="global" params="$warning->note_member"}
		</div>
	{{endif}}
	{{if $warning->note_mods and member.modPermission('mod_see_warn')}}
		<hr class='ipsHr'>
		<h3 class='ipsType_sectionHead'>{lang="warn_mod_note"}</h3>
		<div class='ipsType_richText ipsType_medium'>
			{template="richText" group="global" app="core" location="global" params="$warning->note_mods"}
		</div>
	{{endif}}
</div>