<ips:template parameters="$table, $headers, $rows" />
{{if \count( $rows )}}
	{{foreach $rows as $row}}
		<li class="ipsDataItem">
			<div class='ipsDataItem_icon'>
				{template="userPhoto" group="global" app="core" params="\IPS\Member::load( $row['member_id'] ), 'tiny'"}
			</div>
			<div class='ipsDataItem_main'>
				<h4 class='ipsDataItem_title ipsType_break'>						
					{$row['action']}
				</h4>
				<p class='ipsDataItem_meta ipsType_light'>
					{expression="\IPS\Member::load( $row['member_id'] )->name"}, {datetime="$row['ctime']"}
				</p>
			</div>
		</li>
	{{endforeach}}
{{endif}}
