<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />
{{$minimized = false;}}
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	<div class='ipsComposeArea ipsComposeArea_withPhoto ipsClearfix ipsContained'>
		<div class='ipsPos_left ipsResponsive_hidePhone ipsResponsive_block'>{template="userPhoto" app="core" group="global" params="\IPS\Member::loggedIn(), 'small'"}</div>
		<div class='ipsComposeArea_editor'>
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{{if $input->name == 'guest_name' or $input->name == 'guest_email'}}
						<ul class='ipsForm ipsForm_horizontal ipsMargin_bottom:half' data-ipsEditor-toolList>
							<li class='ipsFieldRow ipsFieldRow_fullWidth'>
								{$input->html()|raw}
								{{if $input->error}}
									<div class="ipsType_warning ipsSpacer_top" data-role="commentFormError">{lang="$input->error"}</div>
								{{endif}}
							</li>
						</ul>
					{{endif}}
				{{endforeach}}
			{{endforeach}}
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{{if $input instanceof \IPS\Helpers\Form\Editor}}
						{{if $input->options['minimize'] !== NULL}}
							{{$minimized = true;}}
						{{endif}}
						{$input->html( TRUE )|raw}
						{{if $input->error}}
							<div class="ipsType_warning ipsSpacer_top" data-role="commentFormError">{lang="$input->error"}</div>
						{{endif}}
					{{endif}}
				{{endforeach}}
			{{endforeach}}
			<ul class='ipsToolList ipsToolList_horizontal ipsClear ipsClearfix {{if $minimized}}ipsJS_hide{{endif}}' data-ipsEditor-toolList>
				{{foreach $elements as $collection}}
					{{foreach $collection as $input}}
						{{if !($input instanceof \IPS\Helpers\Form\Editor) && $input->name != 'guest_name' && $input->name != 'guest_email'}}
							<li class='ipsPos_left ipsResponsive_noFloat {{if !($input instanceof \IPS\Helpers\Form\Captcha)}}ipsComposeArea_formControl{{endif}} ipsType_medium ipsType_light'>
								{$input->html()|raw}
								{{if $input->error}}
									<div class="ipsType_warning ipsSpacer_top" data-role="commentFormError">{lang="$input->error"}</div>
								{{endif}}
							</li>
						{{endif}}
					{{endforeach}}
				{{endforeach}}
				{{foreach $actionButtons as $button}}
					<li>{$button|raw}</li>
				{{endforeach}}
			</ul>
		</div>
	</div>
</form>