<ips:template parameters="$title, $form, $container=NULL" />

{{if $container and \IPS\IPS::classUsesTrait( $container, 'IPS\Content\ClubContainer' ) and $club = $container->club()}}
	{{if settings.clubs and settings.clubs_header == 'full'}}
		{template="header" app="core" group="clubs" params="$club, $container"}
	{{endif}}
{{endif}}

<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
	<h1 class="ipsType_pageTitle">{$title}</h1>
</div>
<div class='ipsBox'>{$form|raw}</div>