<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	{{if $form->error}}
		<div class="ipsMessage ipsMessage_error">
			{$form->error}
		</div>
	{{endif}}
	{{if \count( $form->elements ) < 2}}
		<div class="ipsPadding">
			{{if !empty( $sidebar )}}
				<div class='ipsGrid ipsGrid_collapsePhone'>
					<div class='ipsGrid_span8'>
			{{endif}}
				<ul class='ipsList_reset'>
					{{foreach $elements as $collection}}
						{{foreach $collection as $input}}
							{{if \is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endforeach}}
					{{endforeach}}
				</ul>
			{{if !empty( $sidebar )}}
					</div>
					<div class='ipsGrid_span4'>
						{expression="array_pop( $sidebar )" raw="true"}
					</div>
				</div>
			{{endif}}
		</div>
	{{else}}
		<div class='ipsTabs ipsClearfix ipsJS_show' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
			<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
			<ul role='tablist'>
				{{foreach $elements as $name => $content}}
					<li>
						<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item {{if $name == request.tab}}ipsTabs_activeItem{{endif}}" role="tab">
							{{foreach $content as $element}}{{if !\is_string( $element ) and $element->error}}<i class="fa fa-exclamation-circle"></i> {{break;}}{{endif}}{{endforeach}} {lang="$name"}
						</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<div id='ipsTabs_content_{$id}' class=''>
			{{foreach $elements as $name => $content}}
				<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
					<ul class='ipsList_reset'>
						{{foreach $content as $input}}
							{{if \is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endforeach}}
					</ul>
				</div>
			{{endforeach}}
		</div>
	{{endif}}
	<ul class="ipsPadding ipsToolList ipsToolList_horizontal ipsList_reset ipsClearfix ipsBorder_top">
		{{foreach $actionButtons as $button}}
			<li>{$button|raw}</li>
		{{endforeach}}
	</ul>
</form>