<ips:template parameters="$login, $postBeforeRegister, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
{{if \IPS\Request::i()->isAjax() AND $buttonMethods = $login->buttonMethods()}}
	<div id='elRegisterSocial'>
		<div class='ipsPadding'>
			<h2 class='ipsType_sectionHead'>{lang='reg_start_faster'}</h2>
			<p class='ipsType_normal ipsType_reset ipsType_light'>{lang='reg_connect'}</p>
			<form accept-charset='utf-8' method='post' action='{$login->url}' data-controller="core.global.core.login">
				<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
				<div class='ipsGap:2 ipsMargin_top:half'>
					{{foreach $buttonMethods as $method}}
						<div class='ipsType_center'>
							{$method->button()|raw}
						</div>
					{{endforeach}}
				</div>
			</form>
		</div>
	</div>
	<hr class='ipsHr'>
{{endif}}

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	{{if \count( $form->elements ) < 2}}
		<div class="ipsPadding">
			{{if !empty( $sidebar )}}
				<div class='ipsGrid ipsGrid_collapsePhone'>
					<div class='ipsGrid_span8'>
			{{endif}}
				<ul class='ipsList_reset'>
					{{foreach $elements as $collection}}
						{{foreach $collection as $input}}
							{{if \is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endforeach}}
					{{endforeach}}
				</ul>
			{{if !empty( $sidebar )}}
					</div>
					<div class='ipsGrid_span4'>
						{expression="array_pop( $sidebar )" raw="true"}
					</div>
				</div>
			{{endif}}
		</div>
	{{else}}
		<div class='ipsTabs ipsClearfix ipsJS_show' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
			<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
			<ul role='tablist'>
				{{foreach $elements as $name => $content}}
					<li>
						<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item {{if $name == request.tab}}ipsTabs_activeItem{{endif}}" role="tab">
							{{foreach $content as $element}}{{if !\is_string( $element ) and $element->error}}<i class="fa fa-exclamation-circle"></i> {{break;}}{{endif}}{{endforeach}} {lang="$name"}
						</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<div id='ipsTabs_content_{$id}' class=''>
			{{foreach $elements as $name => $content}}
				<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
					<ul class='ipsList_reset'>
						{{foreach $content as $input}}
							{{if \is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endforeach}}
					</ul>
				</div>
			{{endforeach}}
		</div>
	{{endif}}
	<ul class="ipsPadding ipsList_reset ipsClearfix ipsBorder_top">
		<li>{template="button" group="forms" app="core" location="global" params="'register_button', 'submit', null, 'ipsButton ipsButton_primary ipsButton_large ipsButton_fullWidth', array( 'tabindex' => '2', 'accesskey' => 's' )"}</li>
		{{if $postBeforeRegister}}
		<li class='ipsPadding_top:half'><a href="{url="app=core&module=system&controller=register&do=cancelPostBeforeRegister&id={$postBeforeRegister['id']}&pbr={$postBeforeRegister['secret']}" csrf="true" seoTemplate="register"}" class='ipsButton ipsButton_veryLight ipsButton_large ipsButton_fullWidth' data-ipsPbrCancel="true">{lang="post_before_register_delete_submission"}</a></li>
		{{endif}}
	</ul>
</form>