<ips:template parameters="$lang, $warnings=array(), $ends=NULL" />

<div class='ipsPhotoPanel ipsPhotoPanel_medium ipsPhotoPanel_notPhone ipsClearfix'>
	{template="userPhoto" group="global" app="core" params="\IPS\Member::loggedIn(), 'medium'"}
	<div>
		<strong class='ipsType_warning'><i class="fa fa-warning"></i> {lang="$lang"} {{if $ends !== NULL AND $ends > 0}}{lang="restriction_ends" sprintf="\IPS\DateTime::ts( $ends )->relative()"}{{endif}}</strong>
		{{if \count( $warnings) }}
			{{foreach $warnings as $idx => $warning}}
				{{if $idx === 0}}
					<br><br>
					<a href="{$warning->url()}" data-ipsDialog data-ipsDialog-size='narrow' class='ipsButton ipsButton_verySmall ipsButton_light'>{lang="view_warning_details"}</a>
				{{endif}}
			{{endforeach}}
		{{endif}}
	</div>
</div>
<hr class='ipsHr'>