<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />
<div class='ipsPhotoPanel ipsPhotoPanel_medium ipsPhotoPanel_notPhone ipsClearfix' {{if \IPS\Member::loggedIn()->member_id}}data-controller='core.front.core.reviewForm'{{endif}}>
	{template="userPhoto" group="global" app="core" params="\IPS\Member::loggedIn(), 'medium'"}
	<div>
		<form accept-charset='utf-8' class="ipsForm" action="{$action->setQueryString( '_review', 1 )}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
			<input type="hidden" name="{$id}_submitted" value="1">
			{{foreach $hiddenValues as $k => $v}}
				<input type="hidden" name="{$k}" value="{$v}">
			{{endforeach}}
			{{if $uploadField}}
				<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
				<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
			{{endif}}
			{{if !isset( \IPS\Request::i()->_review ) and \IPS\Member::loggedIn()->member_id}}
				<div data-role='reviewIntro' class="">
					<h3 class='ipsType_reset'>{lang="review_intro_1" sprintf="\IPS\Member::loggedIn()->name"} <span class='ipsType_unbold'>{lang="review_intro_2"}</span></h3>
					<br>
					<a href='#' class='ipsButton ipsButton_primary ipsButton_small ipsJS_show' data-action='writeReview'>{lang="write_a_review"}</a>
				</div>
			{{endif}}
			<ul class='ipsForm ipsForm_vertical {{if !isset( \IPS\Request::i()->_review ) and \IPS\Member::loggedIn()->member_id}}ipsJS_hide{{endif}}' data-role='reviewForm'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $input}}
						{$input|raw}
					{{endforeach}}
				{{endforeach}}
				<li class='ipsFieldRow ipsClearfix'>
					<div class='ipsFieldRow_content'>
						<button type='submit' class='ipsButton ipsButton_primary'>{lang="add_review"}</button>
					</div>
				</li>
			</ul>
		</form>
	</div>
</div>