<ips:template parameters="$label, $element, $desc, $warning, $required=FALSE, $error=NULL, $prefix=NULL, $suffix=NULL, $id=NULL, $object=NULL, $form=NULL, $rowClasses=NULL" />
<li class='ipsFieldRow{{if $object === NULL}} ipsFieldRow_textValue{{endif}}{{if $object instanceof \IPS\Helpers\Form\Checkbox and !( $object instanceof \IPS\Helpers\Form\YesNo )}} ipsFieldRow_checkbox{{endif}} ipsClearfix {{if $error}}ipsFieldRow_error{{endif}} {{if $rowClasses}}{expression="implode(' ', $rowClasses)"}{{endif}}' {{if $id}}id="{$id}"{{endif}}>
	{{if $object instanceof \IPS\Helpers\Form\Checkbox and !( $object instanceof \IPS\Helpers\Form\YesNo )}}
		{$prefix|raw}
		{$element|raw}
		{$suffix|raw}
		<div class='ipsFieldRow_content'>
			<label class='ipsFieldRow_label' for='check_{$id}'><span>{$label|raw}</span> {{if $required}}<span class='ipsFieldRow_required'>{lang="required"}</span>{{endif}}</label>
			{$desc|raw}
			{$warning|raw}
			{{if $error}}
				<br>
				<span class="ipsType_warning">{lang="$error"}</span>
			{{endif}}
		</div>
	{{else}}
		{{if $label}}
			<label class='ipsFieldRow_label' {{if $object !== NULL AND $object->getLabelForAttribute() !== NULL}}for='{$object->getLabelForAttribute()}'{{endif}}>
				<span>{$label|raw}</span> {{if $required}}<span class='ipsFieldRow_required'>{lang="required"}</span>{{endif}}
			</label>
		{{endif}}
		<div class='ipsFieldRow_content' {{if $object instanceof \IPS\Helpers\Form\Text && !$required && $object->options['autocomplete'] !== NULL && !$object->value}}data-controller='core.global.core.optionalAutocomplete'{{endif}}>
			{$prefix|raw}
			{$element|raw}
			{$suffix|raw}
			{$desc|raw}
			{$warning|raw}
			{{if $error}}
				<br>
				<span class="ipsType_warning">{lang="$error"}</span>
			{{endif}}
		</div>
	{{endif}}
</li>