<ips:template parameters="$id, $action, $tabs, $activeTab, $error, $errorTabs, $hiddenValues, $actionButtons, $uploadField, $sidebar, $tabClasses=array(), $formClass='', $attributes=array(), $tabArray=array(), $usingIcons=FALSE" />
<form action="{$action}" method="post" accept-charset='utf-8' {{if $uploadField}}enctype="multipart/form-data"{{endif}} data-ipsForm class="ipsForm {$formClass}" {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} {{if \count($tabArray) > 1}}novalidate="true"{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	{{if $error}}
		<div class="ipsMessage ipsMessage_error">
			{$error}
		</div>
	{{endif}}
	{{if \count( $tabs ) < 2}}
		{{if !empty( $sidebar )}}
			<div class='ipsColumns ipsColumns_collapsePhone'>
				<div class='ipsColumn ipsColumn_fluid'>
		{{endif}}
					<ul class='ipsForm'>
						{expression="array_pop( $tabs )" raw="true"}
						<li class='ipsFieldRow'>
							<div class='ipsFieldRow_content'>
								{expression="implode( '', $actionButtons)" raw="true"}
							</div>
						</li>
					</ul>
		{{if !empty( $sidebar )}}
				</div>
				<div class='ipsColumn ipsColumn_wide'>
					{expression="array_pop( $sidebar )" raw="true"}
				</div>
			</div>
		{{endif}}
	{{else}}
		{{if !empty( $errorTabs )}}
			<p class="ipsMessage ipsMessage_error ipsJS_show">{lang="tab_error"}</p>
		{{endif}}
		<div class='ipsTabs ipsClearfix ipsJS_show{{if $usingIcons}} ipsTabs_withIcons{{endif}}' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
			<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
			<ul role='tablist'>
				{{foreach $tabs as $name => $content}}
					<li>
						<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item {{if $name == $activeTab}}ipsTabs_activeItem{{endif}} {{if \in_array( $name, $errorTabs )}}ipsTabs_error{{endif}}" role="tab" aria-selected="{{if $activeTab == $name}}true{{else}}false{{endif}}">
							{{if \in_array( $name, $errorTabs )}}<i class="fa fa-exclamation-circle"></i> {{endif}}{{if isset($tabArray[$name]['icon'])}}<i class='fa fa-{$tabArray[$name]['icon']}'></i> {{endif}}{lang="$name"}
						</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<div id='ipsTabs_content_{$id}' class=''>
			{{foreach $tabs as $name => $contents}}
				<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
					{{if isset( $sidebar[ $name ] )}}
						<div class='ipsColumns ipsColumns_collapsePhone'>
							<div class='ipsColumn ipsColumn_fluid'>
					{{endif}}
								<ul class='ipsForm {$formClass} {{if isset( $tabClasses[ $name ] )}}{$tabClasses[ $name ]}{{endif}}'>
									<li class='ipsJS_hide'>{lang="$name"}</li>
									{$contents|raw}
								</ul>
					{{if isset( $sidebar[ $name ] )}}
							</div>
							<div class='ipsColumn ipsColumn_wide'>
								{$sidebar[ $name ]|raw}
							</div>
						</div>
					{{endif}}
				</div>
			{{endforeach}}
		</div>
		<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
			{expression="implode( '', $actionButtons)" raw="true"}
		</div>
	{{endif}}
</form>