<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $attachment}}
	<div class='ipsDataItem ipsAttach ipsAttach_done md:ipsFlex md:ipsFlex-ai:center sm:ipsFlex-fw:wrap'>
		<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_center'>
			<a href="{setting="base_url"}applications/core/interface/file/attachment.php?id={$attachment['attach_id']}">
				{{if $attachment['attach_is_image']}}
					<img src="{file="$attachment['attach_location']" extension="core_Attachment"}" alt='' class='ipsImage ipsThumb_small' data-ipsLightbox data-ipsLightbox-group="myAttachments">
				{{else}}
					<i class='fa fa-file ipsType_large'></i>
				{{endif}}
			</a>
		</div>
		<div class='ipsDataItem_main'>
			<h2 class='ipsDataItem_title ipsType_reset ipsType_medium ipsAttach_title ipsContained_container ipsType_blendLinks'><span class='ipsType_break ipsContained'><a href="{setting="base_url"}applications/core/interface/file/attachment.php?id={$attachment['attach_id']}">{$attachment['attach_file']}</a></span></h2>
			<p class='ipsDataItem_meta ipsType_light'>
				{{if !$attachment['attach_is_image']}}{lang="attach_hits_count" pluralize="$attachment['attach_hits']"} &middot; {{endif}} {filesize="$attachment['attach_filesize']"} &middot; {lang="my_attachment_uploaded" htmlsprintf="\IPS\DateTime::ts( $attachment['attach_date'] )->html()"}
			</p>
		</div>
		<div class='ipsDataItem_generic ipsDataItem_size9 ipsType_light'>
			{$attachment['attach_content']|raw}
		</div>
		{{if $table->canModerate()}}
		<div class='ipsDataItem_modCheck'>
			<span class='ipsCustomInput'>
				<input type='checkbox' data-role='moderation' name="moderate[{$attachment['attach_id']}]" data-actions="{expression="implode( ' ', $table->multimodActions() )"}"  data-state=''>
				<span></span>
			</span>
		</div>
		{{endif}}
	</div>
{{endforeach}}
