<ips:template parameters="$comment, $record" />
{{$iposted = $record->container()->contentPostedIn();}}
{{$idField = $record::$databaseColumnId;}}
<div class='sm:ipsMargin_top:double'>
	<h3 class='ipsType_sectionHead ipsType_break'>
		{{if $record->unread()}}
			<a href='{$record->url( 'getNewComment' )}' title='{lang="first_unread_post"}' data-ipsTooltip>
				<span class='ipsItemStatus'><i class="fa {{if \in_array( $record->$idField, $iposted )}}fa-star{{else}}fa-circle{{endif}}"></i></span>
			</a>&nbsp;
		{{else}}
			{{if \in_array( $record->$idField, $iposted )}}
				<span class='ipsItemStatus ipsItemStatus_read ipsItemStatus_posted'><i class="fa fa-star"></i></span>&nbsp;
			{{endif}}
		{{endif}}

		<a href='{$comment->url()}' title='{lang="view_this_cmsrecord" sprintf="\IPS\Member::loggedIn()->language()->addToStack( 'content_db_lang_sl_' . $record::$customDatabaseId, FALSE ), $record->_title"}'>{$record->_title}</a>
		{{if $record->container()->allow_rating}}
			{template="rating" group="global" location="front" app="core" params="'large', $record->rating_hits ? ( $record->rating_total / $record->rating_hits ) : 0"}
		{{endif}}
	</h3>
	<p class='ipsType_normal ipsType_light ipsType_blendLinks ipsType_reset'>{lang="in"} <a href='{$record->container()->url()}'>{$record->container()->_title}</a></p>
</div>