<ips:template parameters="$comment, $item, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$comment, $item->mapped('title'), $comment->mapped('date'), $url"}
	<div class='ipsPadding'>
		<div class='ipsRichEmbed_originalItem ipsAreaBackground_reset ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				{{if $item->record_image}}
					{{$image = \IPS\File::get( "cms_Records", $item->record_image );}}
				{{elseif $contentImage = $item->contentImages(1)}}
					{{$attachType = key( $contentImage[0] );}}
					{{$image = \IPS\File::get( $attachType, $contentImage[0][ $attachType ] );}}
				{{endif}}

				{{if $image}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
						<a href='{$url}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $image->url )"}" )'>
							<img src='{$image->url}' class='ipsHide' alt=''>
						</a>
					</div>
				{{endif}}
				<div class='ipsPadding'>
					{template="embedOriginalItem" group="embed" app="core" params="$item, TRUE, \IPS\Theme::i()->getTemplate( 'global', 'cms' )->embedRecordItemSnippet( $item ) "}
				</div>
			</div>
		</div>

		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$comment->truncated(TRUE)|raw}
		</div>

		{{if settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and \count( $comment->reactions() )}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$comment, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>