<ips:template parameters="$item, $url" />

{{$image = NULL;}}
<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$item, $item->mapped('title'), $item->mapped('date'), $url"}
	{{if $item->record_image}}
		{{$image = \IPS\File::get( "cms_Records", $item->record_image );}}
	{{elseif $contentImage = $item->contentImages(1)}}
		{{$attachType = key( $contentImage[0] );}}
		{{$image = \IPS\File::get( $attachType, $contentImage[0][ $attachType ] );}}
	{{endif}}

	{{if $image}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
			<a href='{$url}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $image->url )"}" )'>
				<img src='{$image->url}' class='ipsHide' alt=''>
			</a>
		</div>
	{{endif}}
	<div class='ipsPadding'>
		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$item->truncated(TRUE)|raw}
		</div>

		{{if \count( $item->customFieldsForDisplay('listing') )}}
			<div class='ipsSpacer_top ipsSpacer_half ipsClearfix'>
				{{foreach $item->customFieldsForDisplay('listing') as $fieldId => $fieldValue}}
					{{if $fieldValue}}
						{$fieldValue|raw}
					{{endif}}
				{{endforeach}}
			</div>
		{{endif}}

		{template="embedItemStats" group="embed" app="core" params="$item"}
	</div>
</div>