<ips:template parameters="$file, $record, $downloadUrl, $cipher" />
{{if $file->isImage()}}
	<img src="{$file->url}" class="ipsImage" data-ipsLightbox>
{{else}}
	{{if $record}}
		<a href="{url="applications/cms/interface/file/file.php?record={$record->_id}&database={$record::$customDatabaseId}&fileKey={$cipher}&file=" base="none"}{expression="urlencode($file->originalFilename)"}">{$file->originalFilename}</a>
	{{else}}
		<a href="{$downloadUrl}">{$file->originalFilename}</a>
	{{endif}}
{{endif}}