<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	<article class='ipsBox ipsBox--child ipsComment ipsComment_parent ipsClearfix ipsClear'>
		<div class='ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini ipsPhotoPanel_notPhone'>
			{template="userPhoto" app="core" group="global" params="$row['revision_member_id'], 'mini'"}
			<div>
				<p class="ipsPos_right">
					<a href="{$table->baseUrl->setQueryString( array( 'do' => 'revisionView', 'revision_id' => $row['revision_id'], 'd' => \IPS\cms\Databases\Dispatcher::i()->databaseId ) )}">{lang="content_revision_button_view"}</a>
					&nbsp; <a data-confirm href="{$table->baseUrl->csrf()->setQueryString( array( 'do' => 'revisionDelete', 'revision_id' => $row['revision_id'], 'd' => \IPS\cms\Databases\Dispatcher::i()->databaseId, 'ajax' => \IPS\Request::i()->isAjax() ) )}">{lang="content_revision_button_delete"}</a>
				</p>
				<h3 class='ipsComment_author ipsType_sectionHead'>
					{$row['revision_member_id']->link()|raw}
				</h3>
				<p class='ipsComment_meta ipsType_light'>
					{$row['revision_date']}
				</p>
			</div>
		</div>
		<div class='ipsAreaBackground_reset ipsPadding_vertical sm:ipsPadding_vertical:half ipsPadding_horizontal'>
			<div class='ipsType_richText'>
				{{$gotDiffs = FALSE;}}
				<ul class='ipsDataList'>
					{{foreach $row['revision_data'] as $key => $diff}}
						<li class='ipsDataItem'>
							<div class='ipsDataItem_main'>
								{{if $diff['original'] != $diff['current']}}
									{{$gotDiffs = TRUE;}}
									<h3 class='ipsType_sectionHead'>{$diff['field']->_title}</h3>
									{{if !\in_array( $diff['field']->type, array( 'Editor', 'CodeMirror', 'TextArea' ) )}}
										<div class='ipsGrid' data-key='{$row['revision_id']}_{$key}' data-method='diff'>
											<div class='ipsGrid_span6 ipsPad'>
												<h3 class='ipsType_sectionHead'>Revision</h3>
												<div data-original='{$row['revision_id']}_{$key}'>{$diff['original']}</div>
											</div>
											<div class='ipsGrid_span6 ipsPad'>
												<h3 class='ipsType_sectionHead'>Current</h3>
												<div data-current='{$row['revision_id']}_{$key}'>{$diff['current']}</div>
											</div>
										</div>
									{{else}}
										<div class='ipsGrid'>
											<div class='ipsGrid_span6'><strong class='ipsType_normal'>{lang="content_record_revision_title_revision"}</strong></div>
											<div class='ipsGrid_span6'><strong class='ipsType_normal'>{lang="content_record_revision_title_record"}</strong></div>
										</div>

										<div class='ipsPagesDiff' data-key='{$row['revision_id']}_{$key}' data-method='merge'></div>
										<textarea class='ipsHide' data-original='{$row['revision_id']}_{$key}'>{$diff['original']}</textarea>
										<textarea class='ipsHide' data-current='{$row['revision_id']}_{$key}'>{$diff['current']}</textarea>
									{{endif}}
								{{endif}}
							</div>
						</li>
					{{endforeach}}
					{{if ! $gotDiffs}}
						<p class="ipsMessage ipsMessage_info">{lang="record_no_revision_data"}</p>
					{{endif}}
				</ul>
			</div>
		</div>
	</article>
{{endforeach}}
