<ips:template parameters="$table, $headers, $rows, $quickSearch" />
{{if ! \IPS\Request::i()->isAjax()}}
<div class='ipsPageHeader ipsClearfix ipsSpacer_bottom'>
	<h1 class='ipsType_pageTitle'>{lang="content_view_revisions"}</h1>
</div>
{{endif}}
<div class='ipsBox' data-baseurl='{$table->baseUrl}' data-resort='{$table->resortKey}' data-controller='cms.front.records.revisions'>
	{{if $table->title}}
		<h2 class='ipsType_sectionTitle ipsType_reset ipsClear'>{lang="$table->title"}</h2>
	{{endif}}
	{{if $table->pages > 1}}
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
			<div data-role="tablePagination">
				{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
			</div>
		</div>
	{{endif}}


	{{if \count( $rows )}}
		{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
	{{else}}
	<div class='ipsType_center'>
		<p class='ipsType_large'>{lang="content_view_revisions_none"}</p>
	</div>
	{{endif}}

	{{if $table->pages > 1}}
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
		<div data-role="tablePagination">
			{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
		</div>
	</div>
	{{endif}}
</div>