<ips:template parameters="$record, $revision, $conflicts, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $formClass='', $attributes=array(), $sidebar=''" />
<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
	<h1 class="ipsType_pageTitle">{lang="content_record_revision_title" sprintf="\IPS\DateTime::ts($revision->date)->relative(), $record->_title"}</h1>
</div>
<hr class='ipsHr'>
<br />
<form accept-charset='utf-8' action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} data-ipsForm class="{$formClass}" {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_v}}
				<input type="hidden" name="{$k}[]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	<ol class='ipsList_reset' data-controller='cms.front.records.revisions'>
		{{foreach $conflicts as $key => $data}}
		<li>
			<h2 class="ipsType_secondaryTitle ipsType_reset ipsType_blendLinks">
				{$data['field']->_title}
			</h2>
			<ol class='ipsDataList ipsDataList_large' id='elTable_{$record->_id}' data-role="tableRows">
				<li class="ipsDataItem">
				{{if isset( $data['diff']) OR $data['original'] != $data['current']}}
					<div class="ipsDataItem_main ipsAreaBackground_light ipsPad_half">
						<table class="ipsTable diff restrict_height">
							<tr>
								<th><span data-conflict-id="{$key}" data-conflict-name="old">{lang="content_record_revision_title_revision"}</span></th>
								<th><span data-conflict-id="{$key}" data-conflict-name="new">{lang="content_record_revision_title_record"} </span></th>
							</tr>
						</table>
						<div data-conflict-id="{$key}">
						{{if !\in_array( $data['field']->type, array( 'Editor', 'CodeMirror', 'TextArea' ) )}}
							<div class='ipsGrid' data-key='{$key}' data-method='diff'>
								<div class='ipsGrid_span6 ipsPad' data-original='{$key}'>{$data['original']}</div>
								<div class='ipsGrid_span6 ipsPad' data-current='{$key}'>{$data['current']}</div>
							</div>
						{{else}}
							<div class='ipsPagesDiff' data-key='{$key}' data-method='merge'></div>
							<textarea class='ipsHide' data-original='{$key}'>{$data['original']}</textarea>
							<textarea class='ipsHide' data-current='{$key}'>{$data['current']}</textarea>
						{{endif}}
						</div>
						{{if \count($elements)}}
							<div class="ipsAreaBackground ipsPad">
								<div class='ipsGrid'>
									<div class='ipsGrid_span6'>
										<span class='' data-conflict-name="old">
											{{foreach $elements as $collection}}
												{{foreach $collection as $name => $input}}
													{{if $name == 'conflict_' . $data['field']->id}}
														{template="radio" location="global" app="core" group="forms" params="$name, 'old', FALSE, array( 'old' => \IPS\Member::loggedIn()->language()->addToStack('content_conflict_use_this_revision') ), FALSE, array(), array(), array(), '', NULL, NULL, 'oldrev'"}
													{{endif}}
												{{endforeach}}
											{{endforeach}}
										</span>
									</div>
									<div class='ipsGrid_span6'>
										<span data-conflict-name="new">
											{{foreach $elements as $collection}}
												{{foreach $collection as $name => $input}}
													{{if $name == 'conflict_' . $data['field']->id}}
														{template="radio" location="global" app="core" group="forms" params="$name, NULL, FALSE, array( 'new' => \IPS\Member::loggedIn()->language()->addToStack('content_conflict_use_this_record') ), FALSE, array(), array(), array(), '', NULL, NULL, 'newrev'"}
													{{endif}}
												{{endforeach}}
											{{endforeach}}
										</span>
									</div>
								</div>
							</div>
						{{endif}}
					</div>
				{{else}}
					<div class="ipsDataItem_main">
						{$data['revision']|raw}
					</div>
				{{endif}}
				</li>
			</ol>
		</li>
		{{endforeach}}
	</ol>	
	<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
		{expression="implode( '', $actionButtons)" raw="true"}
	</div>
</form>