<ips:template parameters="$venue, $upcoming=array(), $past=array(), $address=NULL" />
<div>
	<section>
			<div class='ipsColumns ipsColumns_collapsePhone'>
				<aside class='ipsColumn ipsColumn_wide'>
					{$venue->map( 270, 270 )|raw}
					<div class='ipsAreaBackground_light'>
						{{if $address}}
						<div class='ipsPad_half ipsAreaBackground'>
							<h3 class='ipsType_minorHeading'>
								<strong>{lang="venue_address"}</strong>
							</h3>
							{$address|raw}
						</div>
						{{endif}}
					</div>
					{{if \IPS\Member::loggedIn()->member_id}}
					<ul class="ipsToolList ipsClearfix ipsSpacer_both">
						<li class='ipsToolList_primaryAction'>
							<a class="ipsButton ipsButton_medium ipsButton_important ipsButton_fullWidth" href="{url="app=calendar&module=calendar&controller=submit&venue={$venue->id}" seoTemplate="calendar_submit"}" data-ipsDialog data-ipsdialog-size="narrow">{lang="create_event"}</a>
						</li>
					</ul>
					{{endif}}
				</aside>
				<div class='ipsColumn ipsColumn_fluid'>
					<div class='ipsBox ipsPad ipsClearfix'>
						{{if $venue->description}}
						<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="venue_details"}</h2>

						<div class='ipsType_medium'>
							<div class='ipsClear ipsType_normal ipsType_richText ipsType_break'>
								{$venue->description|raw}
							</div>
						</div>
						<br>
						{{endif}}
						<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="venue_upcoming_events"}</h2>
						<div data-controller='calendar.front.venue.main'>
								{{if $upcoming}}
									{$upcoming|raw}
								{{else}}
									{lang="venues_no_upcoming_events"}
								{{endif}}
						</div>
					</div>
				</div>
			</div>

	</section>
</div>