<ips:template parameters="$announcement" />
{{if \IPS\Request::i()->isAjax()}}
<div>
	<div class='ipsPadding ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
		{template="userPhoto" app="core" group="global" params="$announcement->author(), 'tiny'"}
		<div>
			<p class='ipsType_reset ipsType_large ipsType_blendLinks'>
				{lang="byline_nodate" htmlsprintf="$announcement->author()->link()"}
	            {{if $announcement->start}}
	                <br>
	                <span class='ipsType_light ipsType_medium'>{datetime="$announcement->start" dateonly="true"}</span>
	            {{endif}}
			</p>
		</div>
	</div>
{{else}}
	<div class="ipsPadding">
		<div class='ipsType_pageHeader'>
			<h1 class='ipsType_pageTitle ipsType_largeTitle ipsContained_container'><span class='ipsType_break ipsContained'>{$announcement->mapped( 'title' )}</span></h1>
			{{if !$announcement->active}}
				<p class='ipsType_reset ipsType_light'>{lang="announcement_not_active"}</p>
			{{endif}}
		</div>
		<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
			{template="userPhoto" app="core" group="global" params="$announcement->author(), 'tiny'"}
			<div>
				<p class='ipsType_reset ipsType_large ipsType_blendLinks'>
					{lang="byline_nodate" htmlsprintf="$announcement->author()->link()"}
					{{if $announcement->start}}
						<br>
						<span class='ipsType_light ipsType_medium'>{datetime="$announcement->start" dateonly="true"}</span>
					{{endif}}
				</p>
			</div>
		</div>
	</div>
	<br>
	{{endif}}
	<article class='ipsBox ipsPad'>
		<section class='ipsType_richText ipsType_normal' data-controller='core.front.core.lightboxedImages'>
			{$announcement->mapped( 'content' )|raw}
			{{if \IPS\Member::loggedIn()->modPermission('can_manage_announcements') and ( $announcement->canEdit() or $announcement->canDelete() )}}
				<hr class='ipsHr'>
				<a href='#elAnnouncementActions{$announcement->id}_menu' id='elAnnouncementActions{$announcement->id}' class='ipsButton ipsButton_light ipsButton_verySmall' data-ipsMenu>{lang="announce_actions"} <i class='fa fa-caret-down'></i></a>
				<ul id='elAnnouncementActions{$announcement->id}_menu' class='ipsMenu ipsMenu_auto ipsHide'>
					{{if $announcement->canEdit()}}
						<li class='ipsMenu_item'><a href='{$announcement->url( 'create' )}' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-destructOnClose='true' data-ipsDialog-title='{lang="edit_announcement"}' data-action='ipsMenu_ping'>{lang="edit"}</a></li>
					{{endif}}
					{{if $announcement->canDelete()}}
						<li class='ipsMenu_item'><a href='{$announcement->url( 'delete' )->csrf()}' data-confirm  title='{lang="delete"}'>{lang="delete"}</a></li>
					{{endif}}
					<li class='ipsMenu_item'><a href='{$announcement->url( 'status' )->csrf()}' title='{{if $announcement->active}}{lang="announce_mark_inactive"}{{else}}{lang="announce_mark_active"}{{endif}}'>{{if $announcement->active}}{lang="announce_mark_inactive"}{{else}}{lang="announce_mark_active"}{{endif}}</a></li>
				</ul>
			{{endif}}
		</section>
	</article>

	{{if \IPS\Request::i()->isAjax()}}
	</div>
{{endif}}