<ips:template parameters="$stepNames, $activeStep, $output, $baseUrl, $showSteps" />

<div data-ipsWizard class='ipsWizard'>
	<div data-role="wizardStepbar">
		{{$completion = \intval( (string) \IPS\Member::loggedIn()->profileCompletionPercentage() );}}
		<div class="ipsProgressBar ipsProgressBar_fullWidth ipsSpacer_bottom">
			<div class='ipsProgressBar_progress' style='width: {expression="\IPS\Member::loggedIn()->profileCompletionPercentage()"}%'>
				{lang="profile_completion_percent" sprintf="$completion . '%'"}
			</div>
		</div>
	</div>
	<div data-role="wizardContent" class="ipsBox">
		{$output|raw}
	</div>
</div>