<ips:template parameters="" />

<br><br>
<div class='ipsBox_alt'>
	<p class='ipsType_reset ipsType_center ipsType_huge'>
		<i class='fa fa-envelope'></i>
	</p>

	<h1 class='ipsType_veryLarge ipsType_center'>{lang="contact_sent"}</h1>

	<div class='ipsType_large ipsType_center ipsType_richText'>
		{lang="contact_sent_blurb"}
	</div>
	<br>
	<p class='ipsType_center'>
		<a href='{url="/"}' class='ipsButton ipsButton_normal ipsButton_small'>{lang="go_community_home"}</a>
	</p>
</div>