<ips:template parameters="$form, $postBeforeRegister" />

<section class='ipsPad'>
	<br>
	{{if $postBeforeRegister}}
		<h1 class='ipsType_veryLarge ipsType_center ipsType_reset'>{lang="post_before_register_headline"}</h1>
		<p class='ipsType_reset ipsType_large ipsType_center ipsType_light'>{lang="post_before_register_subtext"}</a></p>
	{{else}}
		<h1 class='ipsType_veryLarge ipsType_center ipsType_reset'>{lang='sign_up'}</h1>
		<p class='ipsType_large ipsType_center ipsType_light'>{lang="existing_user"} <a href='{url="app=core&module=system&controller=login" seoTemplate="login"}'>{lang="sign_in_short"}</a></p>
	{{endif}}
	<br>

	<div data-role='registerForm' class='ipsBox ipsPad'>
		<section class='ipsType_center'>
			<p class='ipsType_large ipsType_reset'><strong>{lang="coppa_verify"}</strong></p>
			<p class='ipsType_normal ipsType_light ipsType_reset'>
				{lang="coppa_verification_only"} {{if \IPS\Settings::i()->privacy_type != "none"}} <a href='{{if \IPS\Settings::i()->privacy_type == "internal"}}{url="app=core&module=system&controller=privacy" seoTemplate="privacy"}{{else}}{setting="privacy_link"}{{endif}}'>{lang="privacy"}</a>.{{endif}}
			</p>
			<br><br>

			{$form->customTemplate( array( \IPS\Theme::i()->getTemplate( 'system', 'core', 'front' ), 'coppaForm' ) )|raw}
		</section>
	</div>
</section>