<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form {{if \IPS\Request::i()->isAjax() }}data-controller='core.front.core.followForm'{{endif}} accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm >
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	<div>
		<h2 class='ipsType_sectionTitle'>{expression="\IPS\Output::i()->title"}</h2>
		<ul class='ipsPadding ipsList_reset'>
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{{if \is_string( $input )}}
						{$input|raw}
						<hr class='ipsHr'>
					{{elseif $input instanceof \IPS\Helpers\Form\Radio}}
						<li class="ipsFieldRow">
							<strong class='ipsType_normal'>{lang="follow_send_me"}</strong>
							{$input->html($form)|raw}
							<hr class='ipsHr'>
						</li>
					{{elseif $input instanceof \IPS\Helpers\Form\Checkbox}}
						{$input->html($form)|raw}
					{{else}}
						{$input->rowHtml($form)|raw}
					{{endif}}
				{{endforeach}}
			{{endforeach}}
		</ul>
	</div>
	<div class="ipsToolList ipsToolList_horizontal ipsBorder_top ipsPadding">
		{$actionButtons[0]|raw} {{if isset( $actionButtons[1] )}}{$actionButtons[1]|raw}{{endif}}
	</div>
</form>