<ips:template parameters="$table, $headers, $rows" />

{{foreach $rows as $row}}
	{{$loadedMember = \IPS\Member::load( $row->member_id );}}
	<li class='ipsDataItem' data-controller='core.front.system.manageFollowed' data-followID='{$row->_followData['follow_area']}-{$row->_followData['follow_rel_id']}'>
		<div class='ipsDataItem_icon'>
			{template="userPhoto" group="global" app="core" params="$loadedMember, 'small'"}
		</div>
		<div class='ipsDataItem_main'>
			<h3 class='ipsType_reset ipsType_large ipsType_unbold'>{$loadedMember->link( NULL, FALSE )|raw}</h3> {{if $loadedMember->isOnline()}}<i class="fa fa-circle ipsOnlineStatus_online" data-ipsTooltip title='{lang="online_now" sprintf="$row->name"}'></i>{{endif}}
			<span class='ipsType_normal'>{expression="\IPS\Member\Group::load( $row->member_group_id )->formattedName" raw="true"}</span>
			<ul class='ipsList_inline ipsType_light'>
				<li>{lang="members_member_posts"}: {$loadedMember->member_posts}</li>
				<li>{lang="members_joined"}: {datetime="$loadedMember->joined"}</li>
				{{if $loadedMember->last_activity}}
					<li>{lang="members_last_visit"}: {datetime="$loadedMember->last_activity"}</li>
				{{endif}}
			</ul>
		</div>
		<div class='ipsDataItem_generic ipsDataItem_size1 ipsType_center ipsType_large'>
			<span class='ipsBadge ipsBadge_icon ipsBadge_new {{if !$row->_followData['follow_is_anon']}}ipsHide{{endif}}' data-role='followAnonymous' data-ipsTooltip title='{lang="follow_is_anon"}'><i class='fa fa-eye-slash'></i></span>
		</div>

		<div class='ipsDataItem_generic ipsDataItem_size6'>
			<ul class='ipsList_reset'>
				<li title='{lang="follow_when"}' data-role='followDate'><i class='fa fa-clock-o'></i> {datetime="$row->_followData['follow_added']"}</li>
				<li title='{lang="follow_how"}' data-role='followFrequency'>
					{{if $row->_followData['follow_notify_freq'] == 'none'}}
						<i class='fa fa-bell-slash-o'></i>
					{{else}}
						<i class='fa fa-bell'></i>
					{{endif}} {lang="follow_freq_{$row->_followData['follow_notify_freq']}"}
				</li>
			</ul>
		</div>

		<div class='ipsDataItem_generic ipsDataItem_size6 ipsType_center'>
			{template="manageFollow" group="system" app="core" params="$row->_followData['follow_app'], $row->_followData['follow_area'], $row->_followData['follow_rel_id']"}
		</div>

		{{if $table->canModerate()}}
			<div class='ipsDataItem_modCheck'>
				<span class='ipsCustomInput'>
					<input type='checkbox' data-role='moderation' name="moderate[{$row->member_id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state=''>
					<span></span>
				</span>
			</div>
		{{endif}}
	</li>
{{endforeach}}