<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar" />

<form accept-charset='utf-8' id="elIgnoreForm" class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm data-controller='core.front.ignore.edit'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	<ul class="ipsForm ipsForm_vertical ipsPad">
		{{foreach $elements as $collection}}
			<li class='ipsFieldRow ipsFieldRow_fullWidth'>
				<ul class='ipsFieldRow_content ipsList_reset'>
					{{foreach $collection as $input}}
						{{if $input instanceof \IPS\Helpers\Form\Checkbox}}
							<li class='ipsFieldRow_inlineCheckbox'>
								{$input->html()|raw}
								<label for='check_{$input->htmlId}'>{lang="$input->name"}</label>
							</li>
						{{endif}}
					{{endforeach}}
				</ul>
			</li>
		{{endforeach}}
	</ul>
	<div class='ipsBorder_top ipsPadding ipsType_right'>
		{{foreach $actionButtons as $button}}
			{$button|raw}
		{{endforeach}}
	</div>
</form>