<ips:template parameters="$links, $url" />

<div class='ipsPad'>
	<h4 class='ipsType_sectionHead'>{lang="block_invite"}</h4>
	<hr class='ipsHr'>
	<h5 class='ipsType_normal ipsType_reset'>{lang="link_to_site"}</h5>

	<input type='text' value='{$url}' class='ipsField_fullWidth'>

	<h5 class='ipsType_normal ipsType_reset ipsSpacer_top'>{lang="share_externally"}</h5>
	{{if \count( $links ) }}
	<ul class='ipsList_inline ipsList_noSpacing ipsClearfix'>
		{{foreach $links as $link }}
		<li>{$link|raw}</li>
		{{endforeach}}
	</ul>
	{{endif}}
</div>