<ips:template parameters="$login" />
<ul class='ipsForm'>
	<li class="ipsFieldRow ipsFieldRow_fullWidth ipsClearfix">
		{{$authType = $login->authType();}}
		<label class="ipsFieldRow_label" for="auth">
			{{if $authType === \IPS\Login::AUTH_TYPE_USERNAME}}
				{lang="username"}
			{{elseif $authType === \IPS\Login::AUTH_TYPE_EMAIL}}
				{lang="email_address"}
			{{else}}
				{lang="username_or_email"}
			{{endif}}
			<span class="ipsFieldRow_required">{lang="required"}</span>
		</label>
		<div class="ipsFieldRow_content">
			{{if $authType === \IPS\Login::AUTH_TYPE_USERNAME}}
				<input type="text" placeholder="{lang="username"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}} autocomplete="username">
			{{elseif $authType === \IPS\Login::AUTH_TYPE_EMAIL}}
				<input type="email" placeholder="{lang="email_address"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}} autocomplete="email">
			{{else}}
				<input type="text" placeholder="{lang="username_or_email"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}} autocomplete="email">
			{{endif}}
		</div>
	</li>
	<li class="ipsFieldRow ipsFieldRow_fullWidth ipsClearfix">
		<label class="ipsFieldRow_label" for="password">
			{lang="password"}
			<span class="ipsFieldRow_required">{lang="required"}</span>
		</label>
		<div class="ipsFieldRow_content">
			<input type="password" placeholder="{lang="password"}" name="password" id="password" {{if isset( \IPS\Request::i()->password )}}value="{request="password"}"{{endif}} autocomplete="current-password">
		</div>
	</li>
	<li class="ipsFieldRow ipsFieldRow_checkbox ipsClearfix">
		<span class="ipsCustomInput">
			<input type="checkbox" name="remember_me" id="remember_me_checkbox" value="1" checked aria-checked="true">
			<span></span>
		</span>
		<div class="ipsFieldRow_content">
			<label class="ipsFieldRow_label" for="remember_me_checkbox">{lang="remember_me"}</label>
			<span class="ipsFieldRow_desc">{lang="remember_me_desc"}</span>
		</div>
	</li>
	<li class="ipsFieldRow ipsFieldRow_fullWidth">
		<button type="submit" name="_processLogin" value="usernamepassword" class="ipsButton ipsButton_primary ipsButton_small" id="elSignIn_submit">{lang="login"}</button>
		{{if settings.allow_forgot_password != 'disabled'}}
			<p class="ipsType_right ipsType_small">
				{{if settings.allow_forgot_password == 'redirect'}}
					<a href='{expression="\IPS\Settings::i()->allow_forgot_password_target"}' target="_blank" rel="noopener">
				{{else}}
					<a href='{url="app=core&module=system&controller=lostpass" seoTemplate="lostpassword"}' data-ipsDialog data-ipsDialog-title='{lang="forgotten_password"}'>
				{{endif}}
				{lang="forgotten_password"}</a>
			</p>
		{{endif}}
	</li>
</ul>