<ips:template parameters="" />
<section class='ipsType_center ipsPadding ipsBox'>
	<h1 class='ipsType_veryLarge ipsType_center'>{lang="coppa_consent_required"}</h1>
	<br>

	<div data-role='registerForm'>
		<p class='ipsType_large'>
			{lang="coppa_consent_required_desc"}
		</p>
		<br><br>

		<a href='{url="app=core&module=system&controller=register&do=coppaForm" seoTemplate="register"}' class='ipsButton ipsButton_primary ipsButton_large'>{lang="coppa_print_form"}</a>
	</div>
</section>