<ips:template parameters="$title, $form, $ajax=FALSE" />
{{if $ajax}}
	<div class='md:ipsPadding'>
		<div class="ipsClearfix">
			<a href="#" class="ipsDialog_close" data-action="closeNotificationSettings">×</a>
			<h3 class="ipsDataItem_title ipsType_reset">
				{$title}
			</h3>
		</div>
		<div class="ipsSpacer_top">
			{$form|raw}
		</div>
	</div>
{{else}}
	{template="pageHeader" group="global" params="$title"}
	<div class="ipsBox ipsPad">
		{$form|raw}
	</div>
{{endif}}