<ips:template parameters="$form=null" />
<div class='ipsAreaBackground_light ipsPadding ipsBorder_bottom'>
	<h2 class='ipsType_pageTitle'>{lang="change_password"}</h2>
</div>

<div class='ipsPadding'>
	{{if \IPS\Member::loggedIn()->passwordResetForced()}}
		<p class='ipsMessage ipsMessage_warning'>{lang="password_reset_required"}</p>
	{{endif}}
	{{if $form}}
		{$form|raw}
	{{else}}
		<div class='ipsType_normal'>
			{lang="change_password_admin_1"}
		</div>

		<ol class='ipsList_bullets ipsList_numbers ipsSpacer_top ipsType_normal'>
			<li>{lang="change_password_admin_2"}</li>
			<li>{lang="change_password_admin_3" sprintf="\IPS\Member::loggedIn()->name"}</li>
			<li>{lang="change_password_admin_4"}</li>
			<li>{lang="change_password_admin_5"}</li>
		</ol>
	{{endif}}
</div>