<ips:template parameters="$form, $sigLimits" />
<div class='ipsPadding'>
{{if $sigLimits[1] != "" or $sigLimits[2] or $sigLimits[3] or $sigLimits[4] or $sigLimits[5]}}
		<h2 class='ipsType_sectionHead'>{lang="signature_restrictions"}</h2>
		<p class='ipsType_medium ipsType_reset'>
			{lang="ensure_signature_restrictions"}:
		</p>

		<div class='ipsType_textBlock ipsType_normal'>
			<br>
			<ul class='ipsList_inline'>
				{{if $sigLimits[1] != ""}}
					<li>{{if $sigLimits[1]}}<i class='fa fa-check'></i> {lang="sig_max_imagesr" pluralize="$sigLimits[1]"}{{else}}<i class='fa fa-close'></i> {lang="sig_max_imagesr_none"}{{endif}}</li>
				{{endif}}
				{{if $sigLimits[2] or $sigLimits[3]}}
					<li><i class='fa fa-check'></i> {lang="sig_max_imgsize" sprintf="$sigLimits[2], $sigLimits[3]"}</li>
				{{endif}}
				{{if $sigLimits[4]}}
					<li><i class='fa fa-check'></i> {lang="sig_max_urls" pluralize="$sigLimits[4]"}</li>
				{{endif}}
				{{if $sigLimits[5]}}
					<li><i class='fa fa-check'></i> {lang="sig_max_lines" pluralize="$sigLimits[5]"}</li>
				{{endif}}
			</ul>
		</div>
		<hr class='ipsHr'><br>
{{endif}}
		{$form|raw}
	</div>