<ips:template parameters="$canChangePassword, $canConfigureMfa, $hasConfiguredMfa, $loginMethods, $oauthApps=0" />
{template="pageHeader" group="global" params="\IPS\Member::loggedIn()->language()->addToStack('secure_account'), \IPS\Member::loggedIn()->language()->addToStack('secure_account_blurb')"}
{{if $canChangePassword}}
	<div class="ipsBox ipsBox--child ipsSpacer_bottom">
		<h2 class="ipsType_sectionTitle ipsType_reset">{lang="change_password"}</h2>
		<div class="ipsPad ipsType_normal">
			<p class="ipsType_reset">
				{lang="secure_account_change_password"}
			</p>
			<div class="ipsSpacer_top">
				<a href="{url="app=core&module=system&controller=settings&area=password" seoTemplate="settings_password"}" target="_blank" rel="noopener" class="ipsButton ipsButton_primary ipsButton_small">{lang="change_password"}</a>
			</div>
		</div>
	</div>
{{endif}}
{{if $canConfigureMfa}}
	<div class="ipsBox ipsBox--child ipsSpacer_bottom">
		<h2 class="ipsType_sectionTitle ipsType_reset">{lang="mfa_settings_title"}</h2>
		<div class="ipsPad ipsType_normal">
			<p class="ipsType_reset">
				{{if $hasConfiguredMfa}}
					{lang="secure_account_mfa_revise"}
				{{else}}
					{lang="secure_account_mfa_setup"}
				{{endif}}
			</p>
			<div class="ipsSpacer_top">
				<a href="{url="app=core&module=system&controller=settings&area=mfa" seoTemplate="settings_mfa"}" target="_blank" rel="noopener" class="ipsButton ipsButton_primary ipsButton_small">{lang="mfa_settings_title"}</a>
			</div>
		</div>
	</div>
{{endif}}
{{if \count( $loginMethods )}}
	<div class="ipsBox ipsBox--child ipsSpacer_bottom">
		<h2 class="ipsType_sectionTitle ipsType_reset">{lang="secure_account_login_title"}</h2>
		<div class="ipsPad ipsType_normal">
			<p class="ipsType_reset ipsSpacer_bottom">
				{lang="secure_account_login_info"}
			</p>
			<ul class="ipsDataList">
				{{foreach $loginMethods as $id => $details}}
					<li class='ipsDataItem ipsClearfix'>
						<div class="ipsDataItem_icon ipsPos_top">
							{{if isset( $details['icon'] )}}
								<img src="{$details['icon']}" class="ipsUserPhoto ipsUserPhoto_mini">
							{{else}}
								<img src="{resource="default_photo.png" app="core" location="global"}" class="ipsUserPhoto ipsUserPhoto_mini">
							{{endif}}
						</div>
						<div class='ipsDataItem_main'>
							<h4 class='ipsDataItem_title'><strong>{$details['title']}</strong></h4><br>
							{$details['blurb']}<br>
							<a href="{url="app=core&module=system&controller=settings&area=login&service={$id}" seoTemplate="settings_login"}" class="ipsButton ipsButton_primary ipsButton_small">{lang="profilesync_configure"}</a>
						</div>							
					</li>
				{{endforeach}}
			</ul>
		</div>
	</div>
{{endif}}
{{if $oauthApps}}
	<div class="ipsBox ipsBox--child ipsSpacer_bottom">
		<h2 class="ipsType_sectionTitle ipsType_reset">{lang="oauth_apps"}</h2>
		<div class="ipsPad ipsType_normal">
			<p class="ipsType_reset">
				{lang="secure_account_apps" pluralize="$oauthApps"}
			</p>
			<div class="ipsSpacer_top">
				<a href="{url="app=core&module=system&controller=settings&area=apps" seoTemplate="settings_apps"}" target="_blank" rel="noopener" class="ipsButton ipsButton_primary ipsButton_small">{lang="review_oauth_apps"}</a>
			</div>
		</div>
	</div>
{{endif}}
