<ips:template parameters="$method, $login, $error" />
{{if $error}}
	<div class="ipsMessage ipsMessage_error">{lang="$error"}</div>
{{endif}}
<form accept-charset='utf-8' method='post' action='{$login->url}' data-controller="core.global.core.login">
	<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
	{{if $method->type() === \IPS\Login::TYPE_USERNAME_PASSWORD}}
		<ul class='ipsForm'>
			<li class="ipsFieldRow ipsFieldRow_fullWidth ipsClearfix">
				{{$authType = $method->authType();}}
				<label class="ipsFieldRow_label" for="auth">
					{{if $authType === \IPS\Login::AUTH_TYPE_USERNAME}}
						{lang="username"}
					{{elseif $authType === \IPS\Login::AUTH_TYPE_EMAIL}}
						{lang="email_address"}
					{{else}}
						{lang="username_or_email"}
					{{endif}}
					<span class="ipsFieldRow_required">{lang="required"}</span>
				</label>
				<div class="ipsFieldRow_content">
					{{if $authType === \IPS\Login::AUTH_TYPE_USERNAME}}
						<input type="text" placeholder="{lang="username"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}}>
					{{elseif $authType === \IPS\Login::AUTH_TYPE_EMAIL}}
						<input type="email" placeholder="{lang="email_address"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}}>
					{{else}}
						<input type="text" placeholder="{lang="username_or_email"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}}>
					{{endif}}
				</div>
			</li>
			<li class="ipsFieldRow ipsFieldRow_fullWidth ipsClearfix">
				<label class="ipsFieldRow_label" for="password">
					{lang="password"}
					<span class="ipsFieldRow_required">{lang="required"}</span>
				</label>
				<div class="ipsFieldRow_content">
					<input type="password" placeholder="{lang="password"}" name="password" id="password" {{if isset( \IPS\Request::i()->password )}}value="{request="password"}"{{endif}}>
				</div>
			</li>
			<li class="ipsFieldRow ipsFieldRow_fullWidth">
				<button type="submit" name="_processLogin" value="usernamepassword" class="ipsButton ipsButton_primary ipsButton_small" id="elSignIn_submit">{lang="login"}</button>
				{{if $forgotPasswordUrl = $method->forgotPasswordUrl()}}
					<p class="ipsType_right ipsType_small">
						<a href='{$forgotPasswordUrl}' target="_blank" rel="noopener">{lang="forgotten_password"}</a>
					</p>
				{{endif}}
			</li>
		</ul>	
	{{else}}
		{$method->button()|raw}
	{{endif}}
</form>