<ips:template parameters="$loginMethods, $canChangePassword" />
<div class='ipsPadding sm:ipsPadding:half'>
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_fluid'>
			<ul class='ipsDataList'>
				<li class='ipsDataItem'>
					<div class='ipsDataItem_main'>
						{{if \IPS\Member::loggedIn()->group['g_dname_changes']}}
							<a href="{url="app=core&module=system&controller=settings&area=username" seoTemplate="settings_username"}" class="ipsButton ipsButton_link ipsPos_right">{lang="change"}</a>
						{{endif}}
						<h4 class='ipsDataItem_title'><strong>{lang="username"}</strong></h4><br>
						{member="name"}
					</div>
				</li>
				<li class='ipsDataItem'>
					<div class='ipsDataItem_main'>
						{{if \IPS\Settings::i()->allow_email_changes != 'disabled'}}
							{{if settings.allow_email_changes == 'redirect'}}
								<a href='{expression="\IPS\Settings::i()->allow_email_changes_target"}' target="_blank" rel="noopener" class="ipsButton ipsButton_link ipsPos_right">
							{{else}}
								<a href='{url="app=core&module=system&controller=settings&area=email" seoTemplate="settings_email"}' class="ipsButton ipsButton_link ipsPos_right">
							{{endif}}
							{lang="change"}</a>
						{{endif}}
						<h4 class='ipsDataItem_title'><strong>{lang="email_address"}</strong></h4><br>
						{member="email"}
					</div>
				</li>
				{{if $canChangePassword}}
					<li class='ipsDataItem'>
						<div class='ipsDataItem_main'>
							<a href="{url="app=core&module=system&controller=settings&area=password" seoTemplate="settings_password"}" class="ipsButton ipsButton_link ipsPos_right">{lang="change"}</a>
							<h4 class='ipsDataItem_title'><strong>{lang="password"}</strong></h4><br>
							********
						</div>
					</li>
				{{endif}}
				<li class='ipsDataItem'>
					<div class='ipsDataItem_main'>
						<h4 class='ipsDataItem_title'><strong>{lang="profile_completion_status"}</strong></h4><br>
						{template="profileNextStep" group="global" app="core" params="\IPS\Member::loggedIn()->nextProfileStep(), false, false"}
					</div>
				</li>
				{{foreach $loginMethods as $id => $details}}
					<li class='ipsDataItem ipsClearfix'>
						<div class="ipsDataItem_icon">
							{{if isset( $details['icon'] )}}
								<img src="{$details['icon']}" class="ipsUserPhoto ipsUserPhoto_mini">
							{{else}}
								<img src="{resource="default_photo.png" app="core" location="global"}" class="ipsUserPhoto ipsUserPhoto_mini">
							{{endif}}
						</div>
						<div class='ipsDataItem_main'>
							<a href="{url="app=core&module=system&controller=settings&area=login&service={$id}" seoTemplate="settings_login"}" class="ipsButton ipsButton_link ipsPos_right">{lang="profilesync_configure"}</a>
							<h4 class='ipsDataItem_title'><strong>{$details['title']}</strong></h4><br>
							{$details['blurb']}
						</div>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<div class='ipsColumn ipsColumn_wide'>
			<div class='ipsBox ipsBox--child'>
				{{$thisMemberID = \IPS\Member::loggedIn()->member_id;}}
				<h3 class='ipsType_sectionTitle'>{lang="other_settings"}</h3>
				<ul class='ipsSideMenu_list ipsPadding:half'>
					<li class='ipsSideMenu_item'><a href='{url="app=core&module=system&controller=notifications&do=options" seoTemplate="notifications_options"}'>{lang="notification_options"}</a></li>
					{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'members', 'front' ) ) AND \IPS\Member::loggedIn()->group['g_edit_profile']}}
						<li class='ipsSideMenu_item'><a href='{expression="\IPS\Member::loggedIn()->url()->setQueryString( 'do', 'edit' )"}' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-title='{lang="profile_edit"}'>{lang="profile_edit"}</a></li>
					{{endif}}
					{{if settings.ignore_system_on}}
						<li class='ipsSideMenu_item'><a href='{url="app=core&module=system&controller=ignore" seoTemplate="ignore"}'>{lang="menu_manage_ignore"}</a></li>
					{{endif}}
				</ul>
			</div>
		</div>
	</div>
</div>