<ips:template parameters="$form=NULL, $login=NULL, $error=NULL" />
<div class='ipsAreaBackground_light ipsPadding ipsBorder_bottom'>
	<h2 class='ipsType_pageTitle'>{lang="change_email_address"}</h2>
</div>
<div class='ipsPadding'>
	{{if $form}}
		{{if \IPS\Settings::i()->reg_auth_type == 'user' or \IPS\Settings::i()->reg_auth_type == 'admin_user'}}
			<div class='ipsType_textBlock ipsType_normal'>
				<ul class='ipsList_bullets'>
					<li>{lang="change_email_explain_1"}</li>
					<li>
						{lang="change_email_explain_2"}
					</li>
				</ul>
			</div>
			<hr class='ipsHr'>
		{{endif}}
		{$form|raw}
	{{elseif $login}}
		<br><hr class='ipsHr'>
		{template="reauthenticate" group="system" params="$login, $error"}
	{{else}}
		<div class='ipsType_normal'>
			{lang="change_email_admin_1"}
		</div>

		<ol class='ipsList_bullets ipsList_numbers ipsSpacer_top ipsType_normal'>
			<li>{lang="change_email_admin_2"}</li>
			<li>{lang="change_email_admin_3" sprintf="\IPS\Member::loggedIn()->name"}</li>
			<li>{lang="change_email_admin_4"}</li>
			<li>{lang="change_email_admin_5"}</li>
		</ol>
	{{endif}}
</div>