<ips:template parameters="$apps" />
<div class='ipsAreaBackground_light ipsPadding ipsBorder_bottom'>
	<h2 class="ipsType_pageTitle">{lang="oauth_apps"}</h2>
</div>

<div class='ipsPadding'>
	<p class="ipsType_normal ipsSpacer_bottom ipsSpacer_double">{lang="oauth_apps_info"}</p>
	{{if \count( $apps )}}
		{{foreach $apps as $app}}
			<div class="ipsBox ipsSpacer_bottom ipsClearfix">
				<div class="ipsAreaBackground_light ipsClearfix ipsPad">
					<div class="ipsPos_right">
						<a href="{url="core&module=system&controller=settings&area=apps&do=revokeApp&client_id={$app['client']->client_id}" seoTemplate="settings_apps" csrf="true"}" class="ipsButton ipsButton_negative ipsButton_small" data-confirm data-confirmSubMessage="{lang="oauth_app_revoke_confirm"}">
							{lang="oauth_app_revoke"}
						</a>
					</div>
					<div class="ipsPad_half">
						<h2 class="ipsType_sectionHead">
							{$app['client']->_title}
						</h2>
					</div>
				</div>
				<div class="ipsPad">
					<ul class="ipsDataList">
						<li class="ipsDataItem">
							<span class="ipsDataItem_generic ipsDataItem_size6">
								<strong>{lang="oauth_app_issued"}</strong>
							</span>
							<span class="ipsDataItem_generic">
								{datetime="$app['issued']"}
							</span>
						</li>
						{{if $app['scopes']}}
							<li class="ipsDataItem">
								<span class="ipsDataItem_generic ipsDataItem_size6">
									<strong>{lang="oauth_app_scopes"}</strong>
								</span>
								<div class="ipsDataItem_generic">
									<ul class="ipsList_reset">
										{{foreach $app['scopes'] as $key => $scope}}
											<li>
												<i class="fa fa-check"></i> {$scope}
											</li>
										{{endforeach}}
									</ul>
								</div>
							</li>
						{{endif}}
					</ul>
				</div>
			</div>
		{{endforeach}}
	{{else}}
		<div class="ipsPad ipsType_center ipsType_light">{lang="oauth_apps_empty"}</div>
	{{endif}}
</div>