<ips:template parameters="" />
{{if !\IPS\Request::i()->isAjax()}}
	{template="pageHeader" group="global" params="\IPS\Member::loggedIn()->language()->addToStack('reg_terms')"}
{{endif}}
<div class='ipsBox_alt ipsType_normal ipsType_richText ipsPad'>
	{template="richText" group="global" app="core" location="global" params="\IPS\Member::loggedIn()->language()->addToStack('reg_rules_value'), array('ipsType_normal')"}
</div>