<ips:template parameters="$forum, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm ipsForm_vertical" method='post' action='{$action}' data-ipsValidation novalidate>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}

	<div class='ipsPad'>
		<p class='ipsType_normal ipsType_reset'>
			{lang="enter_forum_password_1" sprintf="$forum->_title"}
		</p>

		<br>
		<ul class='ipsList_reset'>
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{{if $input instanceof \IPS\Helpers\Form\Text}}
						<li class="ipsFieldRow ipsFieldRow_primary ipsFieldRow_noLabel ipsFieldRow_fullWidth {{if $input->error}}ipsFieldRow_error{{endif}}">
							<input type="{$input->formType}" required placeholder="{lang="$input->name"}" name='{$input->name}' id='{$input->htmlId}'>
							{{if $input->error}}
								<br>
								<span class="ipsType_warning">{lang="$input->error"}</span>
							{{endif}}
						</li>
					{{endif}}
				{{endforeach}}
			{{endforeach}}
		</ul>
	</div>
	<div class='ipsPad ipsAreaBackground ipsType_right'>
		<button type="submit" class="ipsButton ipsButton_primary ipsButton_small">{lang="enter_forum"}</button>
	</div>
</form>