<ips:template parameters="$table, $headers, $rows" />
{{$rowIds = array();}}
{{foreach $rows as $row}}
	{{$idField = $row::$databaseColumnId;}}
	{{$rowIds[] = $row->$idField;}}
{{endforeach}}
{{if \count( $rows )}}
	{{$rowCount=0;}}
	{{foreach $rows as $row}}
		{{if $rowCount == 1 AND $advertisement = \IPS\core\Advertisement::loadByLocation( 'ad_forum_listing' )}}
			<li class="ipsDataItem">
				{$advertisement|raw}
			</li>
		{{endif}}
		{{$rowCount++;}}
		{{$idField = $row::$databaseColumnId;}}
		{{if $row->mapped('moved_to')}}
			{{if $movedTo = $row->movedTo()}}
				<li class="ipsDataItem {{if \IPS\forums\Forum::getMemberListView() == 'snippet'}}ipsTopicSnippet ipsQuestionSnippet{{endif}}">
					<div class='ipsDataItem_icon ipsType_center ipsType_noBreak'>
						<i class="fa fa-arrow-left ipsType_large"></i>
					</div>
					<div class='ipsDataItem_main'>
						<h4 class='ipsDataItem_title ipsType_break'>
							<span class='ipsType_break ipsContained'>
								<em><a href='{$movedTo->url()}' title='{lang="go_to_new_location"}'>{$row->mapped('title')}</a></em>
							</span>
						</h4>
						<div class='ipsDataItem_meta'>
							{{if isset( $row::$databaseColumnMap['status'] )}}
								{{$statusField = $row::$databaseColumnMap['status'];}}
								{{if $row->$statusField == 'merged'}}
									<p class='ipsType_reset ipsType_light ipsType_blendLinks'>{lang="question_merged_to" sprintf="$movedTo->url(), $movedTo->mapped('title')"}</p>
								{{else}}
									<p class='ipsType_reset ipsType_light ipsType_blendLinks'>{lang="question_moved_to" sprintf="$movedTo->container()->url(), $movedTo->container()->_title"}</p>
								{{endif}}
							{{else}}
								<p class='ipsType_reset ipsType_light ipsType_blendLinks'>{lang="question_moved_to" sprintf="$movedTo->container()->url(), $movedTo->container()->_title"}</p>
							{{endif}}
						</div>
					</div>
					{{if $table->canModerate()}}
						<div class='ipsDataItem_modCheck'>
							<span class='ipsCustomInput'>
								<input type='checkbox' data-role='moderation' name="moderate[{$row->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{{if $row->mapped('pinned')}}pinned{{endif}} {{if $row->mapped('featured')}}featured{{endif}}'>
								<span></span>
							</span>
						</div>
					{{endif}}
				</li>
			{{endif}}
		{{else}}
			<li class="ipsDataItem {{if \IPS\forums\Forum::getMemberListView() == 'snippet'}}ipsTopicSnippet ipsQuestionSnippet{{endif}} {{if $row->unread()}}ipsDataItem_unread{{endif}} {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if $row->hidden()}}ipsModerated{{endif}} cForumQuestion" data-rowID='{$row->$idField}'>
				<div class='ipsDataItem_icon'>
					{{if $row->topic_answered_pid}}
						<span title='{lang="answered"}' class='cBestAnswerIndicator' data-ipsTooltip>
							<i class='fa fa-check'></i>
						</span>
					{{else}}
						<span title='{lang="awaiting_answer"}' class='cBestAnswerIndicator cBestAnswerIndicator_off' data-ipsTooltip>
							<i class='fa fa-question'></i>
						</span>
					{{endif}}
				</div>
				<div class='ipsDataItem_main'>
					<h4 class='ipsDataItem_title ipsContained_container'>
						<span class='ipsType_break ipsContained'>
							{{if $row->locked()}}
								<span><i class='fa fa-lock' data-ipsTooltip title='{lang="topic_locked"}'></i></span>
							{{endif}}
							{{if $row->unread()}}
								<span>
									<a href='{$row->url( 'getNewComment' )}' title='{lang="first_unread_post"}' data-ipsTooltip>
										<span class='ipsItemStatus'><i class="fa {{if \in_array( $row->$idField, $table->contentPostedIn )}}fa-star{{else}}fa-circle{{endif}}"></i></span>
									</a>
								</span>
							{{else}}
								{{if \in_array( $row->$idField, $table->contentPostedIn )}}
									<span><span class='ipsItemStatus ipsItemStatus_read ipsItemStatus_posted'><i class="fa fa-star"></i></span></span>
								{{endif}}
							{{endif}}

							{{if $row->mapped('pinned') || $row->mapped('featured') || $row->hidden() === -1 || $row->hidden() === 1}}
							<span>
								{{if $row->hidden() === -1}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$row->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
								{{elseif $row->hidden() === 1}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
								{{endif}}
								{{if $row->mapped('pinned')}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
								{{endif}}
								{{if $row->mapped('featured')}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
								{{endif}}
							</span>
							{{endif}}

							{{if $row->prefix()}}
								<span>{template="prefix" group="global" app="core" params="$row->prefix( TRUE ), $row->prefix()"}</span>
							{{endif}}
							
							<a href='{$row->url( "getPrefComment" )}' title='{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}{lang="content_deleted"}{{endif}} {{if $row->canEdit()}}{lang="click_hold_edit"}{{endif}}' {{if $row->tableHoverUrl and $row->canView()}}data-ipsHover data-ipsHover-target='{$row->url()->setQueryString('preview', 1)}' data-ipsHover-timeout='1.5'{{endif}} {{if $row->canEdit()}} data-role="editableTitle"{{endif}}>
								<span>
									{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}
								</span>
							</a>
						</span>
					</h4>
					{{if \IPS\forums\Forum::getMemberListView() == 'snippet'}}
						<div class='ipsTopicSnippet__snippet ipsType_normal ipsType_blendLinks ipsType_break'>
							<p>{$row->firstComment->snippet(680)}</p>		
						</div>
					{{endif}}
					<div class='ipsDataItem_meta'>
						<p class='ipsDataItem_meta ipsType_reset ipsType_light ipsType_blendLinks'>
							<span>
								{lang="ask_byline_itemprop" htmlsprintf="$row->author()->link(), \IPS\DateTime::ts( $row->start_date )->html()"}
							</span>
							{{if \IPS\Request::i()->controller != 'forums'}}
								{lang="in"} <a href="{$row->container()->url()}">{$row->container()->_title}</a>
							{{endif}}
						</p>
						{{if \count( $row->tags() )}}
							<div>{template="tags" group="global" app="core" params="$row->tags()"}</div>
						{{endif}}
					</div>
				</div>
				<div class='ipsDataItem_generic ipsDataItem_size2 ipsType_center cForumQuestion_stat'>
					<span>{{if $row->question_rating}}{$row->question_rating}{{else}}0{{endif}}</span>
					<span class='ipsType_light'>{lang="votes_no_number" pluralize="$row->question_rating"}</span>
				</div>
				<div class='ipsDataItem_generic ipsDataItem_size2 ipsType_center cForumQuestion_stat'>
					{{foreach $row->stats(FALSE) AS $k => $v}}
						{{if $k == 'forums_comments' OR $k == 'answers_no_number'}}
							<span>{number="$v"}</span>
							<span class='ipsType_light'>
								{lang="answers_no_number" pluralize="$v"}
								{{if \IPS\forums\Topic::modPermission( 'unhide', NULL, $row->container() ) AND $unapprovedComments = $row->mapped('unapproved_comments')}}
									&nbsp;<a href='{$row->url()->setQueryString( 'queued_posts', 1 )}' class='ipsType_warning ipsType_small ipsResponsive_noFloat' data-ipsTooltip title='{lang="queued_posts_badge" pluralize="$row->topic_queuedposts"}'><i class='fa fa-warning'></i> <strong>{$unapprovedComments}</strong></a>
								{{endif}}
							</span>
						{{endif}}
					{{endforeach}}
				</div>
				{{if $table->canModerate()}}
					<div class='ipsDataItem_modCheck'>
						<span class='ipsCustomInput'>
							<input type='checkbox' data-role='moderation' name="moderate[{$row->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{{if $row->tableStates()}}{$row->tableStates()}{{endif}}'>
							<span></span>
						</span>
					</div>
				{{endif}}
			</li>
		{{endif}}
	{{endforeach}}
{{endif}}