<ips:template parameters="" />

{{if $announcements = \IPS\core\Announcements\Announcement::loadAllByLocation('content')}}
	<div class='cAnnouncementsContent'>
		{{foreach $announcements as $announcement}}
		<div class='cAnnouncementContentTop ipsAnnouncement ipsMessage_{$announcement->color} ipsType_center'>
            {{if $announcement->type == \IPS\core\Announcements\Announcement::TYPE_CONTENT}}
			<a href='{$announcement->url()}' data-ipsDialog data-ipsDialog-title="{$announcement->title}">{$announcement->title}</a>
            {{elseif $announcement->type == \IPS\core\Announcements\Announcement::TYPE_URL}}
            <a href='{$announcement->url}' target="_blank" rel='noopener'>{$announcement->title}</a>
            {{else}}
            <span>{$announcement->title}</span>
            {{endif}}
		</div>
		{{endforeach}}
	</div>
{{endif}}