<ips:template parameters="" />

{{if $announcements = \IPS\core\Announcements\Announcement::loadAllByLocation('top')}}
<div class='cAnnouncements' data-controller="core.front.core.announcementBanner" >
	{{foreach $announcements as $announcement}}
	<div class='cAnnouncementPageTop ipsJS_hide ipsAnnouncement ipsMessage_{$announcement->color}' data-announcementId="{$announcement->id}">
        {{if $announcement->type == \IPS\core\Announcements\Announcement::TYPE_CONTENT}}
        <a href='{$announcement->url()}' data-ipsDialog data-ipsDialog-title="{$announcement->title}">{$announcement->title}</a>
        {{elseif $announcement->type == \IPS\core\Announcements\Announcement::TYPE_URL}}
        <a href='{$announcement->url}' target="_blank" rel='noopener'>{$announcement->title}</a>
        {{else}}
        <span>{$announcement->title}</span>
        {{endif}}

		<a href='#' data-role="dismissAnnouncement">×</a>
	</div>
	{{endforeach}}
</div>
{{endif}}