<ips:template parameters="$announcements" />

<div class='ipsBox ipsSpacer_bottom' id="cAnnouncementSidebar">
	<span class="cAnnouncementIcon"><i class='fa fa-bullhorn fa-3x fa-fw'></i></span>
	<h3 class='ipsType_minorHeading ipsType_center ipsType_medium ipsType_dark ipsSpacer_bottom'>{lang="announcements"}</h3>
	<ul class='ipsList_reset'>
	{{foreach $announcements as $announcement}}
		<li class="cAnnouncementSidebar ipsAnnouncement ipsMessage_{$announcement->color}">
            {{if $announcement->type == \IPS\core\Announcements\Announcement::TYPE_CONTENT}}
            <a href='{$announcement->url()}' data-ipsDialog data-ipsDialog-title="{$announcement->title}">{$announcement->title}</a>
            {{elseif $announcement->type == \IPS\core\Announcements\Announcement::TYPE_URL}}
            <a href='{$announcement->url}' target="_blank" rel='noopener'>{$announcement->title}</a>
            {{else}}
            <span>{$announcement->title}</span>
            {{endif}}
        </li>
	{{endforeach}}
	</ul>
</div>