<ips:template parameters="$editHistory, $comment" />
{{if !\IPS\Request::i()->isAjax()}}
<h1 class='ipsType_pageTitle'>{lang="edit_history_title"}</h1>
{{endif}}

{{if \IPS\Settings::i()->edit_log_prune > 0}}
	<div class='ipsMessage ipsMessage_info{{if !\IPS\Request::i()->isAjax()}} ipsSpacer_top{{endif}}'>{lang="edit_log_prune_notice" pluralize="\IPS\Settings::i()->edit_log_prune"}</div>
{{endif}}
<div class="ipsPad" data-role="commentFeed">
	{{if \count($editHistory) }}
		{{foreach $editHistory as $edit}}
		<article class='ipsBox ipsBox--child ipsComment ipsComment_parent ipsClearfix ipsClear'>
			<div class='ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini ipsPhotoPanel_notPhone'>
				{template="userPhoto" app="core" group="global" params="\IPS\Member::load( $edit['member'] ), 'mini'"}
				<div>
					<h3 class='ipsComment_author ipsType_sectionHead'>
						{expression="\IPS\Member::load( $edit['member'] )->link()" raw="true"}
					</h3>
					<p class='ipsComment_meta ipsType_light'>
						{datetime="$edit['time']"}
						{{if $edit['reason']}}
						<br>
						{$edit['reason']}
						{{endif}}
					</p>
				</div>
			</div>
			<div class='ipsAreaBackground_reset ipsPad'>
				<div class='ipsType_richText'>
					{$edit['new']|raw}
				</div>
			</div>
		</article>
		{{endforeach}}
		<article class='ipsBox ipsBox--child ipsComment ipsComment_parent ipsClearfix ipsClear'>
			<div class='ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini ipsPhotoPanel_notPhone'>
				{template="userPhoto" app="core" group="global" params="$comment->author(), 'mini'"}
				<div>
					<h3 class='ipsComment_author ipsType_sectionHead'>
						{$comment->author()->link()|raw}
					</h3>
					<p class='ipsComment_meta ipsType_light'>
						{datetime="$comment->mapped('date')"}
					</p>
				</div>
			</div>
			<div class='ipsAreaBackground_reset ipsPadding_vertical sm:ipsPadding_vertical:half ipsPadding_horizontal'>
				<div class='ipsType_richText'>
					{$edit['old']|raw}
				</div>
			</div>
		</article>
	{{else}}
		<p class='ipsType_large ipsType_light'>{lang="no_edit_history"}</p>
	{{endif}}
</div>
