<ips:template parameters="$item, $container, $type='comment'" />

{{$method = $type . 'MultimodActions';}}
{{if $actions = $item->$method() and \count( $actions )}}
	<div class="ipsCommentMultimod ipsMargin_bottom ipsClearfix">
		<ul class="ipsButtonRow ipsPos_right ipsClearfix">
			<li>
				<a class="ipsJS_show" href="#elCheck_menu" id="elCheck" title='{lang="select_rows_tooltip"}' data-ipsTooltip data-ipsAutoCheck data-ipsAutoCheck-context="{$container}" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active">
					<span class="cAutoCheckIcon ipsType_medium"><i class="fa fa-square-o"></i></span> <i class="fa fa-caret-down"></i>
					<span class='ipsNotificationCount' data-role='autoCheckCount'>0</span>
				</a>
				<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="elCheck_menu">
					<li class="ipsMenu_title">{lang="select_rows"}</li>
					<li class="ipsMenu_item" data-ipsMenuValue="all"><a href="#">{lang="all"}</a></li>
					<li class="ipsMenu_item" data-ipsMenuValue="none"><a href="#">{lang="none"}</a></li>
					<li class="ipsMenu_sep"><hr></li>
					<li class="ipsMenu_item" data-ipsMenuValue="hidden"><a href="#">{lang="hidden"}</a></li>
					<li class="ipsMenu_item" data-ipsMenuValue="unhidden"><a href="#">{lang="unhidden"}</a></li>
					<li class="ipsMenu_item" data-ipsMenuValue="unapproved"><a href="#">{lang="unapproved"}</a></li>
				</ul>
			</li>
		</ul>
	</div>
{{endif}}