<ips:template parameters="$item, $comment, $editorName, $app, $type, $class=''" />
{{$idField = $comment::$databaseColumnId;}}
<div id='comment-{$comment->$idField}_wrap' data-controller='core.front.core.comment' data-commentApp='{$app}' data-commentType='{$type}' data-commentID="{$comment->$idField}" data-quoteData='{expression="json_encode( array('userid' => $comment->author()->member_id, 'username' => $comment->author()->name, 'timestamp' => $comment->mapped('date'), 'contentapp' => $app, 'contenttype' => $type, 'contentclass' => $class, 'contentid' => $item->id, 'contentcommentid' => $comment->$idField) )"}' class='ipsComment_content ipsType_medium'>
	
	{{if $comment->author()->hasHighlightedReplies() || ( settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $comment->reactionCount() >= settings.reputation_highlight ) OR $comment->isFeatured()}}
		<div class='ipsResponsive_showPhone ipsComment_badges'>
			<ul class='ipsList_reset ipsFlex ipsFlex-fw:wrap ipsGap:2 ipsGap_row:1'>
				{{if $comment->author()->hasHighlightedReplies()}}
					<li><strong class='ipsBadge ipsBadge_large ipsBadge_highlightedGroup'>{expression="\IPS\Member\Group::load( $comment->author()->member_group_id )->name" raw="true"}</strong></li>
				{{endif}}
				{{if $comment->isFeatured()}}
					<li><strong class='ipsBadge ipsBadge_large ipsBadge_popular'>{lang="this_is_a_featured_post"}</strong></li>
				{{endif}}
				{{if ( settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $comment->reactionCount() >= settings.reputation_highlight ) }}
					<li><strong class='ipsBadge ipsBadge_large ipsBadge_popular'>{lang="this_is_a_popular_comment"}</strong></li>
				{{endif}}
			</ul>
		</div>
	{{endif}}
	<div class='ipsComment_header ipsFlex ipsFlex-ai:start ipsFlex-jc:between'>
		<div class='ipsPhotoPanel ipsPhotoPanel_mini'>
			{template="userPhoto" app="core" group="global" params="$comment->author(), 'mini', $comment->warningRef()"}
			<div>
				<h3 class='ipsComment_author ipsType_blendLinks'>
					<strong class='ipsType_normal'>{template="userLink" app="core" group="global" params="$comment->author(), $comment->warningRef()"}</strong>
					{template="reputationBadge" group="global" app="core" params="$comment->author()"}
				</h3>
				<p class='ipsComment_meta ipsType_light ipsType_medium'>
					<a href='{$comment->url()}' class='ipsType_blendLinks'>{$comment->dateLine()|raw}</a>
					{{if $comment->ip_address and \IPS\Member::loggedIn()->modPermission('can_use_ip_tools') and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) )}}
						&middot; <a class='ipsType_blendLinks ipsType_light ipsType_noUnderline' href="{url="app=core&module=modcp&controller=modcp&tab=ip_tools&ip=$comment->ip_address" seoTemplate="modcp_ip_tools"}" data-ipsMenu data-ipsMenu-menuID='{$comment->$idField}_ip_menu'>{lang="ip_short"} <i class='fa fa-angle-down'></i></a>
					{{endif}}
					{{if $comment->editLine()}}
						({lang="edited_lc"})
					{{endif}}
					{{if $comment->hidden() AND $comment->hidden() != -2}}
						&middot; {$comment->hiddenBlurb()}
					{{elseif $comment->hidden() == -2}}
						&middot; {$comment->deletedBlurb()}
					{{endif}}
				</p>

				{{if member.modPermission('mod_see_warn') and $comment->warning}}
					{template="commentWarned" group="global" app="core" params="$comment"}
				{{endif}}
			</div>
		</div>
		<div class='ipsType_reset ipsType_light ipsType_blendLinks ipsComment_toolWrap'>
			<div class='ipsResponsive_hidePhone ipsComment_badges'>
				<ul class='ipsList_reset ipsFlex ipsFlex-jc:end ipsFlex-fw:wrap ipsGap:2 ipsGap_row:1'>
					{{if $comment->author()->hasHighlightedReplies() || ( settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $comment->reactionCount() >= settings.reputation_highlight ) OR $comment->isFeatured()}}
						{{if $comment->author()->hasHighlightedReplies()}}
							<li><strong class='ipsBadge ipsBadge_large ipsBadge_highlightedGroup'>{expression="\IPS\Member\Group::load( $comment->author()->member_group_id )->name" raw="true"}</strong></li>
						{{endif}}
						{{if $comment->isFeatured()}}
							<li><strong class='ipsBadge ipsBadge_large ipsBadge_popular'>{lang="this_is_a_featured_post"}</strong></li>
						{{endif}}
						{{if ( settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $comment->reactionCount() >= settings.reputation_highlight ) }}
							<li><strong class='ipsBadge ipsBadge_large ipsBadge_popular'>{lang="this_is_a_popular_comment"}</strong></li>
						{{endif}}
					{{endif}}
				</ul>
			</div>
			{{if $comment->hidden() !== 1 && ( $comment->canReportOrRevoke() === TRUE || \count( $comment->sharelinks() ) || $comment->canEdit() || ( $comment->canPromoteToSocialMedia() || $comment->canDelete() || $comment->canSplit() || ( $comment instanceof \IPS\Content\Hideable AND ( ( !$comment->hidden() and $comment->canHide() ) || ( $comment->hidden() and $comment->canUnhide() ) ) ) || ( $comment->hidden() == -2 AND \IPS\Member::loggedIn()->modPermission('can_manage_deleted_content') ) ) || \count( $item->commentMultimodActions() ) )}}
				<ul class='ipsList_reset ipsComment_tools'>
					<li>
						<a href='#elControlsComments_{$comment->$idField}_menu' class='ipsComment_ellipsis' id='elControlsComments_{$comment->$idField}' title='{lang="more_options"}' data-ipsMenu data-ipsMenu-appendTo='#comment-{$comment->$idField}_wrap'><i class='fa fa-ellipsis-h'></i></a>
						<ul id='elControlsComments_{$comment->$idField}_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
							{{if $comment->canReportOrRevoke() === TRUE}}
								<li class='ipsMenu_item'><a href='{$comment->url('report')}' data-ipsDialog data-ipsDialog-remoteSubmit data-ipsDialog-size='medium' data-ipsDialog-flashMessage='{lang="report_submit_success"}' data-ipsDialog-title="{lang="report"}" data-action='reportComment' title='{lang="report_content"}'>{lang="report"}</a></li>
							{{endif}}
							{{if \count( $comment->sharelinks() )}}
								<li class='ipsMenu_item'><a href='{$comment->item()->url()->setQueryString( array( 'do' => 'findComment', 'comment' => $comment->id ) )}' title='{lang="share_this_comment"}' data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-content='#elShareComment_{$comment->id}_menu' data-ipsDialog-title="share_this_comment" id='elShareComment_{$comment->id}' data-role='shareComment'>{lang="share"}</a></li>
							{{endif}}
							{{if $comment->canReportOrRevoke() === TRUE || \count( $comment->sharelinks() )}}
								{{if $comment->canEdit() || ( $comment->canPromoteToSocialMedia() || $comment->canDelete() || $comment->canSplit() || ( $comment instanceof \IPS\Content\Hideable AND ( ( !$comment->hidden() and $comment->canHide() ) || ( $comment->hidden() and $comment->canUnhide() ) ) ) || ( $comment->hidden() == -2 AND \IPS\Member::loggedIn()->modPermission('can_manage_deleted_content') ) )}}
									<li class='ipsMenu_sep'><hr></li>
								{{endif}}
							{{endif}}
							{{if $comment->canEdit()}}
								{{if $comment->mapped('first') and $comment->item()->canEdit()}}
									<li class='ipsMenu_item'><a href='{$comment->item()->url()->setQueryString( 'do', 'edit' )}'>{lang="edit"}</a></li>
								{{else}}
									<li class='ipsMenu_item'><a href='{$comment->url('edit')}' data-action='editComment'>{lang="edit"}</a></li>
								{{endif}}
							{{endif}}
							{{if $comment->hidden() == -2 AND \IPS\Member::loggedIn()->modPermission('can_manage_deleted_content')}}
								<li class='ipsMenu_item'><a href='{$comment->url('restore')->csrf()}' data-confirm data-confirmSubMessage='{lang="restore_as_visible_desc"}'>{lang="restore_as_visible"}</a></li>
								<li class='ipsMenu_item'><a href='{$comment->url('restore')->csrf()->setQueryString( 'restoreAsHidden', 1 )}' data-confirm data-confirmSubMessage='{lang="restore_as_hidden_desc"}'>{lang="restore_as_hidden"}</a></li>
								<li class='ipsMenu_item'><a href='{$comment->url('delete')->csrf()->setQueryString( 'immediately', 1 )}' data-confirm data-confirmSubMessage='{lang="delete_immediately_desc"}'>{lang="delete_immediately"}</a></li>
							{{else}}
								{{if $comment instanceof \IPS\Content\Hideable}}
									{{if !$comment->hidden() and $comment->canHide()}}
										<li class='ipsMenu_item'><a href='{$comment->url('hide')->csrf()}' data-ipsDialog data-ipsDialog-title="{lang="hide"}">{lang="hide"}</a></li>
									{{elseif $comment->hidden() and $comment->canUnhide()}}
										<li class='ipsMenu_item'><a href='{$comment->url('unhide')->csrf()}'>{lang="unhide"}</a></li>
									{{endif}}
								{{endif}}
								{{if $comment->canSplit()}}
									<li class='ipsMenu_item'><a href='{$comment->url('split')}' data-action='splitComment' data-ipsDialog data-ipsDialog-title="{lang="split_to_new" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $item::$title )"}">{lang="split"}</a></li>
								{{endif}}
								{{if $comment->canDelete()}}
									<li class='ipsMenu_item'><a href='{$comment->url('delete')->csrf()->setPage('page',\IPS\Request::i()->page)}' data-action='deleteComment' data-updateOnDelete="#commentCount">{lang="delete"}</a></li>
								{{endif}}
								{{if $comment->isFeatured() AND $item->canUnfeatureComment()}}
									<li class='ipsMenu_item'><a href='{$comment->url('unfeature')->csrf()->setPage('page',\IPS\Request::i()->page)}' data-action="unrecommendComment">{lang="unrecommend_content"}</a></li>
								{{endif}}
								{{if !$comment->isFeatured() AND $item->canFeatureComment()}}
									<li class='ipsMenu_item'><a href='{$comment->url('feature')->csrf()->setPage('page', \IPS\Request::i()->page)}' data-ipsDialog data-ipsDialog-title='{lang="recommend_comment"}' data-ipsDialog-remoteSubmit data-ipsDialog-size='narrow' data-action="recommendComment">{lang="recommend_content"}</a></li>
								{{endif}}
								{{if $comment->canPromoteToSocialMedia()}}
									<li class='ipsMenu_item'>{template="promoteLink" app="core" group="global" params="$comment"}</li>
								{{endif}}
							{{endif}}
						</ul>
					</li>
					{{if \count( $item->commentMultimodActions() )}}
						<li><span class='ipsCustomInput'>
							<input type="checkbox" name="multimod[{$comment->$idField}]" value="1" data-role="moderation" data-actions="{{if $comment->canSplit()}}split merge{{endif}} {{if $comment->hidden() === -1 AND $comment->canUnhide()}}unhide{{elseif $comment->hidden() === 1 AND $comment->canUnhide()}}approve{{elseif $comment->canHide()}}hide{{endif}} {{if $comment->canDelete()}}delete{{endif}}" data-state='{{if $comment->tableStates()}}{$comment->tableStates()}{{endif}}'>
							<span></span>
						</span></li>
					{{endif}}
				</ul>
			{{endif}}
		</div>
	</div>
	<div class="ipsPadding_vertical sm:ipsPadding_vertical:half ipsPadding_horizontal">
		<div data-role='commentContent' class='ipsType_normal ipsType_richText ipsContained' data-controller='core.front.core.lightboxedImages'>
			{{if $comment->hidden() === 1 && $comment->author()->member_id == \IPS\Member::loggedIn()->member_id}}
				<strong class='ipsType_medium ipsType_warning'><i class='fa fa-info-circle'></i> {lang="comment_awaiting_approval"}</strong>
			{{endif}}
			{$comment->content()|raw}

			{{if $comment->editLine()}}
				{$comment->editLine()|raw}
			{{endif}}
		</div>
	</div>
	{{if ( $comment->hidden() !== 1 && \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and settings.reputation_enabled and $comment->hasReactionBar() ) || ( $comment->hidden() === 1 && ( $comment->canUnhide() || $comment->canDelete() ) ) || ( $comment->hidden() === 0 and $item->canComment() and $editorName ) }}
		<div class='ipsItemControls'>
			{{if $comment->hidden() !== 1 && \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and settings.reputation_enabled and $comment->hasReactionBar()}}
				{template="reputation" group="global" app="core" params="$comment"}
			{{endif}}
			<ul class='ipsComment_controls ipsClearfix ipsItemControls_left' data-role="commentControls">
				{{if $comment->hidden() === 1 && ( $comment->canUnhide() || $comment->canDelete() )}}
					{{if $comment->canUnhide()}}
						<li><a href='{$comment->url('unhide')->csrf()}' class='ipsButton ipsButton_verySmall ipsButton_positive' data-action='approveComment'><i class='fa fa-check'></i> {lang="approve"}</a></li>
					{{endif}}
					{{if $comment->canDelete()}}
						<li><a href='{$comment->url('delete')->csrf()->setPage('page',\IPS\Request::i()->page)}' data-action='deleteComment' data-updateOnDelete="#commentCount" class='ipsButton ipsButton_verySmall ipsButton_negative'><i class='fa fa-times'></i> {lang="delete"}</a></li>
					{{endif}}
					{{if $comment->canEdit() || $comment->canSplit() || $comment->canHide()}}
						<li>
							<a href='#elControlsCommentsSub_{$comment->$idField}_menu' id='elControlsCommentsSub_{$comment->$idField}' data-ipsMenu data-ipsMenu-appendTo='#comment-{$comment->$idField}_wrap'>{lang="moderator_tools"} &nbsp;<i class='fa fa-caret-down'></i></a>
							<ul id='elControlsCommentsSub_{$comment->$idField}_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
								{{if $comment->canEdit()}}
									{{if $comment->mapped('first') and $comment->item()->canEdit()}}
										<li class='ipsMenu_item'><a href='{$comment->item()->url()->setQueryString( 'do', 'edit' )}'>{lang="edit"}</a></li>
									{{else}}
										<li class='ipsMenu_item'><a href='{$comment->url('edit')}' data-action='editComment'>{lang="edit"}</a></li>
									{{endif}}
								{{endif}}
								{{if $comment->canSplit()}}
									<li class='ipsMenu_item'><a href='{$comment->url('split')}' data-action='splitComment' data-ipsDialog data-ipsDialog-title="{lang="split_to_new" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $item::$title )"}">{lang="split"}</a></li>
								{{endif}}
								{{if $comment instanceof \IPS\Content\Hideable and $comment->canHide()}}
									<li class='ipsMenu_item'><a href='{$comment->url('hide')->csrf()}' data-ipsDialog data-ipsDialog-title="{lang="hide"}">{lang="hide"}</a></li>
								{{endif}}
							</ul>
						</li>
					{{endif}}
				{{else}}
					{{if $comment->hidden() === 0 and $item->canComment() and $editorName}}
						<li data-ipsQuote-editor='{$editorName}' data-ipsQuote-target='#comment-{$comment->$idField}' class='ipsJS_show'>
							<button class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_narrow cMultiQuote ipsHide' data-action='multiQuoteComment' data-ipsTooltip data-ipsQuote-multiQuote data-mqId='mq{$comment->$idField}' title='{lang="multiquote"}'><i class='fa fa-plus'></i></button>
						</li>
						<li data-ipsQuote-editor='{$editorName}' data-ipsQuote-target='#comment-{$comment->$idField}' class='ipsJS_show'>
							<a href='#' data-action="quoteComment" data-ipsQuote-singleQuote>{lang="quote"}</a>
						</li>
					{{endif}}
				{{endif}}
				<li class='ipsHide' data-role='commentLoading'>
					<span class='ipsLoading ipsLoading_tiny ipsLoading_noAnim'></span>
				</li>
			</ul>
		</div>
	{{endif}}

	{{if $comment->ip_address and \IPS\Member::loggedIn()->modPermission('can_use_ip_tools') and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) )}}
		<div class='ipsHide ipsPadding ipsMenu ipsMenu_veryWide' id='{$comment->$idField}_ip_menu'>
			<h5 class='ipsType_normal ipsType_reset'>{lang="ip_address"}</h5>
			<input type='text' autofocus class='ipsField_fullWidth ipsMargin_vertical:half' value='{$comment->ip_address}'>
			<a href='{url="app=core&module=modcp&controller=modcp&tab=ip_tools&ip=$comment->ip_address" seoTemplate="modcp_ip_tools"}' class='ipsButton ipsButton_light ipsButton_small ipsButton_fullWidth'>{lang="more_about_ip_address"} <i class='fa fa-angle-right'></i></a>
		</div>
	{{endif}}

	<div class='ipsPadding ipsHide cPostShareMenu' id='elShareComment_{$comment->id}_menu'>
		<h5 class='ipsType_normal ipsType_reset'>{lang="link_to_comment"}</h5>
		<input type='text' value='{$comment->item()->url()->setQueryString( array( 'do' => 'findComment', 'comment' => $comment->id ) )}' class='ipsField_fullWidth'>
		{{if \count( $comment->sharelinks() )}}
		<h5 class='ipsType_normal ipsType_reset ipsSpacer_top'>{lang="share_externally"}</h5>
		{template="sharelinks" group="global" app="core" params="$comment"}
		{{endif}}
	</div>
</div>