<ips:template parameters="$buttons" />
<ul class='ipsControlStrip ipsType_noBreak ipsList_reset' data-ipsControlStrip>
	{{foreach $buttons as $button}}
		<li class='ipsControlStrip_button {{if isset( $button['hidden'] ) and $button['hidden']}}ipsJS_hide{{endif}}' {{if isset( $button['id'] )}}id="{$button['id']}"{{endif}}>
			<a
				{{if isset( $button['link'] )}}href='{$button['link']}'{{endif}}
				title='{lang="$button['title']"}'
				data-ipsTooltip
				aria-label="{lang="$button['title']"}"
				
				{{if isset( $button['class'] )}}class='{$button['class']}'{{endif}}
				{{if isset( $button['data'] )}}
					{{foreach $button['data'] as $k => $v}}
						data-{$k}="{$v}"
					{{endforeach}}
				{{endif}}
				{{if isset( $button['hotkey'] )}}
					data-keyAction='{$button['hotkey']}'
				{{endif}}
				{{if isset( $button['target'] )}}
					target="{$button['target']}"
					{{if $button['target'] == '_blank'}} rel="noopener"{{endif}}
				{{endif}}
			>
				<i class='ipsControlStrip_icon fa fa-{$button['icon']}'></i>
				<span class='ipsControlStrip_item'>{lang="$button['title']"}</span>
			</a>
		</li>
	{{endforeach}}
</ul>
