<ips:template parameters="$item" />

<p class='ipsType_reset ipsType_medium ipsType_light' data-excludequote>
	<strong>{lang="date_edited" htmlsprintf="\IPS\DateTime::ts( $item->mapped('edit_time') )->html(FALSE), htmlspecialchars( $item->mapped('edit_member_name'), ENT_QUOTES | ENT_DISALLOWED, 'UTF-8', FALSE )"}</strong>
	{{if $item->mapped('edit_reason')}}
	<br>{$item->mapped('edit_reason')}
	{{endif}}
	{{if \IPS\Settings::i()->edit_log == 2 and ( \IPS\Settings::i()->edit_log_public or \IPS\Member::loggedIn()->modPermission('can_view_editlog') )}}
	<a href='{$item->url('editlog')}' data-ipsDialog data-ipsDialog-title="{lang="edit_history"}" title="{lang="edit_history"}">({lang="edit_history"})</a>
	{{if !$item->mapped('edit_show') AND \IPS\Member::loggedIn()->modPermission('can_view_editlog')}}
	<br>{lang="comment_edit_show_anyways"}
	{{endif}}
	{{endif}}
</p>