<ips:template parameters="$html, $title=NULL" />
<!DOCTYPE html>
<html lang="{expression="\IPS\Member::loggedIn()->language()->bcp47()"}" dir="{{if member.language()->isrtl}}rtl{{else}}ltr{{endif}}">
	<head>
		<title>{expression="output.getTitle( $title )"}</title>
		{template="includeMeta" app="core" group="global" location="global" params=""}
	<style type="text/css">
		/* ======================================================== */
/* PROGRESS BAR */
@keyframes progress-bar-stripes {
	from { background-position: 40px 0; }
	to { background-position: 0 0; }
}

.ipsProgressBar {
	width: 50%;
	margin: auto;
	height: 26px;
	overflow: hidden;
	background: rgb(156,156,156);
	background: linear-gradient(to bottom, rgba(156,156,156,1) 0%,rgba(180,180,180,1) 100%);
	border-radius: var(--radius-1);
	box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}
	
	.ipsProgressBar.ipsProgressBar_fullWidth {
		width: 100%;
	}

	.ipsProgressBar.ipsProgressBar_animated .ipsProgressBar_progress {
		background-color: #5490c0;
		background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
		background-size: 40px 40px;
	}

.ipsProgressBar_progress {
	float: left;
	width: 0;
	height: 100%;
	font-size: 12px;
	font-weight: bold;
	color: #ffffff;
	text-align: center;
	text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.25);
	background: #5490c0;
	position: relative;
	white-space: nowrap;
	line-height: 26px;
}
	
	.ipsProgressBar_warning .ipsProgressBar_progress {
		background: #8c3737;
	}

	.ipsProgressBar > span:first-child {
		padding-left: 7px;
	}

	.ipsProgressBar_progress[data-progress]:after {
		position: absolute;
		right: 5px;
		top: 0;
		line-height: 32px;
		color: #fff;
		content: attr(data-progress);
		display: block;
		font-weight: bold;
	}
	
	span[data-role=message] {
		text-align: center;
		display: block;
		margin: 8px;
		font-family: Helvetica;
	}

	</style>
	</head>
	<body class="ipsApp ipsApp_front ipsJS_none ipsClearfix ipsLayout_noBackground">
		{$html|raw}
		{template="includeJS" app="core" group="global" location="global" params=""}
	</body>
</html>