<ips:template parameters="$item, $review, $url, $image=NULL" />

{{$useImage = NULL;}}
<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$review, $item->mapped('title'), $review->mapped('date'), $url"}
	<div class='ipsPadding:double'>
		<div class='ipsRichEmbed_originalItem ipsAreaBackground_reset ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				{{if $image}}
					{{$useImage = $image;}}
				{{elseif $contentImage = $item->contentImages(1)}}
					{{$attachType = key( $contentImage[0] );}}
					{{$useImage = \IPS\File::get( $attachType, $contentImage[0][ $attachType ] );}}
				{{endif}}

				{{if $useImage}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
						<a href='{$url}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $useImage->url )"}" )'>
							<img src='{$useImage->url}' class='ipsHide' alt=''>
						</a>
					</div>
				{{endif}}

				<div class='ipsPadding sm:ipsPadding:half'>
					{template="embedOriginalItem" group="embed" app="core" params="$item"}
				</div>
			</div>
		</div>

		{template="rating" app="core" params="'veryLarge', $review->mapped('rating')" group="global"} 
		{{if $review->mapped('votes_total')}}
			<p class='ipsType_reset ipsType_medium'>{$review->helpfulLine()|raw}</p>
		{{endif}}
		<hr class='ipsHr'>
		<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half' data-truncate='3'>
			{$review->truncated(TRUE)|raw}
		</div>

		{{if settings.reputation_enabled and \IPS\IPS::classUsesTrait( $review, 'IPS\Content\Reactable' ) and \count( $review->reactions() )}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$review, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>