<ips:template parameters="$item, $url, $image=NULL" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$item, $item->mapped('title'), $item->mapped('date'), $url"}
	{{if $image}}
		{{$useImage = $image;}}
	{{elseif $contentImage = $item->contentImages(1)}}
		{{$attachType = key( $contentImage[0] );}}
		{{$useImage = \IPS\File::get( $attachType, $contentImage[0][ $attachType ] );}}
	{{endif}}

	{{if $useImage}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
			<a href='{$url}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $useImage->url )"}" )'>
				<img src='{$useImage->url}' class='ipsHide' alt=''>
			</a>
		</div>
	{{endif}}
	<div class='ipsPadding:double ipsClearfix'>
		{{if $desc = $item->truncated(TRUE)}}
			<div class='ipsType_richText ipsType_medium' data-truncate='3'>
				{$desc|raw}
			</div>
		{{endif}}
		{template="embedItemStats" group="embed" app="core" params="$item"}
	</div>
</div>