<ips:template parameters="$html, $js" />
<!DOCTYPE html>
<html lang="{expression="\IPS\Member::loggedIn()->language()->bcp47()"}" dir="{{if member.language()->isrtl}}rtl{{else}}ltr{{endif}}">
	<head>
		<title>{expression="output.title"}</title>
		{template="includeMeta" app="core" group="global" location="global" params=""}
		{template="includeCSS" app="core" group="global" location="global" params=""}

		<script type='text/javascript'>
			var ipsDebug = {{if ( \IPS\IN_DEV and \IPS\DEV_DEBUG_JS ) or \IPS\DEBUG_JS}}true{{else}}false{{endif}};
		</script>

		{{if \is_array( $js )}}
			{{foreach $js as $jsInclude}}
				{{$filename = \IPS\Http\Url::external( $jsInclude[0] );}}
				<script type='text/javascript' src='{$filename}'></script>
			{{endforeach}}
		{{endif}}
	</head>
	<body class='unloaded ipsApp ipsApp_front ipsClearfix ipsLayout_noBackground {{if isset( \IPS\Request::i()->cookie['hasJS'] )}}ipsJS_has{{else}}ipsJS_none{{endif}} ipsClearfix{{foreach output.bodyClasses as $class}} {$class}{{endforeach}}' data-role='internalEmbed' {{if \IPS\Dispatcher::i()->application}}data-pageapp='{expression="\IPS\Dispatcher::i()->application->directory"}'{{endif}} {{if \IPS\Dispatcher::i()->module}}data-pagemodule='{expression="\IPS\Dispatcher::i()->module->key"}'{{endif}} data-pagecontroller='{expression="\IPS\Dispatcher::i()->controller"}'>
		<div id='ipsEmbed'>
			{$html|raw}
		</div>
		<div id='ipsEmbedLoading'>
			<span></span>
		</div>
		{expression="output.endBodyCode" raw="true"}
	</body>
</html>
