<ips:template parameters="$comments, $url, $titleLang='recommended_replies', $commentLang='__defart_comment'" />

<div data-controller='core.front.core.recommendedComments' data-url='{$url}' class='ipsRecommendedComments {{if !\count( $comments )}}ipsHide{{endif}}'>
	<div data-role="recommendedComments">
		<h2 class='ipsType_sectionHead ipsType_large ipsType_bold ipsMargin_bottom'>{lang="$titleLang"}</h2>
		{{if \count( $comments )}}
			{{foreach $comments AS $id => $comment}}
				{template="featuredComment" group="global" app="core" params="$comment, $id, $commentLang"}
			{{endforeach}}
		{{endif}}
	</div>
</div>