<ips:template parameters="$comment, $id, $commentLang='__defart_comment'" />
{{if isset( $comment['comment'] )}}
	{{$idField = $comment['comment']::$databaseColumnId;}}
	<div class='ipsBox ipsBox--child ipsPadding ipsClearfix ipsComment_recommended ipsSpacer_bottom' data-commentID='{$id}'>
		<span class='ipsComment_recommendedFlag'><i class='fa fa-star'></i><span class='ipsResponsive_hidePhone'> {lang="recommended"}</span></span>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<aside class='ipsType_center ipsColumn ipsColumn_narrow ipsResponsive_hidePhone'>
				{template="userPhoto" app="core" group="global" params="$comment['comment']->author(), 'small', $comment['comment']->warningRef()"}
			</aside>
			<div class='ipsColumn ipsColumn_fluid ipsType_blendLinks'>
				<p class='ipsComment_meta ipsSpacer_bottom ipsSpacer_half ipsType_light'>
					{lang="posted_by_x" htmlsprintf="$comment['comment']->author()->link( $comment['comment']->warningRef() ), \IPS\DateTime::ts( $comment['comment']->mapped('date') )->html(FALSE)"}
				</p>
				<div class='ipsType_richText ipsType_normal' data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines'>{$comment['comment']->truncated( TRUE )|raw}</div>
	
				{{if $comment['note']}}
					<div class='ipsComment_recommendedNote ipsType_medium'>
						<p class='ipsType_reset ipsType_richText'>{$comment['note']}</p>
						{{if isset( $comment['featured_by'] )}}
							<p class='ipsType_reset ipsType_light'>{lang="recommended_by" htmlsprintf="$comment['featured_by']->link()"}</p>
						{{endif}}
					</div>
				{{elseif isset( $comment['featured_by'] )}}
					{lang="recommended_by" htmlsprintf="$comment['featured_by']->link()"}
				{{endif}}
			</div>
			<div class='ipsColumn ipsColumn_medium'>
				{{if \IPS\IPS::classUsesTrait( $comment['comment'], 'IPS\Content\Reactable' ) and settings.reputation_enabled}}
					{template="reactionOverview" group="global" app="core" params="$comment['comment']"}
					<hr class='ipsHr'>
				{{endif}}
				<a href='{$comment['comment']->url()}' data-action='goToComment' class='ipsButton ipsButton_link ipsButton_verySmall ipsButton_fullWidth'>{lang="go_to_this_comment" sprintf="\IPS\Member::loggedIn()->language()->get( $commentLang )"} <i class='fa fa-angle-right'></i></a>
			</div>
		</div>
	</div>
{{endif}}