<ips:template parameters="$item, $isReview=FALSE" />

<div data-controller="core.global.core.login">
	<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
	{{if \IPS\Login::registrationType() != 'disabled'}}
		<div class='ipsType_center ipsPad cGuestTeaser'>
			{{if $isReview}}
				<h2 class='ipsType_pageTitle'>{lang="teaser_review_title_reg"}</h2>
				<p class='ipsType_light ipsType_normal ipsType_reset ipsSpacer_top ipsSpacer_half'>{lang="teaser_review_desc_reg"}</p>
			{{else}}
				<h2 class='ipsType_pageTitle'>{lang="teaser_title_reg"}</h2>
				<p class='ipsType_light ipsType_normal ipsType_reset ipsSpacer_top ipsSpacer_half'>{lang="teaser_desc_reg"}</p>
			{{endif}}
	
			<div class='ipsBox ipsPad ipsSpacer_top'>
				<div class='ipsGrid ipsGrid_collapsePhone'>
					<div class='ipsGrid_span6 cGuestTeaser_left'>
						<h2 class='ipsType_sectionHead'>{lang="teaser_account"}</h2>
						<p class='ipsType_normal ipsType_reset ipsType_light ipsSpacer_bottom'>{lang="teaser_account_desc"}</p>
						{{if \IPS\Login::registrationType() == 'redirect'}}
							<a href='{expression="\IPS\Settings::i()->allow_reg_target"}' class='ipsButton ipsButton_primary ipsButton_small' target="_blank" rel="noopener">
						{{else}}
							<a href='{url="app=core&module=system&controller=register" seoTemplate="register"}' class='ipsButton ipsButton_primary ipsButton_small' {{if \IPS\Login::registrationType() == 'normal'}}data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="sign_up"}'{{endif}}>
						{{endif}}
						{lang="teaser_account_button"}</a>
					</div>
					<div class='ipsGrid_span6 cGuestTeaser_right'>
						<h2 class='ipsType_sectionHead'>{lang="teaser_signin"}</h2>
						<p class='ipsType_normal ipsType_reset ipsType_light ipsSpacer_bottom'>{lang="teaser_signin_desc"}</p>
						<a href='{url="app=core&module=system&controller=login" seoTemplate="login" ref="(string) $item->url() . '#replyForm'"}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-remoteVerify="false" data-ipsDialog-title="{lang="teaser_signin_button"}" class='ipsButton ipsButton_primary ipsButton_small'>{lang="teaser_signin_button"}</a>
					</div>
				</div>
			</div>
		</div>
	{{else}}
		<div class='ipsType_center ipsPad'>
			<h2 class='ipsType_pageTitle'>{lang="teaser_title_noreg"}</h2>
			<p class='ipsType_light ipsType_normal ipsType_reset ipsSpacer_top ipsSpacer_half'>{lang="teaser_desc_noreg"}</p>
			<br>
			<br>
			<a href='{url="app=core&module=system&controller=login" seoTemplate="login" ref="(string) $item->url() . '#replyForm'"}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-remoteVerify="false" data-ipsDialog-title="{lang="teaser_signin_button"}" class='ipsButton ipsButton_alternate ipsButton_large'>{lang="teaser_signin_button"}</a>
		</div>
	{{endif}}
</div>