<ips:template parameters="$login" />
<div class="ipsPad ipsForm ipsForm_vertical">
	<h4 class="ipsType_sectionHead">{lang="login"}</h4>
	<br><br>
	<ul class='ipsList_reset'>
		<li class="ipsFieldRow ipsFieldRow_noLabel ipsFieldRow_fullWidth">
			{{$authType = $login->authType();}}
			{{if $authType === \IPS\Login::AUTH_TYPE_USERNAME}}
				<input type="text" placeholder="{lang="username"}" name="auth" autocomplete="username">
			{{elseif $authType === \IPS\Login::AUTH_TYPE_EMAIL}}
				<input type="email" placeholder="{lang="email_address"}" name="auth" autocomplete="email">
			{{else}}
				<input type="text" placeholder="{lang="username_or_email"}" name="auth" autocomplete="email">
			{{endif}}
		</li>
		<li class="ipsFieldRow ipsFieldRow_noLabel ipsFieldRow_fullWidth">
			<input type="password" placeholder="{lang="password"}" name="password" autocomplete="current-password">
		</li>
		<li class="ipsFieldRow ipsFieldRow_checkbox ipsClearfix">
			<span class="ipsCustomInput">
				<input type="checkbox" name="remember_me" id="remember_me_checkbox" value="1" checked aria-checked="true">
				<span></span>
			</span>
			<div class="ipsFieldRow_content">
				<label class="ipsFieldRow_label" for="remember_me_checkbox">{lang="remember_me"}</label>
				<span class="ipsFieldRow_desc">{lang="remember_me_desc"}</span>
			</div>
		</li>
		<li class="ipsFieldRow ipsFieldRow_fullWidth">
			<button type="submit" name="_processLogin" value="usernamepassword" class="ipsButton ipsButton_primary ipsButton_small" id="elSignIn_submit">{lang="login"}</button>
			{{if settings.allow_forgot_password != 'disabled'}}
				<p class="ipsType_right ipsType_small">
					{{if settings.allow_forgot_password == 'redirect'}}
						<a href='{expression="\IPS\Settings::i()->allow_forgot_password_target"}' target="_blank" rel="noopener">
					{{else}}
						<a href='{url="app=core&module=system&controller=lostpass" seoTemplate="lostpassword"}' data-ipsDialog data-ipsDialog-title='{lang="forgotten_password"}'>
					{{endif}}
					{lang="forgotten_password"}</a>
				</p>
			{{endif}}
		</li>
	</ul>
</div>