<ips:template parameters="$items" />

{{foreach $items as $child}}
	{{if $child->canView()}}
		{{if $children = $child->children()}}
			{{$id = md5( mt_rand() );}}
			<li class='ipsDrawer_itemParent'>
				<h4 class='ipsDrawer_title'><a href='#'>{$child->title()}</a></h4>
				<ul class='ipsDrawer_list'>
					<li data-action="back"><a href='#'>{lang="mobile_menu_back"}</a></li>
					{{if $child->link() && $child->link() !== '#'}}
						<li>
							<a href='{$child->link()}'>
								{$child->title()}
							</a>
						</li>
					{{endif}}
					{template="mobileNavigationChildren" group="global" app="core" params="$children"}
				</ul>
			</li>
		{{elseif $child instanceof \IPS\core\extensions\core\FrontNavigation\MenuHeader}}
			<li class='ipsDrawer_section'>
				{$child->title()}
			</li>
		{{elseif $child instanceof \IPS\core\extensions\core\FrontNavigation\MenuSeparator}}
			
		{{elseif $child instanceof \IPS\core\extensions\core\FrontNavigation\MenuButton}}
			<li class='ipsPad_half'>
				<a href='{$child->link()}' class='ipsButton ipsButton_important ipsButton_verySmall ipsButton_fullWidth'>
					{$child->title()}
				</a>
			</li>
		{{else}}
			<li>
				<a href='{$child->link()}' {{if method_exists( $child, 'target' ) AND $child->target()}}target='{$child->target()}'{{if $child->target() == '_blank'}} rel="noopener"{{endif}}{{endif}}>
					{$child->title()}
				</a>
			</li>
		{{endif}}
	{{endif}}
{{endforeach}}