<ips:template parameters=" " />
<ul class='ipsMobileHamburger ipsList_reset ipsResponsive_hideDesktop'>
	<li data-ipsDrawer data-ipsDrawer-drawerElem='#elMobileDrawer'>
		<a href='#'>
			{{$total = \IPS\Member::loggedIn()->notification_cnt;}}
			{{if !\IPS\Member::loggedIn()->members_disable_pm and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'messaging' ) )}}
				{{$total += \IPS\Member::loggedIn()->msg_count_new;}}
			{{endif}}
			{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'modcp' ) ) and \IPS\Member::loggedIn()->modPermission('can_view_reports')}}
				{{$total += \IPS\Member::loggedIn()->reportCount();}}
			{{endif}}
			{{if $total}}
				<span class='ipsNotificationCount' data-notificationType='total'>{$total}</span>
			{{endif}}
			<i class='fa fa-navicon'></i>
		</a>
	</li>
</ul>