<ips:template parameters="$nextStep, $canDismiss=false, $hideOnCompletion=true" />
{{$completion = \intval( (string) \IPS\Member::loggedIn()->profileCompletionPercentage() );}}
{{if ! ( $completion == 100 and $hideOnCompletion )}}
<div class='ipsBox ipsPad ipsSpacer_bottom' data-role='profileWidget' data-controller="core.front.core.profileCompletion">
	<div>
		{{if $completion < 100}}
		<ul class="ipsButton_split ipsPos_right ipsSpacer_bottom">
			<li>
				<a class="ipsButton ipsButton_important ipsButton_veryVerySmall" href="{url="app=core&module=system&controller=settings&do=completion&_new=1" ref="(string) \IPS\Request::i()->url()" seoTemplate="settings"}">{lang="complete_my_profile"}</a>
			</li>
			{{if $canDismiss}}
			<li>
				<a class="ipsButton ipsButton_link ipsButton_linkNeutral ipsButton_veryVerySmall" href='{url="app=core&module=system&controller=settings&do=dismissProfile" ref="(string) \IPS\Request::i()->url()" csrf="true"}' data-role='dismissProfile'>{lang="dismiss"}</a>
			</li>
			{{endif}}
		</ul>
		<h4 class="ipsType_reset ipsType_normal"><strong>{lang="profile_step_next"} {lang="profile_step_title_{$nextStep->id}"}</strong></h4>
		{{endif}}
	</div>
	<div class="ipsProgressBar ipsProgressBar_fullWidth">
		<div class='ipsProgressBar_progress' style='width: {expression="\IPS\Member::loggedIn()->profileCompletionPercentage()"}%'>
			{lang="profile_completion_percent" sprintf="$completion . '%'"}
		</div>
	</div>
</div>
{{endif}}