<ips:template parameters="$log" />
<div id="elQueryLog">
	<h3 class='ipsType_center'>{expression="\count( $log )"}</h3>
	{{foreach $log as $i => $query}}
		<div>
			<pre class="prettyprint lang-sql" data-ipsDialog data-ipsDialog-content="#elQueryLog{$i}_menu">{{if $query['server']}}({$query['server']}): {{endif}}{$query['query']}</pre>
			{{if $query['extra']}}
				<div class="ipsType_center">
					<strong class="ipsType_warning"><i class="fa fa-exclamation-circle"></i> {$query['extra']}</strong>
				</div>
				<br>
			{{endif}}
			<div id='elQueryLog{$i}_menu' class='ipsPad ipsHide'>
				<br>
				<pre>{$query['query']}</pre>
				<hr class="ipsHr">
				<pre class="prettyprint lang-php">{$query['backtrace']}</pre>
				<br>
			</div>
		</div>
		<hr class="ipsHr">
	{{endforeach}}
</div>