<ips:template parameters="$preview=FALSE" />
{{if !$preview and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'search' ) ) AND !\in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}
	<div id="elSearchWrapper">
		<div id='elSearch' class='' data-controller='core.front.core.quickSearch'>
			<form accept-charset='utf-8' action='{url="app=core&module=search&controller=search&do=quicksearch" seoTemplate="search" noprotocol="true"}' method='post'>
				<input type='search' id='elSearchField' placeholder='{lang="search_placeholder"}' name='q' autocomplete='off' aria-label='{lang="search"}'>
				<button class='cSearchSubmit' type="submit" aria-label='{lang="search"}'><i class="fa fa-search"></i></button>
				<div id="elSearchExpanded">
					<div class="ipsMenu_title">
						{lang="class"}
					</div>
					<ul class="ipsSideMenu_list ipsSideMenu_withRadios ipsSideMenu_small" data-ipsSideMenu data-ipsSideMenu-type="radio" data-ipsSideMenu-responsive="false" data-role="searchContexts">
						<li>
							<span class='ipsSideMenu_item ipsSideMenu_itemActive' data-ipsMenuValue='all'>
								<input type="radio" name="type" value="all" checked id="elQuickSearchRadio_type_all">
								<label for='elQuickSearchRadio_type_all' id='elQuickSearchRadio_type_all_label'>{lang="everywhere"}</label>
							</span>
						</li>
						{{$option = \IPS\Output::i()->defaultSearchOption;}}
						{{if \IPS\Output::i()->defaultSearchOption[0] != 'all'}}
							<li>
								<span class='ipsSideMenu_item' data-ipsMenuValue='{$option[0]}'>
									<input type="radio" name="type" value="{$option[0]}" id="elQuickSearchRadio_type_{$option[0]}">
									<label for='elQuickSearchRadio_type_{$option[0]}' id='elQuickSearchRadio_type_{$option[0]}_label'>{lang="$option[1]"}</label>
								</span>
							</li>
						{{endif}}
						{{if \count( output.contextualSearchOptions )}}
							{{foreach array_reverse( output.contextualSearchOptions ) as $name => $data}}
								<li>
									<span class='ipsSideMenu_item' data-ipsMenuValue='contextual_{expression="json_encode( $data )"}'>
										<input type="radio" name="type" value='contextual_{expression="json_encode( $data )"}' id='elQuickSearchRadio_type_contextual_{expression="md5( json_encode( $data ) )"}'>
										<label for='elQuickSearchRadio_type_contextual_{expression="md5( json_encode( $data ) )"}' id='elQuickSearchRadio_type_contextual_{expression="md5( json_encode( $data ) )"}_label'>{$name}</label>
									</span>
								</li>
							{{endforeach}}
						{{endif}}
						<li data-role="showMoreSearchContexts">
							<span class='ipsSideMenu_item' data-action="showMoreSearchContexts" data-exclude="{$option[0]}">
								{lang="more_options"}
							</span>
						</li>
					</ul>
					<div class="ipsMenu_title">
						{lang="andOr"}
					</div>
					<ul class='ipsSideMenu_list ipsSideMenu_withRadios ipsSideMenu_small ipsType_normal' role="radiogroup" data-ipsSideMenu data-ipsSideMenu-type="radio" data-ipsSideMenu-responsive="false" data-filterType='andOr'>
						{{foreach settings.search_default_operator == 'and' ? array( 'and', 'or' ) : array( 'or', 'and' ) as $k}}
							<li>
								<span class='ipsSideMenu_item {{if settings.search_default_operator == $k}}ipsSideMenu_itemActive{{endif}}' data-ipsMenuValue='{$k}'>
									<input type="radio" name="search_and_or" value="{$k}" {{if settings.search_default_operator == $k}}checked{{endif}} id="elRadio_andOr_{$k}">
									<label for='elRadio_andOr_{$k}' id='elField_andOr_label_{$k}'>{lang="search_{$k}"}</label>
								</span>
							</li>
						{{endforeach}}
					</ul>
					<div class="ipsMenu_title">
						{lang="searchIn"}
					</div>
					<ul class='ipsSideMenu_list ipsSideMenu_withRadios ipsSideMenu_small ipsType_normal' role="radiogroup" data-ipsSideMenu data-ipsSideMenu-type="radio" data-ipsSideMenu-responsive="false" data-filterType='searchIn'>
						<li>
							<span class='ipsSideMenu_item ipsSideMenu_itemActive' data-ipsMenuValue='all'>
								<input type="radio" name="search_in" value="all" checked id="elRadio_searchIn_and">
								<label for='elRadio_searchIn_and' id='elField_searchIn_label_all'>{lang="titles_and_body"}</label>
							</span>
						</li>
						<li>
							<span class='ipsSideMenu_item' data-ipsMenuValue='titles'>
								<input type="radio" name="search_in" value="titles" id="elRadio_searchIn_titles">
								<label for='elRadio_searchIn_titles' id='elField_searchIn_label_titles'>{lang="titles_only"}</label>
							</span>
						</li>
					</ul>
				</div>
			</form>
		</div>
	</div>
{{endif}}