<ips:template parameters="$content, $showCount=TRUE, $size=NULL" />

<div class='ipsReactOverview {{if \IPS\Settings::i()->reaction_count_display == 'count'}}ipsReactOverview--points{{else}}ipsReactOverview--reactions{{endif}} {{if $size}}ipsReactOverview_{$size}{{endif}}'>
	{{if \IPS\Settings::i()->reaction_count_display == 'count'}}
		<div class='ipsType_center'>
			<span class='ipsReact_reactCountOnly ipsType_center {{if $content->reactionCount() >= 1}}ipsAreaBackground_positive{{elseif $content->reactionCount() < 0}}ipsAreaBackground_negative{{else}}ipsAreaBackground_light{{endif}} ipsType_blendLinks'>
				{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
					<a href='{$content->url('showReactions')}' data-ipsTooltip title="{lang="see_who_reacted" escape="true"}" data-ipsDialog data-ipsDialog-title="{lang="see_who_reacted" escape="true"}">
				{{endif}}
					{$content->reactionCount()}
				{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
					</a>
				{{endif}}
			</span>
		</div>
		<p class='ipsType_reset ipsType_center'>
			{lang="repuation_points"}
		</p>
	{{else}}
		{{if \count( $content->reactBlurb() )}}
			{{$isItem = ( $content instanceof \IPS\Content\Item ) ? 1 : 0;}}
			<ul>
				{{foreach array_reverse( $content->reactBlurb(), TRUE ) AS $key => $count}}
					{{$reaction = \IPS\Content\Reaction::load( $key );}}
					<li>
						{{if\IPS\Member::loggedIn()->group['gbw_view_reps']}}
							<a href='{$content->url('showReactions')->setQueryString( array( 'reaction' => $reaction->id, 'item' => $isItem ) )}' data-ipsDialog data-ipsDialog-title='{lang="see_who_reacted"}' data-ipsTooltip title="{lang="see_who_reacted_x" sprintf="\IPS\Member::loggedIn()->language()->addToStack( 'reaction_title_' . $reaction->id )" escape="true"}">
						{{else}}
							<span data-ipsTooltip title="{lang="reaction_title_{$reaction->id}"}">
						{{endif}}
								<img src='{$reaction->_icon->url}' alt="{lang="reaction_title_{$reaction->id}" escape="true"}">
						{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
							</a>
						{{else}}
							</span>
						{{endif}}
					</li>
				{{endforeach}}
			</ul>
		{{endif}}
		{{if $showCount && $size == 'small' && \count( $content->reactions() )}}
			<span class='ipsType_medium'>{expression="\count( $content->reactions() )"}</span>
		{{elseif $showCount}}
			<p class='ipsType_reset ipsType_center'>
				{lang="react_total" pluralize="\count( $content->reactions() )"}
			</p>
		{{endif}}
	{{endif}}
</div>