<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	<li class='ipsGrid_span6 ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
		{template="userPhoto" app="core" group="global" params="\IPS\Member::load( $row['member_id'] ), 'mini'"}
		<div>
			<h3 class='ipsType_normal ipsType_reset ipsTruncate ipsTruncate_line'>{template="userLink" app="core" group="global" params="\IPS\Member::load( $row['member_id'] )"}</h3>
			<span class='ipsType_light'>
				{{if !isset( \IPS\Request::i()->reaction ) || \IPS\Request::i()->reaction == 'all'}}
					{{$reaction = \IPS\Content\Reaction::load( $row['reaction'] );}}
					<img src='{$reaction->_icon->url}' height='20' width='20'>
				{{endif}} <span class='ipsType_medium'>{$row['rep_date']|raw}</span>
			</span>
			{{if \IPS\Member::loggedIn()->modPermission('can_remove_reactions') and \count( $row['_buttons'] )}}
				<a href="{$row['_buttons']['delete']['link']}" {{if isset( $row['_buttons']['delete']['data'] )}}
					{{foreach $row['_buttons']['delete']['data'] as $k => $v}}
						data-{$k}="{$v}"
					{{endforeach}}
					{{endif}}><i class="fa fa-{$row['_buttons']['delete']['icon']}"></i></a>
			{{endif}}
		</div>
	</li>
{{endforeach}}