<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	<li class='ipsGrid_span6 ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
		{template="userPhoto" app="core" group="global" params="\IPS\Member::load( $row['member_id'] ), 'mini'"}
		<div>
			<h3 class='ipsType_normal ipsType_reset ipsTruncate ipsTruncate_line'>{template="userLink" app="core" group="global" params="\IPS\Member::load( $row['member_id'] )"}</h3>
			<span class='ipsType_light'>
				{{if $row['rep_rating'] === '1' && settings.reputation_point_types != 'like'}}<i class='ipsType_large ipsType_positive fa fa-arrow-circle-up'></i>{{elseif settings.reputation_point_types != 'like'}}<i class='ipsType_large ipsType_negative fa fa-arrow-circle-down'></i>{{endif}} <span class='ipsType_medium'>{datetime="$row['rep_date']"}</span>
			</span>
		</div>
	</li>
{{endforeach}}