<ips:template parameters="$content, $allowRep=TRUE" />
{{$allowRep = TRUE;}}
<div data-controller='core.front.core.reaction' class='ipsReact ipsReact_mini {{if !$allowRep}}ipsReact_miniNoInteraction{{endif}}'>
	
	{{if $content}}
		{{if \IPS\Settings::i()->reaction_count_display == 'count'}}
			<div class='ipsReact_reactCountOnly ipsReact_reactCountOnly_mini {{if $content->reactionCount() >= 1}}ipsAreaBackground_positive{{elseif $content->reactionCount() < 0}}ipsAreaBackground_negative{{else}}ipsAreaBackground_light{{endif}} ipsType_blendLinks {{if !\count( $content->reactions() )}}ipsHide{{endif}}' data-role='reactCount'>
				{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
					<a href='{$content->url('showReactions')}' data-ipsTooltip title='{lang="see_who_reacted" escape="true"}' data-ipsDialog data-ipsDialog-title='{lang="see_who_reacted" escape="true"}'>
				{{endif}}
				<span data-role='reactCountText'>{$content->reactionCount()}</span>
				{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
					</a>
				{{endif}}
			</div>
		{{else}}
			<div class='ipsReact_blurb {{if !$content->reactBlurb()}}ipsHide{{endif}}' data-role='reactionBlurb'>
				{{if $content->reactBlurb()}}
					{template="reactionBlurb" group="global" app="core" params="$content"}
				{{endif}}
			</div>
		{{endif}}
		
		{{if $content->canReact()}}
			{{$reactButton = NULL;}}
			{{$defaultReaction = NULL;}}
	
			{{foreach \IPS\Content\Reaction::roots() AS $id => $reaction}}
				{{if !$defaultReaction}}
					{{$defaultReaction = $reaction;}}
				{{endif}}
				{{if ( $content->reacted() !== FALSE && $reaction->id == $content->reacted()->id ) || ( $content->reacted() === FALSE )}}
					{{$reactButton = $reaction;}}
					{{break;}}
				{{endif}}
			{{endforeach}}
			{{if $allowRep}}
				<span class='ipsReact_count ipsHide' data-role="reactCount">
					<a href='{$content->url('showReactions')}' data-ipsDialog data-ipsDialog-title='{lang="see_who_reacted"}'>
						{expression="\count( $content->reactions() )"}
					</a>
				</span>
				<div class='ipsReact_types' data-role='reactionInteraction' data-unreact="{$content->url( 'unreact' )->csrf()}">
					{{if !\IPS\Content\Reaction::isLikeMode()}}
						<ul class='ipsList_inline' data-role='reactTypes'>
							{{foreach \IPS\Content\Reaction::roots() AS $id => $reaction}}
							{{if $reaction->id == $reactButton->id OR $reaction->_enabled === FALSE}}
							{{continue;}}
							{{endif}}
	
								<li>
									<a href='{$content->url( 'react' )->setQueryString( 'reaction', $reaction->id )->csrf()}' class='ipsReact_reaction' data-role="reaction" {{if $reaction->id == $defaultReaction->id}}data-defaultReaction{{endif}}>
										<img src='{$reaction->_icon->url}' alt="{lang="reaction_title_{$reaction->id}" escape="true"}" data-ipsTooltip title="{lang="reaction_title_{$reaction->id}" escape="true"}">
										<span class='ipsReact_name'>{lang="reaction_title_{$reaction->id}"}</span>
									</a>
								</li>
							{{endforeach}}
							<li>
								<a href='{$content->url( 'unreact' )->csrf()}' class='ipsReact_unreact {{if $content->reacted() == FALSE}}ipsHide{{endif}}' data-action='unreact' data-ipsTooltip title='{lang="reaction_remove"}'>&times;</a>
							</li>
						</ul>
					{{endif}}
	
					<span class='ipsReact_button {{if $content->reacted() !== FALSE}}ipsReact_reacted{{endif}}' data-action='reactLaunch'>
						<a href='{$content->url( 'react' )->setQueryString( 'reaction', $reactButton->id )->csrf()}' class='ipsReact_reaction' data-role="reaction" {{if $reactButton->id == $defaultReaction->id}}data-defaultReaction{{endif}}>
							<img src='{$reactButton->_icon->url}' alt="{lang="reaction_title_{$reactButton->id}" escape="true"}" data-ipsTooltip title="{lang="reaction_title_{$reactButton->id}" escape="true"}">
							<span class='ipsReact_name'>{lang="reaction_title_{$reactButton->id}"}</span>
						</a>
					</span>
				</div>
			{{endif}}
		{{endif}}
	{{endif}}
</div>