<ips:template parameters="$content, $extraClass='', $forceType=NULL" />
{{if \IPS\IPS::classUsesTrait( $content, 'IPS\Content\Reactable' ) and settings.reputation_enabled and $enabledReactions = \IPS\Content\Reaction::enabledReactions()}}
	<div data-controller='core.front.core.reaction' class='ipsItemControls_right ipsClearfix {{if $extraClass}}{$extraClass}{{endif}}'>	
		<div class='ipsReact ipsPos_right'>
			{{if \IPS\Settings::i()->reaction_count_display == 'count'}}
				{{$reactionCount = $content->reactionCount();}}
				<div class='ipsReact_reactCountOnly {{if $reactionCount >= 1}}ipsAreaBackground_positive{{elseif $reactionCount < 0}}ipsAreaBackground_negative{{else}}ipsAreaBackground_light{{endif}} ipsType_blendLinks {{if !\count( $content->reactions() )}}ipsHide{{endif}}' data-role='reactCount'>
					{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
						<a href='{$content->url('showReactions')}' data-ipsTooltip title='{lang="see_who_reacted" escape="true"}' data-ipsDialog data-ipsDialog-title='{lang="see_who_reacted" escape="true"}'>
					{{endif}}
					<span data-role='reactCountText'>{$reactionCount}</span>
					{{if \IPS\Member::loggedIn()->group['gbw_view_reps']}}
						</a>
					{{endif}}
				</div>
			{{else}}
				{{$reactBlurb = $content->reactBlurb();}}
				<div class='ipsReact_blurb {{if !$reactBlurb}}ipsHide{{endif}}' data-role='reactionBlurb'>
					{{if $reactBlurb}}
						{template="reactionBlurb" group="global" app="core" params="$content"}
					{{endif}}
				</div>
			{{endif}}
			
			{{if $content->canReact()}}
				{{$defaultReaction = reset( $enabledReactions );}}
				{{$reactButton = ( $reacted = $content->reacted() and isset( $enabledReactions[ $reacted->id ] ) ) ? $enabledReactions[ $reacted->id ] : $defaultReaction;}}

				<div class='ipsReact_types' data-role='reactionInteraction' data-unreact="{$content->url( 'unreact' )->csrf()}">
					{{if !\IPS\Content\Reaction::isLikeMode()}}
						<ul class='ipsList_inline' data-role='reactTypes'>
							{{foreach $enabledReactions as $reaction}}
								{{if $reaction->id == $reactButton->id}}
									{{continue;}}
								{{endif}}

								<li>
									<a href='{$content->url( 'react' )->setQueryString( 'reaction', $reaction->id )->csrf()}' class='ipsReact_reaction' data-role="reaction" {{if $reaction->id == $defaultReaction->id}}data-defaultReaction{{endif}}>
										<img src='{$reaction->_icon->url}' alt="{lang="reaction_title_{$reaction->id}" escape="true"}" data-ipsTooltip title="{lang="reaction_title_{$reaction->id}" escape="true"}">
										<span class='ipsReact_name'>{lang="reaction_title_{$reaction->id}"}</span>
									</a>
								</li>
							{{endforeach}}
						</ul>
					{{endif}}

					<span class='ipsReact_button {{if $reacted !== FALSE}}ipsReact_reacted{{endif}}' data-action='reactLaunch'>
						<a href='{$content->url( 'react' )->setQueryString( 'reaction', $reactButton->id )->csrf()}' class='ipsReact_reaction' data-role="reaction" {{if $reactButton->id == $defaultReaction->id}}data-defaultReaction{{endif}}>
							<img src='{$reactButton->_icon->url}' alt="{lang="reaction_title_{$reactButton->id}" escape="true"}" data-ipsTooltip title="{lang="reaction_title_{$reactButton->id}" escape="true"}">
							<span class='ipsReact_name'>{lang="reaction_title_{$reactButton->id}"}</span>
						</a>
					</span>

					<a href='{$content->url( 'unreact' )->csrf()}' class='ipsReact_unreact {{if $reacted == FALSE}}ipsHide{{endif}}' data-action='unreact' data-ipsTooltip title='{lang="reaction_remove"}'>&times;</a>
				</div>
			{{endif}}
		</div>
	</div>
{{endif}}