<ips:template parameters="$item, $review, $editorName, $app, $type" />
<div id='review-{$review->id}_wrap' data-controller='core.front.core.comment' data-commentApp='{$app}' data-commentType='{$type}-review' data-commentID="{$review->id}" data-quoteData='{expression="json_encode( array('userid' => $review->author()->member_id, 'username' => $review->author()->name, 'timestamp' => $review->mapped('date'), 'contentapp' => $app, 'contenttype' => $type, 'contentid' => $item->id, 'contentcommentid' => $review->id) )"}' class='ipsComment_content ipsType_medium'>
	<div class='ipsComment_header ipsFlex ipsFlex-ai:start ipsFlex-jc:between'>
		<div class='ipsPhotoPanel ipsPhotoPanel_small'>
			{template="userPhoto" app="core" group="global" params="$review->author(), 'small', $review->warningRef(), 'ipsPos_left'"}
			<div>
				<h3 class="ipsComment_author ipsType_blendLinks">
					<strong class='ipsType_normal'>{template="userLink" app="core" group="global" params="$review->author(), $review->warningRef()"}</strong>
					{template="reputationBadge" group="global" app="core" params="$review->author()"}
				</h3>
				<p class="ipsComment_meta ipsType_medium ipsType_light">
					{{if $review->mapped('date')}}
						{datetime="$review->mapped('date')"}
					{{else}}
						{lang="unknown_date"}
					{{endif}}

					{{if $review->editLine()}}
						&middot; {$review->editLine()|raw}
					{{endif}}
					{{if $review->hidden() AND $review->hidden() != -2}}
						&middot; {$review->hiddenBlurb()}
					{{elseif $review->hidden() == -2}}
						&middot; {$review->deletedBlurb()}
					{{endif}}
				</p>
				<ul class='ipsList_inline ipsClearfix ipsRating ipsRating_large'>
					{{foreach range( 1, \intval( \IPS\Settings::i()->reviews_rating_out_of ) ) as $i}}
						<li class='{{if $review->mapped('rating') >= $i}}ipsRating_on{{else}}ipsRating_off{{endif}}'>
							<i class='fa fa-star'></i>
						</li>
					{{endforeach}}
				</ul>&nbsp;&nbsp; {{if $review->mapped('votes_total')}}<strong class='ipsType_medium'>{$review->helpfulLine()|raw}</strong><br>{{endif}}
			</div>
		</div>
		<div class='ipsType_reset ipsType_light ipsType_blendLinks ipsComment_toolWrap'>
			<ul class='ipsList_reset ipsComment_tools'>
				<li>
					<a href='#elControlsReviews_{$review->id}_menu' class='ipsComment_ellipsis' id='elControlsReviews_{$review->id}' title='{lang="more_options"}' data-ipsMenu data-ipsMenu-appendTo='#review-{$review->id}_wrap'><i class='fa fa-ellipsis-h'></i></a>
					<ul id='elControlsReviews_{$review->id}_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
						{{if $review->canReportOrRevoke() === TRUE}}
							<li class='ipsMenu_item'>
								<a href='{$review->url('report')}' data-ipsDialog data-ipsDialog-remoteSubmit data-ipsDialog-size='medium' data-ipsDialog-flashMessage='{lang="report_submit_success"}' data-ipsDialog-title="{lang="report"}" data-action='reportComment' title='{lang="report"}'>{lang="report"}</a>
							</li>
						{{endif}}
						<li class='ipsMenu_item'>
							<a class='ipsType_blendLinks' href='{$review->item()->url()->setQueryString( array( 'do' => 'findReview', 'review' => $review->id ) )}' title='{lang="share_this_review"}' data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-content='#elShareReview_{$review->id}_menu' data-ipsDialog-title="{lang="share_this_review"}"  id='elShareReview_{$review->id}' data-role='shareComment'>{lang="share_this_review"}</a>
						</li>

						{{if $review->canEdit() || ( $review->hidden() == -2 AND \IPS\Member::loggedIn()->modPermission('can_manage_deleted_content') ) || ( $review instanceof \IPS\Content\Hideable && ( ( !$review->hidden() and $review->canHide() ) || ( $review->hidden() and $review->canUnhide() ) ) ) || $review->canDelete()}}
							<li class='ipsMenu_sep'><hr></li>
						{{endif}}

						{{if $review->canEdit()}}
							<li class='ipsMenu_item'><a href='{$review->url('edit')}' data-action='editComment'>{lang="edit"}</a></li>
						{{endif}}
						
						{{if $review->hidden() == -2 AND \IPS\Member::loggedIn()->modPermission('can_manage_deleted_content')}}
							<li class='ipsMenu_item'><a href='{$review->url('restore')->csrf()}' data-confirm data-confirmSubMessage='{lang="restore_as_visible_desc"}'>{lang="restore_as_visible"}</a></li>
							<li class='ipsMenu_item'><a href='{$review->url('restore')->csrf()->setQueryString( 'restoreAsHidden', 1 )}' data-confirm data-confirmSubMessage='{lang="restore_as_hidden_desc"}'>{lang="restore_as_hidden"}</a></li>
							<li class='ipsMenu_item'><a href='{$review->url('delete')->csrf()->setQueryString( 'immediately', 1 )}' data-confirm data-confirmSubMessage='{lang="delete_immediately_desc"}'>{lang="delete_immediately"}</a></li>
						{{else}}
							{{if $review instanceof \IPS\Content\Hideable}}
								{{if !$review->hidden() and $review->canHide()}}
									<li class='ipsMenu_item'><a href='{$review->url('hide')->csrf()}' data-ipsDialog data-ipsDialog-title="{lang="hide"}">{lang="hide"}</a></li>
								{{elseif $review->hidden() and $review->canUnhide()}}
									<li class='ipsMenu_item'><a href='{$review->url('unhide')->csrf()}'>{lang="unhide"}</a></li>
								{{endif}}
							{{endif}}
							{{if $review->canDelete()}}
								<li class='ipsMenu_item'><a href='{$review->url('delete')->csrf()->setPage('page',\IPS\Request::i()->page)}' data-action='deleteComment' data-updateOnDelete="#reviewCount">{lang="delete"}</a></li>
							{{endif}}
						{{endif}}
					</ul>
				</li>
				{{if \count( $item->reviewMultimodActions() )}}
					<li>
						<span class='ipsCustomInput'>
							<input type="checkbox" name="multimod[{$review->id}]" value="1" data-role="moderation" data-actions="{{if $review->hidden() === -1 AND $review->canUnhide()}}unhide{{elseif $review->hidden() === 1 AND $review->canUnhide()}}approve{{elseif $review->canHide()}}hide{{endif}} {{if $review->canDelete()}}delete{{endif}}" data-state='{{if $review->tableStates()}}{$review->tableStates()}{{endif}}'>
							<span></span>
						</span>
					</li>
				{{endif}}
			</ul>
		</div>
	</div>
	<div class='ipsPadding_vertical sm:ipsPadding_vertical:half ipsPadding_horizontal'>
		<div id="review-{$review->id}" data-role="commentContent" class="ipsType_richText ipsType_normal ipsContained" data-controller='core.front.core.lightboxedImages'>
			{$review->content()|raw}
		</div>

		{{if $review->hasAuthorResponse()}}
			<div class='ipsReviewResponse ipsPad ipsSpacer_bottom ipsAreaBackground_light ipsClearfix'>
				<div class='ipsFlex ipsFlex-ai:center ipsFlex-jc:between ipsMargin_bottom:half'>
					<h4 class='ipsType_sectionHead ipsType_medium ipsType_bold'>{lang="review_response_title"}</h4>

					<a href='#elControlsReviews_{$review->id}_response_menu' class='ipsComment_ellipsis ipsType_light' id='elControlsReviews_{$review->id}_response' title='{lang="more_options"}' data-ipsMenu data-ipsMenu-appendTo='#review-{$review->id}_wrap'><i class='fa fa-ellipsis-h'></i></a>
				</div>
				<div data-role="reviewResponse" class="ipsType_richText ipsType_normal ipsContained" data-controller='core.front.core.lightboxedImages'>
					{$review->mapped('author_response')|raw}
				</div>

				{{if $review->canEditResponse() OR $review->canDeleteResponse()}}
					<ul class='ipsMenu ipsMenu_narrow ipsHide' id='elControlsReviews_{$review->id}_response_menu'>
						{{if $review->canEditResponse()}}
							<li class='ipsMenu_item'><a href='{$review->url('editResponse')}' data-ipsDialog data-ipsDialog-title='{lang="review_author_respond"}'>{lang="edit"}</a></li>
						{{endif}}
						{{if $review->canDeleteResponse()}}
							<li class='ipsMenu_item'><a href='{$review->url('deleteResponse')->csrf()}' data-confirm>{lang="delete"}</a></li>
						{{endif}}
					</ul>
				{{endif}}
			</div>
		{{endif}}

		{{if $review->hidden() !== 1}}
			{{if member.member_id and ( !$review->mapped('votes_data') or !array_key_exists( member.member_id, json_decode( $review->mapped('votes_data'), TRUE ) ) ) and $review->author()->member_id != \IPS\Member::loggedIn()->member_id}}
				<div class='ipsType_medium ipsMargin_top'><strong>{lang="did_you_find_this_helpful"}</strong> &nbsp;&nbsp;&nbsp;<a href='{$review->url('rate')->setQueryString( 'helpful', TRUE )->csrf()}' class='ipsButton ipsButton_verySmall ipsButton_light' data-action="rateReview"><i class='fa fa-check'></i> {lang="yes"}</a> <a href='{$review->url('rate')->setQueryString( 'helpful', FALSE )->csrf()}' class='ipsButton ipsButton_verySmall ipsButton_light' data-action="rateReview"><i class='fa fa-times'></i> {lang="no"}</a></div>
			{{endif}}
		{{endif}}
	</div>
	{{if ( member.member_id and ( !$review->mapped('votes_data') or !array_key_exists( member.member_id, json_decode( $review->mapped('votes_data'), TRUE ) ) ) ) || $review->canEdit() || $review->canDelete() || $review->canHide() || $review->canUnhide() || ( $review->hidden() !== 1 && \IPS\IPS::classUsesTrait( $review, 'IPS\Content\Reactable' ) and settings.reputation_enabled and $review->hasReactionBar() )}}
		<div class='ipsItemControls'>
			{{if $review->hidden() !== 1 && \IPS\IPS::classUsesTrait( $review, 'IPS\Content\Reactable' ) and settings.reputation_enabled}}
				{template="reputation" group="global" app="core" params="$review"}
			{{endif}}
			{{if $review->canEdit() || $review->canDelete() || $review->canHide() || $review->canUnhide() || ( $review->hidden() !== 1 && $review->canRespond() ) }}
				<ul class='ipsComment_controls ipsClearfix ipsItemControls_left' data-role="commentControls">
					{{if $review->hidden() === 1 && ( $review->canUnhide() || $review->canDelete() )}}
						{{if $review->canUnhide()}}
							<li><a href='{$review->url('unhide')->csrf()}' class='ipsButton ipsButton_verySmall ipsButton_positive' data-action='approveComment'><i class='fa fa-check'></i> {lang="approve"}</a></li>
						{{endif}}
						{{if $review->canDelete()}}
							<li><a href='{$review->url('delete')->csrf()->setPage('page',\IPS\Request::i()->page)}' data-action='deleteComment' data-updateOnDelete="#commentCount" class='ipsButton ipsButton_verySmall ipsButton_negative'><i class='fa fa-times'></i> {lang="delete"}</a></li>
						{{endif}}
						{{if $review->canEdit() || $review->canSplit()}}
							<li>
								<a href='#elControlsReviewsSub_{$review->id}_menu' id='elControlsReviewsSub_{$review->id}' data-ipsMenu data-ipsMenu-appendTo='#review-{$review->id}_wrap'>{lang="options"} &nbsp;<i class='fa fa-caret-down'></i></a>
								<ul id='elControlsReviewsSub_{$review->id}_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
									{{if $review->canEdit()}}
										{{if $review->mapped('first') and $review->item()->canEdit()}}
											<li class='ipsMenu_item'><a href='{$review->item()->url()->setQueryString( 'do', 'edit' )}'>{lang="edit"}</a></li>
										{{else}}
											<li class='ipsMenu_item'><a href='{$review->url('edit')}' data-action='editComment'>{lang="edit"}</a></li>
										{{endif}}
									{{endif}}
									{{if $review->canSplit()}}
										<li class='ipsMenu_item'><a href='{$review->url('split')}' data-action='splitComment' data-ipsDialog data-ipsDialog-title="{lang="split_to_new" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $item::$title )"}">{lang="split"}</a></li>
									{{endif}}
								</ul>
							</li>
						{{endif}}
					{{elseif $review->hidden() !== 1 && $review->canRespond()}}
                        <li>
                            <a href='{$review->url('respond')}' class='ipsButton ipsButton_verySmall ipsButton_light' data-role='respond' data-ipsDialog data-ipsDialog-title='{lang="review_author_respond"}'>{lang="review_author_respond"}</a>
                        </li>
					{{endif}}
					<li class='ipsHide' data-role='commentLoading'>
						<span class='ipsLoading ipsLoading_tiny ipsLoading_noAnim'></span>
					</li>
				</ul>
			{{endif}}
		</div>
	{{endif}}
	
	<div class='ipsPadding ipsHide cPostShareMenu' id='elShareReview_{$review->id}_menu'>
		<h5 class='ipsType_normal ipsType_reset'>{lang="link_to_comment"}</h5>
		<input type='text' value='{$review->item()->url()->setQueryString( array( 'do' => 'findReview', 'review' => $review->id ) )}' class='ipsField_fullWidth'>
	</div>
</div>