<ips:template parameters="" />

{{if \count( \IPS\Output::i()->rssFeeds )}}
	<a href='#' id='elRSS' class='ipsPos_right ipsType_large' title='{lang="available_rss"}' data-ipsTooltip data-ipsMenu data-ipsMenu-above><i class='fa fa-rss-square'></i></a>
	<ul id='elRSS_menu' class='ipsMenu ipsMenu_auto ipsHide'>
		{{foreach \IPS\Output::i()->rssFeeds as $title => $url}}
			<li class='ipsMenu_item'><a title="{lang="$title"}" href="{$url}">{lang="$title"}</a></li>
		{{endforeach}}
	</ul>
{{endif}}