<ips:template parameters="$tabNames, $activeId, $defaultContent, $url, $tabParam='tab', $parseNames=TRUE, $contained=FALSE, $extraClasses=''" />
<div class='ipsTabs ipsClearfix{{if $extraClasses}} {$extraClasses}{{endif}}' id='elTabs_{expression="md5( $url )"}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{expression="md5( $url )"}' {{if \IPS\Request::i()->isAjax()}}data-ipsTabBar-updateURL='false'{{endif}}>
	<a href='#elTabs_{expression="md5( $url )"}' {{if \count( $tabNames ) > 1}}data-action='expandTabs'><i class='fa fa-caret-down'></i>{{else}}>{{endif}}</a>
	<ul role='tablist'>
		{{foreach $tabNames as $i => $name}}
			<li>
				<a href='{$url->setQueryString( $tabParam, $i )}' id='{expression="md5( $url )"}_tab_{$i}' class="ipsTabs_item {{if $i == $activeId}}ipsTabs_activeItem{{endif}}" title='{{if $parseNames}}{striptags="\IPS\Member::loggedIn()->language()->get( $name )"}{{else}}{striptags="$name"}{{endif}}' role="tab" aria-selected="{{if $i == $activeId}}true{{else}}false{{endif}}">
					{{if $parseNames}}{lang="$name"}{{else}}{$name|raw}{{endif}}
				</a>
			</li>
		{{endforeach}}
	</ul>
</div>
<section id='ipsTabs_content_{expression="md5( $url )"}' class='ipsTabs_panels {{if $contained}}ipsTabs_contained{{endif}}'>
	{{foreach $tabNames as $i => $name}}
		{{if $i == $activeId}}
			<div id='ipsTabs_elTabs_{expression="md5( $url )"}_{expression="md5( $url )"}_tab_{$i}_panel' class="ipsTabs_panel" aria-labelledby="{expression="md5( $url )"}_tab_{$i}" aria-hidden="false">
				{$defaultContent|raw}
			</div>
		{{endif}}
	{{endforeach}}
</section>
