<ips:template parameters="$id, $orientation='horizontal'" />
{{if $id == 'header'}}
	{template="announcementContentTop" app="core" group="global" params=""}
{{endif}}
{{if ( isset( \IPS\Output::i()->sidebar['widgets'][ $id ] ) && \count( \IPS\Output::i()->sidebar['widgets'][ $id ] ) ) || ( \IPS\Dispatcher::i()->application instanceof \IPS\Application AND \IPS\Dispatcher::i()->application->canManageWidgets() )}}
	<div class='cWidgetContainer {{if !isset( \IPS\Output::i()->sidebar['widgets'][ $id ] ) or !\count( \IPS\Output::i()->sidebar['widgets'][ $id ] )}}ipsHide{{endif}}' {{if \IPS\Dispatcher::i()->application->canManageWidgets()}}data-controller='core.front.widgets.area'{{endif}} data-role='widgetReceiver' data-orientation='{$orientation}' data-widgetArea='{$id}'>
		<ul class='ipsList_reset'>
			{{if isset( \IPS\Output::i()->sidebar['widgets'][ $id ] )}}
				{{foreach \IPS\Output::i()->sidebar['widgets'][ $id ] as $widget}}
					{{$widgetHtml = (string) $widget;}}
					<li class='ipsWidget ipsWidget_{$orientation} {{if !\in_array( 'IPS\Widget\Builder', class_implements( $widget ) )}}ipsBox{{endif}} {{if trim( $widgetHtml ) === ''}} ipsWidgetHide ipsHide{{endif}} {{if isset($widget->configuration['devices_to_show'])}}ipsResponsive_block{{foreach array_diff( array( 'Phone', 'Tablet', 'Desktop' ), $widget->configuration['devices_to_show'] ) as $device }} ipsResponsive_hide{$device}{{endforeach}}{{endif}}' data-blockID='{{if isset($widget->app) AND !empty($widget->app)}}app_{$widget->app}_{{else}}plugin_{$widget->plugin}_{{endif}}{$widget->key}_{$widget->uniqueKey}'{{if $widget->hasConfiguration()}} data-blockConfig="true"{{endif}} data-blockTitle="{lang="block_{$widget->key}"}" data-blockErrorMessage="{lang="$widget->errorMessage" escape="true"}" {{if \in_array( 'IPS\Widget\Builder', class_implements( $widget ) )}}data-blockBuilder="true"{{endif}} data-controller='core.front.widgets.block'>{$widgetHtml|raw}</li>
				{{endforeach}}
			{{endif}}
		</ul>
	</div>
{{endif}}