<ips:template parameters="$event" />
<div class="ipsPrint">
	<h1>{setting="board_name"}</h1>
	<h2>{lang="event_attendees" sprintf="$event->title"}</h2>
	<h4 class='date'>
		{$event->_start_date->dayName} {$event->_start_date->mday} {$event->_start_date->monthName}, {$event->_start_date->year}{{if !$event->all_day}}, {$event->_start_date->localeTime( FALSE )}{{endif}}
		{{if $event->_end_date}} - {$event->_end_date->dayName} {$event->_end_date->mday} {$event->_end_date->monthName}, {$event->_end_date->year} {{if !$event->all_day}}, {$event->_end_date->localeTime( FALSE )}{{endif}}{{endif}}
	</h4>
	<div></div>
	<div></div>

	<h3>{lang="event_rsvp_attendees"}</h3>
	<ul>
		{{if \count( $event->attendees( \IPS\calendar\Event::RSVP_YES ) ) }}
			{{foreach $event->attendees( \IPS\calendar\Event::RSVP_YES ) as $attendee }}
				<li>{$attendee->name}</li>
			{{endforeach}}
		{{else}}
			<li><em>{lang="no_rsvps_yet"}</em></li>
		{{endif}}
	</ul>

	{{if \count( $event->attendees( \IPS\calendar\Event::RSVP_MAYBE ) ) }}
		<div></div>
		<h3>{lang="rsvp_maybe_attendees"}</h3>
		<ul>
			{{foreach $event->attendees( \IPS\calendar\Event::RSVP_MAYBE ) as $attendee }}
				<li>{$attendee->name}</li>
			{{endforeach}}
		</ul>
	{{endif}}

	{{if \count( $event->attendees( \IPS\calendar\Event::RSVP_NO ) ) }}
		<div></div>
		<h3>{lang="rsvp_notgoing_attendees"}</h3>
		<ul>
			{{foreach $event->attendees( \IPS\calendar\Event::RSVP_NO ) as $attendee }}
				<li>{$attendee->name}</li>
			{{endforeach}}
		</ul>
	{{endif}}
</div>