<ips:template parameters="$event" />

<div class='' data-controller='core.front.core.commentFeed, core.front.core.ignoredComments' {{if settings.auto_polling_enabled}}data-autoPoll{{endif}} data-baseURL='{$event->url()}' {{if $event->isLastPage()}}data-lastPage{{endif}} data-feedID='event-{$event->id}' id='comments'>

	{template="featuredComments" group="global" app="core" params="$event->featuredComments(), $event->url()->setQueryString('tab', 'comments')->setQueryString('recommended', 'comments')"}
	{template="commentMultimodHeader" app="core" group="global" params="$event, '#comments'"}
	{{if $event->commentPageCount() > 1}}
		{$event->commentPagination( array( 'tab' ) )|raw}
		<br><br>
	{{endif}}

	<div data-role='commentFeed' data-controller='core.front.core.moderation'>
		{{if ( $comments = $event->comments( NULL, NULL, 'date', 'asc', NULL, NULL, NULL, NULL, FALSE, isset( \IPS\Request::i()->showDeleted ) ) and \count( $comments ) )}}
			<form action="{$event->url()->csrf()->setQueryString( 'do', 'multimodComment' )->setPage('page',\IPS\Request::i()->page)}" method="post" data-ipsPageAction data-role='moderationTools'>
				{{$commentCount=0; $timeLastRead = $event->timeLastRead(); $lined = FALSE;}}
				{{foreach $comments as $comment}}
					{{if !$lined and $timeLastRead and $timeLastRead->getTimestamp() < $comment->mapped('date')}}
						{{if $lined = TRUE and $commentCount}}
							<hr class="ipsCommentUnreadSeperator">
						{{endif}}
					{{endif}}
					{{$commentCount++;}}
					{$comment->html()|raw}
				{{endforeach}}
				{template="commentMultimod" app="core" group="global" params="$event"}
			</form>
		{{else}}
			<p class='ipsType_normal ipsType_light ipsType_center' data-role='noComments'>{lang="no_comments"}</p>
		{{endif}}
	</div>
	{{if $event->commentPageCount() > 1}}
		<hr class='ipsHr'>
		{$event->commentPagination( array( 'tab' ) )|raw}
	{{endif}}
	{{if $event->commentForm() || $event->locked() || \IPS\Member::loggedIn()->restrict_post || \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings'] || !\IPS\Member::loggedIn()->checkPostsPerDay()}}
		<a id='replyForm'></a>
		<div data-role='replyArea' class='ipsBox ipsPad {{if !$event->canComment()}}cTopicPostArea_noSize{{endif}} ipsSpacer_top'>
			{{if $event->commentForm()}}
				{{if $event->locked()}}
					<p class='ipsType_reset ipsType_warning ipsComposeArea_warning ipsSpacer_bottom ipsSpacer_half'><i class='fa fa-info-circle'></i> {lang="event_locked_can_comment"}</p>
				{{endif}}
				{$event->commentForm()|raw}
				{{else}}
				{{if $event->locked()}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'event_locked_cannot_comment'"}
				{{elseif \IPS\Member::loggedIn()->restrict_post}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment', \IPS\Member::loggedIn()->warnings(5,NULL,'rpa'), \IPS\Member::loggedIn()->restrict_post"}
				{{elseif \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'unacknowledged_warning_cannot_post', \IPS\Member::loggedIn()->warnings( 1, FALSE )"}
				{{elseif !\IPS\Member::loggedIn()->checkPostsPerDay()}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'member_exceeded_posts_per_day'"}
				{{endif}}
			{{endif}}
		</div>
	{{endif}}
</div>