<ips:template parameters="$event, $date, $truncate=FALSE, $map=array( 300, 200 ), $revertToFirst=FALSE" />
{{$coverPhoto = $event->coverPhoto();}}
<div class='cCalendarBlock ipsAreaBackground_reset ipsBox ipsBox--child'>
	<div class='ipsPageHead_special ipsCoverPhoto' data-controller='core.global.core.coverPhoto' data-coverOffset='{$coverPhoto->offset}'>
		{{if $coverPhoto->file}}
			<div class='ipsCoverPhoto_container'>
				{{if settings.lazy_load_enabled}}
					<img src="{expression="\IPS\Text\Parser::blankImage()"}" data-src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo' alt='{$event->title}'>
				{{else}}
					<img src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo' alt='{$event->title}'>
				{{endif}}
			</div>
		{{endif}}
		<div class='ipsColumns'>
			<div class='ipsColumn ipsColumn_fixed ipsColumn_veryNarrow ipsPos_center'>
				<img src='{$event->author()->photo}' class="ipsUserPhoto ipsUserPhoto_mini" alt=''>
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				<h2 class='ipsType_pageTitle ipsType_blendLinks ipsPageHead_barText ipsPageHead_barText_small ipsType_break'><a href='{$event->url( "getPrefComment" )}' title='{$event->title}'>{truncate="$event->title" length="18"}{{if $event->hidden() === 1}} <span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>{{endif}}</a></h2>
			</div>
		</div>
	</div>
	<br>
	<div class='ipsPad ipsClearfix'>
		<h3 class='ipsType_reset'>
			{{$startDate = $event->nextOccurrence( $date, 'startDate' );}}
			{{if $revertToFirst AND $startDate AND $startDate->mon > $date->mon}}
				{{$startDate = $event->nextOccurrence( \IPS\calendar\Date::getDate( $date->year, $date->mon, 1 ), 'startDate' );}}
			{{endif}}
			{{if $startDate}}
				{{$nextEndDate = $event->nextOccurrence( $startDate ?: $date, 'endDate' );}}
				{{$sameDay = ( $nextEndDate AND $startDate->calendarDate() == $nextEndDate->calendarDate() );}}
				{$startDate->calendarDate()}{{if !$event->all_day}} {$startDate->localeTime( FALSE )} {{endif}}
				{{if $event->_end_date AND $event->nextOccurrence( $startDate ?: $date, 'endDate' ) }}
					&nbsp;&nbsp;<i class='fa fa-arrow-circle-right ipsType_large ipsType_light'></i>&nbsp;&nbsp;
					{{if !$sameDay}}
						{$event->nextOccurrence( $startDate ?: $date, 'endDate' )->calendarDate()}
					{{endif}}
					{{if !$event->all_day}}
						{{if !$sameDay}} {{endif}}
						{$event->nextOccurrence( $startDate ?: $date, 'endDate' )->localeTime( FALSE )}
					{{endif}}
				{{endif}}
			{{else}}
				{$event->lastOccurrence( 'startDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'startDate' )->localeTime( FALSE )} {{endif}}
				{{if $event->_end_date AND $event->lastOccurrence( 'endDate' ) }}
					&nbsp;&nbsp;<i class='fa fa-arrow-circle-right ipsType_large ipsType_light'></i>&nbsp;&nbsp;{$event->lastOccurrence( 'endDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'endDate' )->localeTime( FALSE )}{{endif}}
				{{endif}}
			{{endif}}
		</h3>
		{{if $event->recurring}}<p class='ipsType_reset ipsType_normal ipsType_light'>{$event->_recurring_text}</p><br>{{endif}}
		<div class='ipsType_richText ipsType_medium' {{if ( \IPS\Request::i()->isAjax() or $truncate ) && $event->content}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='5 lines'{{endif}}>
			{{if $event->content}}
				{{if \IPS\Request::i()->isAjax() or $truncate}}
					{$event->truncated()|raw}
				{{else}}
					{$event->content|raw}
				{{endif}}
			{{endif}}
			<p class='ipsType_medium ipsType_richText ipsSpacer_both'><a href='{$event->url( "getPrefComment" )}'>{lang="event_details"}</a></p>
		</div>
		{{if $map !== FALSE AND $event->map( $map[0], $map[1] )}}
			<div class='ipsAreaBackground_light cCalendarBlock_map ipsPad_half'>
				{$event->map( $map[0], $map[1] )|raw}
			</div>
		{{endif}}
		<br>
		<a href='{$event->container()->url()}' class='ipsPos_right ipsResponsive_noFloat cEvents_event cEvents_eventSmall cEvents_style{$event->container()->id}'>{$event->container()->_title}</a>
		{{if $event->container()->allow_comments}}<a href='{$event->url()->setQueryString( 'tab', 'comments' )}' class='ipsType_medium ipsType_noBreak'>{lang="event_comment_count" pluralize="$event->comments"}</a>{{endif}}
		{{if $event->container()->allow_comments AND $event->container()->allow_reviews}}&middot;{{endif}}
		{{if $event->container()->allow_reviews}}<a href='{$event->url()->setQueryString( 'tab', 'reviews' )}' class='ipsType_medium ipsType_noBreak'>{lang="event_review_count" pluralize="$event->reviews"}</a>{{endif}}
		{{if $event->rsvp }}
			<hr class='ipsHr'>
			<h4 class='ipsType_reset'><strong>{lang="event_rsvp_attendees_list" pluralize="$event->attendeeCount( \IPS\calendar\Event::RSVP_YES )"}</strong></h4>
			{{if \count( $event->attendees( \IPS\calendar\Event::RSVP_YES, 5 ) )}}
				<ul class='ipsList_inline ipsList_noSpacing ipsSpacer_top ipsSpacer_half'>
					{{foreach $event->attendees( \IPS\calendar\Event::RSVP_YES, 5 ) as $attendee}}
						<li>{template="userPhoto" app="core" group="global" params="$attendee, 'tiny'"}</li>
					{{endforeach}}
				</ul>
			{{endif}}
		{{endif}}
	</div>
</div>