<ips:template parameters="$events" />

<ul class='ipsDataList ipsDataList_reducedSpacing'>
	{{foreach $events as $event}}
		<li class='ipsDataItem'>
			<div class='ipsDataItem_icon cCalendar_date_overlay'>
				{{$nextOccurrence = $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: $event->lastOccurrence();}}
				<time datetime='{$nextOccurrence->mysqlDatetime()}' class='ipsCalendarDate'>
					<span class='ipsCalendarDate_month'>{$nextOccurrence->monthNameShort}</span>
					<span class='ipsCalendarDate_date'>{$nextOccurrence->mday}</span>
				</time>
			</div>
			<div class='ipsDataItem_main'>
				<a href="{$event->url( "getPrefComment" )}" title='{lang="view_this_event" sprintf="$event->title"}'>{$event->title}</a><br>
				<span class='ipsType_light ipsType_medium'>{lang="byline_nodate" sprintf="$event->author()->name"}</span><br>
			</div>
		</li>
	{{endforeach}}
</ul>