<ips:template parameters="$event, $date, $truncate=FALSE, $map=array( 300, 200 ), $revertToFirst=FALSE" />
{{$coverPhoto = $event->coverPhoto();}}
<div class='cCalendarBlock ipsAreaBackground_reset ipsBox ipsBox--child ipsMargin_bottom'>
	<div class='ipsPageHead_special ipsCoverPhoto' data-controller='core.global.core.coverPhoto' data-coverOffset='{$coverPhoto->offset}'>
		{{if $coverPhoto->file}}
			<div class='ipsCoverPhoto_container'>
				{{if settings.lazy_load_enabled}}
					<img src="{expression="\IPS\Text\Parser::blankImage()"}" data-src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo'>
				{{else}}
					<img src='{$coverPhoto->file->url}' class='ipsCoverPhoto_photo'>
				{{endif}}
			</div>
		{{endif}}
		<div class='ipsFlex ipsFlex-ai:center ipsGap:4'>
			<div class='ipsFlex-flex:00'>
				<img src='{$event->author()->photo}' class="ipsUserPhoto ipsUserPhoto_mini" alt=''>
			</div>
			<div class='ipsFlex-flex:11'>
				<h2 class='ipsType_pageTitle ipsType_blendLinks ipsPageHead_barText ipsPageHead_barText_small ipsType_break'><a href='{$event->url( "getPrefComment" )}' title='{$event->title}'>{$event->title}{{if $event->hidden() === 1}} <span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>{{endif}}</a></h2>
			</div>
		</div>
	</div>
	{{if $map !== FALSE AND $event->map( $map[0], $map[1] )}}
	<div class='ipsAreaBackground_light cCalendarBlock_map ipsPad_half ipsPos_right ipsBox'>
		{$event->map( $map[0], $map[1] )|raw}
	</div>
	{{endif}}
	<div class='ipsPad'>
		<div class='ipsFlex ipsGap:4'>
			<div class='ipsFlex-flex:00'>
				<div class='eventStreamDate ipsPos_left'>
					<a href='{$event->url( "getPrefComment" )}'>
						{{if $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )}}
							<time datetime='{$event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->mysqlDatetime()}' class='ipsCalendarDate'>
							<span class='ipsCalendarDate_month'>{$event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->monthNameShort}</span>
							<span class='ipsCalendarDate_date'>{$event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->mday}</span>
						{{else}}
							<time datetime='{$event->lastOccurrence( 'startDate' )->mysqlDatetime()}{{if !$event->all_day}} {$event->lastOccurrence( 'startDate' )->mysqlDatetime( FALSE )} {{endif}}' class='ipsCalendarDate'>
							<span class='ipsCalendarDate_month'>{$event->lastOccurrence( 'startDate' )->monthNameShort}</span>
							<span class='ipsCalendarDate_date'>{$event->lastOccurrence( 'startDate' )->mday}</span>
						{{endif}}
						</time>
					</a>
				</div>
			</div>
			<div class='ipsFlex-flex:11'>
				<div class='ipsFlex ipsFlex-fw:wrap'>
					<div class='ipsFlex-flex:11' style='flex-basis: 450px'>
						<h3 class='ipsType_reset'>
							<time datetime='{expression="$event->_start_date->format( 'Y-m-d' )"}'>
							{{if $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )}}
							{$event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->calendarDate()}{{if !$event->all_day}}, {$event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->localeTime( FALSE )} {{endif}}
							{{else}}
							{$event->lastOccurrence( 'startDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'startDate' )->localeTime( FALSE )} {{endif}}
							{{endif}}
							</time>
							{{if $event->_end_date}}
							&nbsp;&nbsp;<i class='fa fa-arrow-circle-right ipsType_large ipsType_light'></i>&nbsp;&nbsp;
							<time datetime='{expression="$event->_end_date->format( 'Y-m-d' )"}'>
							{{$sameDay = !( ($event->_start_date->mday != $event->_end_date->mday) or ($event->_start_date->mon != $event->_end_date->mon) or ($event->_start_date->year != $event->_end_date->year) );}}
							{{if $event->nextOccurrence( $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: \IPS\calendar\Date::getDate(), 'endDate' )}}
							{{if !$sameDay}}{$event->nextOccurrence( $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: \IPS\calendar\Date::getDate(), 'endDate' )->calendarDate()}{{endif}}{{if !$event->all_day}}{{if !$sameDay}}, {{endif}}{$event->nextOccurrence( $event->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: \IPS\calendar\Date::getDate(), 'endDate' )->localeTime( FALSE )}{{endif}}
							{{else}}
							{$event->lastOccurrence( 'endDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'endDate' )->localeTime( FALSE )}{{endif}}
							{{endif}}
							</time>
							{{endif}}
						</h3>
						{{if $event->recurring}}<p class='ipsType_reset ipsType_normal ipsType_light'>{$event->_recurring_text}</p><br>{{endif}}
						<div class='ipsType_richText ipsType_medium' {{if ( \IPS\Request::i()->isAjax() or $truncate ) && $event->content}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='5 lines'{{endif}}>
							{{if $event->content}}
								{{if \IPS\Request::i()->isAjax() or $truncate}}
									{$event->truncated()|raw}
								{{else}}
									{$event->content|raw}
								{{endif}}
							{{endif}}
						</div>
						{{if $event->container()->allow_comments OR $event->container()->allow_reviews OR $event->rsvp}}
							<div class='ipsMargin_top'>
								{{if $event->container()->allow_comments}}<a href='{$event->url()->setQueryString( 'tab', 'comments' )}' class='ipsType_medium ipsType_noBreak'>{lang="event_comment_count" pluralize="$event->comments"}</a>{{endif}}
								{{if $event->container()->allow_comments AND $event->container()->allow_reviews}}&middot;{{endif}}
								{{if $event->container()->allow_reviews}}<a href='{$event->url()->setQueryString( 'tab', 'reviews' )}' class='ipsType_medium ipsType_noBreak'>{lang="event_review_count" pluralize="$event->reviews"}</a>{{endif}}
								{{if $event->rsvp }}
									<hr class='ipsHr'>
									<h4 class='ipsType_reset'><strong>{lang="event_rsvp_attendees_list" pluralize="$event->attendeeCount( \IPS\calendar\Event::RSVP_YES )"}</strong></h4>
									{{if \count( $event->attendees( \IPS\calendar\Event::RSVP_YES, 5 ) )}}
										<ul class='ipsList_inline ipsList_noSpacing ipsSpacer_top ipsSpacer_half'>
											{{foreach $event->attendees( \IPS\calendar\Event::RSVP_YES, 5 ) as $attendee}}
											<li>{template="userPhoto" app="core" group="global" params="$attendee, 'tiny'"}</li>
											{{endforeach}}
										</ul>
									{{endif}}
								{{endif}}
							</div>
						{{endif}}
					</div>
					<div class='ipsFlex-flex:00'>
						<a href='{$event->container()->url()}' class='ipsResponsive_noFloat cEvents_event cEvents_eventSmall cEvents_style{$event->container()->id}'>{$event->container()->_title}</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>