<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form {{if \IPS\Request::i()->isAjax() }}data-controller='calendar.front.view.reminderForm'{{endif}} accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm >
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
	<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	<div class="ipsPad">
		<h2 class='ipsType_sectionHead'>{expression="\IPS\Output::i()->title"}</h2>
		<br><br>
		<ul class='ipsList_reset'>
			{{foreach $elements as $collection}}
			{{foreach $collection as $input}}
			{{if \is_string( $input )}}
			{$input|raw}
			<hr class='ipsHr'>
			{{elseif $input instanceof \IPS\Helpers\Form\Checkbox}}
			{$input->html($form)|raw}
			{{else}}
			{$input->rowHtml($form)|raw}
			{{endif}}
			{{endforeach}}
			{{endforeach}}
		</ul>
	</div>
	<div class="ipsAreaBackground ipsPad">
		{$actionButtons[0]|raw} {{if isset( $actionButtons[1] )}}{$actionButtons[1]|raw}{{endif}}
	</div>
</form>