<ips:template parameters="$event, $attendees" />
<!-- Don't use IDs here, this template is called twice in view -->
{{if \IPS\Member::loggedIn()->member_id AND ( isset( $attendees[0][ \IPS\Member::loggedIn()->member_id ] ) OR isset( $attendees[1][ \IPS\Member::loggedIn()->member_id ] ) OR isset( $attendees[2][ \IPS\Member::loggedIn()->member_id ] ) )}}
	<div class='{{if isset( $attendees[1][ \IPS\Member::loggedIn()->member_id ] )}}ipsAreaBackground_positive{{elseif isset( $attendees[0][ \IPS\Member::loggedIn()->member_id ] )}}ipsAreaBackground_negative{{else}}ipsAreaBackground_reset{{endif}} ipsPadding'>
		<p class='ipsType_large ipsType_center ipsType_reset'>
			<strong>
				{{if isset( $attendees[1][ \IPS\Member::loggedIn()->member_id ] )}}
					<span><i class='fa fa-check-circle'></i> {{if $event->hasPassed()}}{lang="you_were_going"}{{else}}{lang="you_are_going"}{{endif}}</span>
				{{elseif isset( $attendees[0][ \IPS\Member::loggedIn()->member_id ] )}}
					<span>{{if $event->hasPassed()}}{lang="you_werent_going"}{{else}}{lang="you_arent_going"}{{endif}}</span>
				{{else}}
					{{if !$event->hasPassed() OR !\IPS\Settings::i()->calendar_block_past_changes}}
						{lang="confirm_attendance"}
					{{else}}
						{lang="no_rsvp_past_event"}
					{{endif}}
				{{endif}}
			</strong>
		</p>
		{{if !$event->hasPassed() OR !\IPS\Settings::i()->calendar_block_past_changes}}
		<ul class="ipsToolList ipsToolList_vertical ipsSpacer_top ipsSpacer_half">
			{{if isset( $attendees[2][ \IPS\Member::loggedIn()->member_id ] )}}
				<li>
					<a href='{$event->url('rsvp')->setQueryString( 'action', 'yes' )->csrf()}' class='ipsButton ipsButton_important ipsButton_fullWidth'>{lang="rsvp_attend_event"}</a>
				</li>
				<li>
					<a href='{$event->url('rsvp')->setQueryString( 'action', 'no' )->csrf()}' class='ipsButton ipsButton_link ipsButton_fullWidth ipsButton_verySmall'>{lang="rsvp_notgoing_event"}</a>
				</li>
			{{elseif isset( $attendees[0][ \IPS\Member::loggedIn()->member_id ] )}}
				<li class='ipsType_center'>
					<a href='{$event->url('rsvp')->setQueryString( 'action', 'leave' )->csrf()}' class='ipsType_blendLinks ipsType_noUnderline ipsFaded'>{lang="rsvp_change"}</a>
				</li>
			{{else}}
				<li class='ipsType_center'>
					<a href='{$event->url('rsvp')->setQueryString( 'action', 'leave' )->csrf()}' class='ipsType_blendLinks ipsType_noUnderline ipsFaded'>{lang="rsvp_leave_event"}</a>
				</li>
			{{endif}}
		</ul>
		{{endif}}
	</div>
{{elseif $event->can('rsvp')}}
	<div class='ipsAreaBackground_reset ipsPad'>
		{{if $event->hasPassed() AND \IPS\Settings::i()->calendar_block_past_changes}}
			<div class='ipsMessage ipsMessage_info'>{lang="no_rsvp_past_event"}</div>
		{{elseif $event->rsvp_limit > 0 AND \count($attendees[1]) >= $event->rsvp_limit}}
			<div class='ipsMessage ipsMessage_info'>{lang="rsvp_limit_reached"}</div>
		{{else}}
			{{if $event->rsvp_limit > 0}}<div class='ipsMessage ipsMessage_info'>{lang="rsvp_limit_info" pluralize="\count($attendees[1])" sprintf="$event->rsvp_limit"}</div>{{endif}}
			<a href='{$event->url('rsvp')->setQueryString( 'action', 'yes' )->csrf()}' class='ipsButton ipsButton_important ipsButton_fullWidth'>{{if $event->hasPassed()}}{lang="rsvp_attended_past_event"}{{else}}{lang="rsvp_attend_event"}{{endif}}</a>
			<br>
			<div class='ipsGrid'>
				{{if $event->rsvp_limit == -1 AND !$event->hasPassed()}}<div class='ipsGrid_span6'><a href='{$event->url('rsvp')->setQueryString( 'action', 'maybe' )->csrf()}' class='ipsButton ipsButton_link ipsButton_fullWidth ipsButton_verySmall'>{lang="rsvp_maybe_event"}</a></div>{{endif}}
				<div class='ipsGrid_span{{if $event->rsvp_limit == -1 AND !$event->hasPassed()}}6{{else}}12{{endif}}'><a href='{$event->url('rsvp')->setQueryString( 'action', 'no' )->csrf()}' class='ipsButton ipsButton_link ipsButton_fullWidth ipsButton_verySmall'>{{if $event->hasPassed()}}{lang="rsvp_notattended_past_event"}{{else}}{lang="rsvp_notgoing_event"}{{endif}}</a></div>
			</div>
		{{endif}}
	</div>
{{endif}}