<ips:template parameters="$member, $rep=NULL, $trophy=0, $contentLabel='members_member_posts', $contentCount='member_posts'" />
{{$rep = $rep ?: $member->pp_reputation_points;}}
{{$contentCount = $contentCount ? $member->$contentCount : $member->member_posts;}}
<li class="ipsGrid_span3 ipsStreamItem ipsStreamItem_contentBlock ipsStreamItem_member cTopMembers_member ipsBox ipsBox--child ipsPadding ipsType_center">
	{{if $trophy}}
	<span class="ipsLeaderboard_trophy ipsLeaderboard_trophy_{$trophy}">
		<i class="fa fa-trophy"></i>
	</span>
	{{endif}}
	{template="userPhoto" group="global" app="core" params="$member, 'medium'"}
	<div class='ipsStreamItem_container'>
		<div class='ipsStreamItem_header ipsSpacer_top ipsSpacer_half'>
			<h2 class='ipsType_reset ipsStreamItem_title ipsTruncate ipsTruncate_line' data-searchable>
				{{if member.canAccessModule( \IPS\Application\Module::get( 'core', 'members', 'front' ) )}}
					{template="userLink" app="core" group="global" params="$member"}
				{{else}}
					{$member->name}
				{{endif}}
			</h2>
			<p class='ipsType_reset ipsType_medium'>{$member->groupName|raw}</p>
		</div>

		<hr class='ipsHr ipsHr_small'>

		<ul class='ipsList_reset ipsGrid'>
			<li class='ipsGrid_span6 ipsList_reset ipsType_center'>
				<h3 class='ipsType_minorHeading ipsType_unbold'>
					{{if \IPS\Content\Reaction::isLikeMode()}}
						{lang="rep_system_like"}
					{{else}}
						{lang="rep_level_points"}
					{{endif}}
				</h3>
				<p class='ipsType_reset ipsTruncate ipsTruncate_line'>
					{{if member.group['gbw_view_reps']}}
						<a href='{url="app=core&module=members&controller=profile&id={$member->member_id}&do=reputation" seoTemplate="profile_reputation" seoTitle="$member->members_seo_name"}' title="{lang="reputation_badge_tooltip_period"}" data-ipsTooltip class='ipsRepBadge ipsType_medium {{if $rep > 0}}ipsRepBadge_positive{{elseif $rep < 0}}ipsRepBadge_negative{{else}}ipsRepBadge_neutral{{endif}}'><i class='fa {{if $rep > 0}}fa-plus-circle{{elseif $rep < 0}}fa-minus-circle{{else}}fa-circle-o{{endif}}'></i> {expression="\IPS\Member::loggedIn()->language()->formatNumber( $rep )"}</a>
					{{else}}
						<span title="{lang="reputation_badge_tooltip_period"}" data-ipsTooltip class='ipsRepBadge ipsType_medium {{if $rep > 0}}ipsRepBadge_positive{{elseif $rep < 0}}ipsRepBadge_negative{{else}}ipsRepBadge_neutral{{endif}}'><i class='fa {{if $rep > 0}}fa-plus-circle{{elseif $rep < 0}}fa-minus-circle{{else}}fa-circle-o{{endif}}'></i> {expression="\IPS\Member::loggedIn()->language()->formatNumber( $rep )"}</span>
					{{endif}}
				</p>
			</li>
			<li class='ipsGrid_span6 ipsList_reset ipsType_center'>
				<h3 class='ipsType_minorHeading ipsType_unbold'>{lang="{$contentLabel}"}</h3>
				<p class='ipsType_reset ipsTruncate ipsTruncate_line ipsType_medium'>{number="$contentCount"}</p>
			</li>
		</ul>

		<hr class='ipsHr ipsHr_small'>
		{{$showFollowButton = ( \IPS\Member::loggedIn()->member_id != $member->member_id and ( !$member->members_bitoptions['pp_setting_moderate_followers'] or \IPS\Member::loggedIn()->following( 'core', 'member', $member->member_id ) ) );}}
		<ul class='ipsList_reset {{if ! $showFollowButton}}cTopMembers_NoFollowButton{{endif}}'>
			<li class='{{if $showFollowButton}}ipsSpacer_bottom ipsSpacer_half{{endif}}'>
				<a href='{url="app=core&module=members&controller=profile&do=content&id={$member->member_id}" base="front" seoTemplate="profile_content" seoTitle="$member->members_seo_name"}' class='ipsButton ipsButton_fullWidth ipsButton_light ipsButton_small'>{lang="find_content"}</a>
			</li>
			{{if $showFollowButton}}
				<li>
					{template="memberFollow" app="core" group="profile" params="'core', 'member', $member->member_id, $member->followersCount(), TRUE"}
				</li>
			{{else}}
				<li></li>
			{{endif}}
		</ul>
	</div>
</li>