<ips:template parameters="$tabs, $activeTab, $content" />

<div class='ipsPageHeader ipsClearfix ipsSpacer_bottom'>
	<h1 class='ipsType_pageTitle'>{lang="leaderboard_title"}</h1>
</div>

{{$icons = array('leaderboard' => 'trophy', 'history' => 'clock-o', 'members' => 'star');}}
<div class='ipsTabs ipsTabs_contained ipsTabs_withIcons ipsTabs_large ipsTabs_stretch ipsClearfix ipsResponsive_pull' id='elTabBar' data-ipsTabBar data-ipsTabbar-defaultTab="elTab{$activeTab}" data-ipsTabBar-contentArea='#elLeaderboardContent'>
	<a href='#elTabBar' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
	<ul role='tablist'>
		{{foreach $tabs as $key}}
		<li role='presentation'>
			{{$seoTemplate = 'leaderboard_' . $key;}}
			<a href='{url="app=core&module=discover&controller=popular&tab={$key}" seoTemplate="$seoTemplate"}' role='tab' id='elTab{$key}' class='ipsType_center ipsTabs_item {{if $key == $activeTab}}ipsTabs_activeItem{{endif}}' {{if $key == $activeTab}}aria-selected="true"{{endif}}>
				<i class='fa fa-{$icons[$key]}'></i>
				{lang="leaderboard_tabs_{$key}"}
			</a>
		</li>
		{{endforeach}}
	</ul>
</div>
<section id='elLeaderboardContent' class="ipsTabs_panels ipsTabs_contained ipsResponsive_pull">
	<div id='ipsTabs_elTabBar_elTab{$activeTab}_panel' aria-labelledby='elTab{$activeTab}' aria-hidden='false' class='ipsTabs_panel ipsPadding'>
		{$content|raw}
	</div>
</section>