<ips:template parameters="$filter, $title, $results" />
<div class="ipsPadding sm:ipsPadding:none ipsSpacer_bottom">
	{{if $title}}
		<h2 class="ipsType_pageTitle ipsMargin_bottom">{$title}</h2>
	{{endif}}
	{{if \count( $results )}}
		<ol class="ipsStream ipsList_reset cStream_members ipsGrid ipsGrid_collapsePhone" data-ipsGrid data-ipsGrid-minItemSize='230' data-ipsGrid-maxItemSize='500' data-ipsGrid-equalHeights='row'>
			{{foreach $results as $member}}
				{{if \in_array( $filter, array( 'pp_reputation_points', 'member_posts' ) )}}
					{template="memberRow" group="popular" app="core" params="$member"}
				{{else}}
					{template="memberRow" group="popular" app="core" params="$member, NULL, 0, $filter::$title . '_pl_lc', '_customCount'"}
				{{endif}}
			{{endforeach}}
		</ol>
	{{else}}
		<p class='ipsType_light'>
			{lang="no_results"}
		</p>
	{{endif}}
</div>