<ips:template parameters="$calendar, $calendars, $thisCalendar, $jump, $date, $featured, $downloadLinks" />

{template="calendarHeader" group="browse" app="calendar" params="$calendars, $thisCalendar, $jump, $downloadLinks"}

<div data-controller='calendar.front.browse.main' class='ipsSpacer_top ipsResponsive_pull ipsBox_alt'>
	{$calendar|raw}
</div>

{{if $thisCalendar}}
<div class="ipsBox ipsPadding ipsResponsive_pull ipsResponsive_showPhone ipsMargin_vertical">
	<div>
		{template="follow" app="core" group="global" params="'calendar', 'calendar', $thisCalendar->id, \IPS\calendar\Event::containerFollowerCount( $thisCalendar )"}
	</div>
</div>
{{endif}}

{template="calendarFeatured" group="browse" app="calendar" params="$featured, $date"}