<ips:template parameters="$calendars, $date, $featured, $birthdays, $birthdayCount, $events, $tomorrow, $yesterday, $today, $thisCalendar, $jump" />

<div class='ipsBox'>
	<div class='ipsPager cCalendarNav ipsPadding ipsAreaBackground_light ipsBorder_bottom lg:ipsPos_sticky'>
		<div class='ipsPager_prev'>
			<a href="{{if $thisCalendar}}{url="app=calendar&module=calendar&controller=view&id={$thisCalendar->_id}&y={$yesterday->year}&m={$yesterday->mon}&d={$yesterday->mday}" seoTemplate="calendar_calday" seoTitle="$thisCalendar->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=view&y={$yesterday->year}&m={$yesterday->mon}&d={$yesterday->mday}" seoTemplate="calendar_day"}{{endif}}" title='{lang="cal_month_day" sprintf="$yesterday->monthName, $yesterday->mday, $yesterday->year"}' rel='prev nofollow' data-action='changeView'>
				<span class='ipsPager_type ipsType_normal'>{lang="cal_month_day_noyear" sprintf="$yesterday->monthName, $yesterday->mday"}</span>
				<span class='ipsPager_title ipsType_light'>{$yesterday->year}</span>
			</a>
		</div>
		<div class='ipsPager_center cCalendarNav' data-role='calendarNav'>
			<h1 class='ipsType_pageTitle ipsType_center'>{lang="cal_month_day" sprintf="$date->monthName, $date->mday, $date->year"}</h1>
			<ul class='ipsButton_split ipsType_noBreak'>
				<li><a href='{{if $thisCalendar}}{url="app=calendar&module=calendar&controller=view&view=month&id={$thisCalendar->_id}&y={$date->year}&m={$date->mon}" seoTemplate="calendar_calmonth" seoTitle="$thisCalendar->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=view&view=month&y={$date->year}&m={$date->mon}" seoTemplate="calendar_month"}{{endif}}' title='{lang="cal_month_title" sprintf="$date->monthName, $date->year"}' class='ipsButton ipsButton_veryLight ipsButton_verySmall' data-action='changeView'>{lang="month"}</a></li>
				<li><a href='{{if $thisCalendar}}{url="app=calendar&module=calendar&controller=view&view=week&id={$thisCalendar->_id}&w={$date->year}-{$date->mon}-{$date->mday}" seoTemplate="calendar_calweek" seoTitle="$thisCalendar->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=view&view=week&w={$date->year}-{$date->mon}-{$date->mday}" seoTemplate="calendar_week"}{{endif}}' title='{lang="cal_week_title" sprintf="$date->firstDayOfWeek('monthNameShort'), $date->firstDayOfWeek('mday'), $date->firstDayOfWeek('year'), $date->lastDayOfWeek('monthNameShort'),	$date->lastDayOfWeek('mday'), $date->lastDayOfWeek('year')"}' class='ipsButton ipsButton_veryLight ipsButton_verySmall' data-action='changeView'>{lang="week"}</a></li>
				<li><a href='#' class='ipsButton ipsButton_primary ipsButton_verySmall' title='{lang="cal_month_day" sprintf="$date->monthName, $date->mday, $date->year"}' data-action='changeView'>{lang="day"}</a></li>
				<li><a href='{{if $thisCalendar}}{url="app=calendar&module=calendar&controller=view&view=stream&id={$thisCalendar->_id}&y={$date->year}&m={$date->mon}" seoTemplate="calendar_calstream" seoTitle="$thisCalendar->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=view&view=stream&y={$date->year}&m={$date->mon}" seoTemplate="calendar_stream"}{{endif}}' title='{lang="cal_month_stream_title" sprintf="$date->monthName, $date->year"}' class='ipsButton ipsButton_veryLight ipsButton_verySmall' data-action='changeView'><span class='ipsResponsive_hidePhone ipsResponsive_inline'>{lang="event_stream"}</span><span class='ipsResponsive_showPhone ipsResponsive_inline'>{lang="event_stream_short"}</span></a></li>
			</ul>
		</div>
		<div class='ipsPager_next'>
			<a href="{{if $thisCalendar}}{url="app=calendar&module=calendar&controller=view&id={$thisCalendar->_id}&y={$tomorrow->year}&m={$tomorrow->mon}&d={$tomorrow->mday}" seoTemplate="calendar_calday" seoTitle="$thisCalendar->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=view&y={$tomorrow->year}&m={$tomorrow->mon}&d={$tomorrow->mday}" seoTemplate="calendar_day"}{{endif}}" title='{lang="cal_month_day" sprintf="$tomorrow->monthName, $tomorrow->mday, $tomorrow->year"}' rel='next nofollow' data-action='changeView'>
				<span class='ipsPager_type ipsType_normal'>{lang="cal_month_day_noyear" sprintf="$tomorrow->monthName, $tomorrow->mday"}</span>
				<span class='ipsPager_title ipsType_light'>{$tomorrow->year}</span>
			</a>
		</div>
	</div>

	<div class='ipsPadding sm:ipsPadding:half'>
		{{if \count( $birthdays )}}
		<div class='ipsColumns ipsColumns_collapseTablet'>
			<div class='ipsColumn ipsColumn_fluid'>
		{{endif}}
		<div class='ipsBox ipsBox--child'>
			<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="events_happening_today"}</h2>
			{{if $events['count'] > 0}}
				<ol class='cCalendarDay ipsDataList'>
					{{if isset( $events['allDay'] ) && \count( $events['allDay'] )}}
						<li class='ipsDataItem cCalendarDay_allDay'>
							<div class='ipsDataItem_generic ipsDataItem_size5 cCalendarDay_hour cCalendarDay_allDay ipsAreaBackground_light ipsPad'>
								<h2 class='ipsType_reset'>{lang="day_view_all_day"}</h2>
							</div>
							<div class='ipsDataItem_main ipsPad'>
								<div class='cCalendarDay_eventList' data-ipsPatchwork data-ipsPatchwork-minColSize='300' data-ipsPatchwork-maxColSize='500'>
									<div data-role='patchworkList'>
										{{foreach $events['allDay'] as $event}}
											<div data-role='patchworkItem'>
												{template="eventBlock" app="calendar" group="view" params="$event, $date, true"}
											</div>
										{{endforeach}}
									</div>
								</div>
							</div>
						</li>
					{{endif}}

					{{foreach $events as $hour => $hourEvents}}
						{{if !empty( $hourEvents ) && $hour !== 'allDay' && $hour !== 'count'}}
							<li class='ipsDataItem'>
								<div class='ipsDataItem_generic ipsDataItem_size5 cCalendarDay_hour ipsAreaBackground_light ipsPad'>
									<h2 class='ipsType_reset'>
										{{if \IPS\calendar\Date::usesAmPm()}}
											{expression="\IPS\calendar\Date::getTwelveHour( $hour )"}<br><span>{expression="\IPS\calendar\Date::getAmPm( $hour )"}</span>
										{{else}}
											{$hour}<br><span>:00</span>
										{{endif}}
									</h2>
								</div>
								<div class='ipsDataItem_main ipsAreaBackground_light ipsPad'>
									<div class='cCalendarDay_eventList' data-ipsPatchwork data-ipsPatchwork-minColSize='300' data-ipsPatchwork-maxColSize='500'>
										<div data-role='patchworkList'>
											{{foreach $hourEvents as $idx => $event}}
												<div data-role='patchworkItem'>
													{template="eventBlock" app="calendar" group="view" params="$event, $date, true"}
												</div>
											{{endforeach}}
										</div>
									</div>
								</div>
							</li>
						{{endif}}
					{{endforeach}}
				</ol>
			{{else}}
				<div class='ipsPad ipsAreaBackground_light ipsSpacer_bottom'><span class='ipsType_light ipsType_large'>{lang="no_events_today"}</span></div>
			{{endif}}
		</div>

		{{if \count( $birthdays ) }}
			</div>
			<div class='ipsColumn ipsColumn_wide'>
				{{foreach $birthdays AS $bdayDate => $birthday}}
					<div class='ipsBox ipsBox--child'>
						<h2 class='ipsType_sectionTitle'>{lang="birthdays_today" pluralize="$birthdayCount[ $bdayDate ]"}</h2>
						<ul class='ipsPadding ipsDataList ipsDataList_reducedSpacing'>
							{{foreach $birthday AS $member}}
								<li class='ipsDataItem ipsClearfix'>
									<div class='ipsDataItem_main ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
										{template="userPhoto" app="core" group="global" params="$member, 'tiny'"}
										<div>
											{$member->link()|raw}
											{{if $member->bday_year}}<br>
											{lang="member_age" pluralize="$member->age( $date )"}{{endif}}
										</div>
									</div>
								</li>
							{{endforeach}}
							{{if \count($birthday) < $birthdayCount[ $bdayDate ]}}
								<li class='ipsDataItem ipsClearfix ipsAreaBackground_light ipsPad ipsPad_half ipsType_center'>
									<a data-ipsDialog data-ipsDialog-title='{lang="birthdays_today" pluralize="$birthdayCount[ $bdayDate ]"}' data-ipsDialog-size="narrow" href='{{if $thisCalendar}}{url="app=calendar&module=calendar&controller=view&view=day&id={$thisCalendar->_id}&y={$date->year}&m={$date->mon}&d={$date->mday}&show=birthdays" seoTemplate="calendar_calday" seoTitle="$thisCalendar->title_seo"}{{else}}{url="app=calendar&module=calendar&controller=view&view=day&y={$date->year}&m={$date->mon}&d={$date->mday}&show=birthdays" seoTemplate="calendar_day"}{{endif}}'>{lang="birthdays_view_all"}</a>
								</li>
							{{endif}}
						</ul>
					</div>
				{{endforeach}}
			</div>
		</div>
		{{endif}}
	</div>
</div>