<ips:template parameters="$featured, $date" />

{{if \count($featured) }}
	<div class='ipsBox ipsResponsive_pull'>
		<h2 class='ipsType_reset ipsType_sectionTitle'>{lang="featured_events"}</h2>
		<div class='ipsPad'>
			<div class='ipsCarousel ipsClearfix' data-ipsCarousel>
				<div class='ipsCarousel_inner'>
					<ul class='cCalendarCarousel ipsClearfix' data-role="carouselItems">
						{{foreach $featured as $event}}
							<li class='ipsCarousel_item'>
								{template="eventBlock" app="calendar" group="view" params="$event, $date, true, false"}
							</li>
						{{endforeach}}
					</ul>
				</div>
				<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
				<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
				<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
				<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
			</div>
		</div>
	</div>
{{endif}}