<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<div id='elCalendarJump' class='ipsMenu ipsMenu_medium ipsHide'>
	<form accept-charset='utf-8' class="ipsPad ipsForm ipsForm_vertical" method='post' action='{$action}' data-ipsForm>
		<input type="hidden" name="{$id}_submitted" value="1">
		{{foreach $hiddenValues as $k => $v}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endforeach}}
		<ul class='ipsList_reset'>
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{{if $input instanceof \IPS\Helpers\Form\Date}}
						<li class='ipsFieldRow ipsFieldRow_fullWidth'>
							<input type="date" data-control="date" name='{$input->name}' id='{$input->htmlId}' {{if $input->required === TRUE}}required{{endif}} value="{{if $input->defaultValue instanceof \IPS\DateTime}}{$input->defaultValue->format('Y-m-d')}{{endif}}">
						</li>
					{{else}}
						{$input->rowHtml($form)|raw}
					{{endif}}
				{{endforeach}}
			{{endforeach}}
			<li class='ipsFieldRow'>
				<input type="submit" class="ipsButton ipsButton_primary ipsButton_fullWidth ipsButton_small" value="{lang="calendar_jump"}">
			</li>
			<li class='ipsFieldRow'>
				<input type="submit" class="ipsButton ipsButton_link ipsButton_fullWidth ipsButton_small" value="{lang="calendar_jump_today"}" name="goto">
			</li>
		</ul>
	</form>
</div>