<ips:template parameters="" />

<div class='cStaffDirPreview cStaffDirPreview_full'>
	<div class='cStaffDirPreview_block cStaffDirPreview_row'>
		<span class='cStaffDirPreview_photo'></span><br>
		<span class='cStaffDirPreview_title'></span>
		<span class='cStaffDirPreview_text'></span>
	</div>
	<div class='cStaffDirPreview_block cStaffDirPreview_row'>
		<span class='cStaffDirPreview_photo'></span><br>
		<span class='cStaffDirPreview_title'></span>
		<span class='cStaffDirPreview_text'></span>
	</div>
	<div class='cStaffDirPreview_block cStaffDirPreview_row'>
		<span class='cStaffDirPreview_photo'></span><br>
		<span class='cStaffDirPreview_title'></span>
		<span class='cStaffDirPreview_text'></span>
	</div>
</div>