<ips:template parameters="" />

<div class='cStaffDirPreview cStaffDirPreview_blocks'>
	<div class='ipsGrid ipsGrid_collapsePhone'>
		<div class='ipsGrid_span3 ipsType_center cStaffDirPreview_block'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
		</div>
		<div class='ipsGrid_span3 ipsType_center cStaffDirPreview_block'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
		</div>
		<div class='ipsGrid_span3 ipsType_center cStaffDirPreview_block'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
		</div>
		<div class='ipsGrid_span3 ipsType_center cStaffDirPreview_block'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
		</div>
	</div>
</div>