<ips:template parameters="" />

<div class='cStaffDirPreview cStaffDirPreview_full'>
	<div class='ipsGrid ipsGrid_collapsePhone'>
		<div class='ipsGrid_span6 cStaffDirPreview_block cStaffDirPreview_row'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
			<span class='cStaffDirPreview_text'></span>
		</div>
		<div class='ipsGrid_span6 cStaffDirPreview_block cStaffDirPreview_row'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
			<span class='cStaffDirPreview_text'></span>
		</div>
	</div>
	<div class='ipsGrid ipsGrid_collapsePhone'>
		<div class='ipsGrid_span6 cStaffDirPreview_block cStaffDirPreview_row'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
			<span class='cStaffDirPreview_text'></span>
		</div>
		<div class='ipsGrid_span6 cStaffDirPreview_block cStaffDirPreview_row'>
			<span class='cStaffDirPreview_photo'></span><br>
			<span class='cStaffDirPreview_title'></span>
			<span class='cStaffDirPreview_text'></span>
		</div>
	</div>
</div>