<ips:template parameters="$forum, $isSubForum=FALSE, $table=NULL" />
{{if $forum->can('view')}}
{{$lastPost = $forum->lastPost();}}
{{$club = $forum->club();}}
	<li class="cForumRow ipsDataItem ipsDataItem_responsivePhoto {{if \IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsDataItem_unread{{endif}} ipsClearfix" data-forumID="{$forum->_id}">
		<div class="ipsDataItem_icon ipsDataItem_category">
			{{if !$forum->redirect_on}}
			{{if \IPS\forums\Topic::containerUnread( $forum ) AND \IPS\Member::loggedIn()->member_id}}<a href="{{if $isSubForum}}{$forum->url()->setQueryString( array( 'do' => 'markRead', 'return' => $forum->parent_id ) )->csrf()}{{else}}{$forum->url()->setQueryString( 'do', 'markRead' )->csrf()}{{endif}}" data-action='markAsRead' title='{lang="mark_forum_read"}' data-ipsTooltip>{{endif}}
			{{endif}}
				{{if $club}}
					<img src="{{if $club->profile_photo}}{file="$club->profile_photo" extension="core_Clubs"}{{else}}{resource="default_club.png" app="core" location="global"}{{endif}}" alt='' class='ipsItemStatus ipsItemStatus_large {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}'>
				{{elseif $forum->icon}}
					<img src="{file="$forum->icon" extension="forums_Icons"}" alt='' class='ipsItemStatus ipsItemStatus_custom {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}'>
				{{else}}
					{{if $forum->redirect_on}}
						<span class='ipsItemStatus ipsItemStatus_large cForumIcon_redirect {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
							<i class='fa fa-arrow-right'></i>
						</span>
					{{elseif $forum->forums_bitoptions['bw_enable_answers']}}
						<span class='ipsItemStatus ipsItemStatus_large cForumIcon_answers {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
							<i class='fa fa-question'></i>
						</span>
					{{elseif $forum->password}}
						<span class='ipsItemStatus ipsItemStatus_large cForumIcon_password {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
							{{if $forum->loggedInMemberHasPasswordAccess()}}
								<i class='fa fa-unlock'></i>
							{{else}}
								<i class='fa fa-lock'></i>
							{{endif}}
						</span>
					{{else}}
						<span class='ipsItemStatus ipsItemStatus_large cForumIcon_normal {{if !\IPS\forums\Topic::containerUnread( $forum ) && !$forum->redirect_on}}ipsItemStatus_read{{endif}}' {template="formattedInlineStyle" params="$forum" app="core" group="global" location="front"}>
							<i class="fa fa-comments"></i>
						</span>
					{{endif}}
				{{endif}}
			{{if !$forum->redirect_on and \IPS\forums\Topic::containerUnread( $forum ) AND \IPS\Member::loggedIn()->member_id}}
			</a>
			{{endif}}
		</div>
		<div class="ipsDataItem_main">
			<h4 class="ipsDataItem_title ipsType_break">
				{{if $forum->password && !$forum->loggedInMemberHasPasswordAccess()}}
					<a href="{$forum->url()->setQueryString( 'passForm', '1' )}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="forum_requires_password" sprintf="$forum->_title"}'>{$forum->_title}</a>
				{{else}}
					<a href="{$forum->url()}">{{if $club}}{lang="club_node" sprintf="$club->name, $forum->_title"}{{else}}{$forum->_title}{{endif}}</a>
				{{endif}}
				{{if $forum->redirect_on}}
					&nbsp;&nbsp;<span class='ipsType_light ipsType_medium'>({lang="redirect_hits" pluralize="$forum->redirect_hits"})</span>
				{{endif}}
			</h4>
			{{if $forum->hasChildren()}}
				<ul class="ipsDataItem_subList ipsList_inline">
					{{foreach $forum->children() as $subforum}}
						<li class="{{if \IPS\forums\Topic::containerUnread( $subforum )}}ipsDataItem_unread{{endif}}">
							<a href="{$subforum->url()}">{{if \IPS\forums\Topic::containerUnread( $subforum )}}<span class='ipsItemStatus ipsItemStatus_tiny {{if !\IPS\forums\Topic::containerUnread( $subforum ) && !$subforum->redirect_on}}ipsItemStatus_read{{endif}}'><i class="fa fa-circle"></i></span>&nbsp;{{endif}}{$subforum->_title}</a>
						</li>
					{{endforeach}}
				</ul>
			{{endif}}
			{{if $forum->description}}
				{template="richText" group="global" app="core" location="global" params="$forum->description, array('ipsDataItem_meta', 'ipsContained')"}
			{{endif}}
		</div>
		{{if !$forum->redirect_on}}
			<div class="ipsDataItem_stats ipsDataItem_statsLarge">
				{{if $lastPost AND ( $forum->can_view_others OR \IPS\Member::loggedIn()->modPermission('can_read_all_topics') OR ( \is_array( \IPS\Member::loggedIn()->modPermission('forums') ) AND \in_array( $forum->_id, \IPS\Member::loggedIn()->modPermission('forums') ) ))}}
					<dl>
						{{$count = \IPS\forums\Topic::contentCount( $forum, TRUE );}}
						<dt class="ipsDataItem_stats_number">{number="$count" format="short"}</dt>
						<dd class="ipsDataItem_stats_type ipsType_light">{lang="posts_no_number" pluralize="$count" format="short"}</dd>
					</dl>
				{{endif}}
				{{if \IPS\forums\Topic::modPermission( 'unhide', NULL, $forum ) AND $unapprovedContent = $forum->unapprovedContentRecursive() and ( $unapprovedContent['topics'] OR $unapprovedContent['posts'] )}}
					<strong class='ipsType_warning ipsType_medium'>
						<i class='fa fa-warning'></i>
						{{if $unapprovedContent['topics']}}
							<a href='{$forum->url()->setQueryString( array( 'advanced_search_submitted' => 1, 'topic_type' => 'queued_topics' ) )->csrf()}' data-ipsTooltip title='{lang="queued_topics_badge" pluralize="$unapprovedContent['topics']"}' class='ipsType_blendLinks'>{$unapprovedContent['topics']}</a>
						{{else}}
							<span class='ipsType_light'>0</span>
						{{endif}}
						/
						{{if $unapprovedContent['posts']}}
							<a href='{$forum->url()->setQueryString( array( 'advanced_search_submitted' => 1, 'topic_type' => 'queued_posts' ) )->csrf()}' data-ipsTooltip title='{lang="queued_posts_badge" pluralize="$unapprovedContent['posts']"}' class='ipsType_blendLinks'>{$unapprovedContent['posts']}</a>
						{{else}}
							<span class='ipsType_light'>0</span>
						{{endif}}
					</strong>
				{{endif}}
			</div>
			<ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto">
				{{if $lastPost}}
					<li>{template="userPhoto" app="core" group="global" params="$lastPost['author'], 'tiny'"}</li>
					{{if $lastPost['topic_title']}}<li class='ipsDataItem_lastPoster__title'><a href="{$lastPost['topic_url']->setQueryString( 'do', 'getNewComment' )}" title='{$lastPost['topic_title']}'>{$lastPost['topic_title']}</a></li>{{endif}}
					<li class='ipsType_light ipsType_blendLinks'>
						{lang="byline_nodate" htmlsprintf="$lastPost['author']->link()"}, 
						{{if $lastPost['topic_title']}}
							<a href='{$lastPost['topic_url']->setQueryString( 'do', 'getLastComment' )}' title='{lang="get_last_post"}'>{datetime="$lastPost['date']"}</a>
						{{else}}
							{datetime="$lastPost['date']"}
						{{endif}}
					</li>
				{{else}}
					<li class='ipsType_light ipsResponsive_showDesktop'>{{if $forum->password}}{lang="no_forum_posts_password"}{{else}}{lang="no_forum_posts"}{{endif}}</li>
				{{endif}}
			</ul>	
		{{endif}}
		{{if $table and $table->canModerate()}}
			<div class='ipsDataItem_modCheck'>
				<span class='ipsCustomInput'>
					<input type='checkbox' data-role='moderation' name="moderate[{$forum->_id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $forum ) )"}" data-state=''>
					<span></span>
				</span>
			</div>
		{{endif}}
	</li>
{{endif}}