<ips:template parameters="" />

<div class='ipsPageHeader ipsClearfix ipsMargin_bottom cForumHeader ipsHeaderButtons ipsFlex ipsFlex-ai:center ipsFlex-jc:between'>
	<h1 class='ipsType_pageTitle ipsFlex-flex:11 ipsType_break'>
		{lang="forums"}
	</h1>
	{{if \IPS\forums\Forum::canOnAny( 'add' ) }}
		<ul class='ipsToolList ipsToolList_horizontal ipsClearfix sm:ipsPos_none sm:ipsMargin:none ipsFlex-flex:00'>
			<li class='ipsToolList_primaryAction ipsResponsive_hidePhone'>
				<a class="ipsButton ipsButton_medium ipsButton_important" href="{url="app=forums&module=forums&controller=forums&do=add" seoTemplate="topic_non_forum_add_button"}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="select_forum"}'>{lang="start_new_topic"}</a>
			</li>
			{template="viewChange" group="global" app="forums" params=""}
		</ul>
	{{endif}}
</div>
<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hideDesktop ipsResponsive_hideTablet ipsResponsive_block ipsClearfix">
	{template="indexButtons" group="index" app="forums" params="FALSE"}
</ul>

<section>
	<ol class='ipsList_reset cForumList' data-controller='core.global.core.table, forums.front.forum.forumList' data-baseURL=''>
		{{foreach \IPS\forums\Forum::roots() as $category}}
			{{if $category->can('view') && $category->hasChildren()}}
			<li data-categoryID='{$category->_id}' class='cForumRow ipsBox ipsSpacer_bottom ipsResponsive_pull'>
				<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">
					<a href='#' class='ipsPos_right ipsJS_show ipsType_noUnderline cForumToggle' data-action='toggleCategory' data-ipsTooltip title='{lang="toggle_this_category"}'></a>
					<a href='{$category->url()}'>{$category->_title}</a>
				</h2>
				{{if \IPS\forums\Forum::getMemberView() === 'grid'}}
					<div class='ipsPadding' data-role="forums">
						<div class='ipsForumGrid'>
							{{foreach $category->children() as $forum}}
								{template="forumGridItem" group="index" app="forums" params="$forum"}
							{{endforeach}}
						</div>
					</div>
				{{else}}
					<ol class="ipsDataList ipsDataList_large ipsDataList_zebra" data-role="forums">
						{{foreach $category->children() as $forum}}
							{template="forumRow" group="index" app="forums" params="$forum"}
						{{endforeach}}
					</ol>
				{{endif}}
			</li>
			{{endif}}
		{{endforeach}}
		{{if settings.club_nodes_in_apps and $clubForums = \IPS\forums\Forum::clubNodes()}}
			<li data-categoryID='clubs' class='cForumRow ipsBox ipsSpacer_bottom ipsResponsive_pull'>
				<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">
					<a href='#' class='ipsPos_right ipsJS_show ipsType_noUnderline cForumToggle' data-action='toggleCategory' data-ipsTooltip title='{lang="toggle_this_category"}'></a>
					<a href='{url="app=forums&module=forums&controller=forums&do=clubs" seoTemplate="forums_clubs"}'>{lang="club_node_forums"}</a>
				</h2>
				{{if \IPS\forums\Forum::getMemberView() === 'grid'}}
					<div class='ipsAreaBackground ipsPad' data-role="forums">
						<div class='ipsGrid ipsGrid_collapsePhone' data-ipsGrid data-ipsGrid-minItemSize='250' data-ipsGrid-maxItemSize='500' data-ipsGrid-equalHeights='row'>
							{{foreach $clubForums as $forum}}
								{template="forumGridItem" group="index" app="forums" params="$forum"}
							{{endforeach}}
						</div>
					</div>
				{{else}}
					<ol class="ipsDataList ipsDataList_large ipsDataList_zebra" data-role="forums">
						{{foreach $clubForums as $forum}}
							{template="forumRow" group="index" app="forums" params="$forum"}
						{{endforeach}}
					</ol>
				{{endif}}
			</li>
		{{endif}}
	</ol>
</section>