<ips:template parameters="$forumIds, $map" />
<div data-controller="forums.front.forum.flow" class='ipsBox cForumMiniList_wrapper' id='elFluidFormFilters'>
	<div class='ipsSideMenu'>
		{{if \count( \IPS\forums\Forum::roots() ) === 1}}
			<ul class='ipsSideMenu_list cForumMiniList cForumMiniList_singleRoot'>
				{{foreach \IPS\forums\Forum::roots() as $category}}
					{template="simplifiedViewSidebar_children" app="forums" location="front" group="index" params="$forumIds, $category, 0"}
				{{endforeach}}
			</ul>
		{{else}}
			<ul class='ipsSideMenu_list cForumMiniList cForumMiniList_multiRoot'>
				{{foreach \IPS\forums\Forum::roots() as $category}}
					{{if $category->hasChildren()}}
						<li class="" data-category>
							<a href="{$category->url()}" data-parent-id="{$category->_id}" data-node-id="{$category->_id}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>{$category->_title}</a>
							{{if $category->hasChildren()}}
								<ul class='ipsSideMenu_list cForumMiniList'>
									{template="simplifiedViewSidebar_children" app="forums" location="front" group="index" params="$forumIds, $category, 0"}
								</ul>
							{{endif}}
						</li>
					{{endif}}
				{{endforeach}}
				{{if settings.club_nodes_in_apps and $clubForums = \IPS\forums\Forum::clubNodes()}}
					<li class="{{if \in_array( 'clubs', $map )}}cForumMiniList_categorySelected{{endif}}">
						<a href="{url="app=forums&module=forums&controller=index&forumId=clubs" seoTemplate="forums"}" data-parent-id="clubs" data-node-id="clubs" class='{{if \in_array( 'clubs', $map )}}cForumMiniList_selected{{endif}} ipsSideMenu_item ipsTruncate ipsTruncate_line'>{lang="club_node_forums"}</a>
						<ul class='ipsSideMenu_list cForumMiniList'>
							{{foreach $clubForums as $idx => $forum}}
								{{$lastPost = $forum->lastPost();}}
								{{$unread = \IPS\forums\Topic::containerUnread( $forum );}}
								{{$children = $forum->children();}}
								{{if ! $forum->redirect_on and $forum->can('read') }}
									<li class="{{if $children}}cForumMiniList_category{{endif}} {{if isset( $map[ $forum->parent_id ] ) AND \in_array( $forum->_id, $map[ $forum->parent_id ] )}}cForumMiniList_categorySelected{{endif}}">
										<a href="{$forum->url()}" data-parent-id="clubs" data-node-id="{$forum->_id}" data-has-children="{{if $children}}1{{else}}0{{endif}}" class='{{if \in_array( $forum->_id, $forumIds )}}cForumMiniList_selected{{endif}} ipsSideMenu_item {{if !$unread}}cForumMiniList_unread{{endif}}'>
											<span class='cForumMiniList_blob' {{if $forum->feature_color}}style="background-color: {$forum->feature_color}; color: {$forum->_featureTextColor};"{{endif}} {{if $lastPost AND $lastPost['date']}}title="{lang="forum_simple_view_last_post"} {datetime="$lastPost['date']"}" data-ipsTooltip data-ipsTooltip-safe{{endif}}>
												<span></span>
												<i class='fa fa-check'></i>
											</span>
											<span class='cForumMiniList_title ipsTruncate ipsTruncate_line'>
												{{if $unread}}<strong>{{endif}}{lang="club_node" sprintf="$forum->club()->name, $forum->_title"}{{if $unread}}</strong>{{endif}}
											</span>
											<span class='ipsType_small ipsType_light cForumMiniList_count'>{number="\IPS\forums\Topic::contentCount( $forum )" format="short"}</span>
										</a>
									</li>
								{{endif}}
							{{endforeach}}
						</ul>
					</li>
				{{endif}}
			</ul>
		{{endif}}
	</div>
	<div class='ipsResponsive_hideDesktop ipsResponsive_block'>
		<hr class='ipsHr'>
		<a href='#' class='ipsButton ipsButton_fullWidth ipsButton_primary ipsButton_medium' data-action='dialogClose'>{lang="done_forum_filtering"}</a>
	</div>
</div>