<ips:template parameters="$table, $headers, $rows, $quickSearch" />
<div class='ipsBox cForumFluidTable' data-baseurl='{$table->baseUrl}' data-resort='{$table->resortKey}' data-tableID='topics' data-dummyLoading data-controller='core.global.core.table{{if $table->canModerate()}},core.front.core.moderation{{endif}}'>
	{{if $table->title}}
		<h2 class='ipsType_sectionTitle ipsHide {{if !$table->container()->forums_bitoptions['bw_enable_answers']}}ipsType_medium{{endif}} ipsType_reset ipsClear'>{$table->title}</h2>
	{{endif}}

	{{if $table->count > 0}}
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
		{{if $table->canModerate()}}
			<ul class="ipsButtonRow ipsPos_right ipsClearfix">
				<li>
					<a class="ipsJS_show" href="#elCheck_menu" id="elCheck_{$table->uniqueId}" title='{lang="{$table->langPrefix}select_rows_tooltip"}' data-ipsTooltip data-ipsAutoCheck data-ipsAutoCheck-context="#elTable_{$table->uniqueId}" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active">
						<span class="cAutoCheckIcon ipsType_medium"><i class="fa fa-square-o"></i></span> <i class="fa fa-caret-down"></i>
						<span class='ipsNotificationCount' data-role='autoCheckCount'>0</span>
					</a>
					<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="elCheck_{$table->uniqueId}_menu">
						<li class="ipsMenu_title">{lang="{$table->langPrefix}select_rows"}</li>
						<li class="ipsMenu_item" data-ipsMenuValue="all"><a href="#">{lang="all"}</a></li>
						<li class="ipsMenu_item" data-ipsMenuValue="none"><a href="#">{lang="none"}</a></li>
						{{if \count($table->getFilters())}}
							<li class="ipsMenu_sep"><hr></li>
							{{foreach $table->getFilters() as $filter}}
								<li class="ipsMenu_item" data-ipsMenuValue="{$filter}"><a href="#">{lang="$filter"}</a></li>
							{{endforeach}}
						{{endif}}
					</ul>
				</li>
			</ul>
		{{endif}}
		<ul class="ipsButtonRow ipsPos_right ipsClearfix">
			{{if isset( $table->sortOptions ) and !empty( $table->sortOptions ) }}
				<li>
					<a href="#elSortByMenu_menu" id="elSortByMenu_{$table->uniqueId}" data-role='sortButton' data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="sort_by"} <i class="fa fa-caret-down"></i></a>
					<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elSortByMenu_{$table->uniqueId}_menu">
						{{$custom = TRUE;}}
						{{foreach $table->sortOptions as $k => $col}}
							<li class="ipsMenu_item {{if $col === $table->getSortByColumn()}}{{$custom = FALSE;}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="{$col}" data-sortDirection='{$table->getSortDirection( $col )}'><a href="{$table->baseUrl->setQueryString( array( 'filter' => $table->filter, 'sortby' => $col, 'sortdirection' => $table->getSortDirection( $col ) ) )->setPage( 'page', 1 )}">{lang="{$table->langPrefix}sort_{$k}"}</a></li>
						{{endforeach}}
						{{if $table->advancedSearch}}
							<li class="ipsMenu_item {{if $custom}}ipsMenu_itemChecked{{endif}}" data-noSelect="true">
								<a href='{$table->baseUrl->setQueryString( array( 'advancedSearchForm' => '1', 'filter' => $table->filter, 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection ) )}' data-ipsDialog data-ipsDialog-title='{lang="custom_sort"}'>{lang="custom"}</a>
							</li>
						{{endif}}
					</ul>
				</li>
			{{endif}}
			{{if !empty( $table->filters )}}
				<li>
					<a href="#elFilterByMenu_menu" id="elFilterByMenu_{$table->uniqueId}" data-role='tableFilterMenu' data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="filter_by"} <i class="fa fa-caret-down"></i></a>
					<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide' data-role="tableFilterMenu" id='elFilterByMenu_{$table->uniqueId}_menu'>
						<li data-action="tableFilter" data-ipsMenuValue='' class='ipsMenu_item {{if !$table->filter}}ipsMenu_itemChecked{{endif}}'>
							<a href='{$table->baseUrl->setQueryString( array( 'filter' => '', 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection ) )->setPage( 'page', 1 )}'>{lang="{$table->langPrefix}all"}</a>
						</li>
						{{foreach $table->filters as $k => $q}}
							<li data-action="tableFilter" data-ipsMenuValue='{$k}' class='ipsMenu_item {{if $k === $table->filter}}ipsMenu_itemChecked{{endif}}'>
								<a href='{$table->baseUrl->setQueryString( array( 'filter' => $k, 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection) )->setPage( 'page', 1 )}'>{lang="{$table->langPrefix}{$k}"}</a>
							</li>
						{{endforeach}}
					</ul>
				</li>
			{{endif}}
		</ul>

		{{if $table->pages > 1}}
			<div data-role="tablePagination">
				{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
			</div>
		{{endif}}
	</div>
	{{endif}}
	{{if $table->canModerate()}}
		<form action="{$table->baseUrl->csrf()}" method="post" data-role='moderationTools' data-ipsPageAction>
	{{endif}}
		{{if \count( $rows )}}
			<ol class='ipsDataList ipsDataList_zebra ipsClear cForumTopicTable {{foreach $table->classes as $class}}{$class} {{endforeach}}' id='elTable_{$table->uniqueId}' data-role="tableRows">
				{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
			</ol>
		{{else}}
			<div class='ipsType_center ipsPad'>
				<p class='ipsType_large'>{lang="no_topics_in_forum"}</p>
			</div>
		{{endif}}
		{{if $table->canModerate()}}
			<div class="ipsAreaBackground ipsPad ipsClearfix ipsJS_hide" data-role="pageActionOptions">
				<div class="ipsPos_right">
					<select name="modaction" data-role="moderationAction">
						{{if $table->canModerate('unhide')}}
							<option value='approve' data-icon='check-circle'>{lang="approve"}</option>
						{{endif}}
						{{if $table->canModerate('feature') or $table->canModerate('unfeature')}}
							<optgroup label="{lang="feature"}" data-icon='star' data-action='feature'>
								{{if $table->canModerate('feature')}}
									<option value='feature'>{lang="feature"}</option>
								{{endif}}
								{{if $table->canModerate('unhide')}}
									<option value='unfeature'>{lang="unfeature"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('pin') or $table->canModerate('unpin')}}
							<optgroup label="{lang="pin"}" data-icon='thumb-tack' data-action='pin'>
								{{if $table->canModerate('pin')}}
									<option value='pin'>{lang="pin"}</option>
								{{endif}}
								{{if $table->canModerate('unpin')}}
									<option value='unpin'>{lang="unpin"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('hide') or $table->canModerate('unhide')}}
							<optgroup label="{lang="hide"}" data-icon='eye' data-action='hide'>
								{{if $table->canModerate('hide')}}
									<option value='hide'>{lang="hide"}</option>
								{{endif}}
								{{if $table->canModerate('unhide')}}
									<option value='unhide'>{lang="unhide"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('lock') or $table->canModerate('unlock')}}
							<optgroup label="{lang="lock"}" data-icon='lock' data-action='lock'>
								{{if $table->canModerate('lock')}}
									<option value='lock'>{lang="lock"}</option>
								{{endif}}
								{{if $table->canModerate('unlock')}}
									<option value='unlock'>{lang="unlock"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('move')}}
							<option value='move' data-icon='arrow-right'>{lang="move"}</option>
						{{endif}}
						{{if $table->canModerate('split_merge')}}
							<option value='merge' data-icon='level-up'>{lang="merge"}</option>
						{{endif}}
						{{if $table->canModerate('delete')}}
							<option value='delete' data-icon='trash'>{lang="delete"}</option>
						{{endif}}
						{{if $table->savedActions}}
							<optgroup label="{lang="saved_actions"}" data-icon='tasks' data-action='saved_actions'>
								{{foreach $table->savedActions as $k => $v}}
									<option value='savedAction-{$k}'>{$v}</option>
								{{endforeach}}
							</optgroup>
						{{endif}}
					</select>
					<button type="submit" class="ipsButton ipsButton_alternate ipsButton_verySmall">{lang="submit"}</button>
				</div>
			</div>
		</form>
	{{endif}}
	{{if $table->pages > 1}}
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
			<div data-role="tablePagination">
				{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
			</div>
		</div>
	{{endif}}
</div>