<ips:template parameters="$record, $category, $hasModOptions, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />
{{$modOptions = array( 'create_record_state', 'record_publish_date', 'record_expiry_date', 'record_on_homepage', 'record_pinned', 'record_allow_comments', 'record_comment_cutoff' );}}
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}

	{{if $hasModOptions}}
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_fluid'>
	{{endif}}

	<div class='ipsBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="topic_details"}</h2>
		{{if \count( $elements ) > 1}}
			{{if !empty( $errorTabs )}}
				<p class="ipsMessage ipsMessage_error ipsJS_show">{lang="tab_error"}</p>
			{{endif}}
			<div class='ipsTabs ipsTabs_contained ipsClearfix ipsJS_show' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
				<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
				<ul role='tablist'>
					{{foreach $elements as $name => $content}}
						<li>
							<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item" role="tab">
								{lang="$name"}
							</a>
						</li>
					{{endforeach}}
				</ul>
			</div>
			<div id='ipsTabs_content_{$id}' class='ipsTabs_panels ipsTabs_contained'>
				{{foreach $elements as $name => $contents}}
					<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
						
						{{if $hasModOptions && $name == 'topic_mainTab'}}
							<div class='ipsColumns ipsColumns_collapsePhone'>
								<div class='ipsColumn ipsColumn_fluid'>
						{{endif}}
							<ul class='ipsForm ipsForm_vertical'>
								{{foreach $contents as $inputName => $input}}
									{{if !\in_array( $inputName, $modOptions )}}
										{$input|raw}
									{{endif}}
								{{endforeach}}
							</ul>
						{{if $hasModOptions && $name == 'topic_mainTab'}}
								</div>
								<div class='ipsColumn ipsColumn_wide'>
									<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="topic_moderator_options"}</h2>
									<div class='ipsAreaBackground_light ipsPad'>
										<ul class='ipsForm ipsForm_vertical'>
											{{foreach $elements as $collection}}
												{{foreach $collection as $inputName => $input}}
													{{if \in_array( $inputName, $modOptions )}}
														{$input|raw}
													{{endif}}
												{{endforeach}}
											{{endforeach}}
										</ul>
									</div>
								</div>
							</div>
						{{endif}}
					</div>
				{{endforeach}}
			</div>		
		{{else}}
			<div class='ipsPad'>
				{{if $hasModOptions}}
					<div class='ipsColumns ipsColumns_collapsePhone'>
						<div class='ipsColumn ipsColumn_fluid'>
				{{endif}}
					<ul class='ipsForm ipsForm_vertical'>
						{{foreach $elements as $collection}}
							{{foreach $collection as $inputName => $input}}
								{{if !\in_array( $inputName, $modOptions )}}
									{$input|raw}
								{{endif}}
							{{endforeach}}
						{{endforeach}}
					</ul>
				{{if $hasModOptions}}
						</div>
						<div class='ipsColumn ipsColumn_wide'>
							<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="topic_moderator_options"}</h2>
							<div class='ipsAreaBackground_light ipsPad'>
								<ul class='ipsForm ipsForm_vertical'>
									{{foreach $elements as $collection}}
										{{foreach $collection as $inputName => $input}}
											{{if \in_array( $inputName, $modOptions )}}
												{$input|raw}
											{{endif}}
										{{endforeach}}
									{{endforeach}}
								</ul>
							</div>
						</div>
					</div>
				{{endif}}
			</div>
		{{endif}}
		<div class='ipsAreaBackground ipsPad ipsType_center'>
			<button type='submit' class='ipsButton ipsButton_large ipsButton_primary'>{lang="content_record_form_save"}</button>
		</div>
	</div>
</form>