<ips:template parameters="$item, $showContent=FALSE, $otherInfo=NULL" />

<h3 class='ipsRichEmbed_itemTitle ipsTruncate ipsTruncate_line ipsType_blendLinks'>
	<a href='{$item->url( "getPrefComment" )}' title="{$item->mapped('title')}">{$item->mapped('title')}</a>
</h3>
{{if $showContent}}
	<div class='ipsType_richText ipsType_medium' data-truncate='1'>
		{$item->truncated(TRUE)|raw}
	</div>
{{endif}}
{{if $otherInfo}}
	{$otherInfo|raw}
{{endif}}
<ul class='ipsList_inline ipsType_medium ipsType_light ipsSpacer_top ipsSpacer_half'>
	<li class='ipsRichEmbed_commentPhoto'>
		{template="userPhoto" group="global" app="core" params="$item->author(), 'tinier'"}
	</li>
	<li>
		<a href='{$item->url()->setQueryString( 'do', 'getFirstComment' )}'>
			{lang="byline" sprintf="$item->author()->name"} {datetime="$item->mapped('date')"}
		</a>
	</li>
	{{if $item::$commentClass}}
		<li>
			<a href='{$item->url()->setQueryString( 'do', 'getLastComment' )}'>
				{{if $item::$firstCommentRequired}}
					<i class='fa fa-comment'></i> {lang="num_replies" pluralize="$item->mapped('num_comments') - 1"}
				{{else}}
					<i class='fa fa-comment'></i> {lang="num_comments" pluralize="$item->mapped('num_comments')"}
				{{endif}}
			</a>
		</li>
	{{endif}}
</ul>