<ips:template parameters="$item" />

{{if $item->_end_date}}
	<dl class='cCalendarEmbed_dates ipsSpacer_top ipsSpacer_half'>
		<dt class='ipsType_light'>{lang="from"}</dt>
		<dd>
			<time datetime='{expression="$item->_start_date->format( 'Y-m-d' )"}'>
				{$item->_start_date->dayName} {$item->_start_date->mday} {$item->_start_date->monthName} {$item->_start_date->year}{{if !$item->all_day}}, {$item->_start_date->localeTime( FALSE )}{{endif}}
			</time>
		</dd>
		<dt class='ipsType_light'>{lang="until"}</dt>
		<dd>
			<time datetime='{expression="$item->_end_date->format( 'Y-m-d' )"}'>
				{{$sameDay = !( ($item->_start_date->mday != $item->_end_date->mday) or ($item->_start_date->mon != $item->_end_date->mon) or ($item->_start_date->year != $item->_end_date->year) );}}
				{{if !$sameDay}}{$item->_end_date->dayName} {$item->_end_date->mday} {$item->_end_date->monthName} {$item->_end_date->year}{{endif}}{{if !$item->all_day}}{{if !$sameDay}}, {{endif}}{$item->_end_date->localeTime( FALSE )}{{endif}}
			</time>
		</dd>
	</dl>
{{else}}
	<p class='ipsSpacer_top ipsSpacer_half'>
		<time datetime='{expression="$item->_start_date->format( 'Y-m-d' )"}'>
			{$item->_start_date->dayName} {$item->_start_date->mday} {$item->_start_date->monthName} {$item->_start_date->year}{{if !$item->all_day}}, {$item->_start_date->localeTime( FALSE )}{{endif}}
		</time>
	</p>
{{endif}}