<ips:template parameters="$comment, $item, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$comment, $item->mapped('title'), $comment->mapped('date'), $url"}
	<div class='ipsPadding'>
		<div class='ipsRichEmbed_originalItem ipsAreaBackground_reset ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				{{if $item->map( 500, 100 )}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_masthead_small ipsType_center'>
						<a href='{$url}' title='{$item->mapped('title')}'>
							{$item->map( 500, 100 )|raw}
						</a>
					</div>
				{{elseif $item->coverPhoto() && $item->coverPhoto()->file}}
					{{$photo = $item->coverPhoto()->file;}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_masthead_small ipsRichEmbed_mastheadBg ipsType_center'>
						<a href='{$url}' title='{$item->mapped('title')}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $photo->url )"}") '>
							<img src='{$photo->url}' alt='{$item->mapped('title')}' class='ipsHide'>
						</a>
					</div>
				{{endif}}
				<div class='ipsPadding'>
					<div class='ipsPhotoPanel ipsPhotoPanel_small'>
						<span class='cCalendarEmbed_calendar ipsPos_left ipsType_blendLinks'>
							<a href='{$url}'>
								{{$nextOccurrence = $item->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' ) ?: $item->lastOccurrence( 'startDate' );}}
								<time datetime='{$nextOccurrence->mysqlDatetime()}' class='ipsCalendarDate'>
									<span class='ipsCalendarDate_month'>{$nextOccurrence->monthNameShort}</span>
									<span class='ipsCalendarDate_date'>{$nextOccurrence->mday}</span>
								</time>
							</a>
						</span>
						<div>
							{template="embedOriginalItem" group="embed" app="core" params="$item, FALSE, \IPS\Theme::i()->getTemplate( 'global', 'calendar' )->embedEventItemSnippet( $item )"}
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$comment->truncated(TRUE)|raw}
		</div>

		{{if settings.reputation_enabled AND \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) AND \count( $comment->reactions() )}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$comment, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>