<ips:template parameters="$table, $headers, $rows" />
{{if \count( $rows )}}
	{{foreach $rows as $row}}
		<li class="ipsDataItem {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if $row->hidden()}}ipsModerated{{endif}}">
			<div class='ipsDataItem_generic ipsDataItem_size3 ipsPos_top'>
				{{if $row->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )}}
					<time datetime='{$row->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->mysqlDatetime()}' class='ipsCalendarDate ipsCalendarDate_large'>
						<span class='ipsCalendarDate_month'>{$row->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->monthNameShort}</span>
						<span class='ipsCalendarDate_date'>{$row->nextOccurrence( \IPS\calendar\Date::getDate(), 'startDate' )->mday}</span>
					</time>
				{{else}}
					<time datetime='{$row->lastOccurrence( 'startDate' )->mysqlDatetime()}' class='ipsCalendarDate ipsCalendarDate_large'>
						<span class='ipsCalendarDate_month'>{$row->lastOccurrence( 'startDate' )->monthNameShort}</span>
						<span class='ipsCalendarDate_date'>{$row->lastOccurrence( 'startDate' )->mday}</span>
					</time>
				{{endif}}
			</div>
			<div class='ipsDataItem_main'>
				<h4 class='ipsDataItem_title ipsType_sectionHead ipsContained_container'>
					{{if $row->mapped('locked')}}
						<i class="fa fa-lock"></i>
					{{endif}}
					
					{{if $row->mapped('pinned') || $row->mapped('featured') || $row->hidden() === -1 || $row->hidden() === 1}}
						{{if $row->hidden() === -1}}
							<span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{$row->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
						{{elseif $row->hidden() === 1}}
							<span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
						{{endif}}
						{{if $row->mapped('pinned')}}
							<span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
						{{endif}}
						{{if $row->mapped('featured')}}
							<span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
						{{endif}}
					{{endif}}
					
					{{if $row->prefix()}}
						<span>{template="prefix" group="global" app="core" params="$row->prefix( TRUE ), $row->prefix()"}</span>
					{{endif}}
					
					<span class='ipsType_break ipsContained'>
						<a href='{$row->url( "getPrefComment" )}' {{if $row->tableHoverUrl}}data-ipsHover{{endif}}>
							{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}
						</a>
					</span>
				</h4>
				<div class='ipsDataItem_meta ipsType_light ipsType_blendLinks'>
					{$row->eventBlurb()|raw}
				</div>

				{{if $row->rsvp}}
					{{if $attendees = $row->attendees() and isset( $attendees[1][ \IPS\Member::loggedIn()->member_id ] ) }}
						<p class='ipsType_large ipsType_success'><strong><i class='fa fa-check-circle'></i> {lang="you_are_going_to_this"}</strong></p>
					{{else}}
						<p class='ipsType_large ipsType_light ipsFaded'><strong><i class='fa fa-times-circle'></i> {lang="you_are_not_going_to_this"}</strong></p>
					{{endif}}

					{{if \count( $attendees[1] )}}
						<ul class='ipsList_inline'>
							<li class='ipsType_light'>{lang="rsvp_attend_event"}:</li>
							{{foreach $attendees[1] as $idx => $attendee}}
								{{if $idx < 6}}
									<li>{template="userPhoto" group="global" app="core" params="$attendee, 'tiny', NULL, NULL, TRUE"}</li>
								{{endif}}
							{{endforeach}}
							{{if \count( $attendees[1] ) > 5}}
								<li class='ipsType_light'>{lang="and_x_more" pluralize="\count( $attendees[1] ) - 5"}</li>
							{{endif}}
						</ul>
					{{endif}}
				{{endif}}
				{{if \count( $row->tags() )}}
					&nbsp;&nbsp;
					{template="tags" group="global" app="core" params="$row->tags(), true, true"}
				{{endif}}
			</div>
			<div class='ipsDataItem_generic ipsDataItem_size8'>
				{{if $row->container()->allow_reviews}}
					{template="rating" group="global" location="front" app="core" params="'large', $row->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of, $row->memberReviewRating()"}&nbsp;&nbsp; <span class='ipsType_normal ipsType_light'>({lang="num_reviews" pluralize="$row->reviews"})</span>
				{{endif}}
				{{if $row->container()->allow_comments}}
					<p class='ipsType_normal'>
						{{if $row->comments}}
							<a href='{$row->url()->setQueryString( 'tab', 'comments' )->setFragment('replies')}'>
						{{endif}}
						<i class='fa fa-comment'></i> {lang="num_comments" pluralize="$row->comments"}
						{{if $row->comments}}
							</a>
						{{endif}}
					</p>
				{{endif}}
			</div>
			{{if $table->canModerate()}}
				<div class='ipsDataItem_modCheck'>
					{{$idField = $row::$databaseColumnId;}}
					<span class='ipsCustomInput'>
						<input type='checkbox' data-role='moderation' name="moderate[{$row->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{{if $row->tableStates()}}{$row->tableStates()}{{endif}}'>
						<span></span>
					</span>
				</div>
			{{endif}}
		</li>
	{{endforeach}}
{{endif}}