<ips:template parameters="$indexData, $itemData, $nextOccurance, $startDate, $endDate, $allDay, $condensed" />
{{if $condensed}}
	<time datetime='{$nextOccurance->mysqlDatetime()}' class='ipsCalendarDate ipsCalendarDate_small ipsPos_left'>
		<span class='ipsCalendarDate_month'>{$nextOccurance->monthNameShort}</span>
		<span class='ipsCalendarDate_date'>{$nextOccurance->mday}</span>
	</time>
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_narrow ipsColumn--ipsCalendarDate'>
			<time datetime='{$nextOccurance->mysqlDatetime()}' class='ipsCalendarDate ipsCalendarDate_large ipsPos_center'>
				<span class='ipsCalendarDate_month'>{$nextOccurance->monthNameShort}</span>
				<span class='ipsCalendarDate_date'>{$nextOccurance->mday}</span>
			</time>
		</div>
		<div class='ipsColumn ipsColumn_fluid ipsStream_snippetInfo'>
			<strong class='ipsType_normal'>
				<time datetime='{expression="$startDate->format( 'Y-m-d' )"}'>
					{$startDate->dayName} {$startDate->mday} {$startDate->monthName} {$startDate->year}{{if !$allDay}}, {$startDate->localeTime( FALSE )}{{endif}}
				</time>
				{{if $endDate}}
					{lang="until_lc"}
					{{$sameDay = !( ($startDate->mday != $endDate->mday) or ($startDate->mon != $endDate->mon) or ($startDate->year != $endDate->year) );}}
					<time datetime='{expression="$endDate->format( 'Y-m-d' )"}'>
						{{if !$sameDay}}{$endDate->dayName} {$endDate->mday} {$endDate->monthName} {$endDate->year}{{endif}}{{if !$allDay}}{{if !$sameDay}}, {{endif}}{$endDate->localeTime( FALSE )}{{endif}}
					</time>
				{{endif}}
			</strong>

			{{if trim( $indexData['index_content'] ) !== ''}}
				<div class='ipsSpacer_top ipsSpacer_half ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
					{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
				</div>
			{{endif}}
		</div>
	</div>
{{endif}}