<ips:template parameters="$row, $overview, $folders" />
		<li class='ipsDataItem ipsClearfix {{if $row['map_has_unread']}}ipsDataItem_unread{{endif}} cMessage {{if !\IPS\Request::i()->overview}}ipsCursor_pointer{{endif}} {{if $row['mt_id'] == \IPS\Request::i()->id}}cMessage_active ipsDataItem_selected{{endif}}' data-messageid='{$row['map_topic_id']}' data-keyNavBlock data-keyAction='return'>
			<div class='ipsDataItem_icon ipsType_center ipsPos_top sm:ipsPadding:none'>
				<div class='ipsSpacer_bottom ipsSpacer_half'>
					{{if $row['last_message']}}{template="userPhoto" app="core" group="global" params="$row['last_message']->author(), 'tiny'"}{{endif}}
				</div>
				{{if $overview}}
				<span class='ipsCustomInput'>
					<input type='checkbox' data-role='moderation' name="moderate[{$row['map_topic_id']}]" data-actions='delete {{if \is_array($folders) and \count($folders) > 1}}move{{endif}}' data-state>
					<span></span>
				</span>
				{{endif}}
			</div>
			<div class='ipsDataItem_main sm:ipsPadding_left:half'>
				<h4 class='ipsDataItem_title ipsType_normal ipsType_break'>
					{{if $overview}}
						<a href='{url="app=core&module=messaging&controller=messenger&id={$row['mt_id']}" seoTemplate="messenger_convo"}' class='cMessageTitle {{if $row['map_has_unread']}}cMessageTitle_unread{{endif}}' data-role="messageURL">{truncate="$row['mt_title']" length="45"}</a>
					{{else}}
						<a href='{url="app=core&module=messaging&controller=messenger&id={$row['mt_id']}&latest=1" seoTemplate="messenger_convo"}' class='cMessageTitle {{if $row['map_has_unread']}}cMessageTitle_unread{{endif}}' data-role="messageURL">{truncate="$row['mt_title']" length="45"}</a>
					{{endif}}
				</h4>
				<div class='ipsDataItem_meta ipsContained_container ipsMessageRow' data-ipsTruncate data-ipsTruncate-type="remove" data-ipsTruncate-size="1 lines">
					{{if $row['last_message']}}<span class='ipsType_break ipsContained'>{$row['last_message']->truncated( TRUE )|raw}</span>{{endif}}
				</div>
				<span class='ipsType_light ipsType_medium ipsType_blendLinks'>{$row['participants']}</span>
			</div>
			<div class='ipsDataItem_generic ipsDataItem_size2 ipsPos_top ipsType_right'>
				<div class='ipsCommentCount ipsSpacer_top ipsSpacer_half' title="{lang="messenger_message_count" pluralize="$row['mt_replies']"}" data-ipsTooltip>{number="$row['mt_replies']"}</div>
				<p class='ipsType_reset ipsType_medium ipsType_light ipsType_right'>
					<span data-ipsTooltip title="{lang="messenger_started_by" sprintf="\IPS\Member::load( $row['mt_starter_id'] )->name, \IPS\DateTime::ts( $row['mt_start_time'] )->relative()"}{{if $row['mt_start_time'] !== $row['mt_last_post_time'] AND $row['last_message']}} &middot; {lang="messenger_last_reply" sprintf="$row['last_message']->author()->name, \IPS\DateTime::ts( $row['mt_last_post_time'] )->relative()"}{{endif}}">
						{datetime="$row['mt_last_post_time']" short="true" }
					</span>
				</p>
			</div>
		</li>