<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL, $showTitle=TRUE" />

<h3 class='ipsType_reset ipsType_large cStreamForm_title ipsSpacer_top'>{lang="stream_classes_type"}</h3>
<ul class='ipsSideMenu_list ipsSideMenu_withChecks cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' data-ipsSideMenu data-ipsSideMenu-type='check' data-ipsSideMenu-responsive='false' data-filterType='type'>
	<li>
		<a href='#' class='ipsSideMenu_item {{if $elements['']['stream_classes_type']->value == 0}}ipsSideMenu_itemActive{{endif}}' data-ipsMenuValue='__all'>
			<input type="hidden" name="stream_classes[__EMPTY]" value="__EMPTY">
			{lang="stream_all_content"}
		</a>
		{{if member.canAccessModule( \IPS\Application\Module::get( 'core', 'clubs' ) ) and isset( $elements['']['stream_club_select'] )}}			
			<a href='#' class='ipsType_noUnderline cStreamForm_menu' data-ipsTooltip title='{lang="stream_filter_clubs"}' data-role='streamClubs'>
				<i class='fa fa-cog ipsType_large'></i>
				<i class='fa fa-caret-down'></i>
			</a>
			<div class='cStreamForm_nodes ipsHide' id="elStreamClubs">
				<span class='ipsType_light'>{lang="loading"}</span>
			</div>
			<input type="hidden" name="stream_club_select" value="{$elements['']['stream_club_select']->value}">
			<input type="hidden" name="stream_club_filter" value="{{if \is_array( $elements['']['stream_club_filter']->value )}}{expression="implode(',',$elements['']['stream_club_filter']->value)"}{{else}}{$elements['']['stream_club_filter']->value}{{endif}}">
		{{endif}}
		<input type='radio' class='ipsHide' name='stream_classes_type' value='0' {{if $elements['']['stream_classes_type']->value == 0}}checked{{endif}}>
		<input type='radio' class='ipsHide' name='stream_classes_type' value='1' {{if $elements['']['stream_classes_type']->value == 1}}checked{{endif}}>
	</li>
	{{if isset( $elements['']['stream_classes'] )}}
		{{foreach $elements['']['stream_classes']->options['options'] as $type => $lang}}
			<li>
				<a class='ipsSideMenu_item {{if isset( $elements['']['stream_containers_' . str_replace('_pl', '', $lang ) ] ) || isset( $elements['']['stream_classes_' . str_replace('_pl', '', $lang ) ] )}}cStream_withOptions{{endif}} {{if $elements['']['stream_classes_type']->value !== 0 && \in_array( $type, $elements['']['stream_classes']->value ) !== FALSE}}ipsSideMenu_itemActive{{endif}}' data-class='{$type}' data-ipsMenuValue='{expression="str_replace( '_pl', '', $lang )"}'>
					<input type='checkbox' name='stream_classes[{$type}]' value='1' {{if $elements['']['stream_classes_type']->value !== 0 && \in_array( $type, $elements['']['stream_classes']->value ) !== FALSE}}checked{{endif}}> 
					<span class='ipsSideMenu_noCheck'>{lang="$lang"}</span>
				</a>
				{{if \in_array( $type, array_keys( $elements['']['stream_classes']->options['toggles'] ) )}}
					<a href='#' class='ipsType_noUnderline cStreamForm_menu' data-ipsTooltip title='{lang="stream_filter_options" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $lang )"}' data-role='streamContainer' data-class='{$type}' data-contentKey='{expression="str_replace( '_pl', '', $lang )"}'>
						<i class='fa fa-cog ipsType_large'></i>
						<i class='fa fa-caret-down'></i>
					</a>
				{{endif}}
				<div class='cStreamForm_nodes ipsHide'>
					<span class='ipsType_light'>{lang="loading"}</span>
				</div>
			</li>
		{{endforeach}}
	{{endif}}
	{{if ! isset( \IPS\Request::i()->do ) or \IPS\Request::i()->do != 'create' }}
	<li>
		<p class='ipsCenter'><button data-action='applyFilters' title="{lang="stream_apply_tip"}" type='button' class='ipsButton ipsButton_light ipsButton_fullWidth ipsButton_small ipsButton_disabled'>{lang="stream_apply"}</button></p>
	</li>
	{{endif}}
</ul>
<hr class='ipsHr ipsSpacer_both ipsResponsive_showPhone ipsResponsive_block'>
{{foreach $elements['']['stream_classes']->options['options'] as $type => $lang}}
	{template="filterFormContentType" group="streams" app="core" params="$elements, str_replace('_pl', '', $lang ), $type, ( $elements['']['stream_classes_type']->value !== 0 && $elements['']['stream_classes']->value == $type ), $elements"}
{{endforeach}}
<div class='ipsMenu ipsMenu_wide ipsPad ipsHide' data-role="streamContainer" data-contentKey="clubs" data-className="clubs" id='elMenu_clubFilter_menu'>
</div>