<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<div class='ipsGrid ipsGrid_collapsePhone'>
	<div class='ipsGrid_span4'>
		<h3 class='ipsType_reset ipsType_large cStreamForm_title'>{lang="stream_include_comments"}</h3>
		<ul class='ipsSideMenu_list ipsSideMenu_withRadios cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' data-ipsSideMenu data-ipsSideMenu-type='radio' data-ipsSideMenu-responsive='false'>
			{{foreach $elements['']['stream_include_comments']->options['options'] as $k => $v}}
				<li>
					{template="filterFormRadio" group="streams" app="core" params="$k, $v, 'stream_include_comments', $elements['']['stream_include_comments']->value, $elements['']['stream_include_comments']->required, $elements['']['stream_include_comments']->options['options'], $elements['']['stream_include_comments']->options['disabled']"}
				</li>
			{{endforeach}}
		</ul>
		<hr class='ipsHr ipsSpacer_both ipsSpacer_double ipsResponsive_hidePhone'>
		<hr class='ipsHr ipsSpacer_both ipsResponsive_showPhone ipsResponsive_block'>
		{template="filterFormShowMe" group="streams" params="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class, $attributes, $sidebar, $form"}
	</div>
	<div class='ipsGrid_span8'>
		{{if isset( $elements['']['stream_tags'] )}}
			{template="filterFormTags" group="streams" app="core" params="$elements['']['stream_tags']"}
			<hr class='ipsHr ipsSpacer_bottom ipsSpacer_double ipsResponsive_hidePhone'>
			<hr class='ipsHr ipsSpacer_bottom ipsResponsive_showPhone ipsResponsive_block'>
		{{endif}}
		<div class='ipsGrid ipsGrid_collapsePhone'>
			<div class='ipsGrid_span6'>
				<h3 class='ipsType_reset ipsType_large cStreamForm_title'>{lang="stream_read"}</h3>
				<ul class='ipsSideMenu_list ipsSideMenu_withRadios cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' data-ipsSideMenu data-ipsSideMenu-type='radio' data-ipsSideMenu-responsive='false' data-filterType='read'>
					{{foreach $elements['']['stream_read']->options['options'] as $k => $v}}
						<li>
							{template="filterFormRadio" group="streams" app="core" params="$k, $v, 'stream_read', $elements['']['stream_read']->value, $elements['']['stream_read']->required, $elements['']['stream_read']->options['options'], $elements['']['stream_read']->options['disabled']"}
						</li>
					{{endforeach}}
				</ul>
				<hr class='ipsHr ipsSpacer_both ipsSpacer_double ipsResponsive_hidePhone'>
				<hr class='ipsHr ipsSpacer_both ipsResponsive_showPhone ipsResponsive_block'>
				<h3 class='ipsType_reset ipsType_large cStreamForm_title'>{lang="stream_ownership"}</h3>
				{{if isset( $elements['']['stream_ownership'] )}}
				<ul class='ipsSideMenu_list ipsSideMenu_withRadios cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' role="radiogroup" data-ipsSideMenu data-ipsSideMenu-type='radio' data-ipsSideMenu-responsive='false' data-filterType='ownership'>
					{{foreach $elements['']['stream_ownership']->options['options'] as $k => $v}}
					<li>
						{template="filterFormRadio" group="streams" app="core" params="$k, $v, 'stream_ownership', $elements['']['stream_ownership']->value, $elements['']['stream_ownership']->required, $elements['']['stream_ownership']->options['options'], $elements['']['stream_ownership']->options['disabled']"}
					</li>
					{{endforeach}}
					{template="filterFormOwnership" group="streams" params="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class, $attributes, $sidebar, $form"}
				</ul>
				{{endif}}
				<hr class='ipsHr ipsSpacer_both ipsSpacer_double ipsResponsive_hidePhone'>
				<hr class='ipsHr ipsSpacer_both ipsResponsive_showPhone ipsResponsive_block'>
				<h3 class='ipsType_reset ipsType_large cStreamForm_title'>{lang="stream_default_view"}</h3>
				{{if isset( $elements['']['stream_default_view'] )}}
				<ul class='ipsSideMenu_list ipsSideMenu_withRadios cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' role="radiogroup" data-ipsSideMenu data-ipsSideMenu-type='radio' data-ipsSideMenu-responsive='false' data-filterType='defaultview'>
					{{foreach $elements['']['stream_default_view']->options['options'] as $k => $v}}
					<li>
						{template="filterFormRadio" group="streams" app="core" params="$k, $v, 'stream_default_view', $elements['']['stream_default_view']->value, $elements['']['stream_default_view']->required, $elements['']['stream_default_view']->options['options'], $elements['']['stream_default_view']->options['disabled']"}
					</li>
					{{endforeach}}
				</ul>
				{{endif}}
				<hr class='ipsHr ipsSpacer_both ipsResponsive_showPhone ipsResponsive_block'>
			</div>
			<div class='ipsGrid_span6'>
				{{if isset( $elements['']['stream_follow'] )}}
					<h3 class='ipsType_reset ipsType_large cStreamForm_title'>{lang="stream_follow"}</h3>
					<ul class='ipsSideMenu_list ipsSideMenu_withRadios cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' data-ipsSideMenu data-ipsSideMenu-type='radio' data-ipsSideMenu-responsive='false' data-filterType='follow'>
						{{foreach $elements['']['stream_follow']->options['options'] as $k => $v}}
							<li>
								{template="filterFormRadio" group="streams" app="core" params="$k, $v, 'stream_follow', $elements['']['stream_follow']->value, $elements['']['stream_follow']->required, $elements['']['stream_follow']->options['options'], $elements['']['stream_follow']->options['disabled'], ( $k == 'followed' )"}
								{{if $k == 'followed'}}
									<a class='ipsType_noUnderline cStreamForm_menu' data-ipsTooltip title='' id='elMenu_followOptions' data-ipsMenu data-ipsMenu-activeClass='cStreamForm_menuActive' data-ipsMenu-closeOnClick='false' data-ipsMenu-appendTo='#elStreamFilterForm'>
										<i class='fa fa-cog ipsType_large'></i>
										<i class='fa fa-caret-down'></i>
									</a>
								{{endif}}
							</li>
						{{endforeach}}
					</ul>
					{template="filterFormFollowStatus" group="streams" params="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class, $attributes, $sidebar, $form"}
				{{endif}}
				<hr class='ipsHr ipsSpacer_both ipsSpacer_double ipsResponsive_hidePhone'>
				<hr class='ipsHr ipsSpacer_both ipsResponsive_showPhone ipsResponsive_block'>
				<h3 class='ipsType_reset ipsType_large cStreamForm_title'>{lang="stream_date_type"}</h3>
				{{if isset( $elements['']['stream_date_type'] )}}
					<ul class='ipsSideMenu_list ipsSideMenu_withRadios cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' data-ipsSideMenu data-ipsSideMenu-type='radio' data-ipsSideMenu-responsive='false' data-filterType='date'>
						{{foreach $elements['']['stream_date_type']->options['options'] as $k => $v}}
							<li>
								{template="filterFormRadio" group="streams" app="core" params="$k, $v, 'stream_date_type', $elements['']['stream_date_type']->value, $elements['']['stream_date_type']->required, $elements['']['stream_date_type']->options['options'], $elements['']['stream_date_type']->options['disabled']"}
							</li>
						{{endforeach}}
						{template="filterFormTimePeriod" group="streams" params="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class, $attributes, $sidebar, $form"}
					</ul>
				{{endif}}
			</div>
		</div>
	</div>
</div>