<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL, $showTitle=TRUE" />
{{if isset( $elements['']['stream_follow'] )}}
	<div id='elMenu_followOptions_menu' class='ipsMenu ipsMenu_wide ipsPad ipsHide'>
		<ul class='ipsSideMenu_list ipsSideMenu_withChecks cStreamForm_list ipsType_normal ipsSpacer_top ipsSpacer_half' data-ipsSideMenu data-ipsSideMenu-type='check' data-ipsSideMenu-responsive='false' data-filterType='followed'>
		{{foreach $elements['']['stream_followed_types']->options['options'] as $type => $lang}}
			<li>
				<a href='#' class='ipsSideMenu_item {{if $elements['']['stream_followed_types']->value !== 0 && \in_array( $type, $elements['']['stream_followed_types']->value ) !== FALSE}}ipsSideMenu_itemActive{{endif}}' data-ipsMenuValue='{$type}'>
					<input type='checkbox' name='stream_followed_types[{$type}]' value='1' {{if $elements['']['stream_followed_types']->value !== 0 && \in_array( $type, $elements['']['stream_followed_types']->value ) !== FALSE}}checked{{endif}}> 
					{lang="$lang"}
				</a>
			</li>
		{{endforeach}}
		</ul>
	</div>
{{endif}}
			