<ips:template parameters="$waitUntil" />
<div id="elGoogleAuthenticator" data-controller="core.global.core.googleAuth" data-waitUntil="{$waitUntil}">
	<div class="ipsPad ipsType_normal ipsType_richText ipsType_center">
		{lang="google_mfa_auth"}
	</div>
	<ul class="ipsList_reset ipsPad ipsClearfix ipsAreaBackground" data-role="codeInput">
		<li class="ipsFieldRow ipsClearfix " id="google_authenticator_form_google_authenticator_setup_code">
			<div class="ipsFieldRow_content">
				<input type="text" name="google_authenticator_auth_code" value="" class="{{if request.google_authenticator_auth_code}}ipsField_error{{endif}}" autocomplete="one-time-code" >
				{{if request.google_authenticator_auth_code}}
					<p class="ipsType_warning">{lang="google_mfa_invalid_code"}</p>
				{{endif}}
			</div>
		</li>
		<li>
			<button type='submit' class='ipsButton ipsButton_primary ipsButton_fullWidth ipsButton_medium'>
				<i class='fa fa-lock'></i> &nbsp;{lang="google_submit_code"}
			</button>
		</li>
	</ul>
	<div class="ipsType_center ipsHide" data-role="codeWaiting">
		<div class="ipsProgressBar ipsProgressBar_animated">
			<div class="ipsProgressBar_progress" data-role="codeWaitingProgress"></div>
		</div>
		<p class="ipsType_small">{lang="google_wait_for_code"}</p>
	</div>
</div>