<ips:template parameters="$method" />

<button type="submit" name="_processLogin" value="{$method->id}" class='ipsButton ipsButton_verySmall ipsButton_fullWidth ipsSocial {$method->buttonClass()}' style="background-color: {$method->buttonColor()}">
	{{if $icon = $method->buttonIcon()}}
		<span class='ipsSocial_icon'>
			{{if \is_string( $icon )}}
				<i class='fa fa-{$method->buttonIcon()}'></i>
			{{else}}
				<img src="{$icon->url}">
			{{endif}}
		</span>
		<span class='ipsSocial_text'>{lang="$method->buttonText()"}</span>
	{{else}}
		{lang="$method->buttonText()"}
	{{endif}}
</button>