<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<input type="hidden" name="{$id}_submitted" value="1">
{{foreach $hiddenValues as $k => $v}}
	<input type="hidden" name="{$k}" value="{$v}">
{{endforeach}}
<ul class='ipsList_reset'>
	{{foreach $elements as $collection}}
		{{foreach $collection as $input}}
			{{if $input instanceof \IPS\Helpers\Form\Password}}
				{{if $input instanceof \IPS\Helpers\Form\Password}}
					<li class='ipsFieldRow ipsClearfix {{if $input->error}}ipsFieldRow_error{{endif}}' {{if $input->htmlId}}id="{$input->htmlId}"{{endif}}>
						<label class='ipsFieldRow_label' for='{$input->htmlId}'>
							{lang="$input->name"} {{if $input->required}}<span class='ipsFieldRow_required'>{lang="required"}</span>{{endif}}
						</label>
						<div class='ipsFieldRow_content'>
							{$input->html()|raw}
							{{if settings.allow_forgot_password != 'disabled'}}
								{{if settings.allow_forgot_password == 'redirect'}}
									<a href='{expression="\IPS\Settings::i()->allow_forgot_password_target"}' target="_blank" rel="noopener" class="ipsType_small">
								{{else}}
									<a href='{url="app=core&module=system&controller=lostpass" seoTemplate="lostpassword"}' data-ipsDialog data-ipsDialog-title='{lang="forgotten_password"}' class="ipsType_small">
								{{endif}}
								{lang="forgotten_password"}</a>
							{{endif}}
							{{if $input->error}}
								<br>
								<span class="ipsType_warning">{lang="$input->error"}</span>
							{{endif}}
						</div>
					</li>
				{{endif}}
			{{else}}
				{$input->rowHtml($form)|raw}
			{{endif}}
		{{endforeach}}
	{{endforeach}}
</ul>