<ips:template parameters="$item" />
<!--{$item->id}-->
{{$photoCount = $item->imageObjects() ? \count( $item->imageObjects() ) : 0;}}
{{$staff = \IPS\Member::load( $item->added_by );}}
{{$itemUrl = ( $item->object() instanceof \IPS\Content\Item ) ? $item->object()->url( "getPrefComment" ) : $item->object()->url();}}
<div data-role='patchworkItem'>
	<div class='ipsBox ipsClearfix cPromoted' data-ipsLazyLoad>
		{{if $photoCount}}
			{{$firstPhoto = $item->imageObjects()[0];}}
			<a href='{$itemUrl}' class='ipsAreaBackground_dark cPromotedHeader' {{if settings.lazy_load_enabled}}data-background-src='{backgroundimage="$firstPhoto->url"}'{{else}}style='background-image: url({backgroundimage="$firstPhoto->url"})'{{endif}}>
				<img {{if settings.lazy_load_enabled}}src='{expression="\IPS\Text\Parser::blankImage()"}' data-{{endif}}src='{$firstPhoto->url}' class='ipsHide' alt='{$item->ourPicksTitle}'>
			</a>
		{{endif}}
		{{if $photoCount > 1}}
			<ul class='ipsGrid cPromotedImages ipsClearfix ipsAreaBackground_light' data-ipsGrid data-ipsGrid-minItemSize='60' data-ipsGrid-maxItemSize='100'>
				{{foreach $item->imageObjects() as $file}}
					<li class='ipsGrid_span4'>
						<a href='{$file->url}' {{if settings.lazy_load_enabled}}data-background-src='{backgroundimage="$file->url"}'{{else}}style='background-image: url({backgroundimage="$file->url"})'{{endif}} data-ipsLightbox data-ipsLightbox-group='g{$item->id}'>
							<img {{if settings.lazy_load_enabled}}src='{expression="\IPS\Text\Parser::blankImage()"}' data-{{endif}}src='{$file->url}' alt='' class='ipsHide'>
						</a>
					</li>
				{{endforeach}}
			</ul>
		{{endif}}

		<div class='ipsPadding'>
			<h2 class='ipsType_reset ipsType_large ipsType_blendLinks ipsType_break cPromotedTitle'>
				{{if $item->objectIsUnread}}
					{{if $item->object() instanceof \IPS\Content\Item}}
						<a href='{$item->object()->url( 'getNewComment' )}' title='{lang="first_unread_post"}' data-ipsTooltip>
					{{elseif $item->object() instanceof \IPS\Content\Comment}}
						<a href='{$item->object()->item()->url( 'getNewComment' )}' title='{lang="first_unread_post"}' data-ipsTooltip>
					{{else}}
						<a href="{$item->object()->url()}">
					{{endif}}
						<span class='ipsItemStatus'><i class="fa fa-circle"></i></span>
					</a>
				{{endif}}
				<a href="{$itemUrl}">{$item->ourPicksTitle}</a>
			</h2>
			<p class='ipsType_reset ipsType_light ipsType_medium ipsType_blendLinks'>
				{$item->objectMetaDescription|raw}
			</p>
			{{if $text = $item->getText('internal', true)}}
				<div class="ipsType_richText ipsType_medium ipsSpacer_both">{$text|raw}</div>
			{{endif}}

			<ul class='ipsList_inline ipsType_light'>
				
				{{if $item->objectReactionClass AND \IPS\IPS::classUsesTrait( $item->objectReactionClass, 'IPS\Content\Reactable' ) and settings.reputation_enabled}}
					<li>{template="reactionOverview" group="global" app="core" params="$item->objectReactionClass, FALSE"}</li>
				{{endif}}
				
				{{if $counts = $item->objectDataCount}}
					<li><i class='fa fa-comment'></i> {$counts['words']}</li>
				{{endif}}
			</ul>

			<hr class='ipsHr'>

			<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsType_blendLinks ipsType_light'>
				{template="userPhoto" group="global" app="core" params="$staff, 'tiny'"}
				<div>
					{{if $item->sent && \count( $item->share_to ) > 1}}
						<ul class='ipsList_inline cPromotedNetworks'>
							{{foreach $item->share_to as $service}}
								{{if $service == 'internal'}}
									{{continue;}}
								{{endif}}
								{{if $url = $item->getPublishedUrl( $service )}}
									{{$sharer = $item->getPromoter( $service );}}
									<li class='ipsPos_right'>
										<a href='{$url}' class='cShareLink cShareLink_{$service}' data-ipsTooltip title='{lang="promote_shared_on" sprintf="$sharer->key"}'>
											<i class='fa fa-{$sharer::$icon}'></i>
										</a>
									</li>
								{{endif}}
							{{endforeach}}
						</ul>
					{{endif}}
					<h3 class='ipsType_minorHeading'>{lang="promoted_by"}</h3>
					{template="userLink" group="global" app="core" params="$staff"}, {datetime="$item->sent"}
				</div>
			</div>
		</div>
	</div>
</div>