<ips:template parameters="$table, $headers, $rows, $quickSearch" />
<div class='ipsPageHeader ipsClearfix ipsType_center ipsBox ipsPadding:double sm:ipsPadding ipsResponsive_pull'>
	<h1 class='ipsType_veryLarge ipsMargin:none ipsMargin_bottom:half'>{lang="promote_table_header"}</h1>
	<p class='ipsType_reset ipsType_light ipsType_large'>{lang="promote_table_header_desc"}</p>
</div>

{{if $table->pages > 1}}
<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear ipsSpacer_bottom">
	<div data-role="tablePagination">
		{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
	</div>
</div>
{{endif}}

{{if \is_array( $rows ) AND \count( $rows )}}
	<div class='ipsClear {{foreach $table->classes as $class}}{$class} {{endforeach}}' id='elTable_{$table->uniqueId}' data-role="tableRows" data-ipsPatchwork>
		<div data-role='patchworkList'>
			<div class='ipsGrid'>
				<div class='ipsGrid_span4'>
					{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
				</div>
			</div>
		</div>
	</div>
{{else}}
	<div class='ipsType_center'>
		<p class='ipsType_large'>{lang="promote_table_none"}</p>
	</div>
{{endif}}

{{if $table->pages > 1}}
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear ipsSpacer_top">
		<div data-role="tablePagination">
			{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
		</div>
	</div>
{{endif}}