<ips:template parameters="$table, $headers, $rows" />
{{if \count( $rows )}} 
	{{foreach $rows as $item}}
		{{$sent = $item->sent ? true : false;}}
		<!--{$item->id}-->
		<li class='ipsDataItem {{if $item->scheduled > time()}}ipsDataItem_unread{{endif}} {{if $item->failed}}ipsDataItem_error{{endif}} ipsFlex ipsPadding sm:ipsPadding:half' itemprop="itemListElement">
			<div class='ipsFlex-flex:00 ipsMargin_right:half'>
				{template="userPhoto" app="core" group="global" params="$item->author(), 'tiny'"}
			</div>
			<div class='ipsFlex-flex:11'>
				<div class='ipsFlex ipsFlex-ai:center ipsGap:4 sm:ipsFlex-fd:column sm:ipsFlex-ai:start'>
					<div class='ipsFlex-flex:11'>
						{{if $item->failed and $item->failed < 4}}
							<span class='ipsType_large'>
								<i class="fa fa-exclamation-triangle" data-ipsToolTip title="{lang="promote_failed_count" pluralize="$item->failed"}"></i>
							</span>
						{{elseif $item->failed and $item->failed > 3}}
							<span class='ipsType_large'>
								<i class="fa fa-exclamation-triangle ipsType_negative" data-ipsToolTip title="{lang="promote_failed_totally"}"></i>
							</span>
						{{elseif $item->scheduled > time()}}
							<span class='ipsType_large'>
								<i class="fa fa-circle"></i>
							</span>
							<strong>
						{{endif}}
								<a href="{$item->object()->url()}" class='ipsDataItem_title ipsType_break {{if $item->failed and $item->failed > 3}}ipsType_light{{endif}}'>{$item->objectTitle}</a>
						{{if $item->scheduled > time()}}
							</strong>
						{{endif}}
						<div>
							{{if $item->scheduled > time()}}
								<span class="ipsType_light">{lang="promote_time_scheduled"} {$item->scheduledDateTime()->html()|raw} {$item->scheduledDateTime()->localeTime(FALSE)|raw}</span>
							{{elseif $item->failed and $item->failed < 4}}
								<span class="ipsType_light">{lang="promote_time_failed_resend"} {{if $item->scheduled < time()}}{lang="promote_time_failed_resend_soon"}{{else}}{datetime="$item->scheduled"}{{endif}}</span>
							{{elseif $item->failed and $item->failed > 3}}
								<span class="ipsType_light">{lang="promote_failed_totally_description"}</span>
							{{elseif $sent}}
								<span class="ipsType_light">
									{lang="promote_time_sent"} {datetime="$item->sent"}
									&middot; <a href="{url="app=core&module=promote&controller=promote&do=history&promote_id={$item->id}" seoTemplate="promote_history"}" data-ipsDialog-size="narrow" data-ipsDialog data-ipsDialog-title="{lang="promote_view_history"}">{lang="promote_view_history"}</a>
								</span>
							{{else}}
								<span class="ipsType_light">{lang="promote_time_sending_soon"}</span>
							{{endif}}
							{{$photoCount = ( $item->imageObjects() !== NULL ) ? \count( $item->imageObjects() ) : 0;}}
							{{if $photoCount}}
								&nbsp; <span class="ipsType_light"><i class="fa fa-photo"></i> {lang="promote_photo_count" pluralize="$photoCount"}</span>
							{{endif}}
						</div>
					</div>
					<div class='ipsFlex-flex:00'>
						<div class='ipsFlex ipsGap:4'>
							{{if $item->scheduled > time() or ! $sent}}
								<div>
									<div class='ipsFlex ipsGap:1'>
										{{if ! $sent}}
											<a href="{url="app=core&module=promote&controller=promote&do=delete&promote_id={$item->id}" seoTemplate="promote_manage" csrf="true"}" class="ipsButton ipsButton_verySmall ipsButton_light ipsButton_narrow ipsPos_right" data-ipsToolTip title="{lang="delete"}"><i class="fa fa-times-circle"></i></a>
										{{endif}}
										{{if $item->scheduled > time()}}
											<a href="{url="app=core&module=promote&controller=promote&do=manage&promote_id={$item->id}" seoTemplate="promote"}" data-action="edit" data-ipsDialog ipsDialog-title="{lang="promote_social_button"}" class="ipsButton ipsButton_verySmall ipsButton_light ipsButton_narrow ipsPos_right"><i class="fa fa-pencil"></i></a>
										{{endif}}
									</div>
								</div>
							{{elseif $sent}}
								<div class='ipsFlex-flex:10'>
									<div class='ipsFlex ipsGap:1'>
										{{foreach $item->share_to as $service}}
											{{if $url = $item->getPublishedUrl( $service )}}
												{{$sharer = $item->getPromoter( $service );}}
												{{if !$item->serviceFailed( $service )}}
													<a href="{$url}" class="cShareLink cShareLink_{$service}" title='{lang="promote_shared_on" sprintf="$sharer->key"}' data-ipsTooltip><i class="fa fa-{$sharer::$icon}"></i></a>
												{{else}}
													<span class="cShareLink cShareLink_{$service} cShareLink--failed" title='{lang="promote_service_failed"}' data-ipsTooltip><i class="fa fa-{$sharer::$icon}"></i></span>
												{{endif}}												
											{{endif}}
										{{endforeach}}
									</div>
								</div>
								{{$internalText = $item->getText('internal');}}
								<div class="ipsFlex-flex:10 {{if $internalText}}cPromoteModCP_edit{{endif}}">
									<div class='ipsFlex ipsGap:1'>
										<a href="{url="app=core&module=promote&controller=promote&do=delete&promote_id={$item->id}" seoTemplate="promote_manage" csrf="true"}" data-action="delete" class="ipsButton ipsButton_verySmall ipsButton_light ipsButton_narrow" data-ipsToolTip title="{lang="delete"}"><i class="fa fa-times-circle"></i></a>
										{{if $internalText}}
											<a href="{url="app=core&module=promote&controller=promote&do=edit&promote_id={$item->id}" seoTemplate="promote_manage" csrf="true"}" data-ipsDialog data-ipsDialog-title="{lang="edit"}" data-action="edit" class="ipsButton ipsButton_verySmall ipsButton_light ipsButton_narrow" data-ipsToolTip title="{lang="edit"}"><i class="fa fa-pencil"></i></a>
										{{endif}}
									</div>
								</div>
							{{endif}}
						</div>
					</div>
				</div>
			</div>		
		</li>
	{{endforeach}}
{{endif}}
