<ips:template parameters="$name, $value='', $required, $maxlength=NULL, $disabled=FALSE, $class='', $placeholder='', $tags=array(), $mode='htmlmixed', $id=NULL, $height='300px', $preview=NULL, $tagLinks=array(), $tagSource=NULL" />
{{if !empty( $tags ) OR $tagSource !== NULL}}
<div class='ipsColumns ipsColumns_collapseTablet' data-controller='core.global.editor.customtags' data-tagFieldType='codemirror' data-tagFieldID='elCodemirror_{{if $id}}{$id}{{else}}{$name}{{endif}}' {{if $tagSource}}data-tagSource='{$tagSource}'{{endif}}>
	<div class='ipsColumn_fluid ipsColumn'>
{{endif}}
<div class='ipsAreaBackground ipsPad_half ipsClearfix' data-role="editor" {{if $preview}}data-controller="core.global.editor.codePreview" data-name="{$name}" data-preview-url="{$preview}"{{endif}}>
	<textarea
	name="{$name}"
	id='elCodemirror_{{if $id}}{$id}{{else}}{$name}{{endif}}'
	value="{expression="htmlentities( $value, ENT_DISALLOWED, 'UTF-8', TRUE )"}"
	class="ipsField_fullWidth {$class}"
	{{if $maxlength !== NULL}}maxlength="{$maxlength}"{{endif}}
	{{if $required === TRUE}}aria-required='true'{{endif}}
	{{if $disabled}}disabled aria-disabled='true'{{endif}}
	{{if $placeholder}}placeholder="{$placeholder}"{{endif}}
	data-control="codemirror"
	data-mode="{$mode}"
	{{if $height}}data-height="{$height}"{{endif}}
>{$value}</textarea>
	{{if $preview}}
		<button type="button" data-action="preview" data-ipsDialog data-ipsDialog-content="#{$name}_preview" class="ipsButton ipsButton_veryLight ipsSpacer_top ipsButton_verySmall ipsPos_right ipsJs_hide"><i class="fa fa-search"></i> {lang="preview"}</button>
		<div id="{$name}_preview" class="ipsHide ipsDialog_loading"></div>
	{{endif}}
</div>

{{if !empty( $tags ) OR $tagSource}}
	</div>
	<div class='ipsColumn_medium ipsColumn ipsAreaBackground_light ipsComposeArea_sidebar {{if !isset( \IPS\Request::i()->cookie['tagSidebar'] )}}ipsComposeArea_sidebarOpen{{else}}ipsComposeArea_sidebarClosed{{endif}}' data-codemirrorid='elCodemirror_{{if $id}}{$id}{{else}}{$name}{{endif}}'>
		<a href='#' data-action='tagsToggle' data-ipsTooltip data-ipsTooltip-label="{lang="toggle_sidebar"}">{lang="toggle_sidebar"}</a>
		<h3 class='ipsAreaBackground ipsPad_half ipsType_reset' data-role='tagsHeader'>{lang="editor_tags"}</h3>
		<ul class='ipsList_reset ipsScrollbar' data-role='tagsList'>
		{{if !empty( $tags )}}
			{template="editorTags" app="core" location="global" group="forms" params="$tags, $tagLinks"}
		{{endif}}
		</ul>
	</div>
</div>
{{endif}}