<ips:template parameters="$name, $value, $required, $min=NULL, $max=NULL, $disabled=FALSE, $time=FALSE, $unlimited=NULL, $unlimitedLang=NULL, $unlimitedName=NULL, $toggles=array(), $toggleOn=TRUE, $class='ipsField_short', $placeholder=NULL" />
<input
	type="date"
	name="{$name}"
	{{if $unlimited === NULL or $value !== $unlimited}}value="{{if $value instanceof \IPS\DateTime}}{$value->format('Y-m-d')}{{else}}{$value}{{endif}}" data-preferredFormat="{{if $value instanceof \IPS\DateTime}}{$value->localeDate()}{{else}}{$value}{{endif}}"{{endif}}
	{{if $required === TRUE}}aria-required='true'{{endif}}
	{{if $min !== NULL}}min="{$min}"{{endif}}
	{{if $max !== NULL}}max="{$max}"{{endif}}
	{{if $disabled}}disabled aria-disabled='true'{{endif}}
	class="{$class}"
	data-control="date"
>
{{if $time}}
<input name="{$time}" type="time" size="12" class="ipsField_short" placeholder="{lang="_time_format_hhmm"}" step='60' min='00:00' value="{{if $value instanceof \IPS\DateTime}}{$value->format('H:i')}{{endif}}" {{if $disabled}}disabled aria-disabled='true'{{endif}}>
{{endif}}
{{if $unlimited !== NULL and ( !$disabled or $unlimited === $value )}}
	&nbsp;
	{lang="or"}
	&nbsp;
	<span class='ipsCustomInput'>
		<input type="checkbox" data-control="unlimited{{if \count( $toggles )}} toggle{{endif}}" name="{$unlimitedName}" id='{$unlimitedName}' value="{$unlimited}" {{if $unlimited === $value}}checked aria-checked='true'{{endif}} {{if $disabled}}disabled{{endif}} {{if \count( $toggles )}}{{if $toggleOn === FALSE}}data-togglesOff{{else}}data-togglesOn{{endif}}="{expression="implode( ',', $toggles )"}"{{endif}} aria-labelledby='label_{$unlimitedName}'>
		<span></span>
	</span>
	<label for='{$unlimitedName}' id='label_{$unlimitedName}' class='ipsField_unlimited'>{lang="$unlimitedLang"}</label>
{{endif}}