<ips:template parameters="$start, $end, $unlimited=NULL, $unlimitedLang=NULL, $unlimitedName=NULL, $unlimitedChecked=FALSE, $toggles=array(), $toggleOn=TRUE" />
{lang="between"} {$start|raw} {lang="and"} {$end|raw}
{{if $unlimited !== NULL}}
	&nbsp;
	{lang="or"}
	&nbsp;
	<span class='ipsCustomInput'>
		<input type="checkbox" data-control="unlimited{{if \count( $toggles )}} toggle{{endif}}" name="{$unlimitedName}" id='{$unlimitedName}' value="{$unlimited}" {{if $unlimitedChecked}}checked aria-checked='true'{{endif}} {{if \count( $toggles )}}{{if $toggleOn === FALSE}}data-togglesOff{{else}}data-togglesOn{{endif}}="{expression="implode( ',', $toggles )"}"{{endif}} aria-labelledby='label_{$unlimitedName}'>
		<span></span>
	</span>
	<label for='{$unlimitedName}' id='label_{$unlimitedName}' class='ipsField_unlimited'>{lang="$unlimitedLang"}</label>
{{endif}}