<ips:template parameters="$name, $valueNumber, $selectedUnit, $required, $unlimited, $unlimitedLang, $unlimitedToggles, $unlimitedToggleOn, $valueToggles, $minSeconds, $maxSeconds, $disabled=FALSE, $suffix = NULL" />
<input
	type="number"
	name="{$name}[val]"
	size="5"
	{{if $required === TRUE}}aria-required='true'{{endif}}
	{{if $unlimited !== NULL and $valueNumber == $unlimited}}
		value=""
		data-jsdisable="true"
	{{else}}
		value="{$valueNumber}"
	{{endif}}
	class="ipsField_short"
	{{if $minSeconds !== NULL}}
		min="{expression="floor($minSeconds/86400)"}"
	{{endif}}
	{{if $maxSeconds !== NULL}}
		max="{$maxSeconds}"
	{{endif}}
	step="any"
	{{if $disabled}}
		disabled aria-disabled='true'
	{{endif}}
	{{if \count( $valueToggles )}}
		data-control="toggle" data-toggles="{expression="implode( ',', $valueToggles )"}"
	{{endif}}
>
<select name="{$name}[unit]" {{if $required === TRUE}}aria-required='true'{{endif}} {{if $disabled}}disabled aria-disabled='true'{{endif}}>
	{{if $maxSeconds === NULL or $maxSeconds >= 604800}}
		<option value="w" {{if $selectedUnit === 'w'}}selected{{endif}}>{lang="weeks"}</option>
	{{endif}}
	{{if ( $maxSeconds === NULL or $maxSeconds >= 86400 ) and ( $minSeconds === NULL or $minSeconds < 604800 )}}
		<option value="d" {{if $selectedUnit === 'd'}}selected{{endif}}>{lang="days"}</option>
	{{endif}}
	{{if ( $maxSeconds === NULL or $maxSeconds >= 3600 ) and ( $minSeconds === NULL or $minSeconds < 86400 )}}
		<option value="h" {{if $selectedUnit === 'h'}}selected{{endif}}>{lang="hours"}</option>
	{{endif}}
	{{if ( $maxSeconds === NULL or $maxSeconds >= 60 ) and ( $minSeconds === NULL or $minSeconds < 3600 )}}
		<option value="i" {{if $selectedUnit === 'i'}}selected{{endif}}>{lang="minutes"}</option>
	{{endif}}
	{{if $minSeconds === NULL or $minSeconds < 60}}
		<option value="s" {{if $selectedUnit === 's'}}selected{{endif}}>{lang="seconds"}</option>
	{{endif}}
</select>
{{if \is_string( $suffix )}}
	{$suffix|raw}
{{endif}}
{{if $unlimited !== NULL}}
	&nbsp;
	<div class="ipsFieldRow_inlineCheckbox">
		{lang="or"}
		&nbsp;
		<span class='ipsCustomInput'>
			<input
				type="checkbox"
				data-control="unlimited{{if \count($unlimitedToggles)}} toggle{{endif}}"
				name="{$name}[unlimited]"
				id='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}-unlimitedCheck'
				value="1"
				{{if $unlimited == $valueNumber}}
					checked aria-checked='true'
				{{endif}}
				{{if $disabled}}
					disabled aria-disabled='true'
				{{endif}}
				{{if \count( $unlimitedToggles )}}
					{{if $unlimitedToggleOn === FALSE}}data-togglesOff{{else}}data-togglesOn{{endif}}="{expression="implode( ',', $unlimitedToggles )"}"
				{{endif}}
				aria-labelledby='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}_label'
			>
			<span></span>
		</span>
		<label for='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}-unlimitedCheck' id='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}_label' class='ipsField_unlimited'>
			{lang="$unlimitedLang"}
		</label>
	</div>
{{endif}}