<ips:template parameters="$name, $value, $maxItems, $minAjaxLength, $datasource, $template" />
<input type="hidden" name="{$name}_values" value="{expression="implode( ',', array_keys($value) )"}">
<input
	type="text"
	name="{$name}"
	value=""
	id="elInput_{$name}"
	data-ipsContentItem
	{{if $maxItems}}data-ipsContentItem-maxItems="{$maxItems}"{{endif}}
	data-ipsContentItem-dataSource="{$datasource}"
	data-ipsContentItem-minAjaxLength="{$minAjaxLength}"
>
<ul data-contentItem-results="{$name}" class="ipsList_reset ipsContentItemSelector">
{{if \is_array($value)}}
	{{foreach $value as $item}}
		{{$html = $template( $item );}}
		{{$idColumn = $item::$databaseColumnId;}}
		<li data-id='{$item->$idColumn}'>
			<span class='cContentItem_delete' data-action='delete'>&times;</span>
			{$html|raw}
		</li>
	{{endforeach}}
{{endif}}
</ul>
