<ips:template parameters="$name, $value, $required, $unlimited=NULL, $range=FALSE, $min=NULL, $max=NULL, $step=NULL, $decimals=0, $unlimitedLang='unlimited', $disabled=FALSE, $suffix=NULL, $toggles=array(), $toggleOn=TRUE, $valueToggles=array(), $id=NULL" />
{{if $range && $min !== NULL}}
<strong class='ipsType_small' data-role='rangeBoundary'>{$min}</strong>
{{endif}}
<input
	type="{{if $range}}range{{else}}number{{endif}}"
	name="{$name}"
	{{if $id !== NULL}}
		id="elNumber_{$id}"
	{{endif}}
	size="5"
	{{if $required === TRUE}}aria-required='true'{{endif}}
	{{if $unlimited !== NULL and $value === $unlimited}}
		value=""
		data-jsdisable="true"
	{{elseif \is_numeric( $value )}}
		value="{expression="number_format( $value, $decimals === true ? mb_strlen( mb_substr( $value, mb_strpos( $value, '.' ) + 1 ) ) : $decimals, '.', '' )"}"
	{{else}}
		value="0"
	{{endif}}
	class="ipsField_short"
	{{if $min !== NULL}}
		min="{$min}"
	{{endif}}
	{{if $max !== NULL}}
		max="{$max}"
	{{endif}}
	{{if $step !== NULL and $step != 'any'}}
		step="{expression="number_format( $step, $decimals, '.', '' )"}"
	{{else}}
		step="any"
	{{endif}}
	{{if $disabled}}disabled aria-disabled='true'{{endif}}
	{{if \count($valueToggles)}}data-control="toggle" data-toggles="{expression="implode( ',', $valueToggles )"}"{{endif}}
>
{{if $range && $max !== NULL}}
<strong class='ipsType_small' data-role='rangeBoundary'><span id='{$name}_rangeValue' data-role='rangeValue'>{$value}</span>/{$max}</strong>
{{endif}}
{{if \is_string( $suffix )}}
	{$suffix|raw}
{{elseif isset( $suffix['preUnlimited'] )}}
	{$suffix['preUnlimited']|raw}
{{endif}}
{{if $unlimited !== NULL}}
	&nbsp;
	<div class="ipsFieldRow_inlineCheckbox">
		{lang="or"}
		&nbsp;
		<span class='ipsCustomInput'>
			<input type="checkbox" data-control="unlimited{{if \count($toggles)}} toggle{{endif}}" name="{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}" id='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}-unlimitedCheck' value="{$unlimited}" {{if $unlimited === $value}}checked aria-checked='true'{{endif}} {{if $disabled}}disabled aria-disabled='true'{{endif}} {{if \count($toggles)}}{{if $toggleOn === FALSE}}data-togglesOff{{else}}data-togglesOn{{endif}}="{expression="implode( ',', $toggles )"}"{{endif}} aria-labelledby='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}_label'>
			<span></span>
		</span> <label for='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}-unlimitedCheck' id='{expression="preg_replace( '/\[(.+?)\]/', '[$1_unlimited]', $name, 1 )"}_label' class='ipsField_unlimited'>{lang="$unlimitedLang"}</label>
	</div>
{{endif}}
{{if \is_array( $suffix ) and isset( $suffix['postUnlimited'] )}}
	&nbsp;&nbsp;&nbsp;{$suffix['postUnlimited']|raw}
{{endif}}