<ips:template parameters="$name, $value, $required, $options, $disabled=FALSE, $toggles=array(), $descriptions=array(), $warnings=array(), $userSuppliedInput='', $unlimited=NULL, $unlimitedLang=NULL, $htmlId=NULL, $gridspan=3" />

<div class="ipsGrid ipsGrid_collapsePhone ipsAttachment_fileList ipsContained" data-ipsGrid data-ipsGrid-equalHeights='row'>
	{{foreach $options as $k => $v}}
		<div class='ipsGrid_span{$gridspan} ipsBox ipsAttach ipsImageAttach ipsPad_half'>
			<div class=' ipsType_center' data-role='preview'>
				<label for="elRadio_{$name}_{$k}_{$htmlId}" class='ipsCursor_pointer'><img src="{$v}" alt='' class='ipsImage'></label>
			</div>
			<div class="ipsType_center ipsPad_half">
				<span class='ipsCustomInput'>
					<input type="radio" name="{$name}" value="{$k}" {{if (string) $value == (string) $k or ( isset( $userSuppliedInput ) and !\in_array( $value, array_keys( $options ) ) and $k == $userSuppliedInput )}}checked{{endif}} {{if $disabled === TRUE or ( \is_array( $disabled ) and \in_array( $k, $disabled ) )}}disabled{{endif}} {{if isset( $toggles[ $k ] ) and !empty( $toggles[ $k ] )}}data-control="toggle" data-toggles="{expression="implode( ',', $toggles[ $k ] )"}"{{endif}} id="elRadio_{$name}_{$k}_{$htmlId}">
					<span></span>
				</span>
			</div>
			{{if isset( $descriptions[ $k ] )}}
				<p class='ipsType_light ipsType_center'>{$descriptions[ $k ]|raw}</p>
			{{endif}}
		</div>
	{{endforeach}}
</div>