<ips:template parameters="$name, $fields, $options=array()" />
<div class="ipsField_stack" data-ipsStack data-ipsStack-sortable data-ipsStack-fieldName="{$name}" {{if isset( $options['maxItems'] )}}data-ipsStack-maxItems="{$options['maxItems']}"{{endif}}>
	<ul class="ipsList_reset" data-role="stack">
	{{foreach $fields as $field}}
		<li class='ipsField_stackItem' data-role="stackItem">
			<span class="ipsField_stackDrag ipsDrag ipsJS_show" data-action='stackDrag'>
				<i class='fa fa-bars ipsDrag_dragHandle'></i>
			</span>
			<a href='#' class="ipsField_stackDelete ipsCursor_pointer ipsJS_show" data-action="stackDelete">
				&times;
			</a>
			<input type="submit" class="ipsField_stackDelete ipsJS_hide" name="form_remove_stack[{expression="md5($field)"}]" value="&cross;">
			<div data-ipsStack-wrapper>{$field|raw}</div>
		</li>
	{{endforeach}}
	</ul>
	<a class="ipsField_stackAdd ipsButton ipsButton_light ipsButton_small ipsJS_show" href='#' data-action="stackAdd" role="button"><i class='fa fa-plus-circle'></i>&nbsp; {lang="stack_add"}</a>
	<input type="submit" class="ipsJS_hide" name="form_add_stack" value="{lang="stack_add"}">
</div>