<ips:template parameters="$name, $languages, $values, $editors, $placeholder, $textarea=FALSE, $required=FALSE" />
{{if \count( $languages ) === 1}}
	{{foreach $languages as $lang}}
		{{if !isset( $editors[ $lang->id ] ) }}
			{{if $textarea}}
				<textarea name="{$name}[{$lang->id}]">{{if isset($values[ $lang->id ])}}{$values[ $lang->id ]}{{endif}}</textarea>
			{{else}}
				<input type='text' name="{$name}[{$lang->id}]" value="{{if isset($values[ $lang->id ])}}{$values[ $lang->id ]}{{endif}}" {{if $placeholder !== NULL}}placeholder='{$placeholder}'{{endif}}>
			{{endif}}
		{{else}}
			{$editors[ $lang->id ]->html()|raw}
		{{endif}}
	{{endforeach}}
{{else}}
	{{if $textarea}}
		{{foreach $languages as $lang}}
			<span class="{$lang->_icon}"></span> {$lang->_title} {{if $required and $lang->default}}<span class="ipsFieldRow_required">{lang="required"}</span>{{endif}}<br>
			<br>
			<textarea name="{$name}[{$lang->id}]" aria-label='{$lang->title}' {{if !$required || !$lang->default}}class='ipsFieldRow_errorExclude'{{endif}}>{{if isset( $values[ $lang->id ])}}{$values[ $lang->id ]}{{endif}}</textarea><br>
			<br>
		{{endforeach}}
	{{else}}
		<ul class='ipsField_translatable ipsList_reset'>
			{{foreach $languages as $lang}}
				<li class='ipsClearfix'>
					{{if !isset( $editors[ $lang->id ] ) }}
						<span class="{$lang->_icon}"></span>
						<input type='text' name="{$name}[{$lang->id}]" aria-label='{$lang->title}' placeholder="{$lang->title}" {{if isset( $values[ $lang->id ])}}value="{$values[ $lang->id ]}"{{endif}} {{if !$required || !$lang->default}}class='ipsFieldRow_errorExclude'{{endif}}>
						{{if $required and $lang->default}}
							<span class="ipsFieldRow_required">{lang="required"}</span>
						{{endif}}
					{{else}}
						<p class='ipsFlagEditor'>
							<span class="{$lang->_icon}"></span> <span class='ipsFlagLabel'>{$lang->_title}</span>
							{{if $required and $lang->default}}<span class="ipsFieldRow_required">{lang="required"}</span>{{endif}}
						</p>
						{$editors[ $lang->id ]->html()|raw}
					{{endif}}
				</li>
			{{endforeach}}
		</ul>
	{{endif}}
{{endif}}