<ips:template parameters="$name, $top, $right, $bottom, $left" />
<div class="ipsWidthHeight_container">
	<div class="ipsWidthHeight_controls">
		{lang="form_input_top"} <input type="number" name="{$name}[0]" class="ipsField_tiny" value="{$top}" aria-label='{lang="form_input_top"}'>
		{lang="form_input_right"} <input type="number" name="{$name}[1]" class="ipsField_tiny" value="{$right}" aria-label='{lang="form_input_right"}'>
		{lang="form_input_bottom"} <input type="number" name="{$name}[2]" class="ipsField_tiny" value="{$bottom}" aria-label='{lang="form_input_bottom"}'>
		{lang="form_input_left"} <input type="number" name="{$name}[3]" class="ipsField_tiny" value="{$left}" aria-label='{lang="form_input_left"}'> {lang="px"}
	</div>
</div>