<ips:template parameters="$id, $file, $name=NULL, $editor=FALSE, $showAsImages=FALSE, $link=NULL" />
{{if $showAsImages}}
	<div class='ipsGrid_span3 ipsAttach ipsImageAttach ipsPad_half ipsAreaBackground_light {{if $editor}}ipsAttach_done{{endif}}' data-role='file' data-fileid="{$id}" {{if $link}}data-filelink="{$link}"{{endif}} data-fileType="{$file->mediaType()}" {{if $file->attachmentThumbnailUrl}}data-thumbnailurl="{$file->attachmentThumbnailUrl}"{{endif}} {{if $file->isImage() or $file->isVideo()}}data-fullsizeurl="{$file->url}"{{endif}} {{if $file->isVideo()}}data-mimeType="{expression="\IPS\File::getMimeType( $file->originalFilename )"}"{{endif}}>
		<ul class='ipsList_inline ipsImageAttach_controls'>
			{{if $editor}}
				<li><a href='#' data-action='selectFile' class='ipsAttach_selection' data-ipsTooltip title='{lang="form_upload_insert_one"}'><i class='fa fa-check'></i></a></li>
			{{endif}}
			{{if $name}}
				<li class='ipsPos_right'>
					<input type="hidden" name="{$name}_keep[{$id}]" value="1">
					<a href='#' data-role='deleteFile' class='ipsButton ipsButton_verySmall ipsButton_light' data-ipsTooltip title='{lang="editor_media_remove"}'><i class='fa fa-trash-o'></i></a>
				</li>
			{{endif}}
		</ul>
		{{$screenshot = isset( $file->screenshot ) ? $file->screenshot : $file;}}
		{{$extension =  mb_strtolower( mb_substr( $screenshot->filename, mb_strrpos( $screenshot->filename, '.' ) + 1 ) );}}
		{{if \in_array( $extension, \IPS\Image::$imageExtensions )}}
			<div class='ipsImageAttach_thumb ipsType_center' data-role='preview' data-grid-ratio='65' data-action='selectFile' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), ( $screenshot->attachmentThumbnailUrl ) ? $screenshot->attachmentThumbnailUrl : $screenshot->url )"}" );'>
				<img src="{$screenshot->url}" alt='' class='ipsImage'>
			</div>
		{{elseif \in_array( $extension, \IPS\File::$videoExtensions )}}
			<div class='ipsImageAttach_thumb ipsType_center' data-role='preview' data-grid-ratio='65' data-action='selectFile'>
				<video>
					 <source src="{$screenshot->url}" type="{expression="\IPS\File::getMimeType( $screenshot->originalFilename )"}">
				</video>
			</div>
		{{else}}
			<div class='ipsImageAttach_thumb ipsType_center' data-role='preview' data-grid-ratio='65' data-action='selectFile'>
				<div class='ipsNoThumb'></div>
			</div>
		{{endif}}		
		<h2 class='ipsType_reset ipsAttach_title ipsType_medium ipsTruncate ipsTruncate_line ipsType_break' data-role='title'>{{if isset( $file->contextInfo )}}{$file->contextInfo}{{else}}{$file->originalFilename}{{endif}}</h2>
		<p class='ipsType_light ipsType_small ipsTruncate ipsTruncate_line ipsType_break'><span data-role='status'>{filesize="$file->filesize()"}</span>{{if isset( $file->contextInfo )}} &middot; {$file->originalFilename}{{endif}}</p>
	</div>
{{else}}
	<div class='ipsDataItem ipsAttach {{if $editor}}ipsAttach_done{{endif}}' {{if $file->attachmentThumbnailUrl}}data-thumbnailurl="{$file->attachmentThumbnailUrl}"{{endif}} data-role='file' data-fileid="{$id}" {{if $link}}data-filelink="{$link}"{{endif}} data-fileType="{$file->mediaType()}">
		<div class='ipsDataItem_generic ipsDataItem_size3 ipsResponsive_hidePhone ipsResponsive_block ipsType_center' data-action='selectFile'>
			{{if \in_array( mb_strtolower( mb_substr( $file->filename, mb_strrpos( $file->filename, '.' ) + 1 ) ), \IPS\Image::$imageExtensions )}}
				<img src="{{if $file->attachmentThumbnailUrl}}{$file->attachmentThumbnailUrl}{{else}}{$file->url}{{endif}}" alt='' class='ipsImage ipsThumb_small'>
			{{else}}
				<i class='fa fa-file ipsType_large'></i>
			{{endif}}
		</div>
		<div class='ipsDataItem_main' data-action='selectFile'>
			<h2 class='ipsDataItem_title ipsType_reset ipsType_medium ipsAttach_title ipsTruncate ipsTruncate_line ipsType_break' data-role='title'>{$file->originalFilename}</h2>
			<p class='ipsDataItem_meta ipsType_light'>
				{filesize="$file->filesize()"}
			</p>
		</div>
		<div class='ipsDataItem_generic ipsDataItem_size9 ipsType_light' data-role='status'>
			
		</div>
		<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right'>
			<ul class='ipsList_inline'>
				{{if $editor}}
					<li><a href='#' data-action='selectFile' class='ipsAttach_selection' data-ipsTooltip title='{lang="form_upload_insert_one"}'><i class='fa fa-check'></i></a></li>
				{{endif}}
				{{if $name}}
					<li>
						<input type="hidden" name="{$name}_keep[{$id}]" value="1">
						<a href='#' data-role='deleteFile' class='ipsButton ipsButton_verySmall ipsButton_light' data-ipsTooltip title='{lang="editor_media_remove"}'><i class='fa fa-trash-o'></i></a>
					</li>
				{{endif}}
			</ul>
		</div>		
	</div>
{{endif}}