<ips:template parameters="$url, $count" />
{{if isset( \IPS\Request::i()->q ) and \IPS\Request::i()->q AND ( !isset( \IPS\Request::i()->type ) OR \IPS\Request::i()->type != 'core_members' )}}
{{$words = \IPS\Content\Search\Query::termAsWordsArray( \IPS\Request::i()->q, FALSE, 0 );}}
{{$noPhraseWords = \IPS\Content\Search\Query::termAsWordsArray( \IPS\Request::i()->q, TRUE );}}
	<p class='ipsType_reset'>{lang="search_better_results_hint"}</p>
	<ul class='ipsList_inline ipsType_brandedLinks'>
		{{if ! \IPS\Content\Search\Query::termIsPhrase( \IPS\Request::i()->q ) and \count( $words ) > 1}}
			<li><a href='{$url->setQueryString('q', '"' . \IPS\Request::i()->q . '"')}'>{lang="search_hint_phrase" sprintf="\IPS\Request::i()->q"}</a></li>
		{{elseif \IPS\Content\Search\Query::termIsPhrase( \IPS\Request::i()->q ) and \count( $noPhraseWords ) > 1}}
			<li><a href='{$url->setQueryString( array( 'q' => implode( ' ', $noPhraseWords ), 'search_and_or' => 'or' ) )}'>{expression="implode( ' ' . \IPS\Member::loggedIn()->language()->addToStack('search_join_or') . ' ', $noPhraseWords )"}</a></li>
		{{endif}}
		{{if \count( $words ) > 1}}
			{{if ( ( !isset( \IPS\Request::i()->search_and_or ) and settings.search_default_operator === 'and' ) or \IPS\Request::i()->search_and_or == 'and' )}}
				<li><a href='{$url->setQueryString( 'search_and_or', 'or')}'>{expression="implode( ' ' . \IPS\Member::loggedIn()->language()->addToStack('search_join_or') . ' ', $words )"}</a></li>
			{{elseif ( ( !isset( \IPS\Request::i()->search_and_or ) and settings.search_default_operator === 'or' ) or \IPS\Request::i()->search_and_or == 'or' )}}
				<li><a href='{$url->setQueryString( 'search_and_or', 'and')}'>{expression="implode( ' ' . \IPS\Member::loggedIn()->language()->addToStack('search_join_and') . ' ', $words )"}</a></li>
			{{endif}}
		{{endif}}
		{{if $count > 1 and ( ! isset( \IPS\Request::i()->sortby ) or \IPS\Request::i()->sortby != 'newest' )}}
			<li><a href='{$url->setQueryString('sortby', 'newest')}'>{lang="search_newer_first"}</a></li>
		{{elseif $count > 1 and ( isset( \IPS\Request::i()->sortby ) and \IPS\Request::i()->sortby == 'newest' )}}
			<li><a href='{$url->setQueryString('sortby', 'relevancy')}'>{lang="search_most_pertinent"}</a></li>
		{{endif}}
		{{if isset( \IPS\Request::i()->search_in ) and \IPS\Request::i()->search_in == 'titles'}}
			<li><a href='{$url->setQueryString('search_in', 'all')}'>{lang="search_titles_and_content" sprintf="\IPS\Request::i()->q"}</a></li>
		{{elseif $count > 1 and ( ! isset( \IPS\Request::i()->search_in ) or \IPS\Request::i()->search_in != 'titles' )}}
			<li><a href='{$url->setQueryString('search_in', 'titles')}'>{lang="search_titles_only" sprintf="\IPS\Request::i()->q"}</a></li>
		{{endif}}
		{{if isset( \IPS\Request::i()->updated_after ) and \IPS\Request::i()->updated_after != 'any'}}
			<li><a href='{$url->stripQueryString( array('updated_after' ) )}'>{lang="search_all_dates" sprintf="\IPS\Request::i()->q"}</a></li>
		{{endif}}
	</ul>
{{endif}}
			