<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

{{$exclude = array( 'q', 'joinedDate', 'joinedDateCustom', 'group');}}
{{$totalCustomFields = \count( $elements[''] ) - \count( $exclude ); // Don't count q, joined, joined custom or group}}
{{$perCol = ceil( $totalCustomFields / 2 );}}

{{if !\IPS\Request::i()->isAjax()}}
<form accept-charset='utf-8' class="ipsForm ipsForm_vertical" method='post' action='{$action}' data-ipsForm id='elSearchFilters_content'>
{{endif}}
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}

	<div class='ipsPad_double'>
		<!--<div class='ipsAreaBackground_light ipsPad ipsSpacer_both ipsPhotoPanel ipsPhotoPanel_mini'>
			<i class='fa fa-user ipsType_huge ipsPos_left'></i>
			<div>
				<ul class='ipsList_reset'>
					{{if isset( $elements['']['q'] )}}
						<li class='ipsSpacer_bottom ipsSpacer_half'>
							<h3 class="ipsType_reset ipsType_large cStreamForm_title ipsSpacer_bottom ipsSpacer_half">Search By Member Name</h3>
							<input type='text' name='q' value='{{if \is_array( $elements['']['q']->value )}}{expression="implode( ',', $elements['']['q']->value )"}{{else}}{$elements['']['q']->value}{{endif}}' class='ipsField_primary ipsField_fullWidth'>
						</li>
					{{endif}}
				</ul>
			</div>
		</div>
		<hr class='ipsHr ipsSpacer_bottom ipsSpacer_double'>-->

		<div class='ipsGrid ipsGrid_collapsePhone'>
			<div class='ipsGrid_span4'>
				{{if isset( $elements['']['joinedDate'] )}}
					<h3 class="ipsType_reset ipsType_large cStreamForm_title">Joined</h3>
					<ul class="ipsSideMenu_list ipsSideMenu_withRadios ipsSideMenu_small ipsType_normal ipsSpacer_top ipsSpacer_half" role="radiogroup" data-ipsSideMenu data-ipsSideMenu-type="radio" data-ipsSideMenu-responsive="false" data-filterType='joinedDate'>
						{{foreach $elements['']['joinedDate']->options['options'] as $k => $lang}}
							<li>
								<a href='#' class='ipsSideMenu_item {{if (string) $elements['']['joinedDate']->value == (string) $k}}ipsSideMenu_itemActive{{endif}}' data-ipsMenuValue='{$k}'>
									<input type="radio" name="joinedDate" value="{$k}" {{if (string) $elements['']['joinedDate']->value == (string) $k}}checked{{endif}} id="elRadio_joinedDate_{$k}">
									<label for='elRadio_joinedDate_{$k}' id='elField_joinedDate_label_{$k}'>{lang="$lang"}</label>
								</a>
							</li>
						{{endforeach}}
						<li class='ipsGrid ipsGrid_collapsePhone cStreamForm_dates ipsAreaBackground_light ipsPad_half {{if $elements['']['joinedDate']->value !== 'custom'}}ipsJS_hide{{endif}}' data-role="dateForm">
							<div class='ipsGrid_span6'>
								<h4 class='ipsType_minorHeading'>{lang="start"}</h4>
								<input type='date' name='{$elements['']['joinedDateCustom']->name}[start]' data-control='date' data-role='start' value='{$elements['']['joinedDateCustom']->value['start']}'>	
							</div>
							<div class='ipsGrid_span6'>
								<h4 class='ipsType_minorHeading'>{lang="end"}</h4>
								<input type='date' name='{$elements['']['joinedDateCustom']->name}[end]' data-control='date' data-role='end' value='{$elements['']['joinedDateCustom']->value['end']}'>
							</div>
						</li>
					</ul>
				{{endif}}
			</div>
			<div class='ipsGrid_span8' data-role='searchFilters' id='elSearchFiltersMembers'>
				<div class='ipsGrid ipsGrid_collapsePhone'>
					<div class='ipsGrid_span6'>
						{{if isset( $elements['']['group'] )}}
							<h3 class="ipsType_reset ipsType_large cStreamForm_title">{lang="group"}</h3>
							<ul class="ipsSideMenu_list ipsSideMenu_withChecks ipsSideMenu_small ipsType_normal ipsSpacer_top ipsSpacer_half" data-ipsSideMenu data-ipsSideMenu-type="check" data-ipsSideMenu-responsive="false" data-filterType='group'>
								{{foreach $elements['']['group']->options['options'] as $k => $group}}
									<li>
										<a href='#' class='ipsSideMenu_item {{if \is_array( $elements['']['group']->value ) AND \in_array( $k, $elements['']['group']->value )}}ipsSideMenu_itemActive{{endif}}' data-ipsMenuValue='{$k}'>
											<input type="checkbox" name="group" value="{$k}" {{if \is_array( $elements['']['group']->value ) AND \in_array( $k, $elements['']['group']->value )}}checked{{endif}} id="elCheck_group_{$k}">
											<label for='elCheck_group_{$k}' id='elField_group_label_{$k}'>{$group|raw}</label>
										</a>
									</li>
								{{endforeach}}
							</ul>
						{{endif}}

						{{$countOne = 0;}}
						{{if $totalCustomFields > 1}}
							{{foreach $elements[''] as $id => $element}}
								{{if \in_array( $id, $exclude )}}
									{{continue;}}
								{{endif}}
								{{$countOne++;}}

								<hr class='ipsHr'>
								<h3 class="ipsType_reset ipsType_large cStreamForm_title ipsSpacer_bottom ipsSpacer_half">{lang="$id"}</h3>
								<div class='ipsFieldRow_fullWidth'>
									{$element->html()|raw}
								</div>
								
								{{if $countOne >= $perCol}}
									{{break;}}
								{{endif}}
							{{endforeach}}
						{{endif}}
					</div>
					<div class='ipsGrid_span6'>
						{{$countTwo = 0;}}
						{{foreach $elements[''] as $id => $element}}
							{{if \in_array( $id, $exclude )}}
								{{continue;}}
							{{endif}}
							{{$countTwo++;}}

							{{if $countTwo <= $countOne}}
								{{continue;}}
							{{endif}}

							{{if $countTwo !== ( $countOne + 1 )}}
								<!-- HR except for first item -->
								<hr class='ipsHr'>
							{{endif}}

							<h3 class="ipsType_reset ipsType_large cStreamForm_title ipsSpacer_bottom ipsSpacer_half">{lang="$id"}</h3>
							<div class='ipsFieldRow_fullWidth'>
								{$element->html()|raw}
							</div>
							
							{{if $countTwo >= $perCol}}
								{{break;}}
							{{endif}}
						{{endforeach}}
					</div>			
				</div>			
			</div>
		</div>
	</div>
	<div class='ipsAreaBackground cSearchFiltersSubmit'>
		<ul class='ipsToolList ipsToolList_horizontal ipsClearfix'>
			<li class='ipsPos_right'>
				<button type="submit" class="ipsButton ipsButton_primary ipsButton_medium ipsButton_fullWidth" data-action="updateResults">{lang="update_results"}</button>
			</li>
			<li class='ipsPos_right'>
				<button type="button" class="ipsButton ipsButton_link ipsButton_medium ipsButton_fullWidth" data-action="cancelFilters">{lang="cancel"}</button>
			</li>
		</ul>
	</div>
{{if !\IPS\Request::i()->isAjax()}}	
</form>
{{endif}}