<ips:template parameters="$termArray, $title, $results, $pagination, $baseUrl, $types, $filters, $count=NULL, $advanced=FALSE" />

<div data-controller='core.front.search.main' data-baseURL='{url="app=core&module=search&controller=search" seoTemplate="search"}'>
	<div class='ipsResponsive_hidePhone ipsPageHeader'>
		<h1 class='ipsType_pageTitle'>{lang="search_the_community"}</h1>
		<p class='ipsType_reset ipsType_large {{if $advanced}}ipsHide{{endif}}' data-role='searchBlurb'>{$title}</p>
	</div>
	
	{{if \IPS\Content\Search\Query::isRebuildRunning()}}
	<div class="ipsMessage ipsMessage_info">{lang="search_rebuild_is_running"}</div>
	{{endif}}

	<div class='ipsBox ipsPadding ipsResponsive_pull ipsMargin_top' data-controller='core.front.search.filters' id='elSearchFilters'>
		{$filters|raw}
	</div>

	<div id="elSearch_main" class='ipsSpacer_top' data-role='filterContent'>
		{{if !$advanced}}
			{template="results" group="search" params="$termArray, $title, $results, $pagination, $baseUrl, $count"}
		{{endif}}
	</div>
</div>
