<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	<li class='ipsMargin'>
		{{$idField = $row::$databaseColumnId;}}
		<article id='elComment_{$row->$idField}' class='ipsComment ipsBox ipsBox--child {{if \IPS\IPS::classUsesTrait( $row, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $row->reactionCount() >= settings.reputation_highlight}}ipsComment_popular{{endif}} ipsClearfix ipsClear {{if $row->hidden()}}ipsModerated{{endif}}'>

			{{if \IPS\IPS::classUsesTrait( $row, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $row->reactionCount() >= settings.reputation_highlight}}
				<div class='ipsResponsive_showPhone ipsComment_badges'>
					<ul class='ipsList_reset ipsFlex ipsFlex-fw:wrap ipsGap:2 ipsGap_row:1'>
						<li><strong class='ipsBadge ipsBadge_large ipsBadge_popular'>{lang="this_is_a_popular_post"}</strong></li>
					</ul>
				</div>
			{{endif}}

			<div id='comment-{$row->$idField}_wrap' class='ipsComment_content ipsType_normal ipsClearfix'>	
				<div class='ipsComment_header ipsPadding_top ipsFlex ipsFlex-fd:row-reverse ipsFlex-ai:start ipsFlex-jc:between sm:ipsFlex-fd:column'>
					<div class='ipsComment_toolWrap ipsFlex-flex:00'>
						{{if \IPS\IPS::classUsesTrait( $row, 'IPS\Content\Reactable' ) and settings.reputation_highlight and $row->reactionCount() >= settings.reputation_highlight}}
							<div class='ipsResponsive_hidePhone ipsComment_badges'>
								<ul class='ipsList_reset ipsFlex ipsFlex-jc:end ipsFlex-fw:wrap ipsGap:2 ipsGap_row:1'>
									<li><strong class='ipsBadge ipsBadge_large ipsBadge_popular'>{lang="this_is_a_popular_post"}</strong></li>
								</ul>
							</div>
						{{endif}}
						<ul class='ipsList_reset ipsComment_tools'>
							{{if $row->canReportOrRevoke() === TRUE}}
								<li><a href='{$row->url('report')}' data-ipsDialog data-ipsDialog-remoteSubmit data-ipsDialog-size='medium' data-ipsDialog-flashMessage='{lang="report_submit_success"}' data-ipsDialog-title="{lang="report_reply"}" data-action='reportComment' title='{lang="report_content"}' class='ipsType_medium ipsType_light'>{lang="report"}</a></li>
							{{endif}}
							{{if $table->canModerate() and ( $row->canSplit() or ( $row->hidden() === -1 AND $row->canUnhide() ) or ( $row->hidden() === 1 AND $row->canUnhide() ) or $row->canDelete() )}}
								<li>
									<span class='ipsCustomInput'>
										<input type="checkbox" name="moderate[{$row->$idField}]" value="1" data-role="moderation" data-actions="{{if $row->canSplit()}}split{{endif}} {{if $row->hidden() === -1 AND $row->canUnhide()}}unhide{{elseif $row->hidden() === 1 AND $row->canUnhide()}}approve{{elseif $row->canHide()}}hide{{endif}} {{if $row->canDelete()}}delete{{endif}}" data-state='{{if $row->tableStates()}}{$row->tableStates()}{{endif}}'>
										<span></span>
									</span>
								</li>
							{{endif}}
						</ul>
					</div>
					{$row->contentTableHeader()|raw}
				</div>
				
				<div class=''>
					<div class='ipsPadding_horizontal ipsPadding_bottom ipsPadding_top:half'>
						{{if \IPS\Request::i()->controller == 'activity'}}
							<div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
								{template="userPhoto" group="global" app="core" params="$row->author(), 'mini'"}
								<div>
									<h3 class='ipsType_reset ipsType_normal'>{$row->author()->link()|raw}</h3>
						{{endif}}
						<p class='ipsComment_meta ipsType_light ipsType_medium ipsType_blendLinks'>
							<a href='{$row->url( 'find' )}' class='ipsType_blendLinks'>{$row->dateLine()|raw}</a>
							{{if $row->editLine()}}
								&middot; {$row->editLine()|raw}
							{{endif}}
							{{if $row->hidden()}}
								&middot; {$row->hiddenBlurb()}
							{{endif}}							
						</p>
						{{if \IPS\Request::i()->controller == 'activity'}}
								</div>
							</div>
						{{endif}}

						<div data-role='commentContent' class='ipsType_break ipsType_richText ipsContained ipsMargin_top' data-controller='core.front.core.lightboxedImages'>
							{{if $row->hidden() === 1 && $row->author()->member_id == \IPS\Member::loggedIn()->member_id}}
								<strong class='ipsType_medium ipsType_warning'><i class='fa fa-info-circle'></i> {lang="comment_awaiting_approval"}</strong>
							{{endif}}
							{$row->content()|raw}
						</div>
					</div>
					{{if $row->hidden() !== 1 && \IPS\IPS::classUsesTrait( $row, 'IPS\Content\Reactable' ) and settings.reputation_enabled}}
						<div class='ipsItemControls'>
							{template="reputation" group="global" app="core" params="$row"}
						</div>
					{{endif}}
				</div>		
			</div>
		</article>
	</li>
{{endforeach}}