<ips:template parameters="$table, $headers, $rows, $includeFirstCommentInCommentCount=TRUE" />
{{if \count( $rows )}}
	{{foreach $rows as $row}}
	{{$idField = $row::$databaseColumnId;}}
		<li class="ipsDataItem ipsDataItem_responsivePhoto {{if $row->unread()}}ipsDataItem_unread{{endif}} {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if $row->hidden()}}ipsModerated{{endif}}" data-controller='core.front.system.manageFollowed' data-followID='{$row->_followData['follow_area']}-{$row->_followData['follow_rel_id']}'>
			<div class='ipsDataItem_main'>
				<h4 class='ipsDataItem_title ipsContained_container'>
					{{if $row->mapped('locked')}}
						<span><i class="fa fa-lock"></i></span>
					{{endif}}

					{{if $row->mapped('pinned') || $row->mapped('featured') || $row->hidden() === -1 || $row->hidden() === 1}}
						<span>
							{{if $row->hidden() === -1}}
								<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$row->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
							{{elseif $row->hidden() === 1}}
								<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
							{{endif}}							
							{{if $row->mapped('pinned')}}
								<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
							{{endif}}
							{{if $row->mapped('featured')}}
								<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
							{{endif}}
						</span>
					{{endif}}

					{{if $row->prefix()}}
						<span>{template="prefix" group="global" app="core" params="$row->prefix( TRUE ), $row->prefix()"}</span>
					{{endif}}
					
					<span class='ipsType_break ipsContained'>
						<a href='{$row->url()}'>
							{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}
						</a>
					</span>
				</h4>
				<div class='ipsDataItem_meta ipsType_light ipsType_blendLinks' data-ipsTruncate data-ipsTruncate-size='2 lines' data-ipsTruncate-type='remove'>
					{{if method_exists( $row, 'tableDescription' )}}
						{$row->tableDescription()|raw}
					{{else}}
                        {lang="byline" htmlsprintf="$row->author()->link( $row->warningRef() )"}{datetime="$row->__get( $row::$databaseColumnMap['date'] )"}
						{lang="in"} <a href="{$row->container()->url()}">{$row->container()->_title}</a>
					{{endif}}
				</div>				
			</div>

			<div class='ipsDataItem_generic ipsDataItem_size1 ipsType_center ipsType_large cFollowedContent_anon'>
				<span class='ipsBadge ipsBadge_icon ipsBadge_new {{if !$row->_followData['follow_is_anon']}}ipsHide{{endif}}' data-role='followAnonymous' data-ipsTooltip title='{lang="follow_is_anon"}'><i class='fa fa-eye-slash'></i></span>
			</div>

			<div class='ipsDataItem_generic ipsDataItem_size6 cFollowedContent_info'>
				<ul class='ipsList_reset'>
					<li title='{lang="follow_when"}' data-role='followDate'><i class='fa fa-clock-o'></i> {datetime="$row->_followData['follow_added']"}</li>
					<li title='{lang="follow_how"}' data-role='followFrequency'>
						{{if $row->_followData['follow_notify_freq'] == 'none'}}
							<i class='fa fa-bell-slash-o'></i>
						{{else}}
							<i class='fa fa-bell'></i>
						{{endif}} {lang="follow_freq_{$row->_followData['follow_notify_freq']}"}
					</li>
				</ul>
			</div>

			<div class='ipsDataItem_generic ipsDataItem_size6 ipsType_center cFollowedContent_manage'>
				{template="manageFollow" group="system" app="core" params="$row->_followData['follow_app'], $row->_followData['follow_area'], $row->_followData['follow_rel_id']"}
			</div>

			{{if $table->canModerate()}}
				<div class='ipsDataItem_modCheck'>
					<span class='ipsCustomInput'>
						<input type='checkbox' data-role='moderation' name="moderate[{$row->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{{if $row->tableStates()}}{$row->tableStates()}{{endif}}'>
						<span></span>
					</span>
				</div>
			{{endif}}

		</li>
	{{endforeach}}
{{endif}}
