<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	{{$contentItemClass = $row::$contentItemClass;}}
	<li class="ipsDataItem {{if $contentItemClass::containerUnread( $row )}}ipsDataItem_unread{{endif}} {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}}">
		{{if method_exists( $row, 'tableIcon' )}}
			<div class='ipsDataItem_icon ipsType_center ipsType_noBreak'>
				{$row->tableIcon()|raw}
			</div>
		{{endif}}
		<div class='ipsDataItem_main'>
			<h4 class='ipsDataItem_title'>
				{{if $contentItemClass::containerUnread( $row )}}
					<span class='ipsBadge ipsBadge_new'>{lang="new"}</span>
				{{endif}}

				{{if $row->_locked}}
					<i class="fa fa-lock"></i>
				{{endif}}
				
				<a href='{$row->url()}'>
					{$row->_title}
				</a>
			</h4>
			<div class='ipsDataItem_meta ipsType_light' data-ipsTruncate data-ipsTruncate-size='2 lines' data-ipsTruncate-type='remove'>
				{$row->_description}
			</div>
		</div>
		<ul class='ipsDataItem_stats'>
			<li>
				<span class='ipsDataItem_stats_number'>{number="$row->_items"}</span>
				<span class='ipsDataItem_stats_type'>{lang="node_content_items" pluralize="$row->_items"}</span>
			</li>
			<li>
				<span class='ipsDataItem_stats_number'>{number="$row->_comments"}</span>
				<span class='ipsDataItem_stats_type'>{lang="node_content_comments" pluralize="$row->_comments"}</span>
			</li>
			<li>
				<span class='ipsDataItem_stats_number'>{number="$row->_reviews"}</span>
				<span class='ipsDataItem_stats_type'>{lang="node_content_reviews" pluralize="$row->_reviews"}</span>
			</li>
		</ul>
		{{if $table->canModerate()}}
			<div class='ipsDataItem_modCheck'>
				<span class='ipsCustomInput'>
					<input type='checkbox' data-role='moderation' name="moderate[{$row->_id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state=''>
					<span></span>
				</span>
			</div>
		{{endif}}
	</li>
{{endforeach}}