<ips:template parameters="$table, $headers, $rows" />
{{$rowIds = array();}}
{{foreach $rows as $row}}
	{{$idField = $row::$databaseColumnId;}}
	{{$rowIds[] = $row->$idField;}}
{{endforeach}}
{{if \count( $rows )}}
	{{foreach $rows as $row}}
	{{$idField = $row::$databaseColumnId;}}
		{{if $row->mapped('moved_to')}}
			{{if $movedTo = $row->movedTo()}}
				<li class="ipsDataItem">
					<div class='ipsDataItem_icon ipsType_center ipsType_noBreak'>
						<i class="fa fa-arrow-left ipsType_large"></i>
					</div>
					<div class='ipsDataItem_main'>
						<h4 class='ipsDataItem_title'>
							<span class='ipsType_break ipsContained_container'><em><a href='{$movedTo->url()}' title='{lang="go_to_new_location"}' class='ipsTruncate ipsTruncate_line'>{$row->mapped('title')}</a></em></span>
						</h4>
						<div class='ipsDataItem_meta'>
							{{if isset( $row::$databaseColumnMap['status'] )}}
								{{$statusField = $row::$databaseColumnMap['status'];}}
								{{if $row->$statusField == 'merged'}}
									<p class='ipsType_reset ipsType_light ipsType_blendLinks'>{lang="merged_to" sprintf="$movedTo->url(), $movedTo->mapped('title')"}</p>
								{{else}}
									<p class='ipsType_reset ipsType_light ipsType_blendLinks'>{lang="moved_to" sprintf="$movedTo->container()->url(), $movedTo->container()->_title"}</p>
								{{endif}}
							{{else}}
								<p class='ipsType_reset ipsType_light ipsType_blendLinks'>{lang="moved_to" sprintf="$movedTo->container()->url(), $movedTo->container()->_title"}</p>
							{{endif}}
						</div>
					</div>
					{{if $table->canModerate()}}
						<div class='ipsDataItem_modCheck'>
							<span class='ipsCustomInput'>
								<input type='checkbox' data-role='moderation' name="moderate[{$row->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{{if $row->mapped('pinned')}}pinned{{endif}} {{if $row->mapped('featured')}}featured{{endif}}'>
								<span></span>
							</span>
						</div>
					{{endif}}
				</li>
			{{endif}}
		{{else}}
			<li class="ipsDataItem ipsDataItem_responsivePhoto {{if $row->unread()}}ipsDataItem_unread{{endif}} {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if $row->hidden()}}ipsModerated{{endif}}">
				<div class='ipsDataItem_icon ipsPos_top'>
					{{if $row->unread()}}
						<a href='{$row->url( 'getNewComment' )}' title='{lang="first_unread_post"}' data-ipsTooltip>
							{{if $row->containerWrapper() AND \in_array( $row->$idField, $row->containerWrapper()->contentPostedIn( null, $rowIds ) )}}
								<span class='ipsItemStatus'><i class="fa fa-star"></i></span>
							{{else}}
								<span class='ipsItemStatus'><i class="fa fa-circle"></i></span>
							{{endif}}
						</a>
					{{else}}
						{{if $row->containerWrapper() AND \in_array( $row->$idField, $row->containerWrapper()->contentPostedIn( null, $rowIds ) )}}
							<span class='ipsItemStatus ipsItemStatus_read ipsItemStatus_posted'><i class="fa fa-star"></i></span>
						{{else}}
							&nbsp;
						{{endif}}
					{{endif}}
				</div>
				<div class='ipsDataItem_main'>
					<h4 class='ipsDataItem_title ipsContained_container'>						
						{{if $row->mapped('locked')}}
							<span><i class="fa fa-lock"></i></span>
						{{endif}}

						{{if $row->mapped('pinned') || $row->mapped('featured') || $row->hidden() === -1 || $row->hidden() === 1}}
							<span>
								{{if $row->hidden() === -1}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$row->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
								{{elseif $row->hidden() === 1}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
								{{endif}}							
								{{if $row->mapped('pinned')}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
								{{endif}}
								{{if $row->mapped('featured')}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
								{{endif}}
							</span>
						{{endif}}
						
						{{if $row->prefix()}}
							<span>{template="prefix" group="global" app="core" params="$row->prefix( TRUE ), $row->prefix()"}</span>
						{{endif}}
						
						<span class='ipsType_break ipsContained'>
							<a href='{$row->url()}' {{if $row->tableHoverUrl and $row->canView()}}data-ipsHover data-ipsHover-target='{$row->url()->setQueryString('preview', 1)}'data-ipsHover{{endif}} {{if $row->canEdit() AND $row->editableTitle === TRUE}}data-role="editableTitle" title="{lang="click_hold_edit"}"{{endif}}>
								{{if $row->mapped('title') or $row->mapped('title') == 0}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}
							</a>
						</span>
						{{if $row->commentPageCount() > 1}}
	                        {$row->commentPagination( array(), 'miniPagination' )|raw}
	                    {{endif}}
					</h4>

					<div class='ipsDataItem_meta ipsType_light ipsType_blendLinks' data-ipsTruncate data-ipsTruncate-size='2 lines' data-ipsTruncate-type='remove'>
						{{if method_exists( $row, 'tableDescription' )}}
							{$row->tableDescription()|raw}
						{{else}}
                            {lang="byline" htmlsprintf="$row->author()->link( $row->warningRef() )"}{datetime="$row->__get( $row::$databaseColumnMap['date'] )"}
							{{if \in_array( \IPS\Request::i()->controller, array( 'search' ) )}}
								{lang="in"} <a href="{$row->container()->url()}">{$row->container()->_title}</a>
							{{endif}}
						{{endif}}
					</div>
					{{if $row->tags() AND \count( $row->tags() )}}
						&nbsp;&nbsp;
						{template="tags" group="global" app="core" params="$row->tags(), true, true"}
					{{endif}}
				</div>
				<ul class='ipsDataItem_stats'>
					{{foreach $row->stats(TRUE) as $k => $v}}
						<li {{if \in_array( $k, $row->hotStats )}}class="ipsDataItem_stats_hot" data-text='{lang="hot_item"}' data-ipsTooltip title='{lang="hot_item_desc"}'{{endif}}>
							<span class='ipsDataItem_stats_number'>{number="$v"}</span>
							<span class='ipsDataItem_stats_type'>{lang="$k" pluralize="$v"}</span>
						</li>
					{{endforeach}}
				</ul>
				<ul class='ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks'>
					<li>
						{{if $row->mapped('num_comments')}}
							{template="userPhoto" app="core" group="global" params="$row->lastCommenter(), 'tiny'"}
						{{else}}
							{template="userPhoto" app="core" group="global" params="$row->author(), 'tiny'"}
						{{endif}}
					</li>
					<li>
						{{if $row->mapped('num_comments')}}
							{$row->lastCommenter()->link()|raw}
						{{else}}
							{$row->author()->link()|raw}
						{{endif}}
					</li>
					<li class="ipsType_light">
						{{if $row->mapped('last_comment')}}
							<a href="{$row->url('getLastComment')}">{datetime="$row->mapped('last_comment')"}</a>
						{{else}}
							{datetime="$row->mapped('date')"}
						{{endif}}
					</li>
				</ul>
				{{if $table->canModerate()}}
					<div class='ipsDataItem_modCheck'>
						<span class='ipsCustomInput'>
							<input type='checkbox' data-role='moderation' name="moderate[{$row->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{{if $row->tableStates()}}{$row->tableStates()}{{endif}}'>
							<span></span>
						</span>
					</div>
				{{endif}}

			</li>
		{{endif}}
	{{endforeach}}
{{endif}}
