<ips:template parameters="$table, $headers, $topic, $showReadMarkers=TRUE" />
{{$idField = $topic::$databaseColumnId;}}
{{$iPosted = isset( $table->contentPostedIn ) ? $table->contentPostedIn : ( ( $table AND method_exists( $table, 'container' ) AND $topic->container() !== NULL ) ? $topic->container()->contentPostedIn() : array() );}}
<li class="ipsDataItem ipsDataItem_responsivePhoto {{if $topic->unread()}}ipsDataItem_unread{{endif}} {{if method_exists( $topic, 'tableClass' ) && $topic->tableClass()}}ipsDataItem_{$topic->tableClass()}{{endif}} {{if $topic->hidden()}}ipsModerated{{endif}}">
	{{if $showReadMarkers}}
		{{if $topic->unread()}}
			<div class='ipsDataItem_icon ipsPos_top'>
				<a href='{$topic->url( 'getNewComment' )}' title='{lang="first_unread_post"}' data-ipsTooltip>
					<span class='ipsItemStatus'><i class="fa {{if \in_array( $topic->$idField, $iPosted )}}fa-star{{else}}fa-circle{{endif}}"></i></span>
				</a>
			</div>
		{{else}}
			{{if \in_array( $topic->$idField, $iPosted )}}
				<div class='ipsDataItem_icon ipsPos_top'>
					<span class='ipsItemStatus ipsItemStatus_read ipsItemStatus_posted'><i class="fa fa-star"></i></span>
				</div>
			{{else}}
				<div class='ipsDataItem_icon ipsPos_top'>&nbsp;</div>
			{{endif}}
		{{endif}}
	{{endif}}
	<div class='ipsDataItem_main'>
		<h4 class='ipsDataItem_title ipsContained_container'>
			{{if $topic->mapped('pinned') || $topic->mapped('featured') || $topic->hidden() === -1 || $topic->hidden() === 1 || $topic->isSolved()}}
				{{if $topic->hidden() === -1}}
					<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$topic->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span></span>
				{{elseif $topic->hidden() === 1}}
					<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span></span>
				{{endif}}							
				{{if $topic->mapped('pinned')}}
					<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span></span>
				{{endif}}
				{{if $topic->mapped('featured')}}
					<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span></span>
				{{endif}}
				{{if $topic->isSolved()}}
					<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="this_is_solved"}'><i class='fa fa-check'></i></span></span>
				{{endif}}
			{{endif}}
			{{if $topic->prefix()}}
				<span>{template="prefix" group="global" app="core" params="$topic->prefix( TRUE ), $topic->prefix()"}</span>
			{{endif}}
			
			<span class='ipsType_break ipsContained'>
				<a href='{$topic->url( "getPrefComment" )}' {{if $topic->canView()}}data-ipsHover data-ipsHover-target='{$topic->url()->setQueryString('preview', 1)}' data-ipsHover-timeout='1.5' {{endif}}>
					{{if $topic->isQuestion()}}
						<strong class='ipsType_light'>{lang="question_title"}:</strong>
					{{endif}}
					{$topic->mapped('title')}
				</a>
			</span>
			{{if $topic->commentPageCount() > 1}}
				{$topic->commentPagination( array(), 'miniPagination' )|raw}
			{{endif}}
		</h4>
		
		<p class='ipsType_reset ipsType_medium ipsType_light'>
			{lang="byline" htmlsprintf="$topic->author()->link()"} {datetime="$topic->mapped('date')"}
			{{if \IPS\Request::i()->controller != 'forums'}}
				{lang="in"} <a href="{$topic->container()->url()}">{$topic->container()->_title}</a>
			{{endif}}
		</p>
		<ul class='ipsList_inline ipsClearfix ipsType_light'>
			{{if $topic->isQuestion()}}
				{{if $topic->topic_answered_pid}}
					<li class='ipsType_success'><i class='fa fa-check-circle'></i> <strong>{lang="answered"}</strong></li>
				{{else}}
					<li class='ipsType_light'><i class='fa fa-question'></i> {lang="awaiting_answer"}</li>
				{{endif}}
			{{endif}}
		</ul>
		{{if \count( $topic->tags() )}}
			&nbsp;&nbsp;
			{template="tags" group="global" app="core" params="$topic->tags(), true, true"}
		{{endif}}
	</div>
	<ul class='ipsDataItem_stats'>
		{{if $topic->isQuestion()}}
			<li>
				<span class='ipsDataItem_stats_number'>{{if $topic->question_rating}}{$topic->question_rating}{{else}}0{{endif}}</span>
				<span class='ipsDataItem_stats_type'>{lang="votes_no_number" pluralize="$topic->question_rating"}</span>
			</li>	
			{{foreach $topic->stats(FALSE) as $k => $v}}
				{{if $k == 'forums_comments' OR $k == 'answers_no_number'}}
					<li>
						<span class='ipsDataItem_stats_number'>{number="$v"}</span>
						<span class='ipsDataItem_stats_type'>{lang="answers_no_number" pluralize="$v"}</span>
					</li>
				{{endif}}
			{{endforeach}}
		{{else}}
			{{foreach $topic->stats(FALSE) as $k => $v}}
				<li {{if \in_array( $k, $topic->hotStats )}}class="ipsDataItem_stats_hot" data-text='{lang="hot_item"}' data-ipsTooltip title='{lang="hot_item_desc"}'{{endif}}>
					<span class='ipsDataItem_stats_number'>{number="$v"}</span>
					<span class='ipsDataItem_stats_type'>{lang="{$k}" pluralize="$v"}</span>
				</li>
			{{endforeach}}
		{{endif}}
	</ul>
	<ul class='ipsDataItem_lastPoster ipsDataItem_withPhoto'>
		<li>
			{{if $topic->mapped('num_comments')}}
				{template="userPhoto" app="core" group="global" params="$topic->lastCommenter(), 'tiny'"}
			{{else}}
				{template="userPhoto" app="core" group="global" params="$topic->author(), 'tiny'"}
			{{endif}}
		</li>
		<li>
			{{if $topic->mapped('num_comments')}}
				{$topic->lastCommenter()->link()|raw}
			{{else}}
				{$topic->author()->link()|raw}
			{{endif}}
		</li>
		<li class="ipsType_light">
			<a href='{$topic->url( 'getLastComment' )}' title='{lang="get_last_post"}' class='ipsType_blendLinks'>
				{{if $topic->mapped('last_comment')}}{datetime="$topic->mapped('last_comment')"}{{else}}{datetime="$topic->mapped('date')"}{{endif}}
			</a>
		</li>
	</ul>
	{{if method_exists( $table, 'canModerate' ) AND $table->canModerate()}}
		<div class='ipsDataItem_modCheck'>
			<span class='ipsCustomInput'>
				<input type='checkbox' data-role='moderation' name="moderate[{$topic->tid}]" data-actions="{expression="implode( ' ', $table->multimodActions( $topic ) )"}" data-state='{{if $topic->tableStates()}}{$topic->tableStates()}{{endif}}'>
				<span></span>
			</span>
		</div>
	{{endif}}
</li>