<ips:template parameters="$items, $title, $orientation='vertical'" />
{{if !empty( $items ) }}
	<h3 class='ipsWidget_title ipsType_reset'>{$title}</h3>
		<div class='ipsPad_half ipsWidget_inner'>
			<ul class='ipsDataList ipsDataList_reducedSpacing'>
				{{foreach $items as $item}}
					<li class='ipsDataItem'>
						<div class='ipsDataItem_main'>
							<div class='ipsType_break ipsContained'><a href="{$item['link']}" target="_blank" rel="noopener" class='ipsTruncate ipsTruncate_line'>{$item['title']}</a></div>
							<span class='ipsType_light ipsType_small'>{datetime="$item['date']"}</span>
						</div>
					</li>
				{{endforeach}}
			</ul>
		</div>
{{endif}}