<ips:template parameters="$statuses,$form,$pagination" />
<div class='ipsBox ipsPad'>
	<div class='ipsPageHeader ipsClearFix ipsSpacer_bottom'>
		<h1 class='ipsType_pageTitle'><a href='#elFeed_menu' id='elFeed' data-ipsMenu data-ipsMenu-align-center>{{if isset( \IPS\Request::i()->following )}}{lang="people_i_follow"}{{else}}{lang="status_updates"}{{endif}} <i class='fa fa-caret-down'></i></a></h1>
	</div>
	<ul id='elFeed_menu' class='ipsMenu ipsMenu_auto ipsMenu_selectable ipsHide ipsType_medium'>
		<li class='ipsMenu_item {{if !isset( \IPS\Request::i()->following )}}ipsMenu_itemChecked{{endif}}'>
			<a href='{url="app=core&module=status&controller=feed" seoTemplate="status"}'>{lang="global_feed"}</a>
		</li>
		{{if \IPS\Member::loggedIn()->member_id }}
		<li class='ipsMenu_item {{if isset( \IPS\Request::i()->following )}}ipsMenu_itemChecked{{endif}}'>
			<a href='{url="app=core&module=status&controller=feed&following=1" seoTemplate="status_following"}'>{lang="people_i_follow"}</a>
		</li>
		{{endif}}
	</ul>
	<div data-controller='core.front.statuses.statusFeed' class='cStatusUpdates'>
		{{if \IPS\core\Statuses\Status::canCreate( \IPS\Member::loggedIn() ) AND $form !== NULL}}
			<div class='ipsComposeArea ipsComposeArea_withPhoto ipsClearfix ipsContained' data-role='newStatus'>
				<div class='ipsPos_left ipsResponsive_hidePhone ipsResponsive_block'>{template="userPhoto" app="core" group="global" params="\IPS\Member::loggedIn(), 'small'"}</div>
				<div class='ipsComposeArea_editor'>
					{$form|raw}
				</div>
			</div>
			<br>
		{{endif}}
		{{if isset( $statuses['statuses'] ) and \count( $statuses['statuses'] )}}
			{$pagination|raw}
			<br><br>
			<ol class='ipsType_normal ipsList_reset' data-role='commentFeed'>
				{{foreach $statuses['statuses'] as $status}}
					{template="statusContainer" app="core" group="statuses" params="$status"}
				{{endforeach}}
			</ol>
		{$pagination|raw}
		{{else}}
			<p class='ipsEmpty ipsType_center'>{lang="no_status_updates"}</p>
		{{endif}}
	</div>
</div>