<ips:template parameters="$club" />
{{$memberStatus = $club->memberStatus( \IPS\Member::loggedIn() );}}
<li class="ipsDataItem {{if settings.clubs_require_approval and !$club->approved}}ipsModerated{{endif}}">
	<div class='ipsDataItem_icon'>
		{template="clubIcon" group="clubs" app="core" params="$club, 'tiny'"}
	</div>
	<div class='ipsDataItem_main'>
		<h4 class='ipsDataItem_title ipsContained_container'>
			{{if settings.clubs_require_approval and !$club->approved}}
				<span><span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="club_unapproved"}'><i class='fa fa-eye-slash'></i></span></span>
			{{else}}
				{{if $club->featured}}
					<span><span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span></span>
				{{endif}}
				{{if \in_array( $memberStatus, array( $club::STATUS_MEMBER, $club::STATUS_MODERATOR, $club::STATUS_LEADER ) )}}
					<span><span class='ipsBadge ipsBadge_positive ipsBadge_icon ipsBadge_small' data-ipsTooltip title="{lang="club_member"}"><i class='fa fa-check'></i></span></span>
				{{elseif \in_array( $memberStatus, array( $club::STATUS_EXPIRED, $club::STATUS_EXPIRED_MODERATOR ) )}}
					<span><span class='ipsBadge ipsBadge_intermediary ipsBadge_icon ipsBadge_small' data-ipsTooltip title="{lang="club_expired"}"><i class='fa fa-exclamation-triangle'></i></span></span>
				{{elseif $memberStatus == $club::STATUS_INVITED or $memberStatus == $club::STATUS_INVITED_BYPASSING_PAYMENT}}
					<span><span class='ipsBadge ipsBadge_neutral ipsBadge_icon ipsBadge_small' data-ipsTooltip title="{lang="club_invited"}"><i class='fa fa-envelope'></i></span></span>
				{{elseif $memberStatus == $club::STATUS_WAITING_PAYMENT}}
					<span><span class='ipsBadge ipsBadge_neutral ipsBadge_icon ipsBadge_small' data-ipsTooltip title="{lang="club_awaiting_payment_title"}"><i class='fa fa-check'></i></span></span>
				{{elseif $memberStatus == $club::STATUS_REQUESTED}}
					<span><span class='ipsBadge ipsBadge_intermediary ipsBadge_icon ipsBadge_small' data-ipsTooltip title="{lang="club_requested_desc_short"}"><i class='fa fa-clock-o'></i></span></span>
				{{endif}}
			{{endif}}
			<span class='ipsType_break ipsContained'>
				<a href='{$club->url()}' title="{$club->name}">{$club->name}</a>
			</span>
		</h4>
		<div class='ipsDataItem_meta ipsType_reset ipsType_light ipsType_blendLinks ipsType_break ipsContained' data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='1 lines'>
			{$club->about}
		</div>
	</div>
	<ul class='ipsDataItem_stats'>
		<li>
			{lang="club_{$club->type}"}
		</li>
		{{if $club->type !== $club::TYPE_PUBLIC}}
			<li class="ipsType_light">
				{lang="club_members_count" pluralize="$club->members"}
			</li>
		{{endif}}
	</ul>
</li>