<ips:template parameters="$club, $location" />
<div class="ipsWidget ipsWidget_vertical ipsBox">
	<h2 class='ipsWidget_title ipsType_reset'>{lang="club_location"}</h2>
	<div class='ipsWidget_inner ipsPad ipsPad_half ipsType_center'>
		{$location->map()->render( 500, 300 )|raw}
		<div class='ipsType_richText ipsType_center ipsType_medium ipsPad_half ipsType_blendLinks'>
			{$location}
		</div>
	</div>
</div>