<ips:template parameters="$featuredClubs, $allClubs, $pagination, $baseUrl, $sortOption, $myClubsActivity, $mapMarkers=NULL, $view='grid'" />

<div class='ipsPageHeader ipsClearfix ipsMargin_bottom'>
	{{if settings.clubs_allow_view_change}}
		<div class="ipsPos_right">
			<ul class="ipsButton_split">
				<li>
					<a href="{url="app=core&module=clubs&controller=directory&view=grid" seoTemplate="clubs_list" csrf="true"}" class="ipsButton {{if $view == 'grid'}}ipsButton_primary{{else}}ipsButton_veryLight{{endif}} ipsButton_narrow ipsButton_small" data-ipsTooltip title="{lang="club_view_grid"}" rel="nofollow">
						<i class="fa fa-th-large"></i>
					</a>
				</li>
				<li>
					<a href="{url="app=core&module=clubs&controller=directory&view=list" seoTemplate="clubs_list" csrf="true"}" class="ipsButton {{if $view == 'list'}}ipsButton_primary{{else}}ipsButton_veryLight{{endif}} ipsButton_narrow ipsButton_small" data-ipsTooltip title="{lang="club_view_list"}" rel="nofollow">
						<i class="fa fa-align-justify"></i>
					</a>
				</li>			
			</ul>
		</div>
	{{endif}}
	<h1 class='ipsType_pageTitle'>{lang="club_directory"}</h1>
</div>

{{if \count( $featuredClubs )}}
	<div class="ipsBox ipsMargin_bottom">
		<h2 class="ipsType_sectionTitle ipsType_reset">{lang="featured_clubs"}</h2>
		{{if $view == 'grid'}}
			<div class="ipsAreaBackground_reset ipsPadding">
				<ul class='ipsGrid ipsGrid_collapsePhone' data-ipsGrid data-ipsGrid-minItemSize='500' data-ipsGrid-maxItemSize='600' data-ipsGrid-equalHeights='row'>
					{{foreach $featuredClubs as $club}}
						<li class='ipsGrid_span6 ipsBox ipsBox--child'>{template="clubCard" group="clubs" app="core" params="$club"}</li>
					{{endforeach}}
				</ul>
			</div>
		{{else}}
			<ol class="ipsDataList ipsDataList_zebra ipsAreaBackground_reset">
				{{foreach $featuredClubs as $club}}
					{template="clubRow" group="clubs" app="core" params="$club"}
				{{endforeach}}
			</ol>
		{{endif}}
	</div>
{{endif}}

{{if $mapMarkers !== NULL && settings.clubs_locations}}
	<div class='ipsBox ipsMargin_bottom'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="club_find_by_location"}</h2>
		<div class='ipsPad_half'>
			<div data-ipsMap data-ipsMap-markers="{expression="json_encode( $mapMarkers )"}" data-ipsMap-contentUrl="{url="app=core&module=clubs&controller=view&do=mapPopup&id="}" class="ipsMap ipsMap_small ipsJS_show"></div>
		</div>
	</div>
{{endif}}

<div class="ipsBox ipsMargin_bottom">
	<h2 class="ipsType_sectionTitle ipsType_reset">{lang="all_clubs"}</h2>
	{{if \count( $allClubs )}}
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
			<ul class="ipsButtonRow ipsPos_right ipsClearfix">
				<li>
					<a href="#elSortByMenu_menu" id="elSortByMenu" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="sort_by"} <i class="fa fa-caret-down"></i></a>
				</li>
				{{if member.member_id or \IPS\Member\Club\CustomField::areFilterableFields() or ( \IPS\Application::appIsEnabled( 'nexus' ) and settings.clubs_paid_on )}}
					<li>
						<a href="{$baseUrl->setQueryString( 'do', 'filters' )}" data-ipsDialog data-ipsDialog-title="{lang="filter"}">{lang="filter"}</a>
					</li>
				{{endif}}
			</ul>
			{$pagination|raw}
			<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elSortByMenu_menu">
				{{foreach array('last_activity', 'members', 'content', 'created', 'name') as $k}}
					<li class="ipsMenu_item {{if $k == $sortOption}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="{$k}">
						<a href="{url="app=core&module=clubs&controller=directory&sort={$k}" seoTemplate="clubs_list"}">{lang="clubs_sort_{$k}"}</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		{{if $view == 'grid'}}
			<div class="ipsAreaBackground_reset ipsPadding">
				<ul class='ipsGrid ipsGrid_collapsePhone' data-ipsGrid data-ipsGrid-minItemSize='500' data-ipsGrid-maxItemSize='600' data-ipsGrid-equalHeights='row'>
					{{foreach $allClubs as $club}}
						<li class='ipsGrid_span6 ipsBox ipsBox--child'>{template="clubCard" group="clubs" app="core" params="$club"}</li>
					{{endforeach}}
				</ul>
			</div>
		{{else}}
			<ol class="ipsDataList ipsDataList_zebra ipsAreaBackground_reset">
				{{foreach $allClubs as $club}}
					{template="clubRow" group="clubs" app="core" params="$club"}
				{{endforeach}}
			</ol>
		{{endif}}
		{{if trim( $pagination )}}
			<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
				{$pagination|raw}
			</div>
		{{endif}}
	{{else}}
		<div class="ipsType_reset ipsType_large ipsType_center ipsPadding">
			{lang="all_clubs_empty"}
		</div>
	{{endif}}
</div>