<ips:template parameters="$club" />
{{$coverPhoto = $club->coverPhoto( FALSE );}}
<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed cClubEmbed'>
	<div class='ipsRichEmbed_header ipsAreaBackground_light ipsClearfix'>
		<a href='{$club->url()}' class='ipsRichEmbed_openItem'><i class='fa fa-external-link-square'></i></a>
		<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsType_blendLinks'>
			{template="userPhoto" app="core" group="global" params="$club->owner, 'tiny'"}
			<div>
				<p class='ipsRichEmbed_title ipsType_reset ipsTruncate ipsTruncate_line'>
					<a href='{$club->url()}'>{lang="club_embed_created_line" sprintf="$club->owner->name"}</a>
				</p>
				<p class='ipsRichEmbed_author ipsType_reset ipsType_light ipsTruncate ipsTruncate_line'>
					<a href='{$club->url()}'>{datetime="$club->created"}</a>
				</p>
			</div>
		</div>
	</div>
	<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center cClubEmbedHeader{{if !$coverPhoto->file}} cClubEmbedHeaderNoPhoto{{endif}}'>
		{{if $coverPhoto->file}}
			<span style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $coverPhoto->file->url )"}" )'>
				{template="clubIcon" group="clubs" app="core" params="$club, 'medium'"}
			</span>
		{{else}}
			<span>{template="clubIcon" group="clubs" app="core" params="$club, 'medium'"}</span>
		{{endif}}
	</div>
	<div class='ipsPadding:half ipsClearfix'>
		<p class='ipsRichEmbed_itemTitle ipsType_reset ipsTruncate ipsTruncate_line ipsType_blendLinks'>
			<a href='{$club->url()}'>{$club->name}</a>
		</p>
		<p class='ipsType_reset ipsType_light ipsType_medium'>
			{lang="club_{$club->type}"}&nbsp;&middot;&nbsp;{lang="club_members_count" pluralize="$club->members"}{{if $club->last_activity}}&nbsp;&middot;&nbsp;{lang="club_last_activity"} {datetime="$club->last_activity"}{{endif}}
		</p>
		{{if $desc = $club->about}}
			<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half' data-truncate='3'>
				{$desc}
			</div>
		{{endif}}

		{{if $club->type != $club::TYPE_PUBLIC}}
			{{if $club->canJoin()}}
				<hr class='ipsHr ipsHr_small'>
				<a class="ipsButton ipsButton_small ipsButton_primary ipsButton_fullWidth" href="{$club->url()->setQueryString('do', 'join')->csrf()}" {{if $club->isPaid() and $club->memberStatus( \IPS\Member::loggedIn() ) !== $club::STATUS_INVITED_BYPASSING_PAYMENT}}data-confirm data-confirmIcon="info" data-confirmMessage="{lang="club_membership_item"}" data-confirmSubmessage="{$club->memberFeeMessage()}"{{endif}}>{lang="club_join"}</a>
			{{endif}}
			{{if $club->canViewMembers() }}
				<hr class='ipsHr ipsHr_small'>
				<ul class='cClubCard_memberList ipsList_inline ipsList_noSpacing ipsMargin_top:half'>
					{{foreach $club->randomTenMembers() as $member}}
						<li>
							{template="userPhotoFromData" group="global" app="core" params="$member['core_members']['member_id'], $member['core_members']['name'], $member['core_members']['members_seo_name'], \IPS\Member::photoUrl( $member['core_members'] ), 'tiny'"}
						</li>
					{{endforeach}}
				</ul>
			{{endif}}
		{{endif}}
	</div>
</div>