<ips:template parameters="$club, $memberStatus" />

{{if \is_array( $memberStatus ) AND \in_array( $memberStatus['status'], array( $club::STATUS_INVITED, $club::STATUS_INVITED_BYPASSING_PAYMENT ) ) && $club->canJoin()}}
    {{if $memberStatus['invited_by']}}
    	{{$invitedBy = \IPS\Member::load( $memberStatus['invited_by'] );}}
    	<div class='ipsBox ipsPadding sm:ipsPadding:half'>
	    	<div class='ipsFlex ipsFlex-ai:center ipsFlex-jc:center ipsFlex-fw:wrap ipsGap:2'>
	    		<div class='ipsFlex-flex:11'>
					<div class='ipsPhotoPanel ipsPhotoPanel_tiny'>
						{template="userPhoto" group="global" app="core" params="$invitedBy, 'tiny'"}
						<div class='ipsType_medium'>
							<h3 class='ipsType_reset ipsType_large'>{lang="club_youre_invited"}</h3>
							<p class='ipsType_reset ipsType_medium'>
								{{if $memberStatus['status'] === $club::STATUS_INVITED_BYPASSING_PAYMENT}}
									{lang="club_invited_bypassing_payment" sprintf="$invitedBy->name"}
								{{else}}
									{lang="club_youre_invited_desc" sprintf="$invitedBy->name"}
								{{endif}}
							</p>
						</div>
					</div>
				</div>
				<div>
					<div  class='ipsFlex ipsGap:2 ipsGap_row:0'>
						<div class='ipsFlex-flex:00'>
							<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_positive" href="{$club->url()->setQueryString('do', 'join')->csrf()}" {{if $club->isPaid() and $memberStatus['status'] !== $club::STATUS_INVITED_BYPASSING_PAYMENT}}data-confirm data-confirmIcon="info" data-confirmMessage="{lang="club_membership_item"}" data-confirmSubmessage="{$club->memberFeeMessage()}"{{endif}}>
								{lang="club_join"}
							</a>
						</div>
						<div class='ipsFlex-flex:00'>
							<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_negative" href="{$club->url()->setQueryString('do', 'leave')->csrf()}" data-confirm>
								{lang="club_decline_invite"}
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr class='ipsHr'>
    {{endif}}
{{elseif \is_array( $memberStatus ) AND $memberStatus['status'] == \IPS\Member\Club::STATUS_BANNED}}
	<div class='ipsBox ipsPadding sm:ipsPadding:half ipsSpacer_bottom'>
		<div class='ipsPhotoPanel ipsPhotoPanel_tiny cClubStatus'>
			<i class='fa fa-times ipsPos_left ipsType_large'></i>
			<div>
				<h3 class='ipsType_reset ipsType_large'>{lang="club_banned_title"}</h3>
				<p class='ipsType_reset ipsType_medium'>
					{lang="club_banned_desc"}
				</p>
			</div>
		</div>
	</div>
{{elseif \is_array( $memberStatus ) AND \in_array( $memberStatus['status'], array( \IPS\Member\Club::STATUS_EXPIRED, \IPS\Member\Club::STATUS_EXPIRED_MODERATOR ) )}}
	<div class='ipsBox ipsPadding sm:ipsPadding:half ipsSpacer_bottom'>
    	<div class='ipsColumns ipsColumns_collapsePhone'>
    		<div class='ipsColumn ipsColumn_fluid'>
				<div class='ipsPhotoPanel ipsPhotoPanel_tiny cClubStatus'>
					<i class='fa fa-exclamation-triangle ipsPos_left ipsType_large'></i>
					<div>
						<h3 class='ipsType_reset ipsType_large'>{lang="club_expired_title"}</h3>
						<p class='ipsType_reset ipsType_medium'>
							{lang="club_expired_desc"}
						</p>
					</div>
				</div>
			</div>
			<div class='ipsColumn ipsColumn_medium'>
				<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_positive" href="{$club->url()->setQueryString('do', 'renew')->csrf()}">
					{lang="club_renew_now"}
				</a>
			</div>
		</div>
	</div>
	<hr class='ipsHr'>
{{elseif !$club->canRead()}}
	<div class='ipsBox ipsPadding sm:ipsPadding:half ipsSpacer_bottom'>
		{{if \is_array( $memberStatus ) AND $memberStatus['status'] === $club::STATUS_REQUESTED}}
			<div class='ipsPhotoPanel ipsPhotoPanel_tiny cClubStatus'>
				<i class='fa fa-clock-o ipsPos_left ipsType_large'></i>
				<div>
					<h3 class='ipsType_reset ipsType_large'>{lang="club_requested_title"}</h3>
					<p class='ipsType_reset ipsType_medium'>
						{{if $club->isPaid()}}
							{lang="club_requested_desc_paid"}
						{{else}}
							{lang="club_requested_desc"}
						{{endif}}
					</p>
				</div>
			</div>
		{{elseif \is_array( $memberStatus ) AND $memberStatus['status'] === $club::STATUS_WAITING_PAYMENT}}
			<div class='ipsColumns ipsColumns_collapsePhone'>
	    		<div class='ipsColumn ipsColumn_fluid'>
					<div class='ipsPhotoPanel ipsPhotoPanel_tiny cClubStatus'>
						<i class='fa fa-check ipsPos_left ipsType_large'></i>
						<div>
							<h3 class='ipsType_reset ipsType_large'>{lang="club_awaiting_payment_title"}</h3>
							<p class='ipsType_reset ipsType_medium'>
								{lang="club_awaiting_payment_desc"}
							</p>
						</div>
					</div>
				</div>
				<div class='ipsColumn ipsColumn_narrow'>
					<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_positive" href="{$club->url()->setQueryString('do', 'join')->csrf()}">
						{lang="club_pay_membership_fee"}
					</a>
				</div>
			</div>			
		{{elseif \is_array( $memberStatus ) AND $memberStatus['status'] === \IPS\Member\Club::STATUS_DECLINED}}
			<div class='ipsPhotoPanel ipsPhotoPanel_tiny cClubStatus'>
				<i class='fa fa-times ipsPos_left ipsType_large'></i>
				<div>
					<h3 class='ipsType_reset ipsType_large'>{lang="club_denied_title"}</h3>
					<p class='ipsType_reset ipsType_medium'>
						{lang="club_denied_desc"}
					</p>
				</div>
			</div>
		{{else}}
			<div class='ipsColumns ipsColumns_collapsePhone'>
	    		<div class='ipsColumn ipsColumn_fluid'>
					<div class='ipsPhotoPanel ipsPhotoPanel_tiny cClubStatus'>
						<i class='fa fa-lock ipsPos_left ipsType_large'></i>
						<div>
							<h3 class='ipsType_reset ipsType_large'>{lang="club_closed_title"}</h3>
							<p class='ipsType_reset ipsType_medium'>
								{lang="club_closed_desc"}
							</p>
							{{if $club->about}}
								<h3 class='ipsType_minorHeading ipsSpacer_top'>{lang="club_about_this_club"}</h3>
								<div class='ipsType_richText ipsType_medium'>
									{$club->about}
								</div>
							{{endif}}
						</div>
					</div>
				</div>
				{{if $club->canJoin()}}
				<div class='ipsColumn ipsColumn_narrow'>
					<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_positive" href="{$club->url()->setQueryString('do', 'join')->csrf()}" {{if $club->isPaid() and \is_array( $memberStatus ) AND $memberStatus['status'] !== $club::STATUS_INVITED_BYPASSING_PAYMENT}}data-confirm data-confirmIcon="info" data-confirmMessage="{lang="club_membership_item"}" data-confirmSubmessage="{$club->memberFeeMessage()}"{{endif}}>
						{lang="club_join"}
					</a>
				</div>
				{{endif}}
			</div>
		{{endif}}
	</div>
{{endif}}