<ips:template parameters="$dateRange, $element" />
<ul class='ipsField_fieldList'>
	<li>
		<span class='ipsCustomInput'>
			<input name="{$element->name}[2]" value='none' type='radio' id='{$element->name}[3]_radio'{{if empty($element->value[0]) AND empty($element->value[1]) AND empty($element->value[3])}} checked{{endif}}> 
			<span></span>
		</span>
		<div class='ipsField_fieldList_content'>
			{lang="any_time"}
		</div>
	</li>
	<li>
		<span class='ipsCustomInput ipsSpacer_top ipsSpacer_half'>
			<input name="{$element->name}[2]" value='range' type='radio' id='{$element->name}[3]_radio' data-control="toggle" data-toggles=""{{if $element->value[0]}} checked{{endif}}> 
			<span></span>
		</span>
		<div class='ipsField_fieldList_content'>
			{$dateRange->html()|raw}
		</div>
	</li>
	<li>
		<span class='ipsCustomInput ipsSpacer_top ipsSpacer_half'>
			<input name="{$element->name}[2]" value='days' type='radio' id='{$element->name}[3]_radio'{{if $element->value[1]}} checked{{endif}}> 
			<span></span>
		</span>
		<div class='ipsField_fieldList_content'>
			{lang="or_more_than"}
			{template="number" location="global" app="core" group="forms" params="$element->name . '[1]', $element->value[1], $element->required, NULL, FALSE, 0, NULL, 1, 0, NULL, FALSE, \IPS\Member::loggedIn()->language()->addToStack( 'days_ago' ), array(), TRUE, array(), $element->name . '_number'"}
		</div>
	</li>
	<li>
		<span class='ipsCustomInput ipsSpacer_top ipsSpacer_half'>
			<input name="{$element->name}[2]" value='days_lt' type='radio' id='{$element->name}[3]_radio'{{if ! empty( $element->value[3])}} checked{{endif}}> 
			<span></span>
		</span>
		<div class='ipsField_fieldList_content'>
			{lang="or_less_than"}
			{template="number" location="global" app="core" group="forms" params="$element->name . '[3]', isset( $element->value[3] ) ? $element->value[3] : NULL, $element->required, NULL, FALSE, 0, NULL, 1, 0, NULL, FALSE, \IPS\Member::loggedIn()->language()->addToStack( 'days_ago' ), array(), TRUE, array(), $element->name . '_number_lt'"}
		</div>
	</li>
</ul>