<ips:template parameters="$table, $headers, $rows" />
{{if \count( $rows )}}
	{{foreach $rows as $row}}
		<li class='ipsDataItem'>
			<div class="ipsDataItem_main ipsType_center">
		   		<h4 class='ipsType_minorHeading'>{datetime="$row['log_date']"}</h4>
		   		<p class='ipsType_reset ipsType_large'>
		      		{$row['log_data']['old']} &nbsp;&nbsp;<i class='fa fa-angle-right'></i>&nbsp;&nbsp; {$row['log_data']['new']}
		      	</p>
		   </div>
		</li>
	{{endforeach}}
{{endif}}