<ips:template parameters="$status" />

{{if $status->commentPageCount() > 1}}
	{template="statusPagination" group="statuses" location="front" app="core" params="$status->url(), $status->commentPageCount(), $status->commentCount(), \IPS\Request::i()->page ? \intval( \IPS\Request::i()->page ) : 1, \IPS\core\Statuses\Status::getCommentsPerPage(), 'prev'"}
{{endif}}
{{foreach $status->commentsForDisplay() as $comment}}
	{$comment->html()|raw}
{{endforeach}}
{{if $status->commentPageCount() > 1}}
	{template="statusPagination" group="statuses" location="front" app="core" params="$status->url(), $status->commentPageCount(), $status->commentCount(), \IPS\Request::i()->page ? \intval( \IPS\Request::i()->page ) : 1, \IPS\core\Statuses\Status::getCommentsPerPage(), 'next'"}
{{endif}}