<ips:template parameters="$status, $authorData=NULL, $profileOwnerData=NULL, $condensed=FALSE, $table=NULL" />

<li {{if !$condensed}}data-controller='core.front.statuses.status'{{endif}} class='ipsStreamItem ipsStreamItem_contentBlock {{if $condensed}}ipsStreamItem_condensed{{endif}} {{if $status->hidden()}} ipsModerated{{endif}} ipsAreaBackground_reset ipsPad' data-timestamp='{$status->date}' data-role='activityItem' data-statusid="{$status->id}">
	<a id='status-{$status->id}'></a>
	<div class='ipsStreamItem_container'>
		<div class='ipsStreamItem_header ipsPhotoPanel ipsPhotoPanel_mini'>
			<span class='ipsStreamItem_contentType' data-ipsTooltip title='{lang="status_update"}'><i class='fa fa-user'></i></span>
			{{if $authorData}}
				{template="userPhotoFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], \IPS\Member::photoUrl( $authorData ), ( $condensed ? 'tiny' : 'mini' )"}
			{{else}}
				{template="userPhoto" group="global" app="core" params="$status->author(), ( $condensed ? 'tiny' : 'mini' )"}
			{{endif}}
			<div>
				<h2 class='ipsType_reset ipsStreamItem_title {{if $condensed}}ipsStreamItem_titleSmall{{endif}} ipsType_break'>
					{{if $status->member_id != $status->author()->member_id}}
						<ul class='ipsList_inline ipsList_noSpacing'>
							<li>
								<strong>
									{{if $authorData}}
										{template="userLinkFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], $authorData['member_group_id']"}
									{{else}}
										{template="userLink" app="core" group="global" location="front" params="$status->author()"}
									{{endif}}
								</strong>
							</li>
							<li>
								&nbsp;<i class='fa fa-angle-right'></i>&nbsp;
							</li>
							<li>
								<strong>
									{{if $profileOwnerData}}
										{template="userLinkFromData" group="global" app="core" params="$profileOwnerData['member_id'], $profileOwnerData['name'], $profileOwnerData['members_seo_name'], $profileOwnerData['member_group_id']"}
									{{else}}
										{member="link()" id="$status->member_id" raw="true"}
									{{endif}}
								</strong>
							</li>
						</ul>
					{{else}}
						<strong>
							{{if $authorData}}
								{template="userLinkFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], $authorData['member_group_id']"}
							{{else}}
								{template="userLink" app="core" group="global" location="front" params="$status->author()"}
							{{endif}}
						</strong>
					{{endif}}
					{{if $status->hidden() AND $status->hidden() != -2}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="hidden"}'><i class='fa fa-eye-slash'></i></span>
					{{elseif $status->hidden() == -2}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{$status->deletedBlurb()}'><i class='fa fa-trash'></i></span>
					{{endif}}
				</h2>
				{{if $condensed}}
					<ul class='ipsList_inline ipsStreamItem_stats ipsType_light'>
						<li>
							<a href='{$status->url()}' class='ipsType_blendLinks'><i class='fa fa-clock-o'></i> {datetime="$status->date"}</a>
						</li>
					</ul>
					<p class="ipsStreamItem_status ipsType_reset">
						{{if $status->member_id == $status->author()->member_id}}
							{{if $authorData}}
								{lang="member_posted_status_self" sprintf="$authorData['name']"}
							{{else}}
								{lang="member_posted_status_self" sprintf="$status->author()->name"}
							{{endif}}
						{{else}}
							{{if $authorData}}
								{lang="member_posted_status_other" sprintf="$authorData['name'], $profileOwnerData['name']"}
							{{else}}
								{lang="member_posted_status_other" sprintf="$status->author()->name, \IPS\Member::load( $status->member_id )->name"}
							{{endif}}
						{{endif}}
					</p>
				{{endif}}
			</div>
		</div>
		{{if !$condensed}}
			<div class='ipsStreamItem_snippet' {{if ( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-searchable data-findTerm{{endif}}>
				<div class='ipsType_richText ipsType_normal ipsContained' data-controller='core.front.core.lightboxedImages'>{$status->content|raw}</div>
			</div>
		{{endif}}
		{{if !$condensed}}
			<ul class='ipsList_inline ipsStreamItem_meta ipsFaded_withHover'>
				<li class='ipsType_medium'>{{if $status->locked()}}<i class='fa fa-lock'></i>{{endif}} <a href='{$status->url()}' class='ipsType_blendLinks'><span class='ipsType_light'><i class='fa fa-clock-o'></i> {datetime="$status->date"}</span></a></li>
				{{if \IPS\IPS::classUsesTrait( $status, 'IPS\Content\Reactable' ) and settings.reputation_enabled and ( \count( $status->reactions() ) or $status->canReact() )}}
					<li class='ipsType_light ipsType_medium'>{template="reputationMini" group="global" app="core" params="$status"}</li>
				{{endif}}
				{{if $status->canEdit()}}
					<li>
						<a class='ipsFaded ipsFaded_more' data-ipsDialog data-ipsDialog-title='{lang="edit"}' href='{$status->url('editStatus')}'>{lang="edit"}</a>
					</li>
				{{endif}}
				{{if $status->canDelete() || $status->canLock() || $status->canUnlock() || $status->canHide() || $status->canUnhide()}}
					<li>
						<a href='#elStatus_{$status->id}_menu' data-ipsMenu data-ipsMenu-activeClass='ipsFaded_cancel' id='elStatus_{$status->id}' class='ipsFaded ipsFaded_more'>{lang="options"} <i class='fa fa-caret-down'></i></a>
						<ul class='ipsMenu ipsMenu_narrow ipsHide' id='elStatus_{$status->id}_menu'>
							{{if !$status->locked() and $status->canLock()}}
								<li class='ipsMenu_item'><a href="{$status->url('moderate')->setQueryString( 'action', 'lock' )->csrf()}">{lang="lock"}</a></li>
							{{elseif $status->locked() and $status->canUnlock()}}
								<li class='ipsMenu_item'><a href="{$status->url('moderate')->setQueryString( 'action', 'unlock' )->csrf()}">{lang="unlock"}</a></li>
							{{endif}}
							{{if !$status->hidden() and $status->canHide()}}
								<li class='ipsMenu_item'><a href='{$status->url('moderate')->setQueryString( 'action', 'hide' )->csrf()}'>{lang="hide"}</a></li>
							{{elseif $status->hidden() and $status->canUnhide()}}
								<li class='ipsMenu_item'><a href='{$status->url('moderate')->setQueryString( 'action', 'unhide' )->csrf()}'>{lang="unhide"}</a></li>
							{{endif}}
							{{if $status->canDelete()}}
								<li class='ipsMenu_item'><a data-confirm href="{$status->url('moderate')->setQueryString( 'action', 'delete' )->csrf()}">{lang="delete"}</a></li>
							{{endif}}
						</ul>
					</li>
				{{endif}}
				{{if $status->canReportOrRevoke() === TRUE}}
					<li><a href='{$status->url('report')}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title="{lang="report"}" data-action='reportStatus' title='{lang="report_content"}' class='ipsFaded ipsFaded_more'>{lang="status_report"}</a></li>
				{{endif}}	
			</ul>
		{{endif}}
		{{if !$condensed && ( \count( $status->comments() ) ||  $status->canComment() )}}
			<div class='ipsComment_feed ipsComment_subComments ipsType_medium'>
				<ol class="ipsList_reset" data-role='statusComments' data-currentPage='{expression="\IPS\Request::i()->page ? \intval( \IPS\Request::i()->page ) : 1"}'>
					{template="statusReplies" group="statuses" params="$status"}
				</ol>
				{{if \IPS\core\Statuses\Status::canCreateReply( \IPS\Member::loggedIn() )}}
					<div class="ipsComment ipsFieldRow_fullWidth ipsAreaBackground_light ipsPad" data-role="replyComment">
						<div class="ipsComment_content ipsContained">
							{$status->commentForm()|raw}
						</div>
					</div>
				{{endif}}
			</div>
		{{endif}}
		{{if method_exists( $table, 'canModerate' ) AND $table->canModerate()}}
		<div class='ipsDataItem_modCheck'>
			<span class='ipsCustomInput'>
				<input type='checkbox' data-role='moderation' name="moderate[{$status->id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $status ) )"}" data-state='{{if $status->tableStates()}}{$status->tableStates()}{{endif}}'>
				<span></span>
			</span>
		</div>
		{{endif}}
	</div>
</li>