<ips:template parameters="$status, $comment" />
<div class="ipsComment_content ipsFaded_withHover" data-controller="core.front.core.comment" data-commentID="{$comment->id}">
	<p class="ipsComment_author ipsType_normal">
		<strong>{template="userLink" app="core" group="global" location="front" params="$comment->author()"}</strong>
		{{if $comment->hidden() AND $comment->hidden() != -2}}
			<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="hidden"}'><i class='fa fa-eye-slash'></i></span>
		{{elseif $comment->hidden() == -2}}
			<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$comment->deletedBlurb()}'><i class='fa fa-trash'></i></span>
		{{endif}}
	</p>
	<div data-role="commentContent" class='ipsType_richText ipsType_medium ipsContained' data-controller='core.front.core.lightboxedImages'>
		{$comment->content|raw}
	</div>
	<ul class="ipsList_inline ipsType_medium cStatusTools">
		<li class="ipsType_light"><a href='{$comment->url()}' class='ipsType_blendLinks'>{datetime="$comment->date"}</a></li>
		{{if \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and settings.reputation_enabled and ( \count( $comment->reactions() ) or $comment->canReact() )}}
			<li>{template="reputationMini" group="global" app="core" params="$comment"}</li>
		{{endif}}
		{{if $comment->canEdit()}}
			<li>
				<a href='{$comment->url('editStatusReply')}' class='ipsFaded ipsFaded_more' data-action='editComment'>{lang="edit"}</a>
			</li>
		{{endif}}
		{{if $comment->canDelete() || ( $comment instanceof \IPS\Content\Hideable && ( !$comment->hidden() and $comment->canHide() ) || ( $comment->hidden() and $comment->canUnhide() ) ) }}
			<li>
				<a href='#elComment_{$comment->id}_menu' id='elComment_{$comment->id}' data-ipsMenu data-ipsMenu-activeClass='ipsFaded_cancel' class='ipsFaded ipsFaded_more'>{lang="options"} <i class='fa fa-caret-down'></i></a>
				<ul class='ipsMenu ipsMenu_narrow ipsHide' id='elComment_{$comment->id}_menu'>
					{{if $comment instanceof \IPS\Content\Hideable}}
						{{if !$comment->hidden() and $comment->canHide()}}
							<li class='ipsMenu_item'><a href='{$comment->url('moderate')->setQueryString( 'action', 'hide' )->csrf()}'>{lang="hide"}</a></li>
						{{elseif $comment->hidden() and $comment->canUnhide()}}
							<li class='ipsMenu_item'><a href='{$comment->url('moderate')->setQueryString( 'action', 'unhide' )->csrf()}'>{lang="unhide"}</a></li>
						{{endif}}
					{{endif}}
					{{if $comment->canDelete()}}
						<li class='ipsMenu_item'><a data-confirm href='{$comment->url('moderate')->setQueryString( 'action', 'delete' )->csrf()->setPage('page',\IPS\Request::i()->page)}' data-action='deleteComment' data-updateOnDelete="#commentCount">{lang="delete"}</a></li>
					{{endif}}
				</ul>
			</li>
		{{endif}}
		{{if $comment->canReportOrRevoke() === TRUE}}
			<li><a href='{$comment->url('report')}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title="{lang="report"}" data-action='reportComment' title='{lang="report_content"}' class='ipsFaded ipsFaded_more'>{lang="status_report"}</a></li>
		{{endif}}
	</ul>
</div>