<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $reply}}
	{{$item = $reply->item();}}
	<li data-controller='core.front.statuses.status' class='ipsStreamItem ipsStreamItem_contentBlock {{if $item->hidden()}} ipsModerated{{endif}} ipsAreaBackground_reset ipsPad' data-timestamp='{$item->date}' data-role='activityItem' data-statusid="{$item->id}">
		<a id='status-{$item->id}'></a>
		<div class='ipsStreamItem_container'>
			<div class='ipsStreamItem_header ipsPhotoPanel ipsPhotoPanel_mini'>
				<span class='ipsStreamItem_contentType' data-ipsTooltip title='{lang="status_update"}'><i class='fa fa-user'></i></span>
				{template="userPhoto" group="global" app="core" params="$item->author(), 'mini'"}
				<div>
					<h2 class='ipsType_reset ipsStreamItem_title ipsType_break'>
						<strong>{template="userLink" app="core" group="global" location="front" params="$item->author()"}</strong>{{if $item->member_id != $item->author()->member_id}} &nbsp;<i class='fa fa-angle-right'></i>&nbsp; <strong>{member="link()" id="$item->member_id" raw="true"}</strong>{{endif}}
						{{if $item->hidden()}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="hidden"}'><i class='fa fa-eye-slash'></i></span>
						{{endif}}
					</h2>
				</div>
			</div>
			<div class='ipsStreamItem_snippet'>
				<div class='ipsType_richText ipsType_normal ipsContained'>{$item->content|raw}</div>
			</div>
			<ul class='ipsList_inline ipsStreamItem_meta ipsFaded_withHover'>
				<li class='ipsType_medium'>{{if $item->locked()}}<i class='fa fa-lock'></i>{{endif}} <a href='{$item->url()}' class='ipsType_blendLinks'><span class='ipsType_light'>{datetime="$item->date"}</span></a></li>
				{{if \IPS\IPS::classUsesTrait( $item, 'IPS\Content\Reactable' ) and settings.reputation_enabled and ( $item->reactionCount() or $item->canReact() )}}
					<li class='ipsType_light ipsType_medium'>{template="reputationMini" group="global" app="core" params="$item"}</li>
				{{endif}}
				{{if $item->canDelete() || $item->canLock() || $item->canUnlock() || $item->canHide() || $item->canUnhide()}}
					<li>
						<a href='#elStatus_{$item->id}_menu' data-ipsMenu data-ipsMenu-activeClass='ipsFaded_cancel' id='elStatus_{$item->id}' class='ipsFaded ipsFaded_more'>{lang="options"} <i class='fa fa-caret-down'></i></a>
						<ul class='ipsMenu ipsMenu_narrow ipsHide' id='elStatus_{$item->id}_menu'>
							{{if !$item->locked() and $item->canLock()}}
								<li class='ipsMenu_item'><a href="{$item->url('moderate')->setQueryString( 'action', 'lock' )->csrf()}">{lang="lock"}</a></li>
							{{elseif $item->locked() and $item->canUnlock()}}
								<li class='ipsMenu_item'><a href="{$item->url('moderate')->setQueryString( 'action', 'unlock' )->csrf()}">{lang="unlock"}</a></li>
							{{endif}}
							{{if !$item->hidden() and $item->canHide()}}
								<li class='ipsMenu_item'><a href='{$item->url('moderate')->setQueryString( 'action', 'hide' )->csrf()}'>{lang="hide"}</a></li>
							{{elseif $item->hidden() and $item->canUnhide()}}
								<li class='ipsMenu_item'><a href='{$item->url('moderate')->setQueryString( 'action', 'unhide' )->csrf()}'>{lang="unhide"}</a></li>
							{{endif}}
							{{if $item->canDelete()}}
								<li class='ipsMenu_item'><a data-confirm href="{$item->url('moderate')->setQueryString( 'action', 'delete' )->csrf()}">{lang="delete"}</a></li>
							{{endif}}
						</ul>
					</li>
				{{endif}}
				{{if $item->canReportOrRevoke() === TRUE}}
					<li><a href='{$item->url('report')}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title="{lang="report"}" data-action='reportStatus' title='{lang="report_content"}' class='ipsFaded ipsFaded_more'>{lang="status_report"}</a></li>
				{{endif}}	
			</ul>

			{{if !$item->hidden() && ( \count( $item->comments() ) ||  \IPS\core\Statuses\Status::canCreate( \IPS\Member::loggedIn() ) ) }}
				<div class='ipsComment_feed ipsComment_subComments ipsType_medium'>
					<ol class="ipsList_reset" data-role='statusComments' data-currentPage='{expression="\IPS\Request::i()->page ? \intval( \IPS\Request::i()->page ) : 1"}'>
						{template="statusReplyContainer" group="statuses" params="$item, $reply"}
						{{if ( $item->mapped('num_comments') - 1 ) > 0}}
							<li class='ipsComment ipsAreaBackground_light ipsPad_half ipsType_light'>
								<p class='ipsType_reset ipsType_medium ipsComment_content'><a href='{$item->url()}'>{lang="status_see_x_other_replies" pluralize="( $item->mapped('num_comments') - 1 )"}</a></p>
							</li>
						{{endif}}
					</ol>
				</div>
			{{endif}}	
		</div>
	</li>

{{endforeach}}