<ips:template parameters="$editorId, $mediaSources, $currentMediaSource, $url, $results" />
{{$safeEditorId = preg_replace( "/[^a-zA-Z0-9\-_]/", '_', $editorId );}}
<div class="cMyMedia" data-controller='core.global.editor.mymedia, core.global.editor.insertable' data-editorid='{$editorId}'>
	<div id="elEditor{$safeEditorId}Attach">
		{{if \count( $mediaSources ) > 1}}
			<div class="ipsColumns ipsColumns_collapsePhone"  data-ipsTabBar data-ipsTabBar-contentArea='#elEditor{$safeEditorId}AttachTabContent' data-ipsTabBar-itemSelector=".ipsSideMenu_item" data-ipsTabBar-activeClass="ipsSideMenu_itemActive" data-ipsTabBar-updateURL="false">
				<div class="ipsColumn ipsColumn_medium">
					<div class="ipsSideMenu ipsPad" id='elAttachmentsMenu_{$safeEditorId}' data-ipsSideMenu>
						<h3 class='ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium'>
							<a href='#elAttachmentsMenu_{$safeEditorId}' class='ipsPad_double' data-action='openSideMenu'><i class='fa fa-bars'></i> &nbsp;{lang="editor_attachment_location"}&nbsp;<i class='fa fa-caret-down'></i></a>
						</h3>
						<ul class="ipsSideMenu_list">
							{{foreach $mediaSources as $k}}
								<li>
									<a href="{url="app=core&module=system&controller=editor&do=myMedia&tab={$k}&existing=1"}" id="elEditor{$safeEditorId}AttachTabMedia{$k}" class="ipsSideMenu_item {{if $currentMediaSource == $k}}ipsSideMenu_itemActive{{endif}}">{lang="editorMedia_{$k}"}</a>
								</li>
							{{endforeach}}
						</ul>
					</div>
				</div>
				<div class="ipsColumn ipsColumn_fluid">
		{{endif}}
			<div id="elEditor{$safeEditorId}AttachTabContent" data-role="myMediaContent" class='ipsPad'>
				{{if \count( $mediaSources ) }}
					{$results|raw}
				{{else}}
					{lang="editor_no_media"}
				{{endif}}
			</div>
		{{if \count( $mediaSources ) > 1}}
				</div>
			</div>
		{{endif}}
	</div>
	<div class='ipsPad ipsAreaBackground cMyMedia_controls'>
		<ul class='ipsList_inline ipsType_right'>
			<li><a href='#' data-action="clearAll" class='ipsButton ipsButton_verySmall ipsButton_veryLight ipsButton_disabled'>{lang="editor_clear_selection"}</a></li>
			<li><a href='#' data-action="insertSelected" class='ipsButton ipsButton_verySmall ipsButton_normal ipsButton_disabled'>{lang="editor_image_upload_insert_selected"}</a></li>
		</ul>
	</div>
</div>