<ips:template parameters="$segments, $sorted=TRUE, $classes=''" />

{{if \count( $segments )}}
    <div class='ipsPieBar {$classes}'>
        <div class='ipsPieBar__bar'>
            {{foreach $segments as $segment}}
                <div class='ipsPieBar__barSegment' style='width: {$segment['percentage']}%' 
                    {{if !empty( $segment['title'] ) || !empty( $segment['tooltip'] )}}
                        {{if !empty( $segment['title'] )}}title="{$segment['title']}"{{endif}} {{if !empty( $segment['tooltip'] )}}data-ipsTooltip data-ipsTooltip-label="{$segment['tooltip']}" {{if !empty( $segment['tooltipSafe'] )}}data-ipsTooltip-safe{{endif}}{{endif}}
                    {{else}}
                        title="{$segment['value']} ({$segment['percentage']}%)"
                        data-ipsTooltip
                    {{endif}}
                ></div>
            {{endforeach}}
        </div>
        <ul class='ipsList_inline ipsPieBar__legend'>
            {{foreach $segments as $segment}}
                <li class='ipsPieBar__legendItem'>
                    <span class='ipsPieBar__legendItemKey'></span>
                    {{if isset( $segment['nameRaw'] )}}{$segment['nameRaw']|raw}{{else}}{$segment['name']}{{endif}}
                </li>
            {{endforeach}}
        </ul>
    </div>
{{else}}
    <p class='ipsType_light ipsType_center'>
        {lang="no_data"}
    </p>
{{endif}}