<ips:template parameters="$chart, $html" />
<div class='ipsChart' data-controller='core.admin.core.dynamicChart' data-chart-url='{$chart->baseURL}' data-chart-identifier='{$chart->identifier}' data-chart-type="{$chart->type}" data-chart-timescale="{$chart->timescale}" data-chart-customfilter-submitted='{{if isset( \IPS\Request::i()->filter_form_submitted )}}true{{else}}false{{endif}}'>
	<div class='ipsPad ipsAreaBackground_light ipsClearfix ipsChart_filters'>
		{{if ( \IPS\Request::i()->chartId AND \IPS\Request::i()->chartId != '_default' ) OR $chart->title}}
			<div class='ipsClearfix ipsSpacer_bottom ipsSpacer_half'>
		{{endif}}
		{{if $chart->form AND \IPS\Request::i()->chartId AND \IPS\Request::i()->chartId != '_default'}}
			<a data-confirm href='{$chart->baseURL->setQueryString( array( 'deleteChart' => \IPS\Request::i()->chartId ) )}' class='ipsPos_right ipsButton_veryVerySmall ipsButton ipsButton_negative'>{lang="delete"}</a>
			<button data-role="renameChart" class='ipsPos_right ipsButton_veryVerySmall ipsButton ipsButton_neutral' data-ipsMenu data-ipsMenu-closeOnClick='false' id='el{$chart->identifier}FilterRename'>{lang="stream_rename"}</button>
			<ul id='el{$chart->identifier}FilterRename_menu' class='ipsMenu ipsMenu_auto ipsHide' data-role="filterRenameMenu">
				<li class='ipsMenu_item'>{$chart->form->customTemplate( array( \IPS\Theme::i()->getTemplate( 'forms', 'core', 'front' ), 'popupTemplate' ) )|raw}</li>
			</ul>
		{{endif}}
		{{if $chart->title}}
			<h2 class='ipsType_sectionHead'>{$chart->title}</h2>
		{{endif}}
		{{if ( \IPS\Request::i()->chartId AND \IPS\Request::i()->chartId != '_default' ) OR $chart->title}}
			</div>
		{{endif}}
		<ul class='ipsList_inline'>
			{{if $chart->showIntervals}}
				<li data-role="groupingButtons">
					<span class="ipsButton_split ipsClearfix">
						{{if $chart->enableHourly}}
							<a class='ipsButton ipsButton_verySmall {{if $chart->type == 'Table'}}ipsButton_disabled ipsButton_veryLight{{else}}{{if $chart->timescale == 'hourly'}}ipsButton_primary{{else}}ipsButton_veryLight{{endif}}{{endif}}' href="{$chart->url->setQueryString( array( 'timescale' => array( $chart->identifier => 'hourly' ), 'noheader' => 1 ) )}" data-timescale="hourly" {{if $chart->timescale == 'hourly'}}data-selected{{endif}}>{lang="stats_date_group_hourly"}</a>
						{{endif}}
						{{foreach array( 'daily', 'weekly', 'monthly' ) as $k}}
							<a class='ipsButton ipsButton_verySmall {{if $chart->type == 'Table'}}ipsButton_disabled ipsButton_veryLight{{else}}{{if $chart->timescale == $k}}ipsButton_primary{{else}}ipsButton_veryLight{{endif}}{{endif}}' href="{$chart->url->setQueryString( array( 'timescale' => array( $chart->identifier => $k ), 'noheader' => 1 ) )}" data-timescale="{$k}" {{if $chart->timescale == $k}}data-selected{{endif}}>{lang="stats_date_group_$k"}</a>
						{{endforeach}}
					</span>
				</li>
			{{endif}}
			<li class="ipsClearfix">
				<a data-action='chartDate' data-ipsMenu data-ipsMenu-closeOnBlur='false' data-ipsMenu-closeOnClick='false' id='el{$chart->identifier}Date' href="#" class="ipsButton ipsButton_verySmall ipsButton_veryLight"><i class='fa fa-calendar'></i> &nbsp;{lang="stats_date_range"} <span data-role='dateSummary' class='ipsType_light'>{{if $chart->start AND $chart->end}}({lang="search_betweenXandX" sprintf="$chart->start->localeDate(), $chart->end->localeDate()"}){{elseif $chart->start}}({lang="search_afterX" sprintf="$chart->start->localeDate()"}){{elseif $chart->end}}({lang="search_beforeX" sprintf="$chart->end->localeDate()"}){{endif}}</span> <i class='fa fa-caret-down'></i></a>
				<div id='el{$chart->identifier}Date_menu' class='ipsMenu ipsMenu_normal ipsHide ipsPad'>
					<form accept-charset='utf-8' action="{$chart->url}" method="post" data-role="dateForm" data-ipsForm>
						{template="date" group="forms" location="global" app="core" params="'start', $chart->start ?: NULL, FALSE, NULL, NULL, FALSE, FALSE, NULL, NULL, NULL, array(), TRUE, 'ipsField_fullWidth', \IPS\Member::loggedIn()->language()->addToStack('stats_start_date')"}
						<br><br>
						{template="date" group="forms" location="global" app="core" params="'end', $chart->end ?: NULL, FALSE, NULL, NULL, FALSE, FALSE, NULL, NULL, NULL, array(), TRUE, 'ipsField_fullWidth', \IPS\Member::loggedIn()->language()->addToStack('stats_end_date')"}
						<br><br>
						<button type="submit" class="ipsButton ipsButton_primary ipsButton_fullWidth" data-role="updateDate">{lang="submit"}</button>
					</form>
				</div>
			</li>
			{{if ! $chart->customFiltersForm and \count( $chart->availableFilters ) > 0}}
				<li>
					<a data-action="chartFilter" data-ipsMenu data-ipsMenu-selectable data-ipsMenu-closeOnClick='false' id='el{$chart->identifier}Filter' href="#" class="ipsButton ipsButton_verySmall ipsButton_veryLight"><i class='fa fa-filter'></i> &nbsp;{lang="stats_chart_filters"} <i class='fa fa-caret-down'></i></a>
					<ul id='el{$chart->identifier}Filter_menu' class='ipsMenu ipsMenu_selectable ipsMenu_auto ipsHide' data-role='filterMenu'>
						<li class='ipsMenu_item ipsMenu_itemNonSelect ipsType_center' data-noselect>
							<span>
								<a href='#' data-role='selectAll' class='ipsMenu_itemInline'>{lang="all"}</a>
								<a href='#' data-role='unselectAll' class='ipsMenu_itemInline'>{lang="none"}</a>
							</span>
						</li>
						{{foreach $chart->availableFilters as $f => $name}}
							<li class='ipsMenu_item {{if \in_array( $f, $chart->currentFilters )}}ipsMenu_itemChecked{{endif}}' data-ipsMenuValue='{$f}'><a href="{$chart->flipUrlFilter( $f )}">{$name}</a></li>
						{{endforeach}}
						<li class='ipsMenu_item ipsMenu_itemNonSelect' data-noselect>
							<span>
								<button disabled class='ipsMenu_itemInline ipsButton ipsButton_small ipsButton_primary ipsButton_fullWidth' data-role="applyFilters">{lang="apply_filters"}</button>
							</span>
						</li>
					</ul>
				</li>
			{{endif}}
			{{if $chart->customFiltersForm}}
				<li>
					<a href="#elCustomFiltersForm" class="ipsButton ipsButton_verySmall ipsButton_veryLight" data-ipsDialog data-ipsDialog-size="narrow" data-ipsDialog-title="{lang="chart_customfilters_title"}" data-ipsDialog-content="#el{$chart->identifier}CustomFiltersForm"><i class='fa fa-bar-chart'></i> &nbsp;{lang="chart_customfilters_title"}</a>
					<div id='el{$chart->identifier}CustomFiltersForm' class='ipsAreaBackground_light ipsPad ipsJS_hide'>
						{$chart->getCustomFiltersForm()->customTemplate( array( \IPS\Theme::i()->getTemplate( 'forms', 'core', 'front' ), 'popupTemplate' ) )|raw}
					</div>
				</li>
			{{endif}}
			{{if isset( $chart->options['limitSearch'] )}}
				<li class="ipsClearfix">
					<a data-action='chartSearch' data-ipsMenu data-ipsMenu-closeOnBlur='false' data-ipsMenu-closeOnClick='false' id='el{$chart->identifier}Search' href="#" class="ipsButton ipsButton_verySmall ipsButton_veryLight">{lang="$chart->options['limitSearch']"} <span data-role='searchSummary' class='ipsType_light'></span> <i class='fa fa-caret-down'></i></a>
					<div id='el{$chart->identifier}Search_menu' class='ipsMenu ipsMenu_normal ipsHide ipsPad'>
						<form accept-charset='utf-8' action="{$chart->url}" method="post" data-role="searchForm" data-ipsForm>
							{template="text" group="forms" location="global" app="core" params="'search', 'text', NULL, FALSE"}
							<br><br>
							<button type="submit" class="ipsButton ipsButton_primary ipsButton_fullWidth" data-role="updateSearch">{lang="submit"}</button>
							<button type="submit" value='reset' class="ipsButton ipsButton_light ipsButton_fullWidth ipsSpacer_top ipsSpacer_half" data-role="clearSearchTerm">{lang="stats_search_reset"}</button>
						</form>
					</div>
				</li>
			{{endif}}
			{{if $chart->customFiltersForm or \count( $chart->availableFilters ) > 0}}
				<li>
					<button class='ipsButton ipsButton_verySmall ipsButton_important ipsHide' data-role='saveReport' {{if !\IPS\Request::i()->chartId OR \IPS\Request::i()->chartId == '_default'}}data-ipsMenu data-ipsMenu-closeOnClick='false'{{else}}data-chartId='{request="chartId"}'{{endif}} id='el{$chart->identifier}FilterSave'>{lang="save"}</button>
					{{if !\IPS\Request::i()->chartId OR \IPS\Request::i()->chartId == '_default'}}
						<ul id='el{$chart->identifier}FilterSave_menu' class='ipsMenu ipsMenu_auto ipsHide' data-role='filterSaveMenu'>
							<li class='ipsMenu_item'>{$chart->form->customTemplate( array( \IPS\Theme::i()->getTemplate( 'forms', 'core', 'front' ), 'popupTemplate' ) )|raw}</li>
						</ul>
					{{endif}}
				</li>
			{{endif}}
			{{if \count( $chart->availableTypes ) > 1 || $chart instanceof \IPS\Helpers\Chart\Dynamic}}
				<li class='ipsPos_right ipsType_noBreak'>
					{{if $chart instanceof \IPS\Helpers\Chart\Dynamic}}
						&nbsp;&nbsp;<a class='ipsButton ipsButton_veryLight ipsButton_verySmall' href='{$chart->url->setQueryString(array( "download" => 1 ))->csrf() }' data-ipsTooltip title='{lang="download_as_csv"}' data-role='downloadChart'><i class="fa fa-download"></i> &nbsp;CSV</a>
					{{endif}}
					{{if \count( $chart->availableTypes ) > 1}}
						<span class="ipsButton_split ipsClearfix">
							{{foreach $chart->availableTypes as $t}}
								<a class='ipsButton ipsButton_verySmall {{if $chart->type == $t}}ipsButton_primary{{else}}ipsButton_veryLight{{endif}}' href="{$chart->url->setQueryString( array( 'type' => array( $chart->identifier => $t ), 'noheader' => 1 ) )}" data-ipsTooltip title='{lang="chart_{$t}"}' data-type='{$t}' {{if $chart->type == $t}}data-selected{{endif}}>
									{{if $t === 'Table'}}
										<i class="fa fa-table"></i>
									{{elseif $t === 'LineChart'}}
										<i class="fa fa-line-chart"></i>
									{{elseif $t == 'AreaChart'}}
										<i class='fa fa-area-chart'></i>
									{{elseif $t === 'ColumnChart'}}
										<i class="fa fa-bar-chart"></i>
									{{elseif $t === 'BarChart'}}
										<i class="fa fa-bar-chart fa-rotate-90"></i>
									{{elseif $t === 'PieChart'}}
										<i class="fa fa-pie-chart"></i>
									{{elseif $t === 'GeoChart'}}
										<i class="fa fa-globe"></i>
									{{endif}}
								</a>
							{{endforeach}}
						</span>
					{{endif}}
				</li>
			{{endif}}
		</ul>
		
	</div>
	<div class='ipsChart_chart ipsPad' data-role="chart">
		{$html|raw}
	</div>
</div>
{{if $chart->timezoneError and member.isAdmin()}}
	<p class="ipsType_small ipsType_light ipsPad ipsPad_half"><i class="fa fa-info-circle"></i> {lang="dynamic_chart_timezone_info"}{{if $chart->hideTimezoneLink === FALSE}} <a href="{url="app=core&module=system&controller=ajax&do=chartTimezones"}" data-ipsDialog data-ipsDialog-title="{lang="dynamic_chart_timezone_title"}">{lang="learn_more"}</a>{{endif}}</p>
{{endif}}