<ips:template parameters="$baseUrl, $pages, $activePage=1, $perPage=25, $ajax=FALSE, $pageParam='page'" />
{{if $pages > 1}}
	<span class='ipsPagination ipsPagination_mini' id='elPagination_{expression="md5($baseUrl)"}'>
		{{foreach range( 1, ( 4 > $pages ) ? $pages : 4 ) as $i}}
			<span class='ipsPagination_page'><a href='{$baseUrl->setPage( $pageParam, $i )}' data-ipsTooltip title='{lang="go_to_page_x" sprintf="$i"}'>{$i}</a></span>
		{{endforeach}}
		{{if $pages > 4}}
			<span class='ipsPagination_last'><a href='{$baseUrl->setPage( $pageParam, $pages )}' data-ipsTooltip title='{lang="last_page"}'>{$pages} <i class='fa fa-caret-right'></i></a></span>
		{{endif}}
	</span>
{{endif}}