<ips:template parameters="$url, $mr=NULL, $height=NULL" />
<div class="ipsRedirect_manualButton">
	<a href='{$url->setQueryString( array( 'mr' => '0', '_mrReset' => 1 ) )}' class="ipsButton ipsButton_primary">{lang="start"}</a>
</div>
<div data-controller="core.global.core.multipleRedirect" data-url="{$url}">
	<div class="ipsRedirect ipsHide ipsPad">
		<div class="ipsLoading ipsRedirect_loading" data-role="loadingIcon" data-loading-text="" {{if $height}}style="height: {$height}px;"{{endif}}>
		</div>
		<div class="ipsHide" data-role="progressBarContainer">
			<div class="ipsRedirect_progress" data-loading-text="">
				<div class="ipsProgressBar ipsProgressBar_animated">
					<div class="ipsProgressBar_progress" data-role="progressBar"></div>
				</div>
			</div>
		</div>
	</div>
</div>