<ips:template parameters="$baseUrl, $pages, $activePage=1, $perPage=25, $ajax=TRUE, $pageParam='page', $simple=false" />
{{$firstPage = $baseUrl->setPage( $pageParam );}}
{{if $activePage > 1 || $pages > 1}}
	{{$uniqId = mt_rand();}}
	<ul class='ipsPagination' id='elPagination_{expression="md5($baseUrl)"}_{$uniqId}' data-ipsPagination-seoPagination='{{if $firstPage->seoPagination}}true{{else}}false{{endif}}' data-pages='{$pages}' {{if $ajax and ( theme.ajax_pagination or \IPS\Request::i()->isAjax())}}data-ipsPagination {{if $pageParam != 'page'}}data-ipsPagination-pageParam='{$pageParam}'{{endif}} data-ipsPagination-pages="{$pages}" data-ipsPagination-perPage='{$perPage}'{{endif}}>
		{{if $simple}}
			{{if $activePage > 1}}
				<li class='ipsPagination_prev'><a href='{$baseUrl->setPage( $pageParam, $activePage - 1 )}' rel="prev" data-page='{expression="$activePage - 1"}' data-ipsTooltip title='{lang="prev_page"}'>{lang="prev"}</a></li>
			{{endif}}
			{{if $activePage < $pages}}
				<li class='ipsPagination_next'><a href='{$baseUrl->setPage( $pageParam, $activePage + 1 )}' rel="next" data-page='{expression="$activePage + 1"}' data-ipsTooltip title='{lang="next_page"}'>{lang="next"}</a></li>
			{{endif}}
		{{else}}
			{{if $activePage != 1}}
				<li class='ipsPagination_first'><a href='{$firstPage}' rel="first" data-page='1' data-ipsTooltip title='{lang="first_page"}'><i class='fa fa-angle-double-left'></i></a></li>
				<li class='ipsPagination_prev'><a href='{$baseUrl->setPage( $pageParam, $activePage - 1 )}' rel="prev" data-page='{expression="$activePage - 1"}' data-ipsTooltip title='{lang="prev_page"}'>{lang="prev"}</a></li>
				{{foreach range( ( ( $activePage - 5 ) > 0 ) ? ( $activePage - 5 ) : 1, $activePage - 1 ) as $idx => $i}}
					<li class='ipsPagination_page'><a href='{$baseUrl->setPage( $pageParam, $i )}' data-page='{$i}'>{$i}</a></li>
				{{endforeach}}
			{{else}}
				<li class='ipsPagination_first ipsPagination_inactive'><a href='{$firstPage}' rel="first" data-page='1' data-ipsTooltip title='{lang="first_page"}'><i class='fa fa-angle-double-left'></i></a></li>
				<li class='ipsPagination_prev ipsPagination_inactive'><a href='{$baseUrl->setPage( $pageParam, $activePage - 1 )}' rel="prev" data-page='{expression="$activePage - 1"}' data-ipsTooltip title='{lang="prev_page"}'>{lang="prev"}</a></li>
			{{endif}}
			<li class='ipsPagination_page ipsPagination_active'><a href='{$baseUrl->setPage( $pageParam, $activePage )}' data-page='{$activePage}'>{$activePage}</a></li>
			{{if $activePage != $pages}}
				{{foreach range( $activePage + 1, ( ( $activePage + 5 ) > $pages ) ? $pages : ( $activePage + 5 ) ) as $idx => $i}}
					<li class='ipsPagination_page'><a href='{$baseUrl->setPage( $pageParam, $i )}' data-page='{$i}'>{$i}</a></li>
				{{endforeach}}
				<li class='ipsPagination_next'><a href='{$baseUrl->setPage( $pageParam, $activePage + 1 )}' rel="next" data-page='{expression="$activePage + 1"}' data-ipsTooltip title='{lang="next_page"}'>{lang="next"}</a></li>
				<li class='ipsPagination_last'><a href='{$baseUrl->setPage( $pageParam, $pages )}' rel="last" data-page='{$pages}' data-ipsTooltip title='{lang="last_page"}'><i class='fa fa-angle-double-right'></i></a></li>
			{{else}}
				<li class='ipsPagination_next ipsPagination_inactive'><a href='{$baseUrl->setPage( $pageParam, ( $activePage + 1 > $pages ) ? $pages : $activePage + 1 )}' rel="next" data-page='{expression="( $activePage + 1 > $pages ) ? $pages : $activePage + 1"}' data-ipsTooltip title='{lang="next_page"}'>{lang="next"}</a></li>
				<li class='ipsPagination_last ipsPagination_inactive'><a href='{$baseUrl->setPage( $pageParam, $pages )}' rel="last" data-page='{$pages}' data-ipsTooltip title='{lang="last_page"}'><i class='fa fa-angle-double-right'></i></a></li>
			{{endif}}
			{{if $pages > 1}}
				<li class='ipsPagination_pageJump'>
					<a href='#' data-ipsMenu data-ipsMenu-closeOnClick='false' data-ipsMenu-appendTo='#elPagination_{expression="md5($baseUrl)"}_{$uniqId}' id='elPagination_{expression="md5($baseUrl)"}_{$uniqId}_jump'>{lang="pagination" sprintf="$activePage, $pages"} &nbsp;<i class='fa fa-caret-down'></i></a>
					<div class='ipsMenu ipsMenu_narrow ipsPadding ipsHide' id='elPagination_{expression="md5($baseUrl)"}_{$uniqId}_jump_menu'>
						<form accept-charset='utf-8' method='post' action='{$baseUrl->setPage( 'page', NULL )}' data-role="pageJump">
							<ul class='ipsForm ipsForm_horizontal'>
								<li class='ipsFieldRow'>
									<input type='number' min='1' max='{$pages}' placeholder='{lang="page_number"}' class='ipsField_fullWidth' name='{$pageParam}'>
								</li>
								<li class='ipsFieldRow ipsFieldRow_fullWidth'>
									<input type='submit' class='ipsButton_fullWidth ipsButton ipsButton_verySmall ipsButton_primary' value='{lang="go"}'>
								</li>
							</ul>
						</form>
					</div>
				</li>
			{{endif}}
		{{endif}}
	</ul>
{{endif}}