<ips:template parameters="$value, $extraClasses=array(), $extraControllers=array(), $extraAttributes=array()" />

{{if \IPS\Dispatcher::hasInstance() and \IPS\Dispatcher::i()->controllerLocation == 'front'}}
{{$controllers = array_merge( array('core.front.core.lightboxedImages'), $extraControllers );}}
<div class='ipsType_richText {expression="implode(' ', $extraClasses)"}' data-controller='{expression="implode(',', $controllers)"}' {{foreach $extraAttributes as $attribute}} {$attribute|raw}{{endforeach}}>
{$value|raw}
</div>
{{else}}
{{$controllers = $extraControllers;}}
<div class='ipsType_richText {expression="implode(' ', $extraClasses)"}' data-ipsLazyLoad {{if \is_array( $controllers ) AND \count( $controllers )}}data-controller='{expression="implode(',', $controllers)"}' {{endif}}{{foreach $extraAttributes as $attribute}} {$attribute|raw}{{endforeach}}>
{$value|raw}
</div>
{{endif}}