<ips:template parameters="$linkUrl, $imageUrl, $lat=NULL, $long=NULL, $width=NULL, $height=NULL" />
<div{{if settings.lazy_load_enabled}} data-ipsLazyLoad{{endif}}>
{{if $lat and $long}}
	<span itemscope itemtype='http://schema.org/GeoCoordinates'>
		<meta itemprop='latitude' content='{$lat}'>
		<meta itemprop='longitude' content='{$long}'>
		{{if $linkUrl}}<a href='{$linkUrl}' target='_blank' rel='noopener'>{{endif}}<img {{if settings.lazy_load_enabled}}src='{expression="\IPS\Text\Parser::blankImage()"}' data-{{endif}}src='{$imageUrl}' alt='' class='ipsImage'{{if $width AND $height}} width='{$width}' height='{$height}'{{endif}}>{{if $linkUrl}}</a>{{endif}}
	</span>
{{else}}
{{if $linkUrl}}<a href='{$linkUrl}' target='_blank' rel='noopener'>{{endif}}<img {{if settings.lazy_load_enabled}}src='{expression="\IPS\Text\Parser::blankImage()"}' data-{{endif}}src='{$imageUrl}' alt='' class='ipsImage'{{if $width AND $height}} width='{$width}' height='{$height}'{{endif}}>{{if $linkUrl}}</a>{{endif}}
{{endif}}
</div>